package com.ipproxy.platform.service.mapper;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.*;

@Repository
public class OrderServiceMapper {
    private final JdbcTemplate jdbc; public OrderServiceMapper(JdbcTemplate jdbc){this.jdbc=jdbc;}
    private Map<String,Object> one(String sql,Object... a){List<Map<String,Object>> x=jdbc.queryForList(sql,a);return x.isEmpty()?null:x.getFirst();}
    public String nextOrderNo(){return jdbc.queryForObject("SELECT 'O'||to_char(current_date,'YYYYMMDD')||lpad(nextval('seq_biz_order_no')::text,6,'0')",String.class);}
    public String nextServiceNo(){return jdbc.queryForObject("SELECT 'S'||to_char(current_date,'YYYYMMDD')||lpad(nextval('seq_service_no')::text,6,'0')",String.class);}
    public String nextChangeNo(){return jdbc.queryForObject("SELECT 'C'||to_char(current_date,'YYYYMMDD')||lpad(nextval('seq_service_change_no')::text,6,'0')",String.class);}
    public String nextReleaseNo(){return jdbc.queryForObject("SELECT 'R'||to_char(current_date,'YYYYMMDD')||lpad(nextval('seq_service_release_no')::text,6,'0')",String.class);}

    public Map<String,Object> customer(Long id){return one("SELECT id,customer_code,customer_name,status FROM customer WHERE id=? AND deleted=FALSE",id);}
    public Map<String,Object> product(Long id){return one("SELECT id,product_code,product_name,product_type,status,to_jsonb(prd_product)::text product_json FROM prd_product WHERE id=? AND deleted=FALSE",id);}
    public Map<String,Object> pkg(Long id){return one("SELECT id,package_code,package_name,product_id,service_days,price,currency,status,to_jsonb(prd_package)::text package_json FROM prd_package WHERE id=? AND deleted=FALSE",id);}
    public Map<String,Object> activeStrategy(Long productId){return one("SELECT s.id,s.strategy_code,s.strategy_name,s.status,to_jsonb(s)::text strategy_json FROM prd_resource_strategy s WHERE s.product_id=? AND s.status='ACTIVE' AND s.deleted=FALSE ORDER BY s.id LIMIT 1",productId);}
    public Map<String,Object> primaryPool(Long strategyId){return one("SELECT p.id,p.pool_code,p.pool_name,p.status,sp.priority,sp.weight,(SELECT count(*) FROM res_pool_ip x JOIN res_ip i ON i.id=x.ip_id WHERE x.pool_id=p.id AND x.enabled=TRUE AND i.deleted=FALSE AND i.available_status='AVAILABLE' AND i.duplicate_flag=FALSE) member_count FROM prd_strategy_pool sp JOIN res_pool p ON p.id=sp.pool_id WHERE sp.strategy_id=? AND sp.enabled=TRUE AND p.deleted=FALSE AND p.status='ACTIVE' ORDER BY sp.priority,p.priority,p.id LIMIT 1",strategyId);}
    public Map<String,Object> freeExclusiveIp(Long poolId){return one("SELECT i.id,host(i.ip_address) ip_address FROM res_pool_ip pi JOIN res_ip i ON i.id=pi.ip_id LEFT JOIN res_exclusive_allocation a ON a.resource_type='IP' AND a.resource_id=i.id AND a.deleted=FALSE AND a.status IN ('LOCKED','ALLOCATED') WHERE pi.pool_id=? AND pi.enabled=TRUE AND i.deleted=FALSE AND i.available_status='AVAILABLE' AND i.duplicate_flag=FALSE AND a.id IS NULL ORDER BY i.quality_score DESC NULLS LAST,i.id LIMIT 1 FOR UPDATE SKIP LOCKED",poolId);}
    public Long tunnelDomain(Long productId){List<Long>x=jdbc.query("SELECT entry_domain_id FROM prd_tunnel_config WHERE product_id=? AND entry_domain_id IS NOT NULL",(r,n)->r.getLong(1),productId);return x.isEmpty()?null:x.getFirst();}

    public long countOrders(String keyword,String status,Long customerId){return jdbc.queryForObject("SELECT count(*) FROM biz_order o JOIN customer c ON c.id=o.customer_id WHERE o.deleted=FALSE AND (?='' OR o.order_no ILIKE '%'||?||'%' OR c.customer_name ILIKE '%'||?||'%') AND (?='' OR o.status=?) AND (?=0 OR o.customer_id=?)",Long.class,keyword,keyword,keyword,status,status,customerId==null?0:customerId,customerId==null?0:customerId);}
    public List<Map<String,Object>> orders(String keyword,String status,Long customerId,int size,int offset){return jdbc.queryForList("SELECT o.id,o.order_no,o.customer_id,c.customer_code,c.customer_name,o.order_type,o.status,o.total_amount,o.currency,o.expected_effective_at,o.expected_expire_at,o.remark,o.created_at,(SELECT count(*) FROM biz_order_item i WHERE i.order_id=o.id) item_total,(SELECT count(*) FROM svc_instance s WHERE s.order_id=o.id AND s.deleted=FALSE) service_total FROM biz_order o JOIN customer c ON c.id=o.customer_id WHERE o.deleted=FALSE AND (?='' OR o.order_no ILIKE '%'||?||'%' OR c.customer_name ILIKE '%'||?||'%') AND (?='' OR o.status=?) AND (?=0 OR o.customer_id=?) ORDER BY o.created_at DESC,o.id DESC LIMIT ? OFFSET ?",keyword,keyword,keyword,status,status,customerId==null?0:customerId,customerId==null?0:customerId,size,offset);}
    public Map<String,Object> order(Long id){return one("SELECT o.*,c.customer_code,c.customer_name FROM biz_order o JOIN customer c ON c.id=o.customer_id WHERE o.id=? AND o.deleted=FALSE",id);}
    public List<Map<String,Object>> orderItems(Long id){return jdbc.queryForList("SELECT i.*,p.product_code,p.product_name,p.product_type,k.package_code,k.package_name FROM biz_order_item i JOIN prd_product p ON p.id=i.product_id LEFT JOIN prd_package k ON k.id=i.package_id WHERE i.order_id=? ORDER BY i.line_no",id);}
    public Long insertOrder(String no,Long customerId,String type,BigDecimal total,String currency,OffsetDateTime effective,OffsetDateTime expire,Long owner,String remark,Long actor){return jdbc.queryForObject("INSERT INTO biz_order(order_no,customer_id,order_type,status,total_amount,currency,expected_effective_at,expected_expire_at,owner_user_id,remark,created_by,updated_by) VALUES(?,?,?,'PENDING_CONFIRM',?,?,?,?,?,?,?,?) RETURNING id",Long.class,no,customerId,type,total,currency,effective,expire,owner,remark,actor,actor);}
    public Long insertItem(Long orderId,int line,Long productId,Long packageId,int qty,BigDecimal unit,BigDecimal amount,String productJson,String packageJson,int serviceCount,String remark){return jdbc.queryForObject("INSERT INTO biz_order_item(order_id,line_no,product_id,package_id,quantity,unit_price,line_amount,product_snapshot,package_snapshot,entitlement_snapshot,service_count,remark) VALUES(?,?,?,?,?,?,?,CAST(? AS jsonb),CAST(NULLIF(?,'') AS jsonb),'{}'::jsonb,?,?) RETURNING id",Long.class,orderId,line,productId,packageId,qty,unit,amount,productJson,packageJson==null?"":packageJson,serviceCount,remark);}
    public int orderStatus(Long id,String status,Long actor){return jdbc.update("UPDATE biz_order SET status=?,updated_at=now(),updated_by=?,confirmed_at=CASE WHEN ?='PENDING_PROVISION' THEN now() ELSE confirmed_at END,completed_at=CASE WHEN ?='COMPLETED' THEN now() ELSE completed_at END,cancelled_at=CASE WHEN ?='CANCELLED' THEN now() ELSE cancelled_at END WHERE id=? AND deleted=FALSE",status,actor,status,status,status,id);}
    public int cancelOrder(Long id,String reason,Long actor){return jdbc.update("UPDATE biz_order SET status='CANCELLED',cancel_reason=?,cancelled_at=now(),updated_at=now(),updated_by=? WHERE id=? AND deleted=FALSE",reason,actor,id);}

    public Long insertService(String no,Long customerId,Long orderId,Long itemId,Long productId,Long packageId,Long strategyId,String productType,String productJson,String packageJson,String strategyJson,String quotaJson,OffsetDateTime effective,OffsetDateTime expire,Long actor){return jdbc.queryForObject("INSERT INTO svc_instance(service_no,customer_id,order_id,order_item_id,product_id,package_id,strategy_id,product_type,product_snapshot,package_snapshot,strategy_snapshot,quota_snapshot,effective_at,expire_at,status,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,CAST(? AS jsonb),CAST(NULLIF(?,'') AS jsonb),CAST(? AS jsonb),CAST(? AS jsonb),?,?,'PENDING',?,?) RETURNING id",Long.class,no,customerId,orderId,itemId,productId,packageId,strategyId,productType,productJson,packageJson==null?"":packageJson,strategyJson,quotaJson,effective,expire,actor,actor);}
    public int serviceStatus(Long id,String status,String failure,Long actor){return jdbc.update("UPDATE svc_instance SET status=?,failure_reason=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",status,failure,actor,id);}
    public Long bind(Long serviceId,String type,Long resourceId,String role,String metadata,Long actor){return jdbc.queryForObject("INSERT INTO svc_resource_binding(service_id,resource_type,resource_id,binding_role,metadata,created_by) VALUES(?,?,?,?,CAST(? AS jsonb),?) RETURNING id",Long.class,serviceId,type,resourceId,role,metadata,actor);}
    public Long allocateExclusive(Long serviceId,String type,Long resourceId,Long customerId,OffsetDateTime expire,String snapshot,Long actor){return jdbc.queryForObject("INSERT INTO res_exclusive_allocation(allocation_no,resource_type,resource_id,customer_id,service_id,status,locked_at,allocated_at,expire_at,source_snapshot,created_by,updated_by) VALUES('EA-'||replace(gen_random_uuid()::text,'-',''),?,?,?,?, 'ALLOCATED',now(),now(),?,CAST(? AS jsonb),?,?) RETURNING id",Long.class,type,resourceId,customerId,serviceId,expire,snapshot,actor,actor);}
    public Long insertCredential(Long serviceId,String type,String account,String hash,String mask,OffsetDateTime expire,String metadata,Long actor){return jdbc.queryForObject("INSERT INTO svc_credential(service_id,credential_type,account_name,secret_hash,secret_mask,expire_at,metadata,created_by,updated_by) VALUES(?,?,?,?,?,?,CAST(? AS jsonb),?,?) RETURNING id",Long.class,serviceId,type,account,hash,mask,expire,metadata,actor,actor);}

    public long countServices(String keyword,String status,Long customerId,String productType){return jdbc.queryForObject("SELECT count(*) FROM svc_instance s JOIN customer c ON c.id=s.customer_id WHERE s.deleted=FALSE AND (?='' OR s.service_no ILIKE '%'||?||'%' OR c.customer_name ILIKE '%'||?||'%') AND (?='' OR s.status=?) AND (?=0 OR s.customer_id=?) AND (?='' OR s.product_type=?)",Long.class,keyword,keyword,keyword,status,status,customerId==null?0:customerId,customerId==null?0:customerId,productType,productType);}
    public List<Map<String,Object>> services(String keyword,String status,Long customerId,String productType,int size,int offset){return jdbc.queryForList("SELECT s.id,s.service_no,s.customer_id,c.customer_code,c.customer_name,s.order_id,o.order_no,s.product_id,p.product_name,s.package_id,k.package_name,s.strategy_id,st.strategy_name,s.product_type,s.effective_at,s.expire_at,s.status,s.failure_reason,s.created_at FROM svc_instance s JOIN customer c ON c.id=s.customer_id LEFT JOIN biz_order o ON o.id=s.order_id JOIN prd_product p ON p.id=s.product_id LEFT JOIN prd_package k ON k.id=s.package_id LEFT JOIN prd_resource_strategy st ON st.id=s.strategy_id WHERE s.deleted=FALSE AND (?='' OR s.service_no ILIKE '%'||?||'%' OR c.customer_name ILIKE '%'||?||'%') AND (?='' OR s.status=?) AND (?=0 OR s.customer_id=?) AND (?='' OR s.product_type=?) ORDER BY s.created_at DESC,s.id DESC LIMIT ? OFFSET ?",keyword,keyword,keyword,status,status,customerId==null?0:customerId,customerId==null?0:customerId,productType,productType,size,offset);}
    public Map<String,Object> service(Long id){return one("SELECT s.*,c.customer_code,c.customer_name,o.order_no,p.product_code,p.product_name,k.package_code,k.package_name,st.strategy_code,st.strategy_name FROM svc_instance s JOIN customer c ON c.id=s.customer_id LEFT JOIN biz_order o ON o.id=s.order_id JOIN prd_product p ON p.id=s.product_id LEFT JOIN prd_package k ON k.id=s.package_id LEFT JOIN prd_resource_strategy st ON st.id=s.strategy_id WHERE s.id=? AND s.deleted=FALSE",id);}
    public List<Map<String,Object>> bindings(Long id){return jdbc.queryForList("SELECT * FROM svc_resource_binding WHERE service_id=? ORDER BY created_at,id",id);}
    public List<Map<String,Object>> credentials(Long id){return jdbc.queryForList("SELECT id,service_id,credential_type,account_name,secret_mask,status,issued_at,expire_at,last_used_at,rotated_at,metadata FROM svc_credential WHERE service_id=? AND deleted=FALSE ORDER BY issued_at DESC,id DESC",id);}
    public List<Map<String,Object>> whitelist(Long id){return jdbc.queryForList("SELECT id,service_id,host(ip_address) ip_address,status,remark,created_at FROM svc_whitelist WHERE service_id=? AND deleted=FALSE ORDER BY created_at DESC",id);}
    public int freezeCredentials(Long id){return jdbc.update("UPDATE svc_credential SET status='FROZEN',updated_at=now(),version=version+1 WHERE service_id=? AND deleted=FALSE AND status='ACTIVE'",id);}
    public int activateCredentials(Long id){return jdbc.update("UPDATE svc_credential SET status='ACTIVE',updated_at=now(),version=version+1 WHERE service_id=? AND deleted=FALSE AND status='FROZEN'",id);}
    public int revokeCredentials(Long id){return jdbc.update("UPDATE svc_credential SET status='REVOKED',updated_at=now(),version=version+1 WHERE service_id=? AND deleted=FALSE AND status IN ('ACTIVE','FROZEN')",id);}
    public int releaseBindings(Long id){return jdbc.update("UPDATE svc_resource_binding SET status='RELEASED',released_at=now() WHERE service_id=? AND status='ACTIVE'",id);}
    public int recycleExclusive(Long id){return jdbc.update("UPDATE res_exclusive_allocation SET status='PENDING_RECYCLE',released_at=now(),updated_at=now(),version=version+1 WHERE service_id=? AND deleted=FALSE AND status IN ('LOCKED','ALLOCATED')",id);}
    public int renew(Long id,OffsetDateTime expire,Long actor){return jdbc.update("UPDATE svc_instance SET expire_at=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",expire,actor,id);}
    public Long insertChange(String no,Long serviceId,String type,String beforeJson,String afterJson,String reason,String status,Long actor){return jdbc.queryForObject("INSERT INTO svc_change(change_no,service_id,change_type,before_snapshot,after_snapshot,reason,status,operator_id,started_at,finished_at,created_by,updated_by) VALUES(?,?,?,CAST(? AS jsonb),CAST(? AS jsonb),?,?,?,now(),CASE WHEN ? IN ('SUCCESS','FAILED') THEN now() END,?,?) RETURNING id",Long.class,no,serviceId,type,beforeJson,afterJson,reason,status,actor,status,actor,actor);}
    public List<Map<String,Object>> changes(Long id){return jdbc.queryForList("SELECT * FROM svc_change WHERE service_id=? AND deleted=FALSE ORDER BY created_at DESC,id DESC",id);}
    public Long insertRelease(String no,Long serviceId,String trigger,String status,String credentialResult,String resourceResult,Long actor,String error){return jdbc.queryForObject("INSERT INTO svc_release_record(release_no,service_id,trigger_type,status,credential_result,resource_result,started_at,finished_at,operator_id,error_message) VALUES(?,?,?,?,CAST(? AS jsonb),CAST(? AS jsonb),now(),CASE WHEN ? IN ('SUCCESS','FAILED','PARTIAL_SUCCESS') THEN now() END,?,?) RETURNING id",Long.class,no,serviceId,trigger,status,credentialResult,resourceResult,status,actor,error);}
    public long countReleases(String status){return jdbc.queryForObject("SELECT count(*) FROM svc_release_record WHERE (?='' OR status=?)",Long.class,status,status);}
    public List<Map<String,Object>> releases(String status,int size,int offset){return jdbc.queryForList("SELECT r.*,s.service_no,c.customer_name FROM svc_release_record r JOIN svc_instance s ON s.id=r.service_id JOIN customer c ON c.id=s.customer_id WHERE (?='' OR r.status=?) ORDER BY r.created_at DESC,r.id DESC LIMIT ? OFFSET ?",status,status,size,offset);}
    public Map<String,Object> release(Long id){return one("SELECT * FROM svc_release_record WHERE id=?",id);}
    public Long addWhitelist(Long serviceId,String ip,String remark,Long actor){return jdbc.queryForObject("INSERT INTO svc_whitelist(service_id,ip_address,remark,created_by,updated_by) VALUES(?,CAST(? AS inet),?,?,?) RETURNING id",Long.class,serviceId,ip,remark,actor,actor);}
    public int disableWhitelist(Long serviceId,Long id,Long actor){return jdbc.update("UPDATE svc_whitelist SET status='DISABLED',updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND service_id=? AND deleted=FALSE",actor,id,serviceId);}
    public int revokeCurrentCredential(Long serviceId){return jdbc.update("UPDATE svc_credential SET status='REVOKED',rotated_at=now(),updated_at=now(),version=version+1 WHERE service_id=? AND deleted=FALSE AND status IN ('ACTIVE','FROZEN')",serviceId);}
    public void audit(Long actor,String name,String objectType,Object id,String op,String reason,String ip){jdbc.update("INSERT INTO sys_operation_log(operator_id,operator_name,module_code,object_type,object_id,operation,reason,source_ip,request_id,result) VALUES(?,?, 'ORDER_SERVICE',?,?,?, ?,CAST(NULLIF(?,'') AS inet),?,'SUCCESS')",actor,name,objectType,String.valueOf(id),op,reason,ip,UUID.randomUUID().toString());}
}
