package com.ipproxy.platform.resource;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.ipproxy.platform.common.api.PageResult;
import com.ipproxy.platform.common.exception.BusinessException;
import com.ipproxy.platform.resource.adapter.ResourceAdapter;
import com.ipproxy.platform.resource.mapper.ResourceMapper;
import com.ipproxy.platform.resource.security.ResourceSecretCipher;
import com.ipproxy.platform.security.UserPrincipal;
import org.slf4j.MDC;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.net.URI;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

@Service
public class ResourceService {
    private final ResourceMapper mapper; private final ResourceAdapter adapter; private final ObjectMapper objectMapper; private final ResourceSecretCipher cipher;
    public ResourceService(ResourceMapper mapper,ResourceAdapter adapter,ObjectMapper objectMapper,ResourceSecretCipher cipher){this.mapper=mapper;this.adapter=adapter;this.objectMapper=objectMapper;this.cipher=cipher;}
    public Map<String,Object> overview(){Map<String,Object> r=new LinkedHashMap<>(mapper.overview());r.put("recentSyncTasks",mapper.listSyncTasks("","",8,0));return r;}
    public Map<String,Object> options(){Map<String,Object> r=new LinkedHashMap<>();r.put("carriers",mapper.dictOptions("carrier"));r.put("regions",mapper.dictOptions("region"));r.put("resourceSources",mapper.dictOptions("resource_source"));return r;}
    public PageResult<Map<String,Object>> centos(int p,int s,String k,String status){p=page(p);s=size(s);k=text(k);status=text(status);return new PageResult<>(p,s,mapper.countCentos(k,status),mapper.listCentos(k,status,s,(p-1)*s));}
    public PageResult<Map<String,Object>> ros(int p,int s,String k,String status){p=page(p);s=size(s);k=text(k);status=text(status);return new PageResult<>(p,s,mapper.countRos(k,status),mapper.listRos(k,status,s,(p-1)*s));}
    public PageResult<Map<String,Object>> lines(int p,int s,String k,String status){p=page(p);s=size(s);k=text(k);status=text(status);return new PageResult<>(p,s,mapper.countLines(k,status),mapper.listLines(k,status,s,(p-1)*s));}
    public PageResult<Map<String,Object>> ips(int p,int s,String k,String status,String sourceType){p=page(p);s=size(s);k=text(k);status=text(status);sourceType=text(sourceType);return new PageResult<>(p,s,mapper.countIps(k,status,sourceType),mapper.listIps(k,status,sourceType,s,(p-1)*s));}
    public Map<String,Object> baseDetail(String type,Long id){Map<String,Object> r=switch(type){case "CENTOS"->mapper.getCentos(id);case "ROS"->mapper.getRos(id);case "LINE"->mapper.getLine(id);case "IP"->mapper.getIp(id);default->null;};if(r==null)throw new BusinessException("RESOURCE_NOT_FOUND","资源不存在");return r;}

    @Transactional public Long sync(String sourceType,Long supplierId,Long targetPoolId,String reason,UserPrincipal actor,String ip){
        sourceType=requiredSourceType(sourceType); if("SUPPLIER".equals(sourceType)&&supplierId==null)throw new BusinessException("RESOURCE_SUPPLIER_REQUIRED","外部资源同步必须指定供应商");
        Map<String,Object> supplier=supplierId==null?Map.of():supplierContext(supplierId); String taskNo="RS"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmssSSS"));
        Long taskId=mapper.insertSyncTask(taskNo,sourceType,supplierId,"MANUAL",targetPoolId,actor.userId(),MDC.get("requestId"));mapper.updateSyncTask(taskId,"RUNNING",0,0,0,0,0,null);int received=0,ok=0,available=0,failed=0;
        try{
            List<Map<String,Object>> records=adapter.fetch(sourceType,supplier);received=records.size();
            for(Map<String,Object> rec:records){String sourceRecordId=str(rec.get("sourceId"));try{Long rid=importRecord(sourceType,rec,supplierId);boolean av="AVAILABLE".equals(str(rec.get("availableStatus")));mapper.insertSyncDetail(taskId,sourceRecordId,json(rec),json(rec),"SUPPLIER".equals(sourceType)?"IP":sourceType,rid,"IMPORTED",false,av,null);ok++;if(av)available++;}catch(Exception e){failed++;mapper.insertSyncDetail(taskId,sourceRecordId,json(rec),"{}","SUPPLIER".equals(sourceType)?"IP":sourceType,null,"FAILED",false,false,trimError(e));}}
            String status=failed==0?"SUCCESS":ok>0?"PARTIAL_SUCCESS":"FAILED";mapper.updateSyncTask(taskId,status,received,received,ok,0,available,failed==0?null:(failed+" 条记录处理失败"));
            if(targetPoolId!=null&&ok>0)recalculatePoolInternal(targetPoolId);audit(actor,"SYNC_TASK",taskId,"SYNC_"+sourceType,ip,reason==null?"":reason);return taskId;
        }catch(Exception e){mapper.updateSyncTask(taskId,"FAILED",received,received,ok,0,available,trimError(e));throw e instanceof BusinessException b?b:new BusinessException("RESOURCE_SYNC_FAILED",trimError(e));}
    }
    private Long importRecord(String sourceType,Map<String,Object> r,Long supplierId){String sourceId=required(str(r.get("sourceId")),"sourceId不能为空");String sys="SUPPLIER".equals(sourceType)?"SUPPLIER:"+supplierId:"OPS_API";String code=sourceType.substring(0,Math.min(3,sourceType.length()))+"-"+sourceId;
        if("CENTOS".equals(sourceType))return mapper.upsertCentos(code,str(r.get("resourceName")),sys,sourceId,str(r.get("managementIp")),str(r.get("regionCode")),defaultVal(str(r.get("onlineStatus")),"UNKNOWN"),decimal(r.get("cpuUsage")),decimal(r.get("memoryUsage")),decimal(r.get("diskUsage")),json(r));
        if("ROS".equals(sourceType)){Long parent=mapper.centosIdBySource("OPS_API",required(str(r.get("parentSourceId")),"ROS缺少CentOS引用"));if(parent==null)throw new BusinessException("RESOURCE_PARENT_MISSING","ROS关联的CentOS尚未同步");return mapper.upsertRos(code,str(r.get("resourceName")),parent,sys,sourceId,str(r.get("managementIp")),str(r.get("regionCode")),str(r.get("carrierCode")),defaultVal(str(r.get("onlineStatus")),"UNKNOWN"),json(r));}
        if("LINE".equals(sourceType)){Long parent=mapper.rosIdBySource("OPS_API",required(str(r.get("parentSourceId")),"线路缺少ROS引用"));if(parent==null)throw new BusinessException("RESOURCE_PARENT_MISSING","线路关联的ROS尚未同步");return mapper.upsertLine(code,str(r.get("resourceName")),parent,sys,sourceId,str(r.get("regionCode")),str(r.get("carrierCode")),str(r.get("broadbandAccountMask")),str(r.get("currentPublicIp")),defaultVal(str(r.get("onlineStatus")),"UNKNOWN"),defaultVal(str(r.get("dialStatus")),"UNKNOWN"),integer(r.get("latencyMs")),json(r));}
        if("IP".equals(sourceType)){String parentSource=required(str(r.get("parentSourceId")),"IP缺少线路引用");Long lineId=mapper.lineIdBySource("OPS_API",parentSource);if(lineId==null)throw new BusinessException("RESOURCE_PARENT_MISSING","IP关联的线路尚未同步");Map<String,Object> line=mapper.getLine(lineId);Long rosId=num(line.get("ros_id"));Long centosId=num(line.get("centos_id"));return upsertIp(str(r.get("ipAddress")),"SELF",sys,sourceId,centosId,rosId,lineId,null,r);}
        if("SUPPLIER".equals(sourceType))return upsertIp(str(r.get("ipAddress")),"EXTERNAL",sys,sourceId,null,null,null,supplierId,r);
        throw new BusinessException("RESOURCE_SOURCE_INVALID","不支持的资源同步类型");}
    private Long upsertIp(String ipAddress,String sourceType,String sourceSystem,String sourceId,Long centosId,Long rosId,Long lineId,Long supplierId,Map<String,Object> r){required(ipAddress,"IP地址不能为空");Long id=mapper.ipIdBySource(sourceType,sourceSystem,sourceId,lineId,supplierId);if(id==null)return mapper.insertIp(ipAddress,sourceType,sourceSystem,sourceId,centosId,rosId,lineId,supplierId,str(r.get("regionCode")),str(r.get("carrierCode")),defaultVal(str(r.get("availableStatus")),"UNKNOWN"),integer(r.get("latencyMs")),decimal(r.get("qualityScore")),json(r));mapper.updateIp(id,ipAddress,centosId,rosId,lineId,supplierId,str(r.get("regionCode")),str(r.get("carrierCode")),defaultVal(str(r.get("availableStatus")),"UNKNOWN"),integer(r.get("latencyMs")),decimal(r.get("qualityScore")),json(r));return id;}

    public PageResult<Map<String,Object>> pools(int p,int s,String k,String status){p=page(p);s=size(s);k=text(k);status=text(status);return new PageResult<>(p,s,mapper.countPools(k,status),mapper.listPools(k,status,s,(p-1)*s));}
    public Map<String,Object> pool(Long id){Map<String,Object> r=mapper.getPool(id);if(r==null)throw new BusinessException("RESOURCE_POOL_NOT_FOUND","资源池不存在");return r;}
    @Transactional public Long createPool(String code,String name,String purpose,List<String> regions,List<String> carriers,String sourceScope,Map<String,Object> admission,Map<String,Object> detection,Map<String,Object> dedup,Integer priority,UserPrincipal actor,String ip){required(code,"资源池编码不能为空");required(name,"资源池名称不能为空");scope(sourceScope);try{Long id=mapper.insertPool(code.trim(),name.trim(),blank(purpose),json(list(regions)),json(list(carriers)),sourceScope,json(map(admission)),json(map(detection)),json(map(dedup)),priority==null?100:priority,actor.userId());audit(actor,"RESOURCE_POOL",id,"CREATE",ip,"创建资源池");return id;}catch(Exception e){throw translateUnique(e,"资源池编码已存在");}}
    @Transactional public void updatePool(Long id,String name,String purpose,List<String> regions,List<String> carriers,String sourceScope,Map<String,Object> admission,Map<String,Object> detection,Map<String,Object> dedup,Integer priority,UserPrincipal actor,String ip){pool(id);required(name,"资源池名称不能为空");scope(sourceScope);mapper.updatePool(id,name.trim(),blank(purpose),json(list(regions)),json(list(carriers)),sourceScope,json(map(admission)),json(map(detection)),json(map(dedup)),priority==null?100:priority,actor.userId());audit(actor,"RESOURCE_POOL",id,"UPDATE",ip,"修改资源池");}
    @Transactional public void poolStatus(Long id,String status,String reason,UserPrincipal actor,String ip){Map<String,Object> p=pool(id);String current=str(p.get("status"));boolean ok=("DISABLED".equals(status)&&!"DISABLED".equals(current))||("ACTIVE".equals(status)&&"DISABLED".equals(current));if(!ok)throw new BusinessException("RESOURCE_POOL_STATUS_INVALID","不允许从 "+current+" 变更为 "+status);mapper.updatePoolStatus(id,status,actor.userId());audit(actor,"RESOURCE_POOL",id,"STATUS_"+status,ip,required(reason,"操作原因不能为空"));}
    @Transactional public int recalculatePool(Long id,String reason,UserPrincipal actor,String ip){pool(id);int n=recalculatePoolInternal(id);audit(actor,"RESOURCE_POOL",id,"RECALCULATE",ip,required(reason,"操作原因不能为空"));return n;}
    private int recalculatePoolInternal(Long id){mapper.disablePoolMembers(id);return mapper.recalculatePoolMembers(id);}
    public PageResult<Map<String,Object>> poolIps(Long id,int p,int s,String k){pool(id);p=page(p);s=size(s);k=text(k);return new PageResult<>(p,s,mapper.countPoolIps(id,k),mapper.listPoolIps(id,k,s,(p-1)*s));}

    public PageResult<Map<String,Object>> exclusive(int p,int s,String k,String status){p=page(p);s=size(s);k=text(k);status=text(status);return new PageResult<>(p,s,mapper.countExclusive(k,status),mapper.listExclusive(k,status,s,(p-1)*s));}
    public Map<String,Object> exclusive(Long id){Map<String,Object> r=mapper.getExclusive(id);if(r==null)throw new BusinessException("RESOURCE_EXCLUSIVE_NOT_FOUND","独享资源记录不存在");return r;}
    @Transactional public void releaseExclusive(Long id,String reason,UserPrincipal actor,String ip){exclusive(id);if(mapper.releaseExclusive(id,required(reason,"释放原因不能为空"),actor.userId())==0)throw new BusinessException("RESOURCE_EXCLUSIVE_STATUS_INVALID","当前独享资源状态不可释放");audit(actor,"EXCLUSIVE_ALLOCATION",id,"RELEASE",ip,reason);}

    public PageResult<Map<String,Object>> domains(int p,int s,String k,String status){p=page(p);s=size(s);k=text(k);status=text(status);return new PageResult<>(p,s,mapper.countDomains(k,status),mapper.listDomains(k,status,s,(p-1)*s));}
    public Map<String,Object> domain(Long id){Map<String,Object> r=mapper.getDomain(id);if(r==null)throw new BusinessException("RESOURCE_DOMAIN_NOT_FOUND","域名配置不存在");return r;}
    @Transactional public Long createDomain(String domainName,Long currentIpId,Long lineId,String usageType,String updateMode,UserPrincipal actor,String ip){required(domainName,"域名不能为空");updateMode(updateMode);if(currentIpId==null&&lineId==null)throw new BusinessException("RESOURCE_DOMAIN_TARGET_REQUIRED","域名至少需要关联IP或线路");try{Long id=mapper.insertDomain(domainName.trim().toLowerCase(Locale.ROOT),currentIpId,lineId,blank(usageType),updateMode,actor.userId());audit(actor,"DOMAIN",id,"CREATE",ip,"创建域名配置");return id;}catch(Exception e){throw translateUnique(e,"域名已存在");}}
    @Transactional public void updateDomain(Long id,Long currentIpId,Long lineId,String usageType,String updateMode,UserPrincipal actor,String ip){domain(id);updateMode(updateMode);if(currentIpId==null&&lineId==null)throw new BusinessException("RESOURCE_DOMAIN_TARGET_REQUIRED","域名至少需要关联IP或线路");mapper.updateDomain(id,currentIpId,lineId,blank(usageType),updateMode,actor.userId());audit(actor,"DOMAIN",id,"UPDATE",ip,"修改域名配置");}
    @Transactional public Map<String,Object> refreshDomain(Long id,String reason,UserPrincipal actor,String ip){Map<String,Object> d=domain(id);Long lineId=num(d.get("line_id"));Long targetIp=lineId==null?num(d.get("current_ip_id")):mapper.latestAvailableIpForLine(lineId);if(targetIp==null)throw new BusinessException("RESOURCE_DOMAIN_IP_UNAVAILABLE","当前关联线路没有可用IP");String status="PENDING_UPDATE";String message="已刷新平台目标IP；外部DNS更新适配器尚未配置";mapper.updateDomainRefresh(id,targetIp,status,message,actor.userId());audit(actor,"DOMAIN",id,"REFRESH_TARGET",ip,required(reason,"操作原因不能为空"));Map<String,Object> r=new LinkedHashMap<>();r.put("targetIpId",targetIp);r.put("status",status);r.put("message",message);return r;}

    public PageResult<Map<String,Object>> suppliers(int p,int s,String k,String status){p=page(p);s=size(s);k=text(k);status=text(status);return new PageResult<>(p,s,mapper.countSuppliers(k,status),mapper.listSuppliers(k,status,s,(p-1)*s));}
    public Map<String,Object> supplier(Long id){Map<String,Object> r=mapper.getSupplier(id);if(r==null)throw new BusinessException("RESOURCE_SUPPLIER_NOT_FOUND","供应商不存在");return r;}
    @Transactional public Long createSupplier(String code,String name,String contactName,String contactPhone,String endpoint,String authType,String account,String secret,List<String> regions,List<String> carriers,String fetchMode,UserPrincipal actor,String ip){required(code,"供应商编码不能为空");required(name,"供应商名称不能为空");validateEndpoint(endpoint);required(authType,"认证类型不能为空");fetchMode(fetchMode);try{Long id=mapper.insertSupplier(code.trim(),name.trim(),blank(contactName),blank(contactPhone),endpoint.trim(),authType.trim(),blank(account),cipher.encrypt(secret),json(list(regions)),json(list(carriers)),fetchMode,actor.userId());audit(actor,"SUPPLIER",id,"CREATE",ip,"创建供应商");return id;}catch(Exception e){throw translateUnique(e,"供应商编码已存在");}}
    @Transactional public void updateSupplier(Long id,String name,String contactName,String contactPhone,String endpoint,String authType,String account,String secret,List<String> regions,List<String> carriers,String fetchMode,UserPrincipal actor,String ip){supplier(id);required(name,"供应商名称不能为空");validateEndpoint(endpoint);required(authType,"认证类型不能为空");fetchMode(fetchMode);mapper.updateSupplier(id,name.trim(),blank(contactName),blank(contactPhone),endpoint.trim(),authType.trim(),blank(account),secret==null||secret.isBlank()?null:cipher.encrypt(secret),json(list(regions)),json(list(carriers)),fetchMode,actor.userId());audit(actor,"SUPPLIER",id,"UPDATE",ip,"修改供应商");}
    @Transactional public void supplierStatus(Long id,String status,String reason,UserPrincipal actor,String ip){supplier(id);if(!Set.of("ACTIVE","PAUSED","DISABLED").contains(status))throw new BusinessException("RESOURCE_SUPPLIER_STATUS_INVALID","供应商状态无效");mapper.updateSupplierStatus(id,status,actor.userId());audit(actor,"SUPPLIER",id,"STATUS_"+status,ip,required(reason,"操作原因不能为空"));}
    @Transactional public Map<String,Object> testSupplier(Long id,String reason,UserPrincipal actor,String ip){Map<String,Object> ctx=supplierContext(id);ResourceAdapter.SupplierTestResult test=adapter.testSupplier(ctx);String state=Boolean.TRUE.equals(test.reachable())?"NORMAL":Boolean.FALSE.equals(test.reachable())?"ABNORMAL":"UNKNOWN";mapper.updateSupplierTest(id,state,test.message());audit(actor,"SUPPLIER",id,"TEST",ip,required(reason,"测试原因不能为空"));return Map.of("interfaceStatus",state,"reachable",test.reachable()==null?"UNKNOWN":test.reachable(),"message",test.message());}
    private Map<String,Object> supplierContext(Long id){Map<String,Object> m=mapper.getSupplierInternal(id);if(m==null)throw new BusinessException("RESOURCE_SUPPLIER_NOT_FOUND","供应商不存在");Map<String,Object> r=new LinkedHashMap<>(m);String enc=str(m.get("secret_cipher"));r.remove("secret_cipher");r.put("secret",enc.isBlank()?null:cipher.decrypt(enc));return r;}

    public PageResult<Map<String,Object>> syncTasks(int p,int s,String sourceType,String status){p=page(p);s=size(s);sourceType=text(sourceType);status=text(status);return new PageResult<>(p,s,mapper.countSyncTasks(sourceType,status),mapper.listSyncTasks(sourceType,status,s,(p-1)*s));}
    public Map<String,Object> syncTask(Long id){Map<String,Object> r=mapper.getSyncTask(id);if(r==null)throw new BusinessException("RESOURCE_SYNC_TASK_NOT_FOUND","同步任务不存在");return r;}
    public List<Map<String,Object>> syncDetails(Long id){syncTask(id);return mapper.listSyncDetails(id);}
    @Transactional public Long retrySync(Long id,String reason,UserPrincipal actor,String ip){Map<String,Object> old=syncTask(id);String status=str(old.get("status"));if(!Set.of("FAILED","PARTIAL_SUCCESS").contains(status))throw new BusinessException("RESOURCE_SYNC_RETRY_INVALID","仅失败或部分成功任务允许重试");return sync(str(old.get("source_type")),num(old.get("supplier_id")),num(old.get("target_pool_id")),reason,actor,ip);}

    private String requiredSourceType(String s){s=required(s,"同步类型不能为空").toUpperCase(Locale.ROOT);if(!Set.of("CENTOS","ROS","LINE","IP","SUPPLIER").contains(s))throw new BusinessException("RESOURCE_SOURCE_INVALID","同步类型无效");return s;}
    private void scope(String s){if(!Set.of("SELF","EXTERNAL","MIXED").contains(s))throw new BusinessException("RESOURCE_POOL_SCOPE_INVALID","资源来源范围无效");}
    private void updateMode(String s){if(!Set.of("AUTO","MANUAL","API").contains(s))throw new BusinessException("RESOURCE_DOMAIN_MODE_INVALID","域名更新模式无效");}
    private void fetchMode(String s){if(!Set.of("SCHEDULED","REALTIME","MANUAL").contains(s))throw new BusinessException("RESOURCE_SUPPLIER_FETCH_MODE_INVALID","供应商获取模式无效");}
    private void validateEndpoint(String endpoint){required(endpoint,"API地址不能为空");try{URI u=URI.create(endpoint);if(u.getScheme()==null||u.getHost()==null)throw new IllegalArgumentException();}catch(Exception e){throw new BusinessException("RESOURCE_SUPPLIER_ENDPOINT_INVALID","供应商API地址格式无效");}}
    private RuntimeException translateUnique(Exception e,String message){String m=e.getMessage()==null?"":e.getMessage();return m.contains("duplicate key")||m.contains("unique constraint")?new BusinessException("RESOURCE_DUPLICATE",message):e instanceof RuntimeException r?r:new RuntimeException(e);}
    private void audit(UserPrincipal a,String type,Object id,String op,String ip,String reason){mapper.insertAudit(a.userId(),a.displayName(),type,String.valueOf(id),op,reason==null?"":reason,ip==null?"":ip,MDC.get("requestId"));}
    private String json(Object v){try{return objectMapper.writeValueAsString(v==null?Map.of():v);}catch(JsonProcessingException e){throw new BusinessException("RESOURCE_JSON_INVALID","资源配置JSON格式错误");}}
    private int page(int p){return Math.max(1,p);} private int size(int s){return Math.min(500,Math.max(1,s));} private String text(String s){return s==null?"":s.trim();} private String blank(String s){return s==null||s.isBlank()?null:s.trim();}
    private String required(String s,String msg){if(s==null||s.isBlank())throw new BusinessException("RESOURCE_REQUIRED",msg);return s.trim();} private String str(Object v){return v==null?"":String.valueOf(v);} private String defaultVal(String v,String d){return v==null||v.isBlank()?d:v;}
    private Long num(Object v){return v instanceof Number n?n.longValue():v==null||String.valueOf(v).isBlank()?null:Long.valueOf(String.valueOf(v));} private Integer integer(Object v){return v instanceof Number n?n.intValue():v==null?null:Integer.valueOf(String.valueOf(v));} private BigDecimal decimal(Object v){return v==null?null:v instanceof BigDecimal b?b:new BigDecimal(String.valueOf(v));}
    private List<String> list(List<String> v){return v==null?List.of():v;} private Map<String,Object> map(Map<String,Object> v){return v==null?Map.of():v;} private String trimError(Exception e){String m=e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();return m.length()>900?m.substring(0,900):m;}
}
