package com.ipproxy.platform.resource;

import com.ipproxy.platform.common.api.ApiResponse;
import com.ipproxy.platform.common.exception.BusinessException;
import com.ipproxy.platform.security.UserPrincipal;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import java.util.*;

@RestController
@RequestMapping("/api/admin/v1")
public class ResourceController {
    private final ResourceService service; public ResourceController(ResourceService service){this.service=service;}
    private void require(UserPrincipal p,String permission){if(p==null||(!p.roles().contains("SUPER_ADMIN")&&!p.permissions().contains(permission)))throw new BusinessException("AUTH_FORBIDDEN","当前账号无此操作权限");}
    private String ip(HttpServletRequest r){return r.getRemoteAddr()==null?"":r.getRemoteAddr();}

    @GetMapping("/resources/overview") public ApiResponse<?> overview(@AuthenticationPrincipal UserPrincipal p){require(p,"resource:read");return ApiResponse.success(service.overview());}
    @GetMapping("/resources/options") public ApiResponse<?> options(@AuthenticationPrincipal UserPrincipal p){require(p,"resource:read");return ApiResponse.success(service.options());}
    @GetMapping("/resources/centos") public ApiResponse<?> centos(@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int size,@RequestParam(defaultValue="") String keyword,@RequestParam(defaultValue="") String status,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:read");return ApiResponse.success(service.centos(page,size,keyword,status));}
    @GetMapping("/resources/centos/{id}") public ApiResponse<?> centosDetail(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:read");return ApiResponse.success(service.baseDetail("CENTOS",id));}
    @PostMapping("/resources/centos/sync") public ApiResponse<?> syncCentos(@RequestBody ActionReasonRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:sync");return ApiResponse.success(Map.of("taskId",service.sync("CENTOS",null,null,b.reason,p,ip(r))));}
    @GetMapping("/resources/ros") public ApiResponse<?> ros(@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int size,@RequestParam(defaultValue="") String keyword,@RequestParam(defaultValue="") String status,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:read");return ApiResponse.success(service.ros(page,size,keyword,status));}
    @GetMapping("/resources/ros/{id}") public ApiResponse<?> rosDetail(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:read");return ApiResponse.success(service.baseDetail("ROS",id));}
    @PostMapping("/resources/ros/sync") public ApiResponse<?> syncRos(@RequestBody ActionReasonRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:sync");return ApiResponse.success(Map.of("taskId",service.sync("ROS",null,null,b.reason,p,ip(r))));}
    @GetMapping("/resources/lines") public ApiResponse<?> lines(@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int size,@RequestParam(defaultValue="") String keyword,@RequestParam(defaultValue="") String status,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:read");return ApiResponse.success(service.lines(page,size,keyword,status));}
    @GetMapping("/resources/lines/{id}") public ApiResponse<?> lineDetail(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:read");return ApiResponse.success(service.baseDetail("LINE",id));}
    @PostMapping("/resources/lines/sync") public ApiResponse<?> syncLines(@RequestBody ActionReasonRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:sync");return ApiResponse.success(Map.of("taskId",service.sync("LINE",null,null,b.reason,p,ip(r))));}
    @GetMapping("/resources/ips") public ApiResponse<?> ips(@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int size,@RequestParam(defaultValue="") String keyword,@RequestParam(defaultValue="") String status,@RequestParam(defaultValue="") String sourceType,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:read");return ApiResponse.success(service.ips(page,size,keyword,status,sourceType));}
    @GetMapping("/resources/ips/{id}") public ApiResponse<?> ipDetail(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:read");return ApiResponse.success(service.baseDetail("IP",id));}
    @PostMapping("/resources/ips/sync") public ApiResponse<?> syncIps(@RequestBody ActionReasonRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:sync");return ApiResponse.success(Map.of("taskId",service.sync("IP",null,null,b.reason,p,ip(r))));}

    @GetMapping("/resource-pools") public ApiResponse<?> pools(@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int size,@RequestParam(defaultValue="") String keyword,@RequestParam(defaultValue="") String status,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:pool:read");return ApiResponse.success(service.pools(page,size,keyword,status));}
    @PostMapping("/resource-pools") public ApiResponse<?> createPool(@RequestBody PoolRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:pool:write");return ApiResponse.success(Map.of("id",service.createPool(b.poolCode,b.poolName,b.purpose,b.regionCodes,b.carrierCodes,b.sourceScope,b.admissionRule,b.detectionRule,b.dedupRule,b.priority,p,ip(r))));}
    @GetMapping("/resource-pools/{id}") public ApiResponse<?> pool(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:pool:read");return ApiResponse.success(service.pool(id));}
    @PutMapping("/resource-pools/{id}") public ApiResponse<?> updatePool(@PathVariable Long id,@RequestBody PoolRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:pool:write");service.updatePool(id,b.poolName,b.purpose,b.regionCodes,b.carrierCodes,b.sourceScope,b.admissionRule,b.detectionRule,b.dedupRule,b.priority,p,ip(r));return ApiResponse.success();}
    @GetMapping("/resource-pools/{id}/ips") public ApiResponse<?> poolIps(@PathVariable Long id,@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int size,@RequestParam(defaultValue="") String keyword,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:pool:read");return ApiResponse.success(service.poolIps(id,page,size,keyword));}
    @PostMapping("/resource-pools/{id}/enable") public ApiResponse<?> enablePool(@PathVariable Long id,@RequestBody ActionReasonRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:pool:status");service.poolStatus(id,"ACTIVE",b.reason,p,ip(r));return ApiResponse.success();}
    @PostMapping("/resource-pools/{id}/disable") public ApiResponse<?> disablePool(@PathVariable Long id,@RequestBody ActionReasonRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:pool:status");service.poolStatus(id,"DISABLED",b.reason,p,ip(r));return ApiResponse.success();}
    @PostMapping("/resource-pools/{id}/recalculate") public ApiResponse<?> recalcPool(@PathVariable Long id,@RequestBody ActionReasonRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:pool:write");return ApiResponse.success(Map.of("memberCount",service.recalculatePool(id,b.reason,p,ip(r))));}

    @GetMapping("/exclusive-allocations") public ApiResponse<?> exclusive(@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int size,@RequestParam(defaultValue="") String keyword,@RequestParam(defaultValue="") String status,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:exclusive:read");return ApiResponse.success(service.exclusive(page,size,keyword,status));}
    @GetMapping("/exclusive-allocations/{id}") public ApiResponse<?> exclusiveDetail(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:exclusive:read");return ApiResponse.success(service.exclusive(id));}
    @PostMapping("/exclusive-allocations/{id}/release") public ApiResponse<?> releaseExclusive(@PathVariable Long id,@RequestBody ActionReasonRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:exclusive:release");service.releaseExclusive(id,b.reason,p,ip(r));return ApiResponse.success();}

    @GetMapping("/domains") public ApiResponse<?> domains(@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int size,@RequestParam(defaultValue="") String keyword,@RequestParam(defaultValue="") String status,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:domain:read");return ApiResponse.success(service.domains(page,size,keyword,status));}
    @PostMapping("/domains") public ApiResponse<?> createDomain(@RequestBody DomainRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:domain:write");return ApiResponse.success(Map.of("id",service.createDomain(b.domainName,b.currentIpId,b.lineId,b.usageTypeCode,b.updateMode,p,ip(r))));}
    @GetMapping("/domains/{id}") public ApiResponse<?> domain(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:domain:read");return ApiResponse.success(service.domain(id));}
    @PutMapping("/domains/{id}") public ApiResponse<?> updateDomain(@PathVariable Long id,@RequestBody DomainRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:domain:write");service.updateDomain(id,b.currentIpId,b.lineId,b.usageTypeCode,b.updateMode,p,ip(r));return ApiResponse.success();}
    @PostMapping("/domains/{id}/refresh") public ApiResponse<?> refreshDomain(@PathVariable Long id,@RequestBody ActionReasonRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:domain:refresh");return ApiResponse.success(service.refreshDomain(id,b.reason,p,ip(r)));}

    @GetMapping("/suppliers") public ApiResponse<?> suppliers(@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int size,@RequestParam(defaultValue="") String keyword,@RequestParam(defaultValue="") String status,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:supplier:read");return ApiResponse.success(service.suppliers(page,size,keyword,status));}
    @PostMapping("/suppliers") public ApiResponse<?> createSupplier(@RequestBody SupplierRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:supplier:write");return ApiResponse.success(Map.of("id",service.createSupplier(b.supplierCode,b.supplierName,b.contactName,b.contactPhone,b.apiEndpoint,b.authTypeCode,b.apiAccount,b.secret,b.regionCodes,b.carrierCodes,b.fetchMode,p,ip(r))));}
    @GetMapping("/suppliers/{id}") public ApiResponse<?> supplier(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:supplier:read");return ApiResponse.success(service.supplier(id));}
    @PutMapping("/suppliers/{id}") public ApiResponse<?> updateSupplier(@PathVariable Long id,@RequestBody SupplierRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:supplier:write");service.updateSupplier(id,b.supplierName,b.contactName,b.contactPhone,b.apiEndpoint,b.authTypeCode,b.apiAccount,b.secret,b.regionCodes,b.carrierCodes,b.fetchMode,p,ip(r));return ApiResponse.success();}
    @PostMapping("/suppliers/{id}/test") public ApiResponse<?> testSupplier(@PathVariable Long id,@RequestBody ActionReasonRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:supplier:test");return ApiResponse.success(service.testSupplier(id,b.reason,p,ip(r)));}
    @PostMapping("/suppliers/{id}/enable") public ApiResponse<?> enableSupplier(@PathVariable Long id,@RequestBody ActionReasonRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:supplier:status");service.supplierStatus(id,"ACTIVE",b.reason,p,ip(r));return ApiResponse.success();}
    @PostMapping("/suppliers/{id}/pause") public ApiResponse<?> pauseSupplier(@PathVariable Long id,@RequestBody ActionReasonRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:supplier:status");service.supplierStatus(id,"PAUSED",b.reason,p,ip(r));return ApiResponse.success();}
    @PostMapping("/suppliers/{id}/disable") public ApiResponse<?> disableSupplier(@PathVariable Long id,@RequestBody ActionReasonRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:supplier:status");service.supplierStatus(id,"DISABLED",b.reason,p,ip(r));return ApiResponse.success();}

    @GetMapping("/sync-tasks") public ApiResponse<?> syncTasks(@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int size,@RequestParam(defaultValue="") String sourceType,@RequestParam(defaultValue="") String status,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:sync-task:read");return ApiResponse.success(service.syncTasks(page,size,sourceType,status));}
    @PostMapping("/sync-tasks") public ApiResponse<?> createSync(@RequestBody SyncRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:sync");return ApiResponse.success(Map.of("taskId",service.sync(b.sourceType,b.supplierId,b.targetPoolId,b.reason,p,ip(r))));}
    @GetMapping("/sync-tasks/{id}") public ApiResponse<?> syncTask(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:sync-task:read");return ApiResponse.success(service.syncTask(id));}
    @GetMapping("/sync-tasks/{id}/details") public ApiResponse<?> syncDetails(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal p){require(p,"resource:sync-task:read");return ApiResponse.success(service.syncDetails(id));}
    @PostMapping("/sync-tasks/{id}/retry") public ApiResponse<?> retrySync(@PathVariable Long id,@RequestBody ActionReasonRequest b,@AuthenticationPrincipal UserPrincipal p,HttpServletRequest r){require(p,"resource:sync-task:retry");return ApiResponse.success(Map.of("taskId",service.retrySync(id,b.reason,p,ip(r))));}

    public record ActionReasonRequest(String reason){}
    public record PoolRequest(String poolCode,String poolName,String purpose,List<String> regionCodes,List<String> carrierCodes,String sourceScope,Map<String,Object> admissionRule,Map<String,Object> detectionRule,Map<String,Object> dedupRule,Integer priority){}
    public record DomainRequest(String domainName,Long currentIpId,Long lineId,String usageTypeCode,String updateMode){}
    public record SupplierRequest(String supplierCode,String supplierName,String contactName,String contactPhone,String apiEndpoint,String authTypeCode,String apiAccount,String secret,List<String> regionCodes,List<String> carrierCodes,String fetchMode){}
    public record SyncRequest(String sourceType,Long supplierId,Long targetPoolId,String reason){}
}
