<script setup lang="ts">
import { onMounted,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import { orderServiceApi } from '@/api/orderService'
const route=useRoute(),router=useRouter(),row=ref<any>({}),loading=ref(false),id=Number(route.params.id),data=(r:any)=>r.data.data
async function load(){loading.value=true;try{row.value=data(await orderServiceApi.order(id))||{}}finally{loading.value=false}}
async function act(type:'confirm'|'cancel'|'provision'){const {value}=await ElMessageBox.prompt('请输入操作原因','订单操作',{inputValidator:v=>!!String(v||'').trim()||'必须填写原因'});if(type==='confirm')await orderServiceApi.confirmOrder(id,String(value));if(type==='cancel')await orderServiceApi.cancelOrder(id,String(value));if(type==='provision')await orderServiceApi.provisionOrder(id,String(value));ElMessage.success('操作完成');load()}
onMounted(load)
</script><template><div class="page"><div class="head"><div><h2>订单详情</h2><p>订单确认后进入服务开通流程；实际资源由代码内置规则选择。</p></div><div><el-button @click="router.back()">返回</el-button><el-button v-if="['DRAFT','PENDING_CONFIRM'].includes(row.status)" type="primary" @click="act('confirm')">确认订单</el-button><el-button v-if="row.status==='PENDING_PROVISION'" type="success" @click="act('provision')">开通服务</el-button><el-button v-if="!['PROVISIONED','COMPLETED','CANCELLED'].includes(row.status)" type="danger" @click="act('cancel')">取消</el-button></div></div><el-card shadow="never" v-loading="loading"><el-descriptions :column="3" border><el-descriptions-item label="订单号">{{row.order_no}}</el-descriptions-item><el-descriptions-item label="客户">{{row.customer_name}}</el-descriptions-item><el-descriptions-item label="状态">{{row.status}}</el-descriptions-item><el-descriptions-item label="金额">{{row.total_amount}} {{row.currency}}</el-descriptions-item><el-descriptions-item label="预计生效">{{row.expected_effective_at}}</el-descriptions-item><el-descriptions-item label="预计到期">{{row.expected_expire_at}}</el-descriptions-item><el-descriptions-item label="备注" :span="3">{{row.remark}}</el-descriptions-item></el-descriptions></el-card><el-card shadow="never"><template #header>订单项</template><el-table :data="row.items||[]"><el-table-column prop="line_no" label="#" width="60"/><el-table-column prop="product_name" label="产品"/><el-table-column prop="product_type" label="类型"/><el-table-column prop="package_name" label="套餐"/><el-table-column prop="quantity" label="数量"/><el-table-column prop="service_count" label="服务数"/><el-table-column prop="line_amount" label="金额"/></el-table></el-card></div></template><style scoped>.page{display:grid;gap:16px}.head{display:flex;justify-content:space-between}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494}</style>