<script setup lang="ts">
import { onMounted,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import { orderServiceApi } from '@/api/orderService'
import { useAuthStore } from '@/stores/auth'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),detail=ref<any>({}),credentials=ref<any[]>([]),tab=ref('basic'),id=Number(route.params.id),data=(r:any)=>r.data.data
async function load(){detail.value=data(await orderServiceApi.service(id))||{};if(auth.hasPermission('service:credential:read'))credentials.value=data(await orderServiceApi.credentials(id))||[]}
async function reset(){const {value}=await ElMessageBox.prompt('请输入重置原因','重置服务凭证',{inputValidator:v=>!!String(v||'').trim()||'必须填写原因'});const c=data(await orderServiceApi.resetCredential(id,String(value)));await ElMessageBox.alert(`类型：${c.type}\n账号：${c.account||'-'}\n新密钥：${c.secret}\n\n该密钥只在本次操作返回，请立即妥善保存。`,'一次性凭证',{confirmButtonText:'已保存'});load()}
async function addWhite(){const {value}=await ElMessageBox.prompt('请输入IPv4/IPv6地址','新增白名单');await orderServiceApi.addWhitelist(id,{ipAddress:String(value),remark:'后台添加'});ElMessage.success('已加入白名单');load()}
async function removeWhite(w:any){await orderServiceApi.removeWhitelist(id,w.id,'后台移除白名单');ElMessage.success('已停用');load()}
onMounted(load)
</script>
<template><div class="page"><div class="head"><div><el-button link @click="router.push('/services')">← 返回服务列表</el-button><h2>{{detail.service_no||'服务详情'}}</h2><p>{{detail.customer_name}} · {{detail.product_name}} · {{detail.status}}</p></div></div><el-card shadow="never"><el-tabs v-model="tab"><el-tab-pane label="基本信息" name="basic"><el-descriptions :column="3" border><el-descriptions-item label="客户">{{detail.customer_name}}</el-descriptions-item><el-descriptions-item label="产品">{{detail.product_name}}</el-descriptions-item><el-descriptions-item label="产品类型">{{detail.product_type}}</el-descriptions-item><el-descriptions-item label="订单">{{detail.order_no||'直接开通'}}</el-descriptions-item><el-descriptions-item label="套餐">{{detail.package_name||'-'}}</el-descriptions-item><el-descriptions-item label="交付方式"><el-tag>{{detail.delivery_mode==='EXTERNAL_PROXY'?'外部反向代理':'自有资源'}}</el-tag></el-descriptions-item><el-descriptions-item label="代码策略">{{detail.builtin_policy_code||'-'}}</el-descriptions-item><el-descriptions-item label="生效时间">{{detail.effective_at}}</el-descriptions-item><el-descriptions-item label="到期时间">{{detail.expire_at}}</el-descriptions-item><template v-if="detail.delivery_mode==='EXTERNAL_PROXY'"><el-descriptions-item label="外部采购">{{detail.purchase_no||detail.supplier_purchase_id}}</el-descriptions-item><el-descriptions-item label="反向代理">{{detail.proxy_no||detail.reverse_proxy_id}}</el-descriptions-item><el-descriptions-item label="平台代理入口">{{detail.platform_host}}<span v-if="detail.platform_port">:{{detail.platform_port}}</span></el-descriptions-item></template></el-descriptions></el-tab-pane>
<el-tab-pane label="资源/交付绑定" name="resources"><el-table :data="detail.resourceBindings||[]"><el-table-column prop="resource_type" label="资源类型"/><el-table-column prop="resource_id" label="资源ID"/><el-table-column prop="binding_role" label="作用"/><el-table-column prop="status" label="状态"/><el-table-column prop="effective_at" label="生效时间"/></el-table></el-tab-pane>
<el-tab-pane v-if="auth.hasPermission('service:credential:read')" label="服务凭证" name="credential"><div class="actions"><el-button v-if="auth.hasPermission('service:credential:reset')" type="primary" @click="reset">重置凭证</el-button></div><el-alert type="info" :closable="false" title="历史页面只展示掩码；新密钥只在创建/重置成功时返回一次。"/><el-table :data="credentials" style="margin-top:12px"><el-table-column prop="credential_type" label="类型"/><el-table-column prop="account_name" label="账号"/><el-table-column prop="secret_mask" label="密钥掩码"/><el-table-column prop="status" label="状态"/><el-table-column prop="expire_at" label="到期时间"/></el-table></el-tab-pane>
<el-tab-pane label="白名单" name="whitelist"><div class="actions"><el-button v-if="auth.hasPermission('service:whitelist')" type="primary" @click="addWhite">新增白名单</el-button></div><el-table :data="detail.whitelist||[]"><el-table-column prop="ip_address" label="IP地址"/><el-table-column prop="status" label="状态"/><el-table-column prop="remark" label="备注"/><el-table-column label="操作"><template #default="s"><el-button v-if="auth.hasPermission('service:whitelist')&&s.row.status==='ACTIVE'" link type="danger" @click="removeWhite(s.row)">停用</el-button></template></el-table-column></el-table></el-tab-pane>
<el-tab-pane label="变更记录" name="changes"><el-table :data="detail.changes||[]"><el-table-column prop="change_no" label="变更号"/><el-table-column prop="change_type" label="类型"/><el-table-column prop="status" label="状态"/><el-table-column prop="reason" label="原因"/><el-table-column prop="created_at" label="时间"/></el-table></el-tab-pane>
<el-tab-pane label="长效监控" name="long"><el-alert v-if="detail.product_type!=='LONG_IP'" type="info" :closable="false" title="仅长效IP服务需要创建客户专项监控。"/><el-table v-else :data="detail.longMonitors||[]"><el-table-column prop="monitor_no" label="监控编号"/><el-table-column label="目标"><template #default="s">{{s.row.target_host}}:{{s.row.target_port}}</template></el-table-column><el-table-column prop="current_status" label="状态"/><el-table-column prop="last_checked_at" label="最近检测"/><el-table-column label="操作"><template #default="s"><el-button link type="primary" @click="router.push(`/long-monitor/monitors/${s.row.id}`)">查看</el-button></template></el-table-column></el-table></el-tab-pane>
<el-tab-pane label="释放记录" name="release"><el-table :data="detail.releaseRecords||[]"><el-table-column prop="release_no" label="释放编号"/><el-table-column prop="trigger_type" label="触发方式"/><el-table-column prop="status" label="状态"/><el-table-column prop="created_at" label="时间"/><el-table-column prop="error_message" label="错误"/></el-table></el-tab-pane></el-tabs></el-card></div></template>
<style scoped>.page{display:grid;gap:16px}.head h2{margin:8px 0}.head p{margin:0;color:#7b8494}.actions{margin-bottom:12px}</style>
