<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import { orderServiceApi } from '@/api/orderService'
import { useAuthStore } from '@/stores/auth'
const router=useRouter(),auth=useAuthStore(),rows=ref<any[]>([]),total=ref(0),loading=ref(false);const q=reactive<any>({page:1,size:20,keyword:'',status:'',productType:''});const data=(r:any)=>r.data.data
async function load(){loading.value=true;try{const d=data(await orderServiceApi.services(q));rows.value=d.items;total.value=d.total}finally{loading.value=false}}
async function reason(r:any,type:string){const names:any={suspend:'暂停服务',resume:'恢复服务',terminate:'终止并释放'};const {value}=await ElMessageBox.prompt('请输入操作原因',names[type],{inputValidator:(v)=>!!String(v||'').trim()||'必须填写原因'});if(type==='suspend')await orderServiceApi.suspend(r.id,String(value));if(type==='resume')await orderServiceApi.resume(r.id,String(value));if(type==='terminate'){const x=data(await orderServiceApi.terminate(r.id,String(value)));if(x.status!=='SUCCESS')return ElMessage.error(x.message||'释放失败')}ElMessage.success('操作成功');load()}
async function renew(r:any){const {value}=await ElMessageBox.prompt('请输入续费天数','服务续费',{inputPattern:/^[1-9]\d*$/,inputErrorMessage:'请输入正整数'});const {value:reason}=await ElMessageBox.prompt('请输入续费原因','服务续费');await orderServiceApi.renew(r.id,Number(value),String(reason));ElMessage.success('续费成功');load()}
onMounted(load)
</script>
<template><div class="page"><div class="head"><div><h2>服务实例</h2><p>服务实例是客户真正可使用的业务对象，固化产品、套餐、资源策略和实际资源引用。</p></div></div><el-card shadow="never"><div class="filters"><el-input v-model="q.keyword" placeholder="服务号/客户" clearable/><el-select v-model="q.productType" placeholder="产品类型" clearable><el-option v-for="x in ['SHORT_IP','LONG_IP','EXCLUSIVE_IP','VPN','TUNNEL']" :key="x" :label="x" :value="x"/></el-select><el-select v-model="q.status" placeholder="状态" clearable><el-option v-for="x in ['PENDING','ACTIVE','SUSPENDED','EXPIRED','TERMINATED','PROVISION_FAILED']" :key="x" :label="x" :value="x"/></el-select><el-button type="primary" @click="q.page=1;load()">查询</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="service_no" label="服务号" width="190"/><el-table-column prop="customer_name" label="客户" min-width="150"/><el-table-column prop="product_name" label="产品" min-width="150"/><el-table-column prop="product_type" label="类型" width="120"/><el-table-column prop="package_name" label="套餐" min-width="130"/><el-table-column prop="status" label="状态" width="140"/><el-table-column prop="expire_at" label="到期时间" width="190"/><el-table-column label="操作" width="300" fixed="right"><template #default="s"><el-button link type="primary" @click="router.push(`/services/${s.row.id}`)">详情</el-button><el-button v-if="auth.hasPermission('service:status')&&s.row.status==='ACTIVE'" link @click="reason(s.row,'suspend')">暂停</el-button><el-button v-if="auth.hasPermission('service:status')&&s.row.status==='SUSPENDED'" link type="success" @click="reason(s.row,'resume')">恢复</el-button><el-button v-if="auth.hasPermission('service:renew')&&!['TERMINATED','PROVISION_FAILED'].includes(s.row.status)" link @click="renew(s.row)">续费</el-button><el-button v-if="auth.hasPermission('service:status')&&!['TERMINATED'].includes(s.row.status)" link type="danger" @click="reason(s.row,'terminate')">终止</el-button></template></el-table><div class="pager"><el-pagination v-model:current-page="q.page" v-model:page-size="q.size" :total="total" layout="total,sizes,prev,pager,next" @change="load"/></div></el-card></div></template>
<style scoped>.page{display:grid;gap:16px}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494}.filters{display:flex;gap:10px;margin-bottom:14px}.filters .el-input,.filters .el-select{max-width:230px}.pager{display:flex;justify-content:flex-end;margin-top:14px}</style>
