<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { resourceApi } from '@/api/resource'
import { useAuthStore } from '@/stores/auth'
const route=useRoute();const auth=useAuthStore();const rows=ref<any[]>([]);const total=ref(0);const loading=ref(false);const drawer=ref(false);const detail=ref<any>(null)
const type=computed(()=>String(route.meta.resourceType||'IP'));const title=computed(()=>String(route.meta.title||'基础资源'))
const query=reactive({page:1,size:20,keyword:'',status:'',sourceType:''})
async function load(){loading.value=true;try{const p:any={...query};if(type.value!=='IP')delete p.sourceType;const d=(await resourceApi.baseList(type.value,p)).data.data;rows.value=d.items;total.value=d.total}finally{loading.value=false}}
async function show(row:any){detail.value=(await resourceApi.baseDetail(type.value,row.id)).data.data;drawer.value=true}
async function sync(){const {value}=await ElMessageBox.prompt(`将从已配置的上游适配器同步${title.value}，请输入原因`,'触发资源同步',{inputValidator:v=>!!String(v||'').trim()||'必须填写原因'});const r=await resourceApi.syncBase(type.value,String(value));ElMessage.success(`已完成同步，任务ID ${r.data.data.taskId}`);await load()}
function statusType(v:string){return ['ONLINE','AVAILABLE','CONNECTED'].includes(v)?'success':['ABNORMAL','FAILED','UNAVAILABLE'].includes(v)?'danger':v==='UNKNOWN'?'info':'warning'}
watch(()=>route.fullPath,()=>{query.page=1;query.keyword='';query.status='';query.sourceType='';load()});onMounted(load)
</script>
<template><div class="page"><div class="head"><div><h2>{{ title }}</h2><p>该页面以同步、列表和查看为主，不对未确认的上游资源提供新增、修改、删除或远程控制。</p></div><el-button v-if="auth.hasPermission('resource:sync')" type="primary" @click="sync">立即同步</el-button></div>
<el-card shadow="never"><div class="filters"><el-input v-model="query.keyword" placeholder="编号/名称/IP" clearable @keyup.enter="query.page=1;load()"/><el-select v-model="query.status" placeholder="状态" clearable><el-option label="在线" value="ONLINE"/><el-option label="离线" value="OFFLINE"/><el-option label="异常" value="ABNORMAL"/><el-option label="未知" value="UNKNOWN"/><template v-if="type==='IP'"><el-option label="可用" value="AVAILABLE"/><el-option label="不可用" value="UNAVAILABLE"/><el-option label="停用" value="DISABLED"/></template></el-select><el-select v-if="type==='IP'" v-model="query.sourceType" placeholder="资源来源" clearable><el-option label="自有" value="SELF"/><el-option label="外部" value="EXTERNAL"/></el-select><el-button type="primary" @click="query.page=1;load()">查询</el-button></div>
<el-table :data="rows" v-loading="loading" stripe>
<template v-if="type==='CENTOS'"><el-table-column prop="resource_code" label="编号" width="145"/><el-table-column prop="resource_name" label="名称" min-width="150"/><el-table-column prop="management_ip" label="管理IP" width="140"/><el-table-column prop="region_code" label="地区" width="110"/><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="statusType(s.row.online_status)">{{s.row.online_status}}</el-tag></template></el-table-column><el-table-column prop="cpu_usage" label="CPU%" width="85"/><el-table-column prop="memory_usage" label="内存%" width="85"/><el-table-column prop="disk_usage" label="磁盘%" width="85"/></template>
<template v-else-if="type==='ROS'"><el-table-column prop="resource_code" label="编号" width="145"/><el-table-column prop="resource_name" label="ROS名称" min-width="150"/><el-table-column prop="centos_name" label="所属CentOS" min-width="140"/><el-table-column prop="management_ip" label="管理IP" width="140"/><el-table-column prop="carrier_code" label="运营商" width="100"/><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="statusType(s.row.online_status)">{{s.row.online_status}}</el-tag></template></el-table-column><el-table-column prop="line_total" label="线路数" width="80"/><el-table-column prop="current_ip_count" label="当前IP" width="80"/></template>
<template v-else-if="type==='LINE'"><el-table-column prop="resource_code" label="编号" width="145"/><el-table-column prop="resource_name" label="线路名称" min-width="150"/><el-table-column prop="ros_name" label="所属ROS" min-width="135"/><el-table-column prop="broadband_account_mask" label="家宽账号" min-width="130"/><el-table-column prop="current_public_ip" label="当前出口IP" width="145"/><el-table-column prop="carrier_code" label="运营商" width="100"/><el-table-column label="在线" width="90"><template #default="s"><el-tag :type="statusType(s.row.online_status)">{{s.row.online_status}}</el-tag></template></el-table-column><el-table-column prop="dial_status" label="拨号状态" width="110"/><el-table-column prop="latency_ms" label="延迟ms" width="85"/></template>
<template v-else><el-table-column prop="ip_address" label="IP地址" width="150"/><el-table-column prop="source_type" label="来源" width="90"/><el-table-column prop="line_name" label="线路" min-width="130"/><el-table-column prop="supplier_name" label="供应商" min-width="130"/><el-table-column prop="region_code" label="地区" width="100"/><el-table-column prop="carrier_code" label="运营商" width="100"/><el-table-column label="可用状态" width="110"><template #default="s"><el-tag :type="statusType(s.row.available_status)">{{s.row.available_status}}</el-tag></template></el-table-column><el-table-column prop="quality_score" label="质量分" width="85"/><el-table-column prop="pool_count" label="资源池" width="80"/></template>
<el-table-column label="操作" width="80" fixed="right"><template #default="s"><el-button link type="primary" @click="show(s.row)">详情</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" :total="total" :page-sizes="[20,50,100]" layout="total, sizes, prev, pager, next" @change="load"/></div></el-card>
<el-drawer v-model="drawer" :title="`${title}详情`" size="520px"><el-descriptions v-if="detail" :column="1" border><el-descriptions-item v-for="(v,k) in detail" :key="String(k)" :label="String(k)">{{v??'—'}}</el-descriptions-item></el-descriptions></el-drawer></div></template>
<style scoped>.page{display:grid;gap:16px}.head{display:flex;justify-content:space-between;align-items:flex-start}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494;max-width:760px}.filters{display:flex;gap:10px;margin-bottom:14px}.filters>*{max-width:260px}.pager{display:flex;justify-content:flex-end;margin-top:14px}</style>
