<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { resourceApi } from '@/api/resource'
import { useAuthStore } from '@/stores/auth'
const auth=useAuthStore();const rows=ref<any[]>([]);const total=ref(0);const loading=ref(false);const drawer=ref(false);const detail=ref<any>(null);const query=reactive({page:1,size:20,keyword:'',status:''})
async function load(){loading.value=true;try{const d=(await resourceApi.exclusive(query)).data.data;rows.value=d.items;total.value=d.total}finally{loading.value=false}}
async function show(r:any){detail.value=(await resourceApi.exclusiveDetail(r.id)).data.data;drawer.value=true}
async function release(r:any){const {value}=await ElMessageBox.prompt('释放后资源进入待回收状态，完成检测后才可重新入池。请输入释放原因','释放独享资源',{inputValidator:v=>!!String(v||'').trim()||'必须填写原因'});await resourceApi.releaseExclusive(r.id,String(value));ElMessage.success('已进入待回收状态');await load()}
onMounted(load)
</script><template><div class="page"><div class="head"><div><h2>独享资源</h2><p>展示由服务开通流程形成的独享IP/线路占用关系；本模块不手工制造占用，只负责查看与受控释放。</p></div></div><el-card shadow="never"><div class="filters"><el-input v-model="query.keyword" placeholder="分配编号/客户名称" clearable/><el-select v-model="query.status" placeholder="状态" clearable><el-option v-for="x in ['AVAILABLE','LOCKED','ALLOCATED','PENDING_RECYCLE','DISABLED']" :key="x" :label="x" :value="x"/></el-select><el-button type="primary" @click="query.page=1;load()">查询</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="allocation_no" label="分配编号" width="180"/><el-table-column prop="resource_type" label="资源类型" width="100"/><el-table-column prop="ip_address" label="IP" width="145"/><el-table-column prop="line_name" label="线路" min-width="130"/><el-table-column prop="customer_name" label="客户" min-width="150"/><el-table-column prop="service_id" label="服务ID" width="90"/><el-table-column prop="status" label="状态" width="140"/><el-table-column prop="health_status" label="健康" width="90"/><el-table-column prop="expire_at" label="到期时间" min-width="170"/><el-table-column label="操作" width="130" fixed="right"><template #default="s"><el-button link type="primary" @click="show(s.row)">详情</el-button><el-button v-if="auth.hasPermission('resource:exclusive:release')&&['LOCKED','ALLOCATED'].includes(s.row.status)" link type="danger" @click="release(s.row)">释放</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" :total="total" layout="total, sizes, prev, pager, next" @change="load"/></div></el-card><el-drawer v-model="drawer" title="独享资源详情" size="520px"><el-descriptions v-if="detail" :column="1" border><el-descriptions-item v-for="(v,k) in detail" :key="String(k)" :label="String(k)">{{v??'—'}}</el-descriptions-item></el-descriptions></el-drawer></div></template><style scoped>.page{display:grid;gap:16px}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494}.filters{display:flex;gap:10px;margin-bottom:14px}.filters>*{max-width:280px}.pager{display:flex;justify-content:flex-end;margin-top:14px}</style>
