<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { resourceApi } from '@/api/resource'
const router=useRouter();const loading=ref(false);const data=ref<any>({recentSyncTasks:[]})
async function load(){loading.value=true;try{data.value=(await resourceApi.overview()).data.data}finally{loading.value=false}}
const cards=[['CentOS','centos_total','centos_online','/resources/centos'],['ROS','ros_total','ros_online','/resources/ros'],['家宽/线路','line_total','line_online','/resources/lines'],['IP资源','ip_total','ip_available','/resources/ips']]
onMounted(load)
</script>
<template><div class="page" v-loading="loading"><div class="head"><div><h2>资源概览</h2><p>基础资源来自上游接口同步；平台负责统一展示、资源组织和业务引用。</p></div><el-button @click="load">刷新</el-button></div>
<div class="cards"><el-card v-for="c in cards" :key="String(c[0])" shadow="never" class="card" @click="router.push(String(c[3]))"><small>{{ c[0] }}</small><b>{{ data[String(c[1])]||0 }}</b><span>正常/可用 {{ data[String(c[2])]||0 }}</span></el-card><el-card shadow="never"><small>启用资源池</small><b>{{ data.active_pool_total||0 }}</b><span>统一组织自有/外部IP</span></el-card><el-card shadow="never"><small>外部IP</small><b>{{ data.external_ip_total||0 }}</b><span>已标准化入库</span></el-card><el-card shadow="never"><small>独享占用</small><b>{{ data.exclusive_active_total||0 }}</b><span>锁定/已分配</span></el-card><el-card shadow="never"><small>24h同步失败</small><b>{{ data.sync_failed_24h||0 }}</b><span>需运维关注</span></el-card></div>
<el-card shadow="never"><template #header><div class="section"><b>资源链路</b><span>CentOS → ROS → 家宽/线路 → IP → 资源池 → 产品资源策略</span></div></template><el-steps :active="5" align-center><el-step title="CentOS" description="基础主机列表"/><el-step title="ROS" description="关联上级CentOS"/><el-step title="家宽/线路" description="拨号与出口线路"/><el-step title="IP资源" description="统一IP对象"/><el-step title="资源池" description="业务可消费资源"/></el-steps></el-card>
<el-card shadow="never"><template #header><div class="section"><b>最近同步任务</b><el-button link type="primary" @click="router.push('/sync-tasks')">查看全部</el-button></div></template><el-table :data="data.recentSyncTasks||[]"><el-table-column prop="task_no" label="任务编号" min-width="180"/><el-table-column prop="source_type" label="类型" width="110"/><el-table-column prop="supplier_name" label="供应商" min-width="140"/><el-table-column prop="status" label="状态" width="120"/><el-table-column prop="received_count" label="接收" width="80"/><el-table-column prop="available_count" label="可用" width="80"/><el-table-column prop="created_at" label="创建时间" min-width="180"/></el-table></el-card></div></template>
<style scoped>.page{display:grid;gap:16px}.head,.section{display:flex;justify-content:space-between;align-items:center}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{cursor:pointer}.card small,.card span{display:block;color:#7b8494}.card b{display:block;font-size:28px;margin:8px 0}@media(max-width:1100px){.cards{grid-template-columns:repeat(2,1fr)}}</style>
