<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { resourceApi } from '@/api/resource'
import { useAuthStore } from '@/stores/auth'
const auth=useAuthStore();const rows=ref<any[]>([]);const total=ref(0);const loading=ref(false);const dialog=ref(false);const editId=ref<number|null>(null);const drawer=ref(false);const members=ref<any[]>([]);const options=ref<any>({regions:[],carriers:[]})
const query=reactive({page:1,size:20,keyword:'',status:''});const form=reactive<any>({poolCode:'',poolName:'',purpose:'',regionCodes:[],carrierCodes:[],sourceScope:'MIXED',priority:100,admissionRule:'{}',detectionRule:'{}',dedupRule:'{}'})
async function load(){loading.value=true;try{const d=(await resourceApi.pools(query)).data.data;rows.value=d.items;total.value=d.total}finally{loading.value=false}}
function reset(){Object.assign(form,{poolCode:'',poolName:'',purpose:'',regionCodes:[],carrierCodes:[],sourceScope:'MIXED',priority:100,admissionRule:'{}',detectionRule:'{}',dedupRule:'{}'})}
function add(){editId.value=null;reset();dialog.value=true}function asText(v:any){return JSON.stringify(v??{},null,2)}
function edit(r:any){editId.value=r.id;Object.assign(form,{poolCode:r.pool_code,poolName:r.pool_name,purpose:r.purpose||'',regionCodes:r.region_codes||[],carrierCodes:r.carrier_codes||[],sourceScope:r.source_scope,priority:r.priority,admissionRule:asText(r.admission_rule),detectionRule:asText(r.detection_rule),dedupRule:asText(r.dedup_rule)});dialog.value=true}
function parse(v:string,label:string){try{return JSON.parse(v||'{}')}catch{ElMessage.error(`${label}不是有效JSON`);throw new Error('invalid json')}}
async function save(){if(!form.poolCode||!form.poolName){ElMessage.warning('请填写资源池编码和名称');return}const payload={...form,admissionRule:parse(form.admissionRule,'准入规则'),detectionRule:parse(form.detectionRule,'检测规则'),dedupRule:parse(form.dedupRule,'去重规则')};editId.value?await resourceApi.updatePool(editId.value,payload):await resourceApi.createPool(payload);dialog.value=false;ElMessage.success('资源池已保存');await load()}
async function reasonAction(r:any,type:'enable'|'disable'|'recalc'){const labels={enable:'启用',disable:'停用',recalc:'重新计算成员'};const {value}=await ElMessageBox.prompt(`请输入${labels[type]}原因`,labels[type],{inputValidator:v=>!!String(v||'').trim()||'必须填写原因'});if(type==='enable')await resourceApi.enablePool(r.id,String(value));else if(type==='disable')await resourceApi.disablePool(r.id,String(value));else await resourceApi.recalcPool(r.id,String(value));ElMessage.success(`${labels[type]}完成`);await load()}
async function showMembers(r:any){members.value=(await resourceApi.poolIps(r.id,{page:1,size:500,keyword:''})).data.data.items;drawer.value=true}
onMounted(async()=>{options.value=(await resourceApi.options()).data.data;await load()})
</script>
<template><div class="page"><div class="head"><div><h2>IP资源池</h2><p>统一组织自有与外部IP，供后续产品资源策略引用；成员可按来源、地区、运营商等基础规则重新计算。</p></div><el-button v-if="auth.hasPermission('resource:pool:write')" type="primary" @click="add">新增资源池</el-button></div><el-card shadow="never"><div class="filters"><el-input v-model="query.keyword" placeholder="资源池编码/名称" clearable/><el-select v-model="query.status" placeholder="状态" clearable><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="DISABLED"/><el-option label="异常" value="ABNORMAL"/></el-select><el-button type="primary" @click="query.page=1;load()">查询</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="pool_code" label="编码" width="150"/><el-table-column prop="pool_name" label="名称" min-width="160"/><el-table-column prop="source_scope" label="来源范围" width="110"/><el-table-column prop="ip_count" label="IP总数" width="90"/><el-table-column prop="available_ip_count" label="可用IP" width="90"/><el-table-column prop="priority" label="优先级" width="80"/><el-table-column prop="status" label="状态" width="90"/><el-table-column label="操作" min-width="250" fixed="right"><template #default="s"><el-button link type="primary" @click="showMembers(s.row)">成员</el-button><el-button v-if="auth.hasPermission('resource:pool:write')" link @click="edit(s.row)">编辑</el-button><el-button v-if="auth.hasPermission('resource:pool:write')" link type="primary" @click="reasonAction(s.row,'recalc')">重新计算</el-button><el-button v-if="auth.hasPermission('resource:pool:status')&&s.row.status==='DISABLED'" link type="success" @click="reasonAction(s.row,'enable')">启用</el-button><el-button v-if="auth.hasPermission('resource:pool:status')&&s.row.status!=='DISABLED'" link type="warning" @click="reasonAction(s.row,'disable')">停用</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" :total="total" layout="total, sizes, prev, pager, next" @change="load"/></div></el-card>
<el-dialog v-model="dialog" :title="editId?'编辑资源池':'新增资源池'" width="700px"><el-form label-width="105px"><el-form-item label="资源池编码" required><el-input v-model="form.poolCode" :disabled="!!editId"/></el-form-item><el-form-item label="资源池名称" required><el-input v-model="form.poolName"/></el-form-item><el-form-item label="用途"><el-input v-model="form.purpose"/></el-form-item><el-form-item label="资源来源"><el-select v-model="form.sourceScope"><el-option label="自有" value="SELF"/><el-option label="外部" value="EXTERNAL"/><el-option label="混合" value="MIXED"/></el-select></el-form-item><el-form-item label="地区"><el-select v-model="form.regionCodes" multiple clearable style="width:100%"><el-option v-for="x in options.regions" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="运营商"><el-select v-model="form.carrierCodes" multiple clearable style="width:100%"><el-option v-for="x in options.carriers" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="优先级"><el-input-number v-model="form.priority" :min="1"/></el-form-item><el-form-item label="准入规则JSON"><el-input v-model="form.admissionRule" type="textarea" :rows="3"/></el-form-item><el-form-item label="检测规则JSON"><el-input v-model="form.detectionRule" type="textarea" :rows="3"/></el-form-item><el-form-item label="去重规则JSON"><el-input v-model="form.dedupRule" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
<el-drawer v-model="drawer" title="资源池IP成员" size="700px"><el-table :data="members"><el-table-column prop="ip_address" label="IP" width="150"/><el-table-column prop="source_type" label="来源" width="90"/><el-table-column prop="region_code" label="地区"/><el-table-column prop="carrier_code" label="运营商"/><el-table-column prop="available_status" label="状态"/><el-table-column prop="quality_score" label="质量分"/><el-table-column prop="source_reason" label="入池原因" min-width="160"/></el-table></el-drawer></div></template>
<style scoped>.page{display:grid;gap:16px}.head{display:flex;justify-content:space-between}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494;max-width:820px}.filters{display:flex;gap:10px;margin-bottom:14px}.filters>*{max-width:280px}.pager{display:flex;justify-content:flex-end;margin-top:14px}</style>
