<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { v12ResourceApi } from '@/api/v12Resource'
import { useAuthStore } from '@/stores/auth'
const router=useRouter(),auth=useAuthStore(),rows=ref<any[]>([]),total=ref(0),loading=ref(false),dialog=ref(false),editId=ref<number|null>(null)
const query=reactive({page:1,size:20,keyword:'',status:''});const form=reactive<any>({poolCode:'',poolName:'',poolType:'MIXED',purpose:'',regionCodes:[],carrierCodes:[],lineIds:[]});const data=(r:any)=>r.data.data
async function load(){loading.value=true;try{const d=data(await v12ResourceApi.pools(query));rows.value=d.items||[];total.value=d.total||0}finally{loading.value=false}}
function reset(){Object.assign(form,{poolCode:'',poolName:'',poolType:'MIXED',purpose:'',regionCodes:[],carrierCodes:[],lineIds:[]})}
function add(){editId.value=null;reset();dialog.value=true}
async function edit(r:any){editId.value=r.id;const d=data(await v12ResourceApi.pool(r.id));Object.assign(form,{poolCode:d.pool_code,poolName:d.pool_name,poolType:d.pool_type||'MIXED',purpose:d.purpose||'',regionCodes:d.region_codes||[],carrierCodes:d.carrier_codes||[],lineIds:[]});dialog.value=true}
async function save(){if(!form.poolCode||!form.poolName){ElMessage.warning('请填写资源池编码和名称');return}const payload={...form};if(editId.value)await v12ResourceApi.updatePool(editId.value,payload);else await v12ResourceApi.createPool(payload);dialog.value=false;ElMessage.success('资源池已保存');load()}
onMounted(load)
</script>
<template><div class="page"><div class="head"><div><h2>资源池</h2><p>资源池按家宽/线路组织，是代码内置产品资源规则使用的逻辑资源集合；外部供应商反向代理不进入该资源池。</p></div><el-button v-if="auth.hasPermission('resource:pool:write')" type="primary" @click="add">新增资源池</el-button></div><el-card shadow="never"><div class="filters"><el-input v-model="query.keyword" placeholder="资源池编码/名称" clearable/><el-select v-model="query.status" placeholder="状态" clearable><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="DISABLED"/><el-option label="异常" value="ABNORMAL"/></el-select><el-button type="primary" @click="query.page=1;load()">查询</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="pool_code" label="编码" width="150"/><el-table-column prop="pool_name" label="名称" min-width="170"/><el-table-column prop="pool_type" label="类型" width="110"/><el-table-column prop="line_count" label="线路总数" width="100"/><el-table-column prop="online_line_count" label="在线线路" width="100"/><el-table-column prop="distinct_ip_count" label="当前去重IP" width="110"/><el-table-column prop="status" label="状态" width="90"/><el-table-column prop="purpose" label="用途" min-width="180"/><el-table-column label="操作" width="150" fixed="right"><template #default="s"><el-button link type="primary" @click="router.push(`/resource-pools/${s.row.id}`)">详情/成员</el-button><el-button v-if="auth.hasPermission('resource:pool:write')" link @click="edit(s.row)">编辑</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" :total="total" layout="total,sizes,prev,pager,next" @change="load"/></div></el-card>
<el-dialog v-model="dialog" :title="editId?'编辑资源池':'新增资源池'" width="620px"><el-form label-width="105px"><el-form-item label="资源池编码" required><el-input v-model="form.poolCode" :disabled="!!editId"/></el-form-item><el-form-item label="资源池名称" required><el-input v-model="form.poolName"/></el-form-item><el-form-item label="资源池类型"><el-select v-model="form.poolType" style="width:100%"><el-option label="混合" value="MIXED"/><el-option label="共享/短效" value="SHARED"/><el-option label="长效" value="LONG"/><el-option label="独享" value="EXCLUSIVE"/><el-option label="VPN" value="VPN"/><el-option label="隧道" value="TUNNEL"/></el-select></el-form-item><el-form-item label="用途"><el-input v-model="form.purpose" type="textarea" :rows="3"/></el-form-item><el-alert type="info" :closable="false" title="线路成员请保存后进入“详情/成员”页面维护。产品资源选择、优先级和切换规则不在业务端配置，由代码内置策略实现。"/></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
<style scoped>.page{display:grid;gap:16px}.head{display:flex;justify-content:space-between}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494;max-width:900px}.filters{display:flex;gap:10px;margin-bottom:14px}.filters>*{max-width:280px}.pager{display:flex;justify-content:flex-end;margin-top:14px}</style>
