<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { resourceApi } from '@/api/resource'
const router=useRouter();const loading=ref(false);const data=ref<any>({recentSyncTasks:[]})
async function load(){loading.value=true;try{data.value=(await resourceApi.overview()).data.data}finally{loading.value=false}}
const cards=[['CentOS','centos_total','centos_online','/resources/centos'],['ROS','ros_total','ros_online','/resources/ros'],['家宽/线路','line_total','line_online','/resources/lines'],['资源池','active_pool_total','active_pool_total','/resource-pools']]
onMounted(load)
</script>
<template><div class="page" v-loading="loading"><div class="head"><div><h2>资源概览</h2><p>当前阶段 CentOS 与 ROS 按 1:1 部署：CentOS负责管理及B/C段聚合，ROS负责拨号执行；家宽/线路是资源池的基础成员。</p></div><el-button @click="load">刷新</el-button></div>
<div class="cards"><el-card v-for="c in cards" :key="String(c[0])" shadow="never" class="card" @click="router.push(String(c[3]))"><small>{{ c[0] }}</small><b>{{ data[String(c[1])]||0 }}</b><span>{{c[0]==='资源池'?'当前启用':`在线 ${data[String(c[2])]||0}`}}</span></el-card><el-card shadow="never"><small>外部供应商</small><b>{{ data.supplier_total||0 }}</b><span>外部资源独立交付</span></el-card><el-card shadow="never"><small>独享占用</small><b>{{ data.exclusive_active_total||0 }}</b><span>锁定/已分配</span></el-card><el-card shadow="never"><small>24h同步失败</small><b>{{ data.sync_failed_24h||0 }}</b><span>需运维关注</span></el-card></div>
<el-card shadow="never"><template #header><div class="section"><b>自有资源主链</b><span>CentOS（管理） → ROS（拨号） → 家宽/线路 → 当前公网IP</span></div></template><el-steps :active="4" align-center><el-step title="CentOS" description="管理、负载、B/C段聚合"/><el-step title="ROS" description="与CentOS 1:1，负责拨号"/><el-step title="家宽/线路" description="家宽账号/节点统一对象"/><el-step title="当前公网IP" description="线路当前拨号结果"/><el-step title="资源池" description="按来源属性组织线路"/></el-steps></el-card>
<el-card shadow="never"><template #header><div class="section"><b>最近同步任务</b><el-button link type="primary" @click="router.push('/sync-tasks')">查看全部</el-button></div></template><el-table :data="data.recentSyncTasks||[]"><el-table-column prop="task_no" label="任务编号" min-width="180"/><el-table-column prop="source_type" label="类型" width="110"/><el-table-column prop="supplier_name" label="供应商" min-width="140"/><el-table-column prop="status" label="状态" width="120"/><el-table-column prop="received_count" label="接收" width="80"/><el-table-column prop="available_count" label="可用" width="80"/><el-table-column prop="created_at" label="创建时间" min-width="180"/></el-table></el-card></div></template>
<style scoped>.page{display:grid;gap:16px}.head,.section{display:flex;justify-content:space-between;align-items:center}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{cursor:pointer}.card small,.card span{display:block;color:#7b8494}.card b{display:block;font-size:28px;margin:8px 0}@media(max-width:1100px){.cards{grid-template-columns:repeat(2,1fr)}}</style>
