<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { v12ResourceApi } from '@/api/v12Resource'
const route=useRoute(),router=useRouter(),id=Number(route.params.id),detail=ref<any>({}),rows=ref<any[]>([]),total=ref(0),page=ref(1),size=ref(20),loading=ref(false)
const data=(r:any)=>r.data.data
async function load(){loading.value=true;try{detail.value=data(await v12ResourceApi.pool(id));const d=data(await v12ResourceApi.poolLines(id,{page:page.value,size:size.value}));rows.value=d.items||[];total.value=d.total||0}finally{loading.value=false}}
onMounted(load)
</script>
<template><div class="page"><div class="head"><div><h2>资源池详情</h2><p>资源池以家宽/线路为成员，是产品代码内置资源规则使用的逻辑资源集合。</p></div><el-button @click="router.back()">返回</el-button></div><el-card shadow="never" v-loading="loading"><el-descriptions :column="3" border><el-descriptions-item label="资源池编码">{{detail.pool_code}}</el-descriptions-item><el-descriptions-item label="资源池名称">{{detail.pool_name}}</el-descriptions-item><el-descriptions-item label="类型">{{detail.pool_type}}</el-descriptions-item><el-descriptions-item label="线路总数">{{detail.line_count}}</el-descriptions-item><el-descriptions-item label="在线线路">{{detail.online_line_count}}</el-descriptions-item><el-descriptions-item label="当前去重IP">{{detail.distinct_ip_count}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.status}}</el-descriptions-item><el-descriptions-item label="用途" :span="2">{{detail.purpose}}</el-descriptions-item></el-descriptions></el-card><el-card shadow="never"><template #header>线路成员</template><el-table :data="rows" stripe><el-table-column prop="resource_code" label="线路编号" width="150"/><el-table-column prop="line_alias" label="线路别名"/><el-table-column prop="ros_name" label="ROS"/><el-table-column prop="broadband_account_mask" label="家宽账号"/><el-table-column prop="current_public_ip" label="当前IP" width="150"/><el-table-column prop="carrier_code" label="运营商"/><el-table-column prop="online_status" label="状态"/></el-table><div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" layout="total,sizes,prev,pager,next" @change="load"/></div></el-card></div></template>
<style scoped>.page{display:grid;gap:16px}.head{display:flex;justify-content:space-between}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494}.pager{display:flex;justify-content:flex-end;margin-top:14px}</style>