<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import { v12ResourceApi } from '@/api/v12Resource'
import { useAuthStore } from '@/stores/auth'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),id=Number(route.params.id)
const detail=ref<any>({}),rows=ref<any[]>([]),total=ref(0),loading=ref(false),activeTab=ref('ALL'),selected=ref<any[]>([]),operations=ref<any[]>([])
const q=reactive({page:1,size:20,keyword:'',status:''})
const addDialog=ref(false),candidateRows=ref<any[]>([]),candidateTotal=ref(0),candidateLoading=ref(false),candidateSelected=ref<any[]>([])
const cq=reactive({page:1,size:20,keyword:'',type:''})
const canWrite=computed(()=>auth.hasPermission('resource:pool:write'))
const data=(r:any)=>r.data.data
function lineTypeLabel(v:any){return v==='SHARED'?'共享':v==='LONG'?'长效':'未设置'}
function statusType(v:any){return v==='ONLINE'?'success':v==='ABNORMAL'?'warning':v==='OFFLINE'?'danger':'info'}
async function loadDetail(){detail.value=data(await v12ResourceApi.pool(id))}
async function loadLines(){if(!['ALL','SHARED','LONG'].includes(activeTab.value))return;loading.value=true;try{const type=activeTab.value==='ALL'?'':activeTab.value;const d=data(await v12ResourceApi.poolLines(id,{...q,type}));rows.value=d.items||[];total.value=d.total||0;selected.value=[]}finally{loading.value=false}}
async function loadOperations(){try{operations.value=data(await v12ResourceApi.poolOperations(id,200))||[]}catch{operations.value=[]}}
async function loadAll(){await Promise.all([loadDetail(),loadOperations()]);await loadLines()}
function resetFilter(){Object.assign(q,{page:1,size:20,keyword:'',status:''});loadLines()}
async function openAdd(){addDialog.value=true;Object.assign(cq,{page:1,size:20,keyword:'',type:''});await loadCandidates()}
async function loadCandidates(){candidateLoading.value=true;try{const d=data(await v12ResourceApi.candidatePoolLines(id,cq));candidateRows.value=d.items||[];candidateTotal.value=d.total||0;candidateSelected.value=[]}finally{candidateLoading.value=false}}
async function addLines(){if(!candidateSelected.value.length){ElMessage.warning('请选择要加入资源池的线路');return}const {value}=await ElMessageBox.prompt('请输入加入资源池的原因','加入线路',{inputValidator:v=>!!String(v||'').trim()||'必须填写原因'});await v12ResourceApi.addPoolLines(id,candidateSelected.value.map(x=>x.id),String(value));ElMessage.success('线路已加入资源池');addDialog.value=false;await loadAll()}
async function removeLines(items:any[]){if(!items.length){ElMessage.warning('请选择要移出的线路');return}const {value}=await ElMessageBox.prompt(`确认移出 ${items.length} 条线路，请填写原因`,'移出线路',{inputValidator:v=>!!String(v||'').trim()||'必须填写原因'});await v12ResourceApi.removePoolLines(id,items.map(x=>x.id),String(value));ElMessage.success('线路已移出资源池');await loadAll()}
watch(activeTab,async()=>{q.page=1;if(activeTab.value==='OPERATIONS')await loadOperations();else await loadLines()})
onMounted(loadAll)
</script>
<template><div class="page"><div class="head"><div><el-button link @click="router.back()">← 返回资源池</el-button><h2>{{detail.pool_name||'资源池详情'}}</h2><p>资源池按来源属性组织自有家宽线路；成员线路仅允许“共享 / 长效”，同一线路可属于多个符合来源属性的资源池。</p></div><el-button @click="loadAll">刷新</el-button></div>
<el-card shadow="never"><el-descriptions :column="4" border><el-descriptions-item label="资源池编号">{{detail.pool_code||'—'}}</el-descriptions-item><el-descriptions-item label="资源池名称">{{detail.pool_name||'—'}}</el-descriptions-item><el-descriptions-item label="省/市">{{detail.province_code||'—'}} / {{detail.city_code||'—'}}</el-descriptions-item><el-descriptions-item label="运营商">{{detail.carrier_code||'—'}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.status||'—'}}</el-descriptions-item><el-descriptions-item label="说明" :span="3">{{detail.purpose||'—'}}</el-descriptions-item></el-descriptions></el-card>
<div class="metric-grid"><el-card shadow="never"><span>ROS数量</span><strong>{{detail.ros_count||0}}</strong></el-card><el-card shadow="never"><span>线路总数</span><strong>{{detail.line_count||0}}</strong></el-card><el-card shadow="never"><span>共享线路</span><strong>{{detail.shared_line_count||0}}</strong></el-card><el-card shadow="never"><span>长效线路</span><strong>{{detail.long_line_count||0}}</strong></el-card><el-card shadow="never"><span>在线 / 异常</span><strong>{{detail.online_line_count||0}} / {{detail.abnormal_line_count||0}}</strong></el-card><el-card shadow="never"><span>当前IP / 去重IP</span><strong>{{detail.current_ip_count||0}} / {{detail.unique_ip_count||0}}</strong></el-card><el-card shadow="never"><span>B段数量</span><strong>{{detail.b_prefix_count||0}}</strong></el-card><el-card shadow="never"><span>C段数量</span><strong>{{detail.c_prefix_count||0}}</strong></el-card></div>
<el-card shadow="never"><el-tabs v-model="activeTab"><el-tab-pane label="全部线路" name="ALL"/><el-tab-pane label="共享线路" name="SHARED"/><el-tab-pane label="长效线路" name="LONG"/><el-tab-pane label="使用情况" name="USAGE"/><el-tab-pane label="变更记录" name="OPERATIONS"/></el-tabs>
<template v-if="['ALL','SHARED','LONG'].includes(activeTab)"><div class="toolbar"><el-input v-model="q.keyword" placeholder="线路编号/别名/IP" clearable style="width:240px" @keyup.enter="q.page=1;loadLines()"/><el-select v-model="q.status" placeholder="状态" clearable style="width:130px"><el-option label="在线" value="ONLINE"/><el-option label="异常" value="ABNORMAL"/><el-option label="离线" value="OFFLINE"/></el-select><el-button type="primary" @click="q.page=1;loadLines()">查询</el-button><el-button @click="resetFilter">重置</el-button><span class="spacer"/><el-button v-if="canWrite" type="primary" @click="openAdd">添加线路</el-button><el-button v-if="canWrite" :disabled="!selected.length" type="danger" plain @click="removeLines(selected)">批量移出</el-button></div><el-table :data="rows" v-loading="loading" stripe border @selection-change="selected=$event"><el-table-column v-if="canWrite" type="selection" width="46"/><el-table-column prop="resource_code" label="线路编号" width="145"/><el-table-column prop="line_alias" label="线路别名" min-width="130"/><el-table-column prop="line_type" label="线路类型" width="90"><template #default="s"><el-tag :type="s.row.line_type==='LONG'?'warning':'info'">{{lineTypeLabel(s.row.line_type)}}</el-tag></template></el-table-column><el-table-column prop="ros_code" label="ROS" width="130"/><el-table-column prop="current_public_ip" label="当前IP" width="135"/><el-table-column prop="province_code" label="省" width="85"/><el-table-column prop="city_code" label="市" width="85"/><el-table-column prop="carrier_code" label="运营商" width="90"/><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="statusType(s.row.online_status)">{{s.row.online_status}}</el-tag></template></el-table-column><el-table-column prop="latency_ms" label="延迟ms" width="80"/><el-table-column prop="bas_name" label="BAS/BRAS" min-width="130"/><el-table-column prop="joined_at" label="加入时间" min-width="165"/><el-table-column fixed="right" label="操作" width="130"><template #default="s"><el-button link type="primary" @click="router.push(`/resources/lines/${s.row.id}`)">线路详情</el-button><el-button v-if="canWrite" link type="danger" @click="removeLines([s.row])">移出</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="q.page" v-model:page-size="q.size" :total="total" layout="total,sizes,prev,pager,next" @change="loadLines"/></div></template>
<template v-else-if="activeTab==='USAGE'"><el-descriptions :column="3" border><el-descriptions-item label="当前服务数">{{detail.usage?.service_count||0}}</el-descriptions-item><el-descriptions-item label="当前客户数">{{detail.usage?.customer_count||0}}</el-descriptions-item><el-descriptions-item label="使用产品类型">{{detail.usage?.product_types||'—'}}</el-descriptions-item></el-descriptions><el-alert class="mt" type="info" :closable="false" title="资源池只提供共享/长效线路分组。具体产品选择、线路调度、保持与切换规则由后端内置代码实现。"/></template>
<template v-else><el-table :data="operations" stripe border><el-table-column prop="created_at" label="时间" min-width="165"/><el-table-column prop="operator_name" label="操作人" width="120"/><el-table-column prop="operation" label="操作" width="150"/><el-table-column prop="reason" label="原因" min-width="220"/><el-table-column prop="result" label="结果" width="90"/><el-table-column prop="error_message" label="错误信息" min-width="180"/></el-table></template></el-card>
<el-dialog v-model="addDialog" title="添加线路成员" width="980px"><el-alert type="info" :closable="false" title="这里只显示共享/长效线路，并自动按当前资源池的省/市/运营商来源属性筛选。"/><div class="toolbar mt"><el-input v-model="cq.keyword" placeholder="线路编号/别名/IP" clearable style="width:240px"/><el-select v-model="cq.type" placeholder="线路类型" clearable style="width:140px"><el-option label="共享" value="SHARED"/><el-option label="长效" value="LONG"/></el-select><el-button type="primary" @click="cq.page=1;loadCandidates()">查询</el-button></div><el-table :data="candidateRows" v-loading="candidateLoading" stripe border @selection-change="candidateSelected=$event"><el-table-column type="selection" width="46"/><el-table-column prop="resource_code" label="线路编号" width="145"/><el-table-column prop="line_alias" label="线路别名"/><el-table-column prop="line_type" label="类型" width="90"><template #default="s">{{lineTypeLabel(s.row.line_type)}}</template></el-table-column><el-table-column prop="ros_code" label="ROS"/><el-table-column prop="current_public_ip" label="当前IP"/><el-table-column prop="province_code" label="省"/><el-table-column prop="city_code" label="市"/><el-table-column prop="carrier_code" label="运营商"/><el-table-column prop="online_status" label="状态"/></el-table><div class="pager"><el-pagination v-model:current-page="cq.page" v-model:page-size="cq.size" :total="candidateTotal" layout="total,prev,pager,next" @change="loadCandidates"/></div><template #footer><el-button @click="addDialog=false">取消</el-button><el-button type="primary" :disabled="!candidateSelected.length" @click="addLines">加入资源池</el-button></template></el-dialog></div></template>
<style scoped>.page{display:grid;gap:16px}.head{display:flex;justify-content:space-between}.head h2{margin:8px 0 6px}.head p{margin:0;color:#7b8494;max-width:980px}.metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.metric-grid span{display:block;color:#7b8494;font-size:13px}.metric-grid strong{display:block;margin-top:8px;font-size:24px;color:#1677ff}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:4px 0 14px}.spacer{flex:1}.pager{display:flex;justify-content:flex-end;margin-top:14px}.mt{margin-top:14px}@media(max-width:1200px){.metric-grid{grid-template-columns:repeat(2,1fr)}}</style>