<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import { externalDeliveryApi } from '@/api/externalDelivery'
const router=useRouter(),rows=ref<any[]>([]),total=ref(0),loading=ref(false),q=reactive<any>({page:1,size:20,keyword:'',status:''});const data=(r:any)=>r.data.data
async function load(){loading.value=true;try{const d=data(await externalDeliveryApi.reverseProxies(q));rows.value=d.items||[];total.value=d.total||0}finally{loading.value=false}}
async function action(r:any,type:'apply'|'test'|'disable'){const {value}=await ElMessageBox.prompt('请输入操作原因','确认操作',{inputValidator:v=>!!String(v||'').trim()||'必须填写原因'});if(type==='apply')await externalDeliveryApi.applyReverseProxy(r.id,String(value));if(type==='test')await externalDeliveryApi.testReverseProxy(r.id,String(value));if(type==='disable')await externalDeliveryApi.disableReverseProxy(r.id,String(value));ElMessage.success('操作完成');load()}
onMounted(load)
</script>
<template><div class="page"><div><h2>反向代理交付</h2><p>将已采购的供应商套餐映射为平台代理入口，并绑定客户服务。</p></div><el-card shadow="never"><div class="filters"><el-input v-model="q.keyword" placeholder="代理编号/客户/入口" clearable/><el-select v-model="q.status" placeholder="状态" clearable><el-option v-for="x in ['PENDING','ACTIVE','ABNORMAL','DISABLED']" :key="x" :label="x" :value="x"/></el-select><el-button type="primary" @click="q.page=1;load()">查询</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="proxy_no" label="代理编号" width="180"/><el-table-column prop="customer_name" label="客户"/><el-table-column prop="supplier_name" label="供应商"/><el-table-column prop="upstream_host" label="上游地址"/><el-table-column label="平台代理入口" min-width="180"><template #default="s">{{s.row.platform_host}}:{{s.row.platform_port}}</template></el-table-column><el-table-column prop="protocol" label="协议"/><el-table-column prop="status" label="状态"/><el-table-column label="操作" width="230"><template #default="s"><el-button link type="primary" @click="router.push(`/reverse-proxies/${s.row.id}`)">详情</el-button><el-button link @click="action(s.row,'test')">测试</el-button><el-button v-if="s.row.status!=='ACTIVE'" link type="success" @click="action(s.row,'apply')">应用</el-button><el-button v-if="s.row.status!=='DISABLED'" link type="danger" @click="action(s.row,'disable')">停用</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="q.page" v-model:page-size="q.size" :total="total" layout="total,sizes,prev,pager,next" @change="load"/></div></el-card></div></template><style scoped>.page{display:grid;gap:16px}h2{margin:0 0 6px}p{margin:0;color:#7b8494}.filters{display:flex;gap:10px;margin-bottom:14px}.filters>*{max-width:260px}.pager{display:flex;justify-content:flex-end;margin-top:14px}</style>