<script setup lang="ts">
import{computed,onMounted,reactive,ref,watch}from'vue'
import{useRoute,useRouter}from'vue-router'
import{v12ResourceApi}from'@/api/v12Resource'
const route=useRoute(),router=useRouter(),rows=ref<any[]>([]),total=ref(0),loading=ref(false),options=ref<any>({ros:[],customers:[],lineTypes:[]})
const type=computed(()=>String(route.meta.resourceType||'CENTOS')),title=computed(()=>String(route.meta.title||'资源列表'))
const q=reactive<any>({page:1,size:20,keyword:'',status:'',autoSwitch:'',rosId:undefined,type:'',province:'',city:'',carrier:'',customerId:undefined})
async function load(){loading.value=true;try{let r:any;if(type.value==='CENTOS')r=await v12ResourceApi.centos(q);else if(type.value==='ROS')r=await v12ResourceApi.ros(q);else r=await v12ResourceApi.lines(q);rows.value=r.data.data.items;total.value=r.data.data.total}finally{loading.value=false}}
function detail(r:any){router.push(type.value==='CENTOS'?`/resources/centos/${r.id}`:type.value==='ROS'?`/resources/ros/${r.id}`:`/resources/lines/${r.id}`)}
function reset(){Object.assign(q,{page:1,size:20,keyword:'',status:'',autoSwitch:'',rosId:undefined,type:'',province:'',city:'',carrier:'',customerId:undefined});load()}
function tag(v:string){return ['ONLINE','NORMAL','CONNECTED'].includes(v)?'success':['OFFLINE','FAILED','ABNORMAL'].includes(v)?'danger':'info'}
function lineTypeLabel(v:any){return v==='SHARED'?'共享':v==='LONG'?'长效':'未设置'}
watch(()=>route.fullPath,()=>reset());onMounted(async()=>{try{options.value=(await v12ResourceApi.options()).data.data}catch{}await load()})
</script>
<template><div class="page-stack"><div class="page-head"><div><h1>{{title}}</h1><p v-if="type==='CENTOS'">对应现有“主机列表”，查看承载主机、硬件负载、ROS及线路汇总。</p><p v-else-if="type==='ROS'">对应现有“ROS主机”，重点查看主备切换、负载、B/C段及BAS汇总。</p><p v-else>统一“ROS逻辑线路 / 家宽账号 / 节点”为同一个家宽/线路业务对象；资源池线路类型仅允许“共享 / 长效”单选。</p></div><el-button @click="load">刷新</el-button></div>
<el-card shadow="never"><div class="filter-row"><el-input v-model="q.keyword" clearable placeholder="编号/名称/账号/IP/域名" style="width:260px" @keyup.enter="q.page=1;load()"/><el-select v-model="q.status" clearable placeholder="状态" style="width:130px"><el-option label="在线" value="ONLINE"/><el-option label="异常" value="ABNORMAL"/><el-option label="离线" value="OFFLINE"/></el-select><template v-if="type==='ROS'"><el-select v-model="q.autoSwitch" clearable placeholder="自动切换" style="width:130px"><el-option label="开启" value="true"/><el-option label="关闭" value="false"/></el-select></template><template v-if="type==='LINE'"><el-select v-model="q.rosId" clearable filterable placeholder="ROS" style="width:180px"><el-option v-for="x in options.ros" :key="x.id" :label="x.name" :value="x.id"/></el-select><el-select v-model="q.type" clearable placeholder="线路类型" style="width:130px"><el-option label="共享" value="SHARED"/><el-option label="长效" value="LONG"/></el-select><el-input v-model="q.province" placeholder="省" style="width:100px"/><el-input v-model="q.city" placeholder="市" style="width:100px"/><el-input v-model="q.carrier" placeholder="运营商" style="width:110px"/></template><el-button type="primary" @click="q.page=1;load()">查询</el-button><el-button @click="reset">重置</el-button></div></el-card>
<el-card shadow="never"><el-table :data="rows" v-loading="loading" stripe border>
<template v-if="type==='CENTOS'"><el-table-column prop="resource_code" label="ID" width="135"/><el-table-column prop="resource_name" label="主机名称" min-width="155"/><el-table-column prop="host_account" label="账号" width="120"/><el-table-column prop="management_ip" label="IP" width="135"/><el-table-column prop="location_name" label="地点" width="120"/><el-table-column prop="carrier_code" label="运营商" width="90"/><el-table-column prop="ros_count" label="ROS数" width="75"/><el-table-column prop="line_count" label="线路数" width="80"/><el-table-column prop="cpu_usage" label="CPU%" width="75"/><el-table-column prop="memory_usage" label="内存%" width="75"/><el-table-column prop="system_load" label="负载" width="75"/><el-table-column prop="disk_usage" label="硬盘%" width="75"/><el-table-column label="VPN" width="70"><template #default="s">{{s.row.vpn_supported?'支持':'否'}}</template></el-table-column><el-table-column prop="pppoe_server_name" label="PPPoE服务器" min-width="130"/><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="tag(s.row.online_status)">{{s.row.online_status}}</el-tag></template></el-table-column><el-table-column prop="last_communicated_at" label="心跳时间" min-width="165"/></template>
<template v-else-if="type==='ROS'"><el-table-column prop="resource_code" label="ROS ID" width="140"/><el-table-column prop="centos_code" label="CentOS" width="130"/><el-table-column prop="record_name" label="记录名" width="130"/><el-table-column prop="cpu_usage" label="CPU%" width="70"/><el-table-column prop="memory_usage" label="内存%" width="70"/><el-table-column prop="system_load" label="负载" width="70"/><el-table-column prop="disk_usage" label="硬盘%" width="70"/><el-table-column prop="line_total" label="线路" width="70"/><el-table-column prop="line_online" label="在线" width="70"/><el-table-column prop="current_ip_count" label="当前IP" width="78"/><el-table-column prop="b_prefix_count" label="B段数" width="75"/><el-table-column prop="c_prefix_count" label="C段数" width="75"/><el-table-column prop="bas_count" label="BAS数" width="75"/><el-table-column prop="ha_role" label="主备" width="80"/><el-table-column prop="replacement_ros_code" label="替换ROS" width="130"/><el-table-column prop="switch_status" label="切换状态" width="100"/><el-table-column label="自动切换" width="90"><template #default="s">{{s.row.auto_switch?'开启':'关闭'}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="tag(s.row.online_status)">{{s.row.online_status}}</el-tag></template></el-table-column><el-table-column prop="last_report_at" label="上报时间" min-width="165"/></template>
<template v-else><el-table-column prop="resource_code" label="线路ID" width="145"/><el-table-column prop="line_alias" label="线路别名" min-width="135"/><el-table-column prop="ros_code" label="ROS" width="135"/><el-table-column prop="broadband_account" label="拨号账号" min-width="150"/><el-table-column prop="current_public_ip" label="当前IP" width="135"/><el-table-column prop="http_port" label="HTTP" width="75"/><el-table-column prop="socks5_port" label="SOCKS5" width="80"/><el-table-column prop="domain_name" label="域名" min-width="170"/><el-table-column prop="customer_name" label="客户" min-width="135"/><el-table-column prop="line_type" label="类型" width="90"><template #default="s"><el-tag :type="s.row.line_type==='LONG'?'warning':'info'">{{lineTypeLabel(s.row.line_type)}}</el-tag></template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="tag(s.row.online_status)">{{s.row.online_status}}</el-tag></template></el-table-column><el-table-column prop="latency_ms" label="延迟ms" width="80"/><el-table-column prop="user_limit" label="限制人数" width="85"/><el-table-column prop="active_users" label="在用" width="65"/><el-table-column label="VPN重拨" width="85"><template #default="s">{{s.row.vpn_redial_monitor?'监控':'关闭'}}</template></el-table-column><el-table-column prop="bas_name" label="BAS/BRAS" min-width="140"/><el-table-column prop="province_code" label="省" width="85"/><el-table-column prop="city_code" label="市" width="85"/><el-table-column prop="carrier_code" label="运营商" width="90"/><el-table-column prop="last_ros_report_at" label="ROS上报" min-width="165"/></template>
<el-table-column fixed="right" label="操作" width="90"><template #default="s"><el-button link type="primary" @click="detail(s.row)">详情</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="q.page" v-model:page-size="q.size" :total="total" :page-sizes="[20,50,100]" layout="total,sizes,prev,pager,next" @change="load"/></div></el-card></div></template>
<style scoped>.page-stack{display:grid;gap:16px}.page-head{display:flex;justify-content:space-between}.page-head h1{margin:0;font-size:24px}.page-head p{margin:7px 0 0;color:#7b8495}.filter-row{display:flex;gap:10px;flex-wrap:wrap}.pager{display:flex;justify-content:flex-end;margin-top:14px}</style>
