<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { customerApi } from '@/api/customer'
import { useAuthStore } from '@/stores/auth'
const route=useRoute();const router=useRouter();const auth=useAuthStore();const detail=ref<any>(null);const credentials=ref<any[]>([]);const loading=ref(false);const id=Number(route.params.id)
const fmt=(v:any)=>v==null?'—':String(v)
async function load(){loading.value=true;try{detail.value=(await customerApi.detail(id)).data.data;if(auth.hasPermission('customer:credential:read'))credentials.value=(await customerApi.credentials(id)).data.data;else credentials.value=[]}finally{loading.value=false}}
onMounted(load)
</script>
<template><div v-loading="loading" class="page" v-if="detail"><div class="head"><div><el-button link @click="router.push('/customers')">← 返回客户列表</el-button><h2>{{ detail.customer.customer_name }}</h2><p>{{ detail.customer.customer_code }}</p></div><div><el-tag>{{ detail.customer.customer_type_code }}</el-tag> <el-tag type="success">{{ detail.customer.status }}</el-tag></div></div>
<div class="metrics"><el-card shadow="never"><small>服务总数</small><b>{{ detail.usage.service_total||0 }}</b></el-card><el-card shadow="never"><small>正常服务</small><b>{{ detail.usage.active_service_count||0 }}</b></el-card><el-card shadow="never"><small>IP提取次数</small><b>{{ detail.usage.extract_call_count||0 }}</b></el-card><el-card shadow="never"><small>返回IP数量</small><b>{{ detail.usage.extracted_ip_count||0 }}</b></el-card><el-card shadow="never"><small>使用请求</small><b>{{ detail.usage.usage_request_count||0 }}</b></el-card></div>
<el-card shadow="never"><template #header><b>客户档案</b></template><el-descriptions :column="3" border><el-descriptions-item label="客户编号">{{ fmt(detail.customer.customer_code) }}</el-descriptions-item><el-descriptions-item label="客户类型">{{ fmt(detail.customer.customer_type_code) }}</el-descriptions-item><el-descriptions-item label="认证状态">{{ fmt(detail.customer.auth_status) }}</el-descriptions-item><el-descriptions-item label="联系人">{{ fmt(detail.customer.contact_name) }}</el-descriptions-item><el-descriptions-item label="联系电话">{{ fmt(detail.customer.contact_phone) }}</el-descriptions-item><el-descriptions-item label="联系邮箱">{{ fmt(detail.customer.contact_email) }}</el-descriptions-item><el-descriptions-item label="业务负责人">{{ fmt(detail.customer.owner_name) }}</el-descriptions-item><el-descriptions-item label="创建时间">{{ fmt(detail.customer.created_at) }}</el-descriptions-item><el-descriptions-item label="备注">{{ fmt(detail.customer.remark) }}</el-descriptions-item></el-descriptions></el-card>
<el-card shadow="never"><el-tabs><el-tab-pane label="认证记录"><el-table :data="detail.authRecords"><el-table-column prop="auth_no" label="认证编号"/><el-table-column prop="auth_type_code" label="类型"/><el-table-column prop="status" label="状态"/><el-table-column prop="submitted_at" label="提交时间"/><el-table-column prop="reviewer_name" label="审核人"/><el-table-column prop="review_opinion" label="审核意见"/></el-table></el-tab-pane><el-tab-pane label="客户账号"><el-table :data="detail.accounts"><el-table-column prop="username" label="用户名"/><el-table-column prop="account_type_code" label="账号类型"/><el-table-column prop="status" label="状态"/><el-table-column prop="last_login_at" label="最后登录"/></el-table></el-tab-pane><el-tab-pane label="服务实例"><el-table :data="detail.services"><el-table-column prop="service_no" label="服务编号"/><el-table-column prop="product_name" label="产品"/><el-table-column prop="package_name" label="套餐"/><el-table-column prop="product_type" label="类型"/><el-table-column prop="status" label="状态"/><el-table-column prop="expire_at" label="到期时间"/><el-table-column prop="credential_count" label="凭证" width="70"/><el-table-column prop="whitelist_count" label="白名单" width="80"/></el-table></el-tab-pane><el-tab-pane v-if="auth.hasPermission('customer:credential:read')" label="服务认证信息"><el-alert title="这里只展示服务凭证引用和掩码，不返回Token、私钥或密码明文。" type="info" :closable="false"/><el-table :data="credentials"><el-table-column prop="service_no" label="服务编号"/><el-table-column prop="product_name" label="产品"/><el-table-column prop="credential_type" label="凭证类型"/><el-table-column prop="account_name" label="账号"/><el-table-column prop="secret_mask" label="凭证掩码"/><el-table-column prop="status" label="状态"/></el-table></el-tab-pane></el-tabs></el-card></div></template>
<style scoped>.page{display:grid;gap:16px}.head{display:flex;justify-content:space-between;align-items:flex-end}.head h2{margin:6px 0}.head p{margin:0;color:#7b8494}.metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.metrics small{display:block;color:#7b8494}.metrics b{display:block;font-size:26px;margin-top:8px}@media(max-width:1100px){.metrics{grid-template-columns:repeat(2,1fr)}}</style>
