<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { customerApi } from '@/api/customer'
import { useAuthStore } from '@/stores/auth'
const auth=useAuthStore();const rows=ref<any[]>([]);const customers=ref<any[]>([]);const options=ref<any>({authTypes:[]});const total=ref(0);const detail=ref<any>(null);const detailDialog=ref(false);const createDialog=ref(false);const query=reactive({page:1,size:20,keyword:'',status:''});const form=reactive<any>({customerId:null,authTypeCode:'ENTERPRISE',subjectName:'',documentNo:'',attachmentRefs:''})
const data=(r:any)=>r.data.data
async function load(){const r=data(await customerApi.authList(query));rows.value=r.items;total.value=r.total}
async function init(){options.value=data(await customerApi.options());customers.value=data(await customerApi.list({page:1,size:500})).items;await load()}
async function open(row:any){detail.value=data(await customerApi.authDetail(row.id));detailDialog.value=true}
async function create(){if(!form.customerId){ElMessage.warning('请选择客户');return}await customerApi.createAuth(form.customerId,{authTypeCode:form.authTypeCode,submittedData:{subjectName:form.subjectName,documentNo:form.documentNo},attachmentRefs:String(form.attachmentRefs||'').split(',').map((x:string)=>x.trim()).filter(Boolean)});createDialog.value=false;ElMessage.success('认证申请已创建');await load()}
async function review(row:any,approve:boolean){const {value}=await ElMessageBox.prompt('请输入审核意见',approve?'审核通过':'审核驳回',{inputValue:approve?'资料核验通过':'',inputValidator:(v)=>approve||!!String(v||'').trim()||'驳回必须填写原因'});approve?await customerApi.approveAuth(row.id,String(value||'')):await customerApi.rejectAuth(row.id,String(value||''));ElMessage.success('审核完成');detailDialog.value=false;await load()}
const json=(v:any)=>typeof v==='string'?v:JSON.stringify(v??{},null,2)
onMounted(init)
</script>
<template><div class="page"><div class="head"><div><h2>客户认证</h2><p>区分个人/企业认证，保留完整申请与审核记录。</p></div><el-button v-if="auth.hasPermission('customer:write')" type="primary" @click="createDialog=true">新建认证申请</el-button></div><el-alert title="M3 暂以 JSON 保存认证资料，正式接入实名认证/企业认证服务后再固化证件字段与附件模型。" type="info" :closable="false"/>
<el-card shadow="never"><div class="filters"><el-input v-model="query.keyword" placeholder="认证编号/客户" clearable/><el-select v-model="query.status" placeholder="审核状态" clearable><el-option label="待审核" value="PENDING"/><el-option label="审核中" value="REVIEWING"/><el-option label="已通过" value="APPROVED"/><el-option label="已驳回" value="REJECTED"/></el-select><el-button type="primary" @click="query.page=1;load()">查询</el-button></div><el-table :data="rows" stripe><el-table-column prop="auth_no" label="认证编号" width="180"/><el-table-column prop="customer_name" label="客户"/><el-table-column prop="auth_type_code" label="类型" width="100"/><el-table-column prop="status" label="状态" width="100"/><el-table-column prop="submitted_at" label="提交时间" width="190"/><el-table-column prop="reviewer_name" label="审核人" width="110"/><el-table-column label="操作" width="180"><template #default="s"><el-button link @click="open(s.row)">详情</el-button><template v-if="auth.hasPermission('customer:auth:review')&&['PENDING','REVIEWING'].includes(s.row.status)"><el-button link type="success" @click="review(s.row,true)">通过</el-button><el-button link type="danger" @click="review(s.row,false)">驳回</el-button></template></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" :total="total" layout="total, prev, pager, next" @change="load"/></div></el-card>
<el-dialog v-model="createDialog" title="新建认证申请" width="600px"><el-form label-width="120px"><el-form-item label="客户"><el-select v-model="form.customerId" filterable style="width:100%" @change="(id:number)=>{const c=customers.find(x=>x.id===id);if(c)form.authTypeCode=c.customer_type_code}"><el-option v-for="c in customers" :key="c.id" :label="`${c.customer_code} · ${c.customer_name}`" :value="c.id"/></el-select></el-form-item><el-form-item label="认证类型"><el-select v-model="form.authTypeCode" style="width:100%"><el-option v-for="x in options.authTypes" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="认证主体名称"><el-input v-model="form.subjectName"/></el-form-item><el-form-item label="证件/主体编号"><el-input v-model="form.documentNo"/></el-form-item><el-form-item label="附件引用"><el-input v-model="form.attachmentRefs" placeholder="多个引用用逗号分隔"/></el-form-item></el-form><template #footer><el-button @click="createDialog=false">取消</el-button><el-button type="primary" @click="create">提交</el-button></template></el-dialog>
<el-dialog v-model="detailDialog" title="认证详情" width="680px"><template v-if="detail"><el-descriptions :column="2" border><el-descriptions-item label="认证编号">{{ detail.auth_no }}</el-descriptions-item><el-descriptions-item label="客户">{{ detail.customer_name }}</el-descriptions-item><el-descriptions-item label="类型">{{ detail.auth_type_code }}</el-descriptions-item><el-descriptions-item label="状态">{{ detail.status }}</el-descriptions-item><el-descriptions-item label="审核人">{{ detail.reviewer_name||'—' }}</el-descriptions-item><el-descriptions-item label="审核意见">{{ detail.review_opinion||'—' }}</el-descriptions-item></el-descriptions><h4>提交资料</h4><pre>{{ json(detail.submitted_data) }}</pre><h4>附件引用</h4><pre>{{ json(detail.attachment_refs) }}</pre></template></el-dialog></div></template>
<style scoped>.page{display:grid;gap:14px}.head{display:flex;justify-content:space-between}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494}.filters{display:flex;gap:10px;margin-bottom:14px}.filters .el-input{max-width:320px}.filters .el-select{width:180px}.pager{display:flex;justify-content:flex-end;margin-top:14px}pre{background:#f6f7f9;padding:12px;border-radius:6px;white-space:pre-wrap}</style>
