<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { customerApi } from '@/api/customer'
import { useAuthStore } from '@/stores/auth'
const auth=useAuthStore();const rows=ref<any[]>([]);const customers=ref<any[]>([]);const options=ref<any>({accountTypes:[]});const total=ref(0);const dialog=ref(false);const query=reactive({page:1,size:20,keyword:'',status:''});const form=reactive<any>({customerId:null,username:'',password:'',accountTypeCode:'DEFAULT'})
const data=(r:any)=>r.data.data
async function load(){const r=data(await customerApi.accountList(query));rows.value=r.items;total.value=r.total}
async function init(){options.value=data(await customerApi.options());customers.value=data(await customerApi.list({page:1,size:500})).items;await load()}
function add(){Object.assign(form,{customerId:null,username:'',password:'',accountTypeCode:'DEFAULT'});dialog.value=true}
async function save(){if(!form.customerId||!form.username||String(form.password).length<6){ElMessage.warning('请选择客户并填写至少6位密码');return}await customerApi.createAccount(form);dialog.value=false;ElMessage.success('客户账号已创建');await load()}
async function reset(row:any){const {value:password}=await ElMessageBox.prompt('请输入新密码','重置密码',{inputType:'password',inputPattern:/.{6,}/,inputErrorMessage:'密码至少6位'});const {value:reason}=await ElMessageBox.prompt('请输入重置原因','操作审计',{inputValidator:(v)=>!!String(v||'').trim()||'必须填写原因'});await customerApi.resetAccountPassword(row.id,String(password),String(reason));ElMessage.success('密码已重置')}
async function action(row:any,type:'freezeAccount'|'resumeAccount'|'disableAccount'){const label=type==='freezeAccount'?'冻结':type==='resumeAccount'?'恢复':'停用';const {value}=await ElMessageBox.prompt(`请输入${label}原因`,`${label}客户账号`,{inputValidator:(v)=>!!String(v||'').trim()||'必须填写原因'});await customerApi[type](row.id,String(value));ElMessage.success(`${label}成功`);await load()}
onMounted(init)
</script>
<template><div class="page"><div class="head"><div><h2>客户账号</h2><p>管理客户登录/API账号。服务Token、VPN私钥等凭证不存放在此表。</p></div><el-button v-if="auth.hasPermission('customer:account:write')" type="primary" @click="add">创建账号</el-button></div><el-card shadow="never"><div class="filters"><el-input v-model="query.keyword" placeholder="用户名/客户" clearable/><el-select v-model="query.status" placeholder="状态" clearable><el-option label="正常" value="ACTIVE"/><el-option label="冻结" value="FROZEN"/><el-option label="停用" value="DISABLED"/></el-select><el-button type="primary" @click="query.page=1;load()">查询</el-button></div><el-table :data="rows" stripe><el-table-column prop="username" label="用户名"/><el-table-column prop="customer_name" label="客户"/><el-table-column prop="customer_code" label="客户编号" width="160"/><el-table-column prop="account_type_code" label="账号类型" width="110"/><el-table-column prop="status" label="状态" width="90"/><el-table-column prop="last_login_at" label="最后登录" width="190"/><el-table-column label="操作" width="250"><template #default="s"><template v-if="auth.hasPermission('customer:account:write')"><el-button link @click="reset(s.row)">重置密码</el-button><el-button v-if="s.row.status==='ACTIVE'" link type="warning" @click="action(s.row,'freezeAccount')">冻结</el-button><el-button v-if="s.row.status==='FROZEN'" link type="success" @click="action(s.row,'resumeAccount')">恢复</el-button><el-button v-if="s.row.status!=='DISABLED'" link type="danger" @click="action(s.row,'disableAccount')">停用</el-button></template></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" :total="total" layout="total, prev, pager, next" @change="load"/></div></el-card>
<el-dialog v-model="dialog" title="创建客户账号" width="560px"><el-form label-width="100px"><el-form-item label="客户"><el-select v-model="form.customerId" filterable style="width:100%"><el-option v-for="c in customers" :key="c.id" :label="`${c.customer_code} · ${c.customer_name}`" :value="c.id"/></el-select></el-form-item><el-form-item label="用户名"><el-input v-model="form.username"/></el-form-item><el-form-item label="初始密码"><el-input v-model="form.password" type="password" show-password/></el-form-item><el-form-item label="账号类型"><el-select v-model="form.accountTypeCode" style="width:100%"><el-option v-for="x in options.accountTypes" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">创建</el-button></template></el-dialog></div></template>
<style scoped>.page{display:grid;gap:16px}.head{display:flex;justify-content:space-between}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494}.filters{display:flex;gap:10px;margin-bottom:14px}.filters .el-input{max-width:320px}.filters .el-select{width:180px}.pager{display:flex;justify-content:flex-end;margin-top:14px}</style>
