<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import { productApi } from '@/api/product';import { useAuthStore } from '@/stores/auth'
const route=useRoute(),auth=useAuthStore();const rows=ref<any[]>([]),total=ref(0),loading=ref(false),dialog=ref(false),editId=ref<number|null>(null),options=ref<any>({products:[]});const query=reactive<any>({page:1,size:20,keyword:'',status:'',productId:route.query.productId?Number(route.query.productId):null});const form=reactive<any>({});const data=(r:any)=>r.data.data
function reset(){Object.assign(form,{packageCode:'',productId:query.productId||null,packageName:'',serviceDays:30,ipCount:null,extractQuota:null,trafficQuotaBytes:null,concurrencyLimit:null,deviceLimit:null,whitelistLimit:null,changeIpLimit:null,price:0,currency:'CNY',quotaConfig:{}})}
async function load(){loading.value=true;try{const r=data(await productApi.packages(query));rows.value=r.items;total.value=r.total}finally{loading.value=false}}
async function loadOptions(){options.value=data(await productApi.options())}
function add(){editId.value=null;reset();dialog.value=true} function edit(r:any){editId.value=r.id;Object.assign(form,{packageCode:r.package_code,productId:r.product_id,packageName:r.package_name,serviceDays:r.service_days,ipCount:r.ip_count,extractQuota:r.extract_quota,trafficQuotaBytes:r.traffic_quota_bytes,concurrencyLimit:r.concurrency_limit,deviceLimit:r.device_limit,whitelistLimit:r.whitelist_limit,changeIpLimit:r.change_ip_limit,price:r.price,currency:r.currency,quotaConfig:r.quota_config||{}});dialog.value=true}
async function save(){if(!form.packageCode||!form.productId||!form.packageName){ElMessage.warning('请填写套餐编号、产品和名称');return}editId.value?await productApi.updatePackage(editId.value,form):await productApi.createPackage(form);dialog.value=false;ElMessage.success('套餐已保存');await load()}
async function action(r:any,t:'enable'|'disable'|'copy'){const n={enable:'启用',disable:'停用',copy:'复制'};const {value}=await ElMessageBox.prompt(`请输入${n[t]}原因`,`${n[t]}套餐`,{inputValidator:v=>!!String(v||'').trim()||'必须填写原因'});if(t==='enable')await productApi.enablePackage(r.id,String(value));else if(t==='disable')await productApi.disablePackage(r.id,String(value));else await productApi.copyPackage(r.id,String(value));ElMessage.success(`${n[t]}成功`);await load()}
onMounted(async()=>{await loadOptions();await load()})
</script>
<template><div class="page"><div class="head"><div><h2>套餐管理</h2><p>套餐只描述可售期限、数量、配额和价格；订单与服务会保存套餐快照。</p></div><el-button v-if="auth.hasPermission('product:package:write')" type="primary" @click="add">新增套餐</el-button></div><el-card shadow="never"><div class="filters"><el-input v-model="query.keyword" placeholder="套餐编号/名称" clearable/><el-select v-model="query.productId" placeholder="所属产品" clearable><el-option v-for="x in options.products" :key="x.id" :label="x.product_name" :value="x.id"/></el-select><el-select v-model="query.status" placeholder="状态" clearable><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="DISABLED"/></el-select><el-button type="primary" @click="query.page=1;load()">查询</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="package_code" label="套餐编号" width="150"/><el-table-column prop="package_name" label="套餐名称" min-width="160"/><el-table-column prop="product_name" label="产品" min-width="160"/><el-table-column prop="service_days" label="有效天数" width="90"/><el-table-column prop="ip_count" label="IP数" width="80"/><el-table-column prop="extract_quota" label="提取配额" width="110"/><el-table-column prop="concurrency_limit" label="并发" width="80"/><el-table-column prop="price" label="价格" width="100"/><el-table-column prop="status" label="状态" width="90"/><el-table-column label="操作" width="200" fixed="right"><template #default="s"><el-button v-if="auth.hasPermission('product:package:write')" link @click="edit(s.row)">编辑</el-button><el-button v-if="s.row.status==='ACTIVE'" link type="warning" @click="action(s.row,'disable')">停用</el-button><el-button v-else link type="success" @click="action(s.row,'enable')">启用</el-button><el-button link @click="action(s.row,'copy')">复制</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" layout="total, sizes, prev, pager, next" :total="total" @change="load"/></div></el-card>
<el-dialog v-model="dialog" :title="editId?'编辑套餐':'新增套餐'" width="760px"><el-form label-width="120px"><el-form-item label="套餐编号" required><el-input v-model="form.packageCode" :disabled="!!editId"/></el-form-item><el-form-item label="所属产品" required><el-select v-model="form.productId" :disabled="!!editId" style="width:100%"><el-option v-for="x in options.products" :key="x.id" :label="`${x.product_name} (${x.product_type})`" :value="x.id"/></el-select></el-form-item><el-form-item label="套餐名称" required><el-input v-model="form.packageName"/></el-form-item><div class="grid"><el-form-item label="有效天数"><el-input-number v-model="form.serviceDays" :min="1"/></el-form-item><el-form-item label="IP数量"><el-input-number v-model="form.ipCount" :min="0"/></el-form-item><el-form-item label="提取配额"><el-input-number v-model="form.extractQuota" :min="0"/></el-form-item><el-form-item label="流量配额(Byte)"><el-input-number v-model="form.trafficQuotaBytes" :min="0"/></el-form-item><el-form-item label="并发上限"><el-input-number v-model="form.concurrencyLimit" :min="0"/></el-form-item><el-form-item label="设备上限"><el-input-number v-model="form.deviceLimit" :min="0"/></el-form-item><el-form-item label="白名单上限"><el-input-number v-model="form.whitelistLimit" :min="0"/></el-form-item><el-form-item label="换IP上限"><el-input-number v-model="form.changeIpLimit" :min="0"/></el-form-item><el-form-item label="价格"><el-input-number v-model="form.price" :min="0" :precision="2"/></el-form-item></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
<style scoped>.page{display:grid;gap:16px}.head{display:flex;justify-content:space-between}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494}.filters{display:flex;gap:10px;margin-bottom:14px}.filters>*{max-width:240px}.pager{display:flex;justify-content:flex-end;margin-top:14px}.grid{display:grid;grid-template-columns:1fr 1fr}</style>
