<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { productApi } from '@/api/product'
import { useAuthStore } from '@/stores/auth'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),id=Number(route.params.id),p=ref<any>({}),options=ref<any>({}),packages=ref<any[]>([]),base=reactive<any>({}),cfg=reactive<any>({})
const data=(r:any)=>r.data.data;const names:any={SHORT_IP:'短效IP',LONG_IP:'长效IP',EXCLUSIVE_IP:'独享IP',VPN:'VPN',TUNNEL:'隧道'}
async function load(){p.value=data(await productApi.product(id));options.value=data(await productApi.options());Object.assign(base,{productCode:p.value.product_code,productName:p.value.product_name,productType:p.value.product_type,accessModeCode:p.value.access_mode_code,protocolCodes:p.value.protocol_codes||[],authModeCodes:p.value.auth_mode_codes||[],resourceMode:p.value.resource_mode,regionCodes:p.value.region_codes||[],carrierCodes:p.value.carrier_codes||[],description:p.value.description||''});Object.keys(cfg).forEach(k=>delete cfg[k]);const c=p.value.type_config||{};if(p.value.product_type==='SHORT_IP')Object.assign(cfg,{ipValidSeconds:c.ip_valid_seconds||60,singleExtractLimit:c.single_extract_limit||10,extractRateLimit:c.extract_rate_limit||null,extractRateWindowSeconds:c.extract_rate_window_seconds||60,dedupPeriodSeconds:c.dedup_period_seconds||300,whitelistRequired:c.whitelist_required??true});if(p.value.product_type==='LONG_IP')Object.assign(cfg,{holdPeriodSeconds:c.hold_period_seconds||86400,bindType:c.bind_type||'LINE',autoReplace:c.auto_replace??true,failureThreshold:c.failure_threshold||3});if(p.value.product_type==='EXCLUSIVE_IP')Object.assign(cfg,{exclusiveResourceType:'LINE',resourceCountDefault:c.resource_count_default||1,lockTimeoutSeconds:c.lock_timeout_seconds||300});if(p.value.product_type==='VPN')Object.assign(cfg,{vpnProtocolCode:c.vpn_protocol_code||'TBD',credentialTypeCode:c.credential_type_code||'USERNAME_PASSWORD',defaultDeviceLimit:c.default_device_limit||1,defaultConnectionLimit:c.default_connection_limit||1});if(p.value.product_type==='TUNNEL')Object.assign(cfg,{entryDomainId:c.entry_domain_id||null,entryHost:c.entry_host||'',entryPort:c.entry_port||18080,sessionHoldSeconds:c.session_hold_seconds||300,concurrencyLimit:c.concurrency_limit||100});packages.value=data(await productApi.packages({page:1,size:20,productId:id})).items||[]}
async function saveBase(){await productApi.updateProduct(id,{...base,typeConfig:{}});ElMessage.success('通用配置已保存');load()}
async function saveConfig(){const c:any={...cfg};if(p.value.product_type==='SHORT_IP')c.switchPolicy={mode:'BUILTIN'};if(p.value.product_type==='LONG_IP')c.failoverPolicy={mode:'BUILTIN'};if(p.value.product_type==='EXCLUSIVE_IP'){c.exclusiveResourceType='LINE';c.replacementRule={mode:'BUILTIN'};c.releaseRule={mode:'BUILTIN'}}if(p.value.product_type==='VPN')c.outboundPolicy={mode:'BUILTIN'};if(p.value.product_type==='TUNNEL')c.ipSwitchPolicy={mode:'BUILTIN'};await productApi.updateConfig(id,c);ElMessage.success('专项业务参数已保存');load()}
onMounted(load)
</script>
<template><div class="page"><div class="head"><div><el-button link @click="router.push('/products')">← 返回产品列表</el-button><h2>{{p.product_name}} <el-tag>{{names[p.product_type]||p.product_type}}</el-tag></h2><p>{{p.product_code}} · {{p.status}} · 内置策略 {{p.builtin_policy_code||('BUILTIN_'+p.product_type)}}</p></div></div><el-alert type="info" :closable="false" title="V1.2：产品的资源选择、优先级、切换和故障转移等资源策略由代码层实现，业务端不提供“产品资源策略”配置。"/>
<el-tabs type="border-card"><el-tab-pane label="通用配置"><el-form label-width="120px" class="form"><el-form-item label="产品编号"><el-input v-model="base.productCode" disabled/></el-form-item><el-form-item label="产品名称"><el-input v-model="base.productName"/></el-form-item><el-form-item label="产品类型"><el-input :model-value="names[base.productType]||base.productType" disabled/></el-form-item><el-form-item label="接入方式"><el-select v-model="base.accessModeCode" style="width:100%"><el-option v-for="x in options.accessModes||[]" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="代理协议"><el-select v-model="base.protocolCodes" multiple style="width:100%"><el-option v-for="x in options.protocols||[]" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="认证方式"><el-select v-model="base.authModeCodes" multiple style="width:100%"><el-option v-for="x in options.authModes||[]" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="资源模式"><el-select v-model="base.resourceMode" :disabled="base.productType==='EXCLUSIVE_IP'" style="width:100%"><el-option label="共享" value="SHARED"/><el-option label="独享" value="EXCLUSIVE"/></el-select></el-form-item><el-form-item label="地区范围"><el-select v-model="base.regionCodes" multiple clearable style="width:100%"><el-option v-for="x in options.regions||[]" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="运营商范围"><el-select v-model="base.carrierCodes" multiple clearable style="width:100%"><el-option v-for="x in options.carriers||[]" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="产品说明"><el-input v-model="base.description" type="textarea" :rows="3"/></el-form-item><el-form-item><el-button v-if="auth.hasPermission('product:write')" type="primary" @click="saveBase">保存</el-button></el-form-item></el-form></el-tab-pane>
<el-tab-pane label="专项业务参数"><el-form label-width="150px" class="form"><template v-if="p.product_type==='SHORT_IP'"><el-form-item label="IP有效秒数"><el-input-number v-model="cfg.ipValidSeconds" :min="1"/></el-form-item><el-form-item label="单次提取上限"><el-input-number v-model="cfg.singleExtractLimit" :min="1"/></el-form-item><el-form-item label="频控上限"><el-input-number v-model="cfg.extractRateLimit" :min="1"/></el-form-item><el-form-item label="频控窗口(秒)"><el-input-number v-model="cfg.extractRateWindowSeconds" :min="1"/></el-form-item><el-form-item label="去重周期(秒)"><el-input-number v-model="cfg.dedupPeriodSeconds" :min="1"/></el-form-item><el-form-item label="要求白名单"><el-switch v-model="cfg.whitelistRequired"/></el-form-item></template><template v-if="p.product_type==='LONG_IP'"><el-form-item label="稳定/保持周期"><el-input-number v-model="cfg.holdPeriodSeconds" :min="1"/></el-form-item><el-form-item label="绑定类型"><el-input model-value="线路" disabled/></el-form-item><el-form-item label="故障自动替换"><el-switch v-model="cfg.autoReplace"/></el-form-item><el-form-item label="故障阈值"><el-input-number v-model="cfg.failureThreshold" :min="1"/></el-form-item></template><template v-if="p.product_type==='EXCLUSIVE_IP'"><el-form-item label="独享资源"><el-input model-value="家宽/线路" disabled/></el-form-item><el-form-item label="默认线路数"><el-input-number v-model="cfg.resourceCountDefault" :min="1"/></el-form-item><el-form-item label="锁定超时(秒)"><el-input-number v-model="cfg.lockTimeoutSeconds" :min="1"/></el-form-item></template><template v-if="p.product_type==='VPN'"><el-form-item label="VPN协议"><el-select v-model="cfg.vpnProtocolCode"><el-option v-for="x in options.vpnProtocols||[]" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="凭证类型"><el-input v-model="cfg.credentialTypeCode"/></el-form-item><el-form-item label="默认设备数"><el-input-number v-model="cfg.defaultDeviceLimit" :min="1"/></el-form-item><el-form-item label="默认连接数"><el-input-number v-model="cfg.defaultConnectionLimit" :min="1"/></el-form-item></template><template v-if="p.product_type==='TUNNEL'"><el-form-item label="入口域名"><el-select v-model="cfg.entryDomainId" clearable style="width:100%"><el-option v-for="x in options.domains||[]" :key="x.id" :label="x.domain_name" :value="x.id"/></el-select></el-form-item><el-form-item label="入口主机"><el-input v-model="cfg.entryHost"/></el-form-item><el-form-item label="入口端口"><el-input-number v-model="cfg.entryPort" :min="1" :max="65535"/></el-form-item><el-form-item label="会话保持(秒)"><el-input-number v-model="cfg.sessionHoldSeconds" :min="1"/></el-form-item><el-form-item label="并发上限"><el-input-number v-model="cfg.concurrencyLimit" :min="1"/></el-form-item></template><el-form-item><el-button v-if="auth.hasPermission('product:config')" type="primary" @click="saveConfig">保存专项参数</el-button></el-form-item></el-form></el-tab-pane>
<el-tab-pane label="套餐"><div class="tab-head"><span>套餐决定服务周期、额度和价格。</span><el-button @click="router.push({path:'/packages',query:{productId:id}})">管理套餐</el-button></div><el-table :data="packages"><el-table-column prop="package_code" label="套餐编号"/><el-table-column prop="package_name" label="套餐名称"/><el-table-column prop="service_days" label="天数"/><el-table-column prop="price" label="价格"/><el-table-column prop="status" label="状态"/></el-table></el-tab-pane></el-tabs></div></template>
<style scoped>.page{display:grid;gap:16px}.head h2{margin:8px 0}.head p{color:#7b8494}.form{max-width:780px;margin-top:12px}.tab-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px;color:#667085}</style>
