<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { productApi } from '@/api/product'
import { useAuthStore } from '@/stores/auth'
const route=useRoute(),router=useRouter(),auth=useAuthStore();const id=Number(route.params.id);const p=ref<any>({}),options=ref<any>({}),packages=ref<any[]>([]),strategies=ref<any[]>([]);const base=reactive<any>({});const cfg=reactive<any>({});const policy=reactive<any>({a:'{}',b:'{}'})
const data=(r:any)=>r.data.data;function typeName(t:string){return ({SHORT_IP:'短效IP',LONG_IP:'长效IP',EXCLUSIVE_IP:'独享IP',VPN:'VPN',TUNNEL:'隧道'} as any)[t]||t}
function jsonText(v:any){return JSON.stringify(v||{},null,2)} function parseJson(v:string){try{return JSON.parse(v||'{}')}catch{throw new Error('策略JSON格式不正确')}}
async function load(){p.value=data(await productApi.product(id));options.value=data(await productApi.options());Object.assign(base,{productCode:p.value.product_code,productName:p.value.product_name,productType:p.value.product_type,accessModeCode:p.value.access_mode_code,protocolCodes:p.value.protocol_codes||[],authModeCodes:p.value.auth_mode_codes||[],resourceMode:p.value.resource_mode,regionCodes:p.value.region_codes||[],carrierCodes:p.value.carrier_codes||[],description:p.value.description||''});const c=p.value.type_config||{};Object.keys(cfg).forEach(k=>delete cfg[k]);
if(p.value.product_type==='SHORT_IP'){Object.assign(cfg,{ipValidSeconds:c.ip_valid_seconds||60,singleExtractLimit:c.single_extract_limit||10,extractRateLimit:c.extract_rate_limit||null,extractRateWindowSeconds:c.extract_rate_window_seconds||60,dedupPeriodSeconds:c.dedup_period_seconds||300,whitelistRequired:c.whitelist_required??true});policy.a=jsonText(c.switch_policy)}
if(p.value.product_type==='LONG_IP'){Object.assign(cfg,{holdPeriodSeconds:c.hold_period_seconds||86400,bindType:c.bind_type||'LINE',autoReplace:c.auto_replace??true,failureThreshold:c.failure_threshold||3});policy.a=jsonText(c.failover_policy)}
if(p.value.product_type==='EXCLUSIVE_IP'){Object.assign(cfg,{exclusiveResourceType:c.exclusive_resource_type||'IP',resourceCountDefault:c.resource_count_default||1,lockTimeoutSeconds:c.lock_timeout_seconds||300});policy.a=jsonText(c.replacement_rule);policy.b=jsonText(c.release_rule)}
if(p.value.product_type==='VPN'){Object.assign(cfg,{vpnProtocolCode:c.vpn_protocol_code||'TBD',credentialTypeCode:c.credential_type_code||'VPN_PRIVATE_KEY',defaultDeviceLimit:c.default_device_limit||1,defaultConnectionLimit:c.default_connection_limit||1});policy.a=jsonText(c.outbound_policy)}
if(p.value.product_type==='TUNNEL'){Object.assign(cfg,{entryDomainId:c.entry_domain_id||null,entryHost:c.entry_host||'',entryPort:c.entry_port||18080,sessionHoldSeconds:c.session_hold_seconds||300,concurrencyLimit:c.concurrency_limit||100});policy.a=jsonText(c.ip_switch_policy)}
packages.value=data(await productApi.packages({page:1,size:10,productId:id})).items;strategies.value=data(await productApi.strategies({page:1,size:10,productId:id})).items}
async function saveBase(){await productApi.updateProduct(id,{...base,typeConfig:{}});ElMessage.success('通用配置已保存');await load()}
async function saveConfig(){try{const c:any={...cfg};if(p.value.product_type==='SHORT_IP')c.switchPolicy=parseJson(policy.a);if(p.value.product_type==='LONG_IP')c.failoverPolicy=parseJson(policy.a);if(p.value.product_type==='EXCLUSIVE_IP'){c.replacementRule=parseJson(policy.a);c.releaseRule=parseJson(policy.b)}if(p.value.product_type==='VPN')c.outboundPolicy=parseJson(policy.a);if(p.value.product_type==='TUNNEL')c.ipSwitchPolicy=parseJson(policy.a);await productApi.updateConfig(id,c);ElMessage.success('专项配置已保存');await load()}catch(e:any){ElMessage.error(e.message||'保存失败')}}
onMounted(load)
</script>
<template><div class="page"><div class="head"><div><el-button link @click="router.push('/products')">← 返回产品列表</el-button><h2>{{ p.product_name }} <el-tag>{{ typeName(p.product_type) }}</el-tag></h2><p>{{ p.product_code }} · 当前状态 {{ p.status }}</p></div></div>
<el-tabs type="border-card"><el-tab-pane label="通用配置"><el-form label-width="120px" class="form"><el-form-item label="产品编号"><el-input v-model="base.productCode" disabled/></el-form-item><el-form-item label="产品名称"><el-input v-model="base.productName"/></el-form-item><el-form-item label="产品类型"><el-input :model-value="typeName(base.productType)" disabled/></el-form-item><el-form-item label="接入方式"><el-select v-model="base.accessModeCode" style="width:100%"><el-option v-for="x in options.accessModes" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="代理协议"><el-select v-model="base.protocolCodes" multiple style="width:100%"><el-option v-for="x in options.protocols" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="认证方式"><el-select v-model="base.authModeCodes" multiple style="width:100%"><el-option v-for="x in options.authModes" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="资源模式"><el-select v-model="base.resourceMode" :disabled="base.productType==='EXCLUSIVE_IP'" style="width:100%"><el-option label="共享" value="SHARED"/><el-option label="独享" value="EXCLUSIVE"/></el-select></el-form-item><el-form-item label="地区范围"><el-select v-model="base.regionCodes" multiple clearable style="width:100%"><el-option v-for="x in options.regions" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="运营商范围"><el-select v-model="base.carrierCodes" multiple clearable style="width:100%"><el-option v-for="x in options.carriers" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="产品说明"><el-input v-model="base.description" type="textarea" :rows="3"/></el-form-item><el-form-item><el-button v-if="auth.hasPermission('product:write')" type="primary" @click="saveBase">保存通用配置</el-button></el-form-item></el-form></el-tab-pane>
<el-tab-pane label="专项配置"><el-alert type="info" :closable="false" title="这里只定义产品行为，不直接控制 CentOS/ROS/线路；具体可使用哪些资源由“产品资源策略”决定。"/><el-form label-width="150px" class="form" style="margin-top:16px">
<template v-if="p.product_type==='SHORT_IP'"><el-form-item label="IP有效秒数"><el-input-number v-model="cfg.ipValidSeconds" :min="1"/></el-form-item><el-form-item label="单次提取上限"><el-input-number v-model="cfg.singleExtractLimit" :min="1"/></el-form-item><el-form-item label="提取频率上限"><el-input-number v-model="cfg.extractRateLimit" :min="1"/></el-form-item><el-form-item label="频控窗口(秒)"><el-input-number v-model="cfg.extractRateWindowSeconds" :min="1"/></el-form-item><el-form-item label="去重周期(秒)"><el-input-number v-model="cfg.dedupPeriodSeconds" :min="1"/></el-form-item><el-form-item label="要求白名单"><el-switch v-model="cfg.whitelistRequired"/></el-form-item><el-form-item label="切换策略JSON"><el-input v-model="policy.a" type="textarea" :rows="5"/></el-form-item></template>
<template v-if="p.product_type==='LONG_IP'"><el-form-item label="保持周期(秒)"><el-input-number v-model="cfg.holdPeriodSeconds" :min="1"/></el-form-item><el-form-item label="绑定类型"><el-select v-model="cfg.bindType"><el-option label="IP" value="IP"/><el-option label="线路" value="LINE"/></el-select></el-form-item><el-form-item label="故障自动替换"><el-switch v-model="cfg.autoReplace"/></el-form-item><el-form-item label="故障阈值"><el-input-number v-model="cfg.failureThreshold" :min="1"/></el-form-item><el-form-item label="故障转移策略JSON"><el-input v-model="policy.a" type="textarea" :rows="5"/></el-form-item></template>
<template v-if="p.product_type==='EXCLUSIVE_IP'"><el-form-item label="独享资源类型"><el-select v-model="cfg.exclusiveResourceType"><el-option label="IP" value="IP"/><el-option label="线路" value="LINE"/></el-select></el-form-item><el-form-item label="默认资源数量"><el-input-number v-model="cfg.resourceCountDefault" :min="1"/></el-form-item><el-form-item label="锁定超时(秒)"><el-input-number v-model="cfg.lockTimeoutSeconds" :min="1"/></el-form-item><el-form-item label="替换规则JSON"><el-input v-model="policy.a" type="textarea" :rows="4"/></el-form-item><el-form-item label="释放规则JSON"><el-input v-model="policy.b" type="textarea" :rows="4"/></el-form-item></template>
<template v-if="p.product_type==='VPN'"><el-form-item label="VPN协议"><el-select v-model="cfg.vpnProtocolCode"><el-option v-for="x in options.vpnProtocols" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="凭证类型"><el-input v-model="cfg.credentialTypeCode"/></el-form-item><el-form-item label="默认设备数"><el-input-number v-model="cfg.defaultDeviceLimit" :min="1"/></el-form-item><el-form-item label="默认连接数"><el-input-number v-model="cfg.defaultConnectionLimit" :min="1"/></el-form-item><el-form-item label="出口策略JSON"><el-input v-model="policy.a" type="textarea" :rows="5"/></el-form-item></template>
<template v-if="p.product_type==='TUNNEL'"><el-form-item label="入口域名"><el-select v-model="cfg.entryDomainId" clearable style="width:100%"><el-option v-for="x in options.domains" :key="x.id" :label="x.domain_name" :value="x.id"/></el-select></el-form-item><el-form-item label="入口主机"><el-input v-model="cfg.entryHost"/></el-form-item><el-form-item label="入口端口"><el-input-number v-model="cfg.entryPort" :min="1" :max="65535"/></el-form-item><el-form-item label="会话保持(秒)"><el-input-number v-model="cfg.sessionHoldSeconds" :min="1"/></el-form-item><el-form-item label="并发上限"><el-input-number v-model="cfg.concurrencyLimit" :min="1"/></el-form-item><el-form-item label="IP切换策略JSON"><el-input v-model="policy.a" type="textarea" :rows="5"/></el-form-item></template>
<el-form-item><el-button v-if="auth.hasPermission('product:config')" type="primary" @click="saveConfig">保存专项配置</el-button></el-form-item></el-form></el-tab-pane>
<el-tab-pane label="套餐"><div class="tab-head"><span>套餐决定服务期限、配额和价格；历史订单/服务使用快照，不随这里后续修改。</span><el-button @click="router.push({path:'/packages',query:{productId:id}})">管理套餐</el-button></div><el-table :data="packages"><el-table-column prop="package_code" label="套餐编号"/><el-table-column prop="package_name" label="套餐名称"/><el-table-column prop="service_days" label="天数"/><el-table-column prop="price" label="价格"/><el-table-column prop="status" label="状态"/></el-table></el-tab-pane>
<el-tab-pane label="资源策略"><div class="tab-head"><span>资源策略连接产品与 M4 统一资源池；策略修改后会自动停用并要求重新验证。</span><el-button @click="router.push({path:'/resource-strategies',query:{productId:id}})">管理资源策略</el-button></div><el-table :data="strategies"><el-table-column prop="strategy_code" label="策略编号"/><el-table-column prop="strategy_name" label="策略名称"/><el-table-column prop="dispatch_mode" label="调度模式"/><el-table-column prop="pool_count" label="资源池"/><el-table-column prop="pool_member_total" label="成员数"/><el-table-column prop="status" label="状态"/></el-table></el-tab-pane></el-tabs></div></template>
<style scoped>.page{display:grid;gap:16px}.head h2{margin:8px 0}.head p{color:#7b8494}.form{max-width:780px}.tab-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px;color:#667085}</style>
