<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import { productApi } from '@/api/product'
import { useAuthStore } from '@/stores/auth'
const route=useRoute(),router=useRouter(),auth=useAuthStore();const rows=ref<any[]>([]),total=ref(0),loading=ref(false),dialog=ref(false),options=ref<any>({productTypes:[],accessModes:[],protocols:[],authModes:[],carriers:[],regions:[]}),overview=ref<any>({})
const query=reactive<any>({page:1,size:20,keyword:'',status:'',productType:''});const form=reactive<any>({productCode:'',productName:'',productType:'SHORT_IP',accessModeCode:'API_EXTRACT',protocolCodes:['HTTP'],authModeCodes:['TOKEN'],resourceMode:'SHARED',regionCodes:[],carrierCodes:[],description:''})
const fixedType=computed(()=>String(route.meta.productType||''));const title=computed(()=>fixedType.value?`${typeName(fixedType.value)}产品`:'产品列表');const data=(r:any)=>r.data.data
function typeName(t:string){return ({SHORT_IP:'短效IP',LONG_IP:'长效IP',EXCLUSIVE_IP:'独享IP',VPN:'VPN',TUNNEL:'隧道'} as any)[t]||t}
async function load(){if(fixedType.value)query.productType=fixedType.value;loading.value=true;try{const r=data(await productApi.products(query));rows.value=r.items;total.value=r.total;overview.value=data(await productApi.overview())}finally{loading.value=false}}
async function loadOptions(){options.value=data(await productApi.options())}
function add(){Object.assign(form,{productCode:'',productName:'',productType:fixedType.value||'SHORT_IP',accessModeCode:fixedType.value==='VPN'?'VPN':fixedType.value==='TUNNEL'?'TUNNEL':'API_EXTRACT',protocolCodes:['HTTP'],authModeCodes:['TOKEN'],resourceMode:fixedType.value==='EXCLUSIVE_IP'?'EXCLUSIVE':'SHARED',regionCodes:[],carrierCodes:[],description:''});dialog.value=true}
async function save(){if(!form.productCode||!form.productName){ElMessage.warning('请填写产品编号和名称');return}const r=data(await productApi.createProduct({...form,typeConfig:{}}));dialog.value=false;ElMessage.success('产品已创建，请继续完成专项配置和资源策略');router.push(`/products/${r.id}`)}
async function action(row:any,type:'enable'|'disable'|'copy'){const names={enable:'启用',disable:'停用',copy:'复制'};const {value}=await ElMessageBox.prompt(`请输入${names[type]}原因`,`${names[type]}产品`,{inputValidator:(v)=>!!String(v||'').trim()||'必须填写原因'});if(type==='enable')await productApi.enableProduct(row.id,String(value));else if(type==='disable')await productApi.disableProduct(row.id,String(value));else await productApi.copyProduct(row.id,String(value));ElMessage.success(`${names[type]}成功`);await load()}
function statusType(s:string){return s==='ACTIVE'?'success':s==='DRAFT'?'warning':'info'}
watch(()=>route.meta.productType,()=>{query.page=1;query.productType=fixedType.value;load()});onMounted(async()=>{await loadOptions();await load()})
</script>
<template><div class="page"><div class="head"><div><h2>{{ title }}</h2><p>维护五类客户产品的通用定义；专项参数、套餐和资源策略在产品详情中继续配置。</p></div><el-button v-if="auth.hasPermission('product:write')" type="primary" @click="add">新增产品</el-button></div>
<div class="cards"><el-card shadow="never"><b>{{ overview.product_total||0 }}</b><span>全部产品</span></el-card><el-card shadow="never"><b>{{ overview.active_product_total||0 }}</b><span>已启用</span></el-card><el-card shadow="never"><b>{{ overview.draft_product_total||0 }}</b><span>草稿</span></el-card><el-card shadow="never"><b>{{ overview.active_package_total||0 }}</b><span>启用套餐</span></el-card><el-card shadow="never"><b>{{ overview.active_strategy_total||0 }}</b><span>启用策略</span></el-card></div>
<el-card shadow="never"><div class="filters"><el-input v-model="query.keyword" placeholder="产品编号/名称" clearable @keyup.enter="query.page=1;load()"/><el-select v-if="!fixedType" v-model="query.productType" placeholder="产品类型" clearable><el-option v-for="x in options.productTypes" :key="x.code" :label="x.name" :value="x.code"/></el-select><el-select v-model="query.status" placeholder="状态" clearable><el-option label="草稿" value="DRAFT"/><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="DISABLED"/></el-select><el-button type="primary" @click="query.page=1;load()">查询</el-button></div>
<el-table :data="rows" v-loading="loading" stripe><el-table-column prop="product_code" label="产品编号" width="150"/><el-table-column prop="product_name" label="产品名称" min-width="180"/><el-table-column label="类型" width="100"><template #default="s">{{ typeName(s.row.product_type) }}</template></el-table-column><el-table-column prop="access_mode_code" label="接入方式" width="120"/><el-table-column prop="resource_mode" label="资源模式" width="100"/><el-table-column label="套餐" width="100"><template #default="s">{{ s.row.active_package_total }}/{{ s.row.package_total }}</template></el-table-column><el-table-column label="资源策略" width="110"><template #default="s">{{ s.row.active_strategy_total }}/{{ s.row.strategy_total }}</template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="statusType(s.row.status)">{{ s.row.status }}</el-tag></template></el-table-column><el-table-column label="操作" width="240" fixed="right"><template #default="s"><el-button link type="primary" @click="router.push(`/products/${s.row.id}`)">详情配置</el-button><el-button v-if="auth.hasPermission('product:status')&&s.row.status!=='ACTIVE'" link type="success" @click="action(s.row,'enable')">启用</el-button><el-button v-if="auth.hasPermission('product:status')&&s.row.status==='ACTIVE'" link type="warning" @click="action(s.row,'disable')">停用</el-button><el-button v-if="auth.hasPermission('product:write')" link @click="action(s.row,'copy')">复制</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" layout="total, sizes, prev, pager, next" :total="total" :page-sizes="[20,50,100]" @change="load"/></div></el-card>
<el-dialog v-model="dialog" title="新增产品" width="720px"><el-alert type="info" :closable="false" title="新产品默认保存为草稿。创建后进入详情页完成专项配置、套餐和资源策略。"/><el-form label-width="110px" style="margin-top:16px"><el-form-item label="产品编号" required><el-input v-model="form.productCode"/></el-form-item><el-form-item label="产品名称" required><el-input v-model="form.productName"/></el-form-item><el-form-item label="产品类型" required><el-select v-model="form.productType" :disabled="!!fixedType" style="width:100%"><el-option v-for="x in options.productTypes" :key="x.code" :label="x.name" :value="x.code"/></el-select></el-form-item><el-form-item label="接入方式" required><el-select v-model="form.accessModeCode" style="width:100%"><el-option v-for="x in options.accessModes" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="代理协议"><el-select v-model="form.protocolCodes" multiple style="width:100%"><el-option v-for="x in options.protocols" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="认证方式"><el-select v-model="form.authModeCodes" multiple style="width:100%"><el-option v-for="x in options.authModes" :key="x.item_code" :label="x.item_name" :value="x.item_code"/></el-select></el-form-item><el-form-item label="资源模式"><el-select v-model="form.resourceMode" :disabled="form.productType==='EXCLUSIVE_IP'" style="width:100%"><el-option label="共享" value="SHARED"/><el-option label="独享" value="EXCLUSIVE"/></el-select></el-form-item><el-form-item label="说明"><el-input v-model="form.description" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">创建并配置</el-button></template></el-dialog></div></template>
<style scoped>.page{display:grid;gap:16px}.head{display:flex;justify-content:space-between}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.cards :deep(.el-card__body){display:grid;gap:6px}.cards b{font-size:26px}.cards span{color:#7b8494}.filters{display:flex;gap:10px;margin-bottom:14px}.filters .el-input,.filters .el-select{max-width:240px}.pager{display:flex;justify-content:flex-end;margin-top:14px}@media(max-width:1100px){.cards{grid-template-columns:repeat(2,1fr)}}</style>
