<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue';import { useRoute } from 'vue-router';import { ElMessage,ElMessageBox } from 'element-plus';import { productApi } from '@/api/product';import { useAuthStore } from '@/stores/auth'
const route=useRoute(),auth=useAuthStore();const rows=ref<any[]>([]),total=ref(0),loading=ref(false),dialog=ref(false),editId=ref<number|null>(null),options=ref<any>({products:[],pools:[],dispatchModes:[],carriers:[],regions:[]});const query=reactive<any>({page:1,size:20,keyword:'',status:'',productId:route.query.productId?Number(route.query.productId):null});const form=reactive<any>({});const policy=reactive({failover:'{}',hold:'{}',switch:'{}'});const data=(r:any)=>r.data.data
function reset(){Object.assign(form,{strategyCode:'',strategyName:'',productId:query.productId||null,dispatchMode:'QUALITY_FIRST',sourcePriority:['SELF','EXTERNAL'],regionCodes:[],carrierCodes:[],poolBindings:[{poolId:null,priority:100,weight:100,enabled:true}],scopes:[]});Object.assign(policy,{failover:'{}',hold:'{}',switch:'{}'})}
async function load(){loading.value=true;try{const r=data(await productApi.strategies(query));rows.value=r.items;total.value=r.total}finally{loading.value=false}} async function loadOptions(){options.value=data(await productApi.options())}
function add(){editId.value=null;reset();dialog.value=true} async function edit(r:any){const x=data(await productApi.strategy(r.id));editId.value=r.id;Object.assign(form,{strategyCode:x.strategy_code,strategyName:x.strategy_name,productId:x.product_id,dispatchMode:x.dispatch_mode,sourcePriority:x.source_priority||[],regionCodes:x.region_codes||[],carrierCodes:x.carrier_codes||[],poolBindings:(x.pool_bindings||[]).map((p:any)=>({poolId:p.pool_id,priority:p.priority,weight:p.weight,enabled:p.enabled})),scopes:(x.scopes||[]).map((s:any)=>({scopeType:s.scope_type,resourceId:s.resource_id,scopeCode:s.scope_code,includeFlag:s.include_flag,priority:s.priority}))});policy.failover=JSON.stringify(x.failover_rule||{},null,2);policy.hold=JSON.stringify(x.ip_hold_rule||{},null,2);policy.switch=JSON.stringify(x.switch_rule||{},null,2);dialog.value=true}
function payload(){return {...form,failoverRule:JSON.parse(policy.failover||'{}'),ipHoldRule:JSON.parse(policy.hold||'{}'),switchRule:JSON.parse(policy.switch||'{}')}}
async function save(){try{if(!form.strategyCode||!form.strategyName||!form.productId){ElMessage.warning('请填写策略编号、名称和产品');return}editId.value?await productApi.updateStrategy(editId.value,payload()):await productApi.createStrategy(payload());dialog.value=false;ElMessage.success(editId.value?'策略已保存并自动停用，请重新验证':'策略已创建，默认停用，请先验证');await load()}catch(e:any){ElMessage.error(e.message||'策略JSON格式错误')}}
async function action(r:any,t:'validate'|'enable'|'disable'){const names={validate:'验证',enable:'启用',disable:'停用'};const {value}=await ElMessageBox.prompt(`请输入${names[t]}原因`,`${names[t]}资源策略`,{inputValidator:v=>!!String(v||'').trim()||'必须填写原因'});if(t==='validate'){const v=data(await productApi.validateStrategy(r.id,String(value)));v.valid?ElMessage.success(`验证通过：${v.usablePoolCount}个可用资源池，${v.memberCount}个成员`):ElMessage.error(`验证失败：${(v.errors||[]).join('；')}`)}else if(t==='enable'){await productApi.enableStrategy(r.id,String(value));ElMessage.success('策略已启用')}else{await productApi.disableStrategy(r.id,String(value));ElMessage.success('策略已停用')}await load()}
function addPool(){form.poolBindings.push({poolId:null,priority:100,weight:100,enabled:true})} function addScope(){form.scopes.push({scopeType:'LINE',resourceId:null,scopeCode:'',includeFlag:true,priority:100})}
onMounted(async()=>{await loadOptions();await load()})
</script>
<template><div class="page"><div class="head"><div><h2>产品资源策略</h2><p>连接产品与 M4 统一资源池。策略必须验证通过后才能启用，修改已启用策略会自动停用。</p></div><el-button v-if="auth.hasPermission('product:strategy:write')" type="primary" @click="add">新增策略</el-button></div><el-card shadow="never"><div class="filters"><el-input v-model="query.keyword" placeholder="策略编号/名称" clearable/><el-select v-model="query.productId" placeholder="所属产品" clearable><el-option v-for="x in options.products" :key="x.id" :label="x.product_name" :value="x.id"/></el-select><el-select v-model="query.status" placeholder="状态" clearable><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="DISABLED"/></el-select><el-button type="primary" @click="query.page=1;load()">查询</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="strategy_code" label="策略编号" width="160"/><el-table-column prop="strategy_name" label="策略名称" min-width="170"/><el-table-column prop="product_name" label="产品" min-width="150"/><el-table-column prop="dispatch_mode" label="调度模式" width="130"/><el-table-column prop="pool_count" label="资源池" width="80"/><el-table-column prop="pool_member_total" label="池成员" width="90"/><el-table-column prop="status" label="状态" width="90"/><el-table-column label="操作" width="230" fixed="right"><template #default="s"><el-button link @click="edit(s.row)">编辑</el-button><el-button link type="primary" @click="action(s.row,'validate')">验证</el-button><el-button v-if="s.row.status!=='ACTIVE'" link type="success" @click="action(s.row,'enable')">启用</el-button><el-button v-else link type="warning" @click="action(s.row,'disable')">停用</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" layout="total, prev, pager, next" :total="total" @change="load"/></div></el-card>
<el-dialog v-model="dialog" :title="editId?'编辑资源策略':'新增资源策略'" width="900px"><el-form label-width="120px"><el-form-item label="策略编号" required><el-input v-model="form.strategyCode" :disabled="!!editId"/></el-form-item><el-form-item label="策略名称" required><el-input v-model="form.strategyName"/></el-form-item><el-form-item label="所属产品" required><el-select v-model="form.productId" :disabled="!!editId" style="width:100%"><el-option v-for="x in options.products" :key="x.id" :label="`${x.product_name} (${x.product_type})`" :value="x.id"/></el-select></el-form-item><el-form-item label="调度模式"><el-select v-model="form.dispatchMode" style="width:100%"><el-option v-for="x in options.dispatchModes" :key="x" :label="x" :value="x"/></el-select></el-form-item><el-form-item label="来源优先级"><el-select v-model="form.sourcePriority" multiple style="width:100%"><el-option label="自有资源" value="SELF"/><el-option label="外部资源" value="EXTERNAL"/></el-select></el-form-item>
<el-divider content-position="left">资源池绑定</el-divider><div v-for="(b,i) in form.poolBindings" :key="i" class="row"><el-select v-model="b.poolId" placeholder="资源池" style="flex:1"><el-option v-for="x in options.pools" :key="x.id" :label="`${x.pool_name} · ${x.member_count} IP · ${x.status}`" :value="x.id"/></el-select><el-input-number v-model="b.priority" :min="1"/><el-input-number v-model="b.weight" :min="1"/><el-switch v-model="b.enabled"/><el-button type="danger" link @click="form.poolBindings.splice(i,1)">移除</el-button></div><el-button link type="primary" @click="addPool">+ 增加资源池</el-button>
<el-divider content-position="left">资源范围（可选）</el-divider><div v-for="(s,i) in form.scopes" :key="i" class="row"><el-select v-model="s.scopeType"><el-option v-for="x in ['CENTOS','ROS','LINE','IP','NODE_TAG']" :key="x" :label="x" :value="x"/></el-select><el-input-number v-if="s.scopeType!=='NODE_TAG'" v-model="s.resourceId" placeholder="资源ID" :min="1"/><el-input v-else v-model="s.scopeCode" placeholder="标签编码"/><el-switch v-model="s.includeFlag"/><el-input-number v-model="s.priority" :min="1"/><el-button type="danger" link @click="form.scopes.splice(i,1)">移除</el-button></div><el-button link type="primary" @click="addScope">+ 增加范围</el-button>
<el-divider content-position="left">高级策略 JSON</el-divider><el-form-item label="故障转移"><el-input v-model="policy.failover" type="textarea" :rows="3"/></el-form-item><el-form-item label="IP保持"><el-input v-model="policy.hold" type="textarea" :rows="3"/></el-form-item><el-form-item label="切换规则"><el-input v-model="policy.switch" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
<style scoped>.page{display:grid;gap:16px}.head{display:flex;justify-content:space-between}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494}.filters{display:flex;gap:10px;margin-bottom:14px}.filters>*{max-width:250px}.pager{display:flex;justify-content:flex-end;margin-top:14px}.row{display:flex;gap:10px;align-items:center;margin-bottom:10px}</style>
