<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import { longMonitorApi } from '@/api/longMonitor'
const router=useRouter(),rows=ref<any[]>([]),total=ref(0),loading=ref(false),q=reactive<any>({page:1,size:20,keyword:'',status:'',enabled:undefined}),data=(r:any)=>r.data.data
async function load(){loading.value=true;try{const d=data(await longMonitorApi.monitors(q));rows.value=d.items||[];total.value=d.total||0}finally{loading.value=false}}
async function toggle(r:any){const {value}=await ElMessageBox.prompt('请输入操作原因',r.enabled?'停用监控':'启用监控',{inputValidator:v=>!!String(v||'').trim()||'必须填写原因'});await longMonitorApi.setMonitorEnabled(r.id,!r.enabled,String(value));ElMessage.success('状态已更新');load()}
async function check(r:any){await longMonitorApi.check(r.id,'手工检测');ElMessage.success('检测完成');load()}
onMounted(load)
</script><template><div class="page"><div><h2>长效监控配置</h2><p>一条监控对应一个客户的长效代理服务，并关联具体线路或反向代理以及客户机器人。</p></div><el-card shadow="never"><div class="filters"><el-input v-model="q.keyword" placeholder="监控编号/客户/服务/地址" clearable/><el-select v-model="q.status" placeholder="状态" clearable><el-option v-for="x in ['UNKNOWN','NORMAL','ABNORMAL']" :key="x" :label="x" :value="x"/></el-select><el-button type="primary" @click="q.page=1;load()">查询</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="monitor_no" label="监控编号" width="180"/><el-table-column prop="customer_name" label="客户"/><el-table-column prop="service_no" label="服务" width="180"/><el-table-column label="代理目标" min-width="180"><template #default="s">{{s.row.target_host}}:{{s.row.target_port}}</template></el-table-column><el-table-column prop="current_status" label="状态"/><el-table-column prop="last_checked_at" label="最近检测" width="180"/><el-table-column prop="bot_name" label="通知机器人"/><el-table-column label="操作" width="200"><template #default="s"><el-button link type="primary" @click="router.push(`/long-monitor/monitors/${s.row.id}`)">详情</el-button><el-button link @click="check(s.row)">检测</el-button><el-button link :type="s.row.enabled?'danger':'success'" @click="toggle(s.row)">{{s.row.enabled?'停用':'启用'}}</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="q.page" v-model:page-size="q.size" :total="total" layout="total,sizes,prev,pager,next" @change="load"/></div></el-card></div></template><style scoped>.page{display:grid;gap:16px}h2{margin:0 0 6px}p{margin:0;color:#7b8494}.filters{display:flex;gap:10px;margin-bottom:14px}.filters>*{max-width:280px}.pager{display:flex;justify-content:flex-end;margin-top:14px}</style>