package com.ipproxy.platform.product.mapper;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import java.math.BigDecimal;
import java.util.*;

@Repository
public class ProductMapper {
    private final JdbcTemplate jdbc;
    public ProductMapper(JdbcTemplate jdbc){this.jdbc=jdbc;}
    private Map<String,Object> one(String sql,Object... args){List<Map<String,Object>> r=jdbc.queryForList(sql,args);return r.isEmpty()?null:r.getFirst();}
    private Long scalarLong(String sql,Object... args){List<Long> r=jdbc.query(sql,(rs,n)->rs.getLong(1),args);return r.isEmpty()?null:r.getFirst();}

    public Map<String,Object> overview(){return one("SELECT (SELECT count(*) FROM prd_product WHERE deleted=FALSE) product_total,(SELECT count(*) FROM prd_product WHERE deleted=FALSE AND status='ACTIVE') active_product_total,(SELECT count(*) FROM prd_product WHERE deleted=FALSE AND status='DRAFT') draft_product_total,(SELECT count(*) FROM prd_package WHERE deleted=FALSE AND status='ACTIVE') active_package_total,(SELECT count(*) FROM prd_resource_strategy WHERE deleted=FALSE AND status='ACTIVE') active_strategy_total,(SELECT count(DISTINCT product_type) FROM prd_product WHERE deleted=FALSE AND status='ACTIVE') active_product_type_total");}

    public long countProducts(String keyword,String status,String type){return jdbc.queryForObject("SELECT count(*) FROM prd_product p WHERE p.deleted=FALSE AND (?='' OR p.product_code ILIKE '%'||?||'%' OR p.product_name ILIKE '%'||?||'%') AND (?='' OR p.status=?) AND (?='' OR p.product_type=?)",Long.class,keyword,keyword,keyword,status,status,type,type);}
    public List<Map<String,Object>> listProducts(String keyword,String status,String type,int size,int offset){return jdbc.queryForList("SELECT p.id,p.product_code,p.product_name,p.product_type,p.access_mode_code,p.protocol_codes::text protocol_codes_json,p.auth_mode_codes::text auth_mode_codes_json,p.resource_mode,p.region_codes::text region_codes_json,p.carrier_codes::text carrier_codes_json,p.description,p.status,p.created_at,p.updated_at,(SELECT count(*) FROM prd_package k WHERE k.product_id=p.id AND k.deleted=FALSE) package_total,(SELECT count(*) FROM prd_package k WHERE k.product_id=p.id AND k.deleted=FALSE AND k.status='ACTIVE') active_package_total,(SELECT count(*) FROM prd_resource_strategy s WHERE s.product_id=p.id AND s.deleted=FALSE) strategy_total,(SELECT count(*) FROM prd_resource_strategy s WHERE s.product_id=p.id AND s.deleted=FALSE AND s.status='ACTIVE') active_strategy_total FROM prd_product p WHERE p.deleted=FALSE AND (?='' OR p.product_code ILIKE '%'||?||'%' OR p.product_name ILIKE '%'||?||'%') AND (?='' OR p.status=?) AND (?='' OR p.product_type=?) ORDER BY p.updated_at DESC,p.id DESC LIMIT ? OFFSET ?",keyword,keyword,keyword,status,status,type,type,size,offset);}
    public Map<String,Object> getProduct(Long id){return one("SELECT p.id,p.product_code,p.product_name,p.product_type,p.access_mode_code,p.protocol_codes::text protocol_codes_json,p.auth_mode_codes::text auth_mode_codes_json,p.resource_mode,p.region_codes::text region_codes_json,p.carrier_codes::text carrier_codes_json,p.description,p.status,p.created_at,p.updated_at,p.version,(SELECT count(*) FROM prd_package k WHERE k.product_id=p.id AND k.deleted=FALSE) package_total,(SELECT count(*) FROM prd_resource_strategy s WHERE s.product_id=p.id AND s.deleted=FALSE) strategy_total FROM prd_product p WHERE p.id=? AND p.deleted=FALSE",id);}
    public boolean productCodeExists(String code){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM prd_product WHERE product_code=? AND deleted=FALSE)",Boolean.class,code));}
    public Long insertProduct(String code,String name,String type,String accessMode,String protocolsJson,String authModesJson,String resourceMode,String regionsJson,String carriersJson,String description,Long actor){return jdbc.queryForObject("INSERT INTO prd_product(product_code,product_name,product_type,access_mode_code,protocol_codes,auth_mode_codes,resource_mode,region_codes,carrier_codes,description,status,created_by,updated_by) VALUES(?,?,?,?,CAST(? AS jsonb),CAST(? AS jsonb),?,CAST(? AS jsonb),CAST(? AS jsonb),?,'DRAFT',?,?) RETURNING id",Long.class,code,name,type,accessMode,protocolsJson,authModesJson,resourceMode,regionsJson,carriersJson,description,actor,actor);}
    public int updateProduct(Long id,String name,String accessMode,String protocolsJson,String authModesJson,String resourceMode,String regionsJson,String carriersJson,String description,Long actor){return jdbc.update("UPDATE prd_product SET product_name=?,access_mode_code=?,protocol_codes=CAST(? AS jsonb),auth_mode_codes=CAST(? AS jsonb),resource_mode=?,region_codes=CAST(? AS jsonb),carrier_codes=CAST(? AS jsonb),description=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",name,accessMode,protocolsJson,authModesJson,resourceMode,regionsJson,carriersJson,description,actor,id);}
    public int updateProductStatus(Long id,String status,Long actor){return jdbc.update("UPDATE prd_product SET status=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",status,actor,id);}

    public Map<String,Object> getShortConfig(Long id){return one("SELECT product_id,ip_valid_seconds,single_extract_limit,extract_rate_limit,extract_rate_window_seconds,dedup_period_seconds,switch_policy::text switch_policy_json,whitelist_required,updated_at FROM prd_short_ip_config WHERE product_id=?",id);}
    public Map<String,Object> getLongConfig(Long id){return one("SELECT product_id,hold_period_seconds,bind_type,auto_replace,failure_threshold,failover_policy::text failover_policy_json,updated_at FROM prd_long_ip_config WHERE product_id=?",id);}
    public Map<String,Object> getExclusiveConfig(Long id){return one("SELECT product_id,exclusive_resource_type,resource_count_default,lock_timeout_seconds,replacement_rule::text replacement_rule_json,release_rule::text release_rule_json,updated_at FROM prd_exclusive_ip_config WHERE product_id=?",id);}
    public Map<String,Object> getVpnConfig(Long id){return one("SELECT product_id,vpn_protocol_code,credential_type_code,default_device_limit,default_connection_limit,outbound_policy::text outbound_policy_json,updated_at FROM prd_vpn_config WHERE product_id=?",id);}
    public Map<String,Object> getTunnelConfig(Long id){return one("SELECT c.product_id,c.entry_domain_id,d.domain_name,c.entry_host,c.entry_port,c.session_hold_seconds,c.concurrency_limit,c.ip_switch_policy::text ip_switch_policy_json,c.updated_at FROM prd_tunnel_config c LEFT JOIN res_domain d ON d.id=c.entry_domain_id WHERE c.product_id=?",id);}
    public int upsertShort(Long id,int valid,int single,Integer rate,Integer window,Integer dedup,String switchJson,boolean whitelist){return jdbc.update("INSERT INTO prd_short_ip_config(product_id,ip_valid_seconds,single_extract_limit,extract_rate_limit,extract_rate_window_seconds,dedup_period_seconds,switch_policy,whitelist_required) VALUES(?,?,?,?,?,?,CAST(? AS jsonb),?) ON CONFLICT(product_id) DO UPDATE SET ip_valid_seconds=EXCLUDED.ip_valid_seconds,single_extract_limit=EXCLUDED.single_extract_limit,extract_rate_limit=EXCLUDED.extract_rate_limit,extract_rate_window_seconds=EXCLUDED.extract_rate_window_seconds,dedup_period_seconds=EXCLUDED.dedup_period_seconds,switch_policy=EXCLUDED.switch_policy,whitelist_required=EXCLUDED.whitelist_required,updated_at=now()",id,valid,single,rate,window,dedup,switchJson,whitelist);}
    public int upsertLong(Long id,Long hold,String bind,boolean autoReplace,int threshold,String failoverJson){return jdbc.update("INSERT INTO prd_long_ip_config(product_id,hold_period_seconds,bind_type,auto_replace,failure_threshold,failover_policy) VALUES(?,?,?,?,?,CAST(? AS jsonb)) ON CONFLICT(product_id) DO UPDATE SET hold_period_seconds=EXCLUDED.hold_period_seconds,bind_type=EXCLUDED.bind_type,auto_replace=EXCLUDED.auto_replace,failure_threshold=EXCLUDED.failure_threshold,failover_policy=EXCLUDED.failover_policy,updated_at=now()",id,hold,bind,autoReplace,threshold,failoverJson);}
    public int upsertExclusive(Long id,String resourceType,int count,int lockTimeout,String replacementJson,String releaseJson){return jdbc.update("INSERT INTO prd_exclusive_ip_config(product_id,exclusive_resource_type,resource_count_default,lock_timeout_seconds,replacement_rule,release_rule) VALUES(?,?,?,?,CAST(? AS jsonb),CAST(? AS jsonb)) ON CONFLICT(product_id) DO UPDATE SET exclusive_resource_type=EXCLUDED.exclusive_resource_type,resource_count_default=EXCLUDED.resource_count_default,lock_timeout_seconds=EXCLUDED.lock_timeout_seconds,replacement_rule=EXCLUDED.replacement_rule,release_rule=EXCLUDED.release_rule,updated_at=now()",id,resourceType,count,lockTimeout,replacementJson,releaseJson);}
    public int upsertVpn(Long id,String protocol,String credential,Integer device,Integer connections,String outboundJson){return jdbc.update("INSERT INTO prd_vpn_config(product_id,vpn_protocol_code,credential_type_code,default_device_limit,default_connection_limit,outbound_policy) VALUES(?,?,?,?,?,CAST(? AS jsonb)) ON CONFLICT(product_id) DO UPDATE SET vpn_protocol_code=EXCLUDED.vpn_protocol_code,credential_type_code=EXCLUDED.credential_type_code,default_device_limit=EXCLUDED.default_device_limit,default_connection_limit=EXCLUDED.default_connection_limit,outbound_policy=EXCLUDED.outbound_policy,updated_at=now()",id,protocol,credential,device,connections,outboundJson);}
    public int upsertTunnel(Long id,Long domainId,String host,int port,Integer hold,Integer concurrency,String switchJson){return jdbc.update("INSERT INTO prd_tunnel_config(product_id,entry_domain_id,entry_host,entry_port,session_hold_seconds,concurrency_limit,ip_switch_policy) VALUES(?,?,?,?,?,?,CAST(? AS jsonb)) ON CONFLICT(product_id) DO UPDATE SET entry_domain_id=EXCLUDED.entry_domain_id,entry_host=EXCLUDED.entry_host,entry_port=EXCLUDED.entry_port,session_hold_seconds=EXCLUDED.session_hold_seconds,concurrency_limit=EXCLUDED.concurrency_limit,ip_switch_policy=EXCLUDED.ip_switch_policy,updated_at=now()",id,domainId,host,port,hold,concurrency,switchJson);}

    public long countPackages(String keyword,String status,Long productId){return jdbc.queryForObject("SELECT count(*) FROM prd_package k JOIN prd_product p ON p.id=k.product_id WHERE k.deleted=FALSE AND (?='' OR k.package_code ILIKE '%'||?||'%' OR k.package_name ILIKE '%'||?||'%' OR p.product_name ILIKE '%'||?||'%') AND (?='' OR k.status=?) AND (?=0 OR k.product_id=?)",Long.class,keyword,keyword,keyword,keyword,status,status,productId,productId);}
    public List<Map<String,Object>> listPackages(String keyword,String status,Long productId,int size,int offset){return jdbc.queryForList("SELECT k.id,k.package_code,k.product_id,p.product_code,p.product_name,p.product_type,k.package_name,k.service_days,k.ip_count,k.extract_quota,k.traffic_quota_bytes,k.concurrency_limit,k.device_limit,k.whitelist_limit,k.change_ip_limit,k.price,k.currency,k.quota_config::text quota_config_json,k.status,k.created_at,k.updated_at FROM prd_package k JOIN prd_product p ON p.id=k.product_id WHERE k.deleted=FALSE AND (?='' OR k.package_code ILIKE '%'||?||'%' OR k.package_name ILIKE '%'||?||'%' OR p.product_name ILIKE '%'||?||'%') AND (?='' OR k.status=?) AND (?=0 OR k.product_id=?) ORDER BY k.updated_at DESC,k.id DESC LIMIT ? OFFSET ?",keyword,keyword,keyword,keyword,status,status,productId,productId,size,offset);}
    public Map<String,Object> getPackage(Long id){return one("SELECT k.id,k.package_code,k.product_id,p.product_code,p.product_name,p.product_type,k.package_name,k.service_days,k.ip_count,k.extract_quota,k.traffic_quota_bytes,k.concurrency_limit,k.device_limit,k.whitelist_limit,k.change_ip_limit,k.price,k.currency,k.quota_config::text quota_config_json,k.status,k.created_at,k.updated_at,k.version FROM prd_package k JOIN prd_product p ON p.id=k.product_id WHERE k.id=? AND k.deleted=FALSE",id);}
    public boolean packageCodeExists(String code){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM prd_package WHERE package_code=? AND deleted=FALSE)",Boolean.class,code));}
    public Long insertPackage(String code,Long productId,String name,int days,Integer ipCount,Long extractQuota,Long traffic,Integer concurrency,Integer device,Integer whitelist,Integer changeIp,BigDecimal price,String currency,String quotaJson,String status,Long actor){return jdbc.queryForObject("INSERT INTO prd_package(package_code,product_id,package_name,service_days,ip_count,extract_quota,traffic_quota_bytes,concurrency_limit,device_limit,whitelist_limit,change_ip_limit,price,currency,quota_config,status,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,CAST(? AS jsonb),?,?,?) RETURNING id",Long.class,code,productId,name,days,ipCount,extractQuota,traffic,concurrency,device,whitelist,changeIp,price,currency,quotaJson,status,actor,actor);}
    public int updatePackage(Long id,String name,int days,Integer ipCount,Long extractQuota,Long traffic,Integer concurrency,Integer device,Integer whitelist,Integer changeIp,BigDecimal price,String currency,String quotaJson,Long actor){return jdbc.update("UPDATE prd_package SET package_name=?,service_days=?,ip_count=?,extract_quota=?,traffic_quota_bytes=?,concurrency_limit=?,device_limit=?,whitelist_limit=?,change_ip_limit=?,price=?,currency=?,quota_config=CAST(? AS jsonb),updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",name,days,ipCount,extractQuota,traffic,concurrency,device,whitelist,changeIp,price,currency,quotaJson,actor,id);}
    public int updatePackageStatus(Long id,String status,Long actor){return jdbc.update("UPDATE prd_package SET status=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",status,actor,id);}

    public long countStrategies(String keyword,String status,Long productId){return jdbc.queryForObject("SELECT count(*) FROM prd_resource_strategy s JOIN prd_product p ON p.id=s.product_id WHERE s.deleted=FALSE AND (?='' OR s.strategy_code ILIKE '%'||?||'%' OR s.strategy_name ILIKE '%'||?||'%' OR p.product_name ILIKE '%'||?||'%') AND (?='' OR s.status=?) AND (?=0 OR s.product_id=?)",Long.class,keyword,keyword,keyword,keyword,status,status,productId,productId);}
    public List<Map<String,Object>> listStrategies(String keyword,String status,Long productId,int size,int offset){return jdbc.queryForList("SELECT s.id,s.strategy_code,s.strategy_name,s.product_id,p.product_code,p.product_name,p.product_type,s.dispatch_mode,s.source_priority::text source_priority_json,s.region_codes::text region_codes_json,s.carrier_codes::text carrier_codes_json,s.status,s.created_at,s.updated_at,(SELECT count(*) FROM prd_strategy_pool sp WHERE sp.strategy_id=s.id AND sp.enabled=TRUE) pool_count,(SELECT COALESCE(sum(x.cnt),0) FROM prd_strategy_pool sp JOIN LATERAL (SELECT count(*) cnt FROM res_pool_ip pi WHERE pi.pool_id=sp.pool_id AND pi.enabled=TRUE) x ON TRUE WHERE sp.strategy_id=s.id AND sp.enabled=TRUE) pool_member_total FROM prd_resource_strategy s JOIN prd_product p ON p.id=s.product_id WHERE s.deleted=FALSE AND (?='' OR s.strategy_code ILIKE '%'||?||'%' OR s.strategy_name ILIKE '%'||?||'%' OR p.product_name ILIKE '%'||?||'%') AND (?='' OR s.status=?) AND (?=0 OR s.product_id=?) ORDER BY s.updated_at DESC,s.id DESC LIMIT ? OFFSET ?",keyword,keyword,keyword,keyword,status,status,productId,productId,size,offset);}
    public Map<String,Object> getStrategy(Long id){return one("SELECT s.id,s.strategy_code,s.strategy_name,s.product_id,p.product_code,p.product_name,p.product_type,p.resource_mode,s.dispatch_mode,s.source_priority::text source_priority_json,s.region_codes::text region_codes_json,s.carrier_codes::text carrier_codes_json,s.failover_rule::text failover_rule_json,s.ip_hold_rule::text ip_hold_rule_json,s.switch_rule::text switch_rule_json,s.status,s.created_at,s.updated_at,s.version FROM prd_resource_strategy s JOIN prd_product p ON p.id=s.product_id WHERE s.id=? AND s.deleted=FALSE",id);}
    public boolean strategyCodeExists(String code){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM prd_resource_strategy WHERE strategy_code=? AND deleted=FALSE)",Boolean.class,code));}
    public Long insertStrategy(String code,String name,Long productId,String dispatch,String sourceJson,String regionsJson,String carriersJson,String failoverJson,String holdJson,String switchJson,Long actor){return jdbc.queryForObject("INSERT INTO prd_resource_strategy(strategy_code,strategy_name,product_id,dispatch_mode,source_priority,region_codes,carrier_codes,failover_rule,ip_hold_rule,switch_rule,status,created_by,updated_by) VALUES(?,?,?, ?,CAST(? AS jsonb),CAST(? AS jsonb),CAST(? AS jsonb),CAST(? AS jsonb),CAST(? AS jsonb),CAST(? AS jsonb),'DISABLED',?,?) RETURNING id",Long.class,code,name,productId,dispatch,sourceJson,regionsJson,carriersJson,failoverJson,holdJson,switchJson,actor,actor);}
    public int updateStrategy(Long id,String name,String dispatch,String sourceJson,String regionsJson,String carriersJson,String failoverJson,String holdJson,String switchJson,Long actor){return jdbc.update("UPDATE prd_resource_strategy SET strategy_name=?,dispatch_mode=?,source_priority=CAST(? AS jsonb),region_codes=CAST(? AS jsonb),carrier_codes=CAST(? AS jsonb),failover_rule=CAST(? AS jsonb),ip_hold_rule=CAST(? AS jsonb),switch_rule=CAST(? AS jsonb),updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",name,dispatch,sourceJson,regionsJson,carriersJson,failoverJson,holdJson,switchJson,actor,id);}
    public int updateStrategyStatus(Long id,String status,Long actor){return jdbc.update("UPDATE prd_resource_strategy SET status=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",status,actor,id);}
    public List<Map<String,Object>> strategyPools(Long id){return jdbc.queryForList("SELECT sp.pool_id,p.pool_code,p.pool_name,p.source_scope,p.status,sp.priority,sp.weight,sp.enabled,(SELECT count(*) FROM res_pool_ip pi WHERE pi.pool_id=p.id AND pi.enabled=TRUE) member_count FROM prd_strategy_pool sp JOIN res_pool p ON p.id=sp.pool_id WHERE sp.strategy_id=? ORDER BY sp.priority,sp.pool_id",id);}
    public List<Map<String,Object>> strategyScopes(Long id){return jdbc.queryForList("SELECT id,scope_type,resource_id,scope_code,include_flag,priority FROM prd_strategy_scope WHERE strategy_id=? ORDER BY priority,id",id);}
    public int deleteStrategyPools(Long id){return jdbc.update("DELETE FROM prd_strategy_pool WHERE strategy_id=?",id);}
    public int insertStrategyPool(Long id,Long poolId,int priority,int weight,boolean enabled){return jdbc.update("INSERT INTO prd_strategy_pool(strategy_id,pool_id,priority,weight,enabled) VALUES(?,?,?,?,?)",id,poolId,priority,weight,enabled);}
    public int deleteStrategyScopes(Long id){return jdbc.update("DELETE FROM prd_strategy_scope WHERE strategy_id=?",id);}
    public int insertStrategyScope(Long id,String type,Long resourceId,String code,boolean include,int priority){return jdbc.update("INSERT INTO prd_strategy_scope(strategy_id,scope_type,resource_id,scope_code,include_flag,priority) VALUES(?,?,?,?,?,?)",id,type,resourceId,code,include,priority);}
    public List<Long> activeStrategyIds(Long productId){return jdbc.query("SELECT id FROM prd_resource_strategy WHERE product_id=? AND status='ACTIVE' AND deleted=FALSE",(rs,n)->rs.getLong(1),productId);}

    public List<Map<String,Object>> productOptions(){return jdbc.queryForList("SELECT id,product_code,product_name,product_type,status FROM prd_product WHERE deleted=FALSE ORDER BY product_type,product_name");}
    public List<Map<String,Object>> poolOptions(){return jdbc.queryForList("SELECT p.id,p.pool_code,p.pool_name,p.source_scope,p.status,(SELECT count(*) FROM res_pool_ip pi WHERE pi.pool_id=p.id AND pi.enabled=TRUE) member_count FROM res_pool p WHERE p.deleted=FALSE ORDER BY p.status,p.priority,p.pool_name");}
    public List<Map<String,Object>> domainOptions(){return jdbc.queryForList("SELECT id,domain_name,status FROM res_domain WHERE deleted=FALSE ORDER BY domain_name");}
    public List<Map<String,Object>> dictOptions(String code){return jdbc.queryForList("SELECT i.item_code,i.item_name,i.item_value,i.sort_order FROM sys_dict_item i JOIN sys_dict_type t ON t.id=i.dict_type_id WHERE t.dict_code=? AND t.deleted=FALSE AND i.deleted=FALSE AND t.status='ACTIVE' AND i.status='ACTIVE' ORDER BY i.sort_order,i.id",code);}
    public boolean domainExists(Long id){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM res_domain WHERE id=? AND deleted=FALSE)",Boolean.class,id));}
    public boolean poolExists(Long id){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM res_pool WHERE id=? AND deleted=FALSE)",Boolean.class,id));}
    public boolean scopeResourceExists(String type,Long id){String table=switch(type){case "CENTOS"->"res_centos";case "ROS"->"res_ros";case "LINE"->"res_line";case "IP"->"res_ip";default->null;};if(table==null)return false;return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM "+table+" WHERE id=? AND deleted=FALSE)",Boolean.class,id));}

    public int insertAudit(Long operatorId,String operatorName,String objectType,String objectId,String operation,String reason,String ip,String requestId){return jdbc.update("INSERT INTO sys_operation_log(operator_id,operator_name,module_code,object_type,object_id,operation,reason,source_ip,request_id,result) VALUES(?,?,'PRODUCT',?,?,?,?,CAST(NULLIF(?,'') AS inet),?,'SUCCESS')",operatorId,operatorName,objectType,objectId,operation,reason,ip,requestId);}
}
