-- IP代理管理平台 V11 - M7 Open API + 运行日志体系
-- V1-V10 已冻结。本脚本新增客户Open API授权模型、运行日志后台权限及高频查询索引。

CREATE TABLE open_access_grant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES customer_account(id),
    customer_id BIGINT NOT NULL REFERENCES customer(id),
    service_id BIGINT NOT NULL REFERENCES svc_instance(id),
    token_version BIGINT NOT NULL DEFAULT 1 CHECK (token_version > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','REVOKED','DISABLED')),
    policy_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    rotated_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version INT NOT NULL DEFAULT 0,
    UNIQUE(account_id, service_id)
);
CREATE INDEX idx_open_access_grant_service_status ON open_access_grant(service_id,status);
CREATE INDEX idx_open_access_grant_account_status ON open_access_grant(account_id,status);

INSERT INTO sys_permission(permission_code,permission_name,permission_type,parent_id,route_path,sort_order,status)
SELECT 'runtime-log:access','运行日志','MENU',NULL,'/runtime-logs',500,'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM sys_permission WHERE permission_code='runtime-log:access' AND deleted=FALSE);

WITH p(code,name,sort_no) AS (
  VALUES
    ('runtime-log:extract:read','查看IP提取日志',10),
    ('runtime-log:api:read','查看API日志',11),
    ('runtime-log:usage:read','查看使用日志',12)
)
INSERT INTO sys_permission(permission_code,permission_name,permission_type,parent_id,sort_order,status)
SELECT p.code,p.name,'ACTION',parent.id,p.sort_no,'ACTIVE'
FROM p JOIN sys_permission parent ON parent.permission_code='runtime-log:access' AND parent.deleted=FALSE
WHERE NOT EXISTS (SELECT 1 FROM sys_permission x WHERE x.permission_code=p.code AND x.deleted=FALSE);

INSERT INTO sys_role_permission(role_id,permission_id)
SELECT r.id,p.id FROM sys_role r CROSS JOIN sys_permission p
WHERE r.role_code='SUPER_ADMIN' AND r.deleted=FALSE AND p.deleted=FALSE
  AND (p.permission_code='runtime-log:access' OR p.permission_code LIKE 'runtime-log:%')
ON CONFLICT DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_log_ip_extract_service_result_time ON log_ip_extract(service_id,result,occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_log_api_scope_service_time ON log_api(api_scope,service_id,occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_log_usage_service_result_time ON log_usage(service_id,result,occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_svc_instance_open_lookup ON svc_instance(customer_id,status,product_type,effective_at,expire_at) WHERE deleted=FALSE;
