-- IP代理管理平台 V12 - M8 监控 + 告警 + 数据统计
-- V1-V11 已冻结。本迁移仅增加 M8 权限、采集/统计运行记录和告警去重约束。

INSERT INTO sys_permission(permission_code,permission_name,permission_type,parent_id,route_path,sort_order,status)
SELECT 'monitor:access','监控中心','MENU',NULL,'/monitor',600,'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM sys_permission WHERE permission_code='monitor:access' AND deleted=FALSE);
WITH p(code,name,sort_no) AS (
  VALUES ('monitor:read','查看监控数据',10),('monitor:collect','执行监控采集',11)
)
INSERT INTO sys_permission(permission_code,permission_name,permission_type,parent_id,sort_order,status)
SELECT p.code,p.name,'ACTION',parent.id,p.sort_no,'ACTIVE'
FROM p JOIN sys_permission parent ON parent.permission_code='monitor:access' AND parent.deleted=FALSE
WHERE NOT EXISTS (SELECT 1 FROM sys_permission x WHERE x.permission_code=p.code AND x.deleted=FALSE);

INSERT INTO sys_permission(permission_code,permission_name,permission_type,parent_id,route_path,sort_order,status)
SELECT 'alarm:access','告警中心','MENU',NULL,'/alarms',700,'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM sys_permission WHERE permission_code='alarm:access' AND deleted=FALSE);
WITH p(code,name,sort_no) AS (
  VALUES
    ('alarm:read','查看告警记录',10),
    ('alarm:rule:read','查看告警规则',20),
    ('alarm:rule:write','维护告警规则',21),
    ('alarm:handle','处理告警',30),
    ('alarm:notification:read','查看通知记录',40)
)
INSERT INTO sys_permission(permission_code,permission_name,permission_type,parent_id,sort_order,status)
SELECT p.code,p.name,'ACTION',parent.id,p.sort_no,'ACTIVE'
FROM p JOIN sys_permission parent ON parent.permission_code='alarm:access' AND parent.deleted=FALSE
WHERE NOT EXISTS (SELECT 1 FROM sys_permission x WHERE x.permission_code=p.code AND x.deleted=FALSE);

INSERT INTO sys_permission(permission_code,permission_name,permission_type,parent_id,route_path,sort_order,status)
SELECT 'statistics:access','数据统计','MENU',NULL,'/statistics',800,'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM sys_permission WHERE permission_code='statistics:access' AND deleted=FALSE);
WITH p(code,name,sort_no) AS (
  VALUES ('statistics:read','查看统计数据',10),('statistics:recalculate','执行统计重算',11)
)
INSERT INTO sys_permission(permission_code,permission_name,permission_type,parent_id,sort_order,status)
SELECT p.code,p.name,'ACTION',parent.id,p.sort_no,'ACTIVE'
FROM p JOIN sys_permission parent ON parent.permission_code='statistics:access' AND parent.deleted=FALSE
WHERE NOT EXISTS (SELECT 1 FROM sys_permission x WHERE x.permission_code=p.code AND x.deleted=FALSE);

INSERT INTO sys_role_permission(role_id,permission_id)
SELECT r.id,p.id FROM sys_role r CROSS JOIN sys_permission p
WHERE r.role_code='SUPER_ADMIN' AND r.deleted=FALSE AND p.deleted=FALSE
  AND (p.permission_code LIKE 'monitor:%' OR p.permission_code LIKE 'alarm:%' OR p.permission_code LIKE 'statistics:%')
ON CONFLICT DO NOTHING;

CREATE TABLE mon_collect_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_type VARCHAR(20) NOT NULL DEFAULT 'MANUAL' CHECK (trigger_type IN ('MANUAL','SCHEDULED','CI')),
    status VARCHAR(20) NOT NULL DEFAULT 'RUNNING' CHECK (status IN ('RUNNING','SUCCESS','PARTIAL','FAILURE')),
    object_count INT NOT NULL DEFAULT 0,
    sample_count INT NOT NULL DEFAULT 0,
    alarm_trigger_count INT NOT NULL DEFAULT 0,
    alarm_recovery_count INT NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    error_message VARCHAR(2000),
    created_by BIGINT REFERENCES sys_user(id)
);
CREATE INDEX idx_mon_collect_run_time ON mon_collect_run(started_at DESC);

CREATE TABLE stat_calculation_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_hour TIMESTAMPTZ NOT NULL,
    trigger_type VARCHAR(20) NOT NULL DEFAULT 'MANUAL' CHECK (trigger_type IN ('MANUAL','SCHEDULED','CI')),
    status VARCHAR(20) NOT NULL DEFAULT 'RUNNING' CHECK (status IN ('RUNNING','SUCCESS','FAILURE')),
    resource_rows INT NOT NULL DEFAULT 0,
    ip_rows INT NOT NULL DEFAULT 0,
    customer_usage_rows INT NOT NULL DEFAULT 0,
    product_service_rows INT NOT NULL DEFAULT 0,
    supplier_rows INT NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    error_message VARCHAR(2000),
    created_by BIGINT REFERENCES sys_user(id)
);
CREATE INDEX idx_stat_calculation_run_hour ON stat_calculation_run(stat_hour DESC,started_at DESC);

-- 同一规则、同一对象在未恢复期间只保留一个活动告警，重复触发累加 occurrence_count。
CREATE UNIQUE INDEX IF NOT EXISTS uk_alarm_event_active_rule_object
ON alarm_event(rule_id,object_type,object_id,COALESCE(metric_code,''))
WHERE status IN ('OPEN','ACKNOWLEDGED','PROCESSING');

CREATE INDEX IF NOT EXISTS idx_mon_object_status_type_collect ON mon_object_status(object_type,last_collected_at DESC);
CREATE INDEX IF NOT EXISTS idx_alarm_event_last_triggered ON alarm_event(last_triggered_at DESC,status);
CREATE INDEX IF NOT EXISTS idx_alarm_notification_channel_time ON alarm_notification(channel,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stat_resource_hour ON stat_resource_hourly(stat_hour DESC);
CREATE INDEX IF NOT EXISTS idx_stat_ip_hour ON stat_ip_hourly(stat_hour DESC);
CREATE INDEX IF NOT EXISTS idx_stat_customer_hour ON stat_customer_usage_hourly(stat_hour DESC);
CREATE INDEX IF NOT EXISTS idx_stat_product_hour ON stat_product_service_hourly(stat_hour DESC);
CREATE INDEX IF NOT EXISTS idx_stat_supplier_hour ON stat_supplier_hourly(stat_hour DESC);
