-- IP代理管理平台 V13 - V1.2 自有资源模型升级
-- V1-V12 保持冻结；本脚本将资源主链收敛为 CentOS -> ROS -> 家宽/线路(节点) -> 当前IP。
-- res_ip 继续保留为兼容/历史记录表，但不再作为业务端独立资源主数据页面。

ALTER TABLE res_centos ADD COLUMN IF NOT EXISTS host_account VARCHAR(128);
ALTER TABLE res_centos ADD COLUMN IF NOT EXISTS host_type VARCHAR(64);
ALTER TABLE res_centos ADD COLUMN IF NOT EXISTS location_name VARCHAR(128);
ALTER TABLE res_centos ADD COLUMN IF NOT EXISTS carrier_code VARCHAR(64);
ALTER TABLE res_centos ADD COLUMN IF NOT EXISTS remark VARCHAR(1000);
ALTER TABLE res_centos ADD COLUMN IF NOT EXISTS system_load NUMERIC(10,3);
ALTER TABLE res_centos ADD COLUMN IF NOT EXISTS vpn_supported BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE res_centos ADD COLUMN IF NOT EXISTS pppoe_server_name VARCHAR(255);

ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS host_type VARCHAR(64);
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS cpu_usage NUMERIC(5,2);
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS memory_usage NUMERIC(5,2);
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS disk_usage NUMERIC(5,2);
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS system_load NUMERIC(10,3);
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS uptime_seconds BIGINT;
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS record_name VARCHAR(200);
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS ha_role VARCHAR(20) NOT NULL DEFAULT 'STANDALONE';
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS replacement_ros_id BIGINT REFERENCES res_ros(id);
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS switch_status VARCHAR(32) NOT NULL DEFAULT 'NORMAL';
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS auto_switch BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS b_prefix_count INT NOT NULL DEFAULT 0;
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS c_prefix_count INT NOT NULL DEFAULT 0;
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS bas_count INT NOT NULL DEFAULT 0;
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS bas_summary JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE res_ros ADD COLUMN IF NOT EXISTS last_report_at TIMESTAMPTZ;

ALTER TABLE res_line ADD COLUMN IF NOT EXISTS line_alias VARCHAR(200);
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS broadband_account VARCHAR(255);
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS account_prefix VARCHAR(128);
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS password_cipher TEXT;
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS http_port INT;
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS socks5_port INT;
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS domain_name VARCHAR(255);
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS customer_id BIGINT REFERENCES customer(id);
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS managed_flag BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS line_type VARCHAR(32);
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS user_limit INT;
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS active_users INT NOT NULL DEFAULT 0;
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS restart_interval_minutes INT;
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS available_time_range VARCHAR(64);
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS vpn_supported BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS vpn_redial_monitor BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS bas_name VARCHAR(255);
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS bas_address VARCHAR(255);
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS province_code VARCHAR(64);
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS city_code VARCHAR(64);
ALTER TABLE res_line ADD COLUMN IF NOT EXISTS last_ros_report_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_res_line_customer ON res_line(customer_id) WHERE deleted=FALSE;
CREATE INDEX IF NOT EXISTS idx_res_line_bas ON res_line(bas_name) WHERE deleted=FALSE;
CREATE INDEX IF NOT EXISTS idx_res_line_type_status ON res_line(line_type,online_status) WHERE deleted=FALSE;

CREATE TABLE IF NOT EXISTS res_line_ip_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id BIGINT NOT NULL REFERENCES res_line(id) ON DELETE CASCADE,
    ip_address INET NOT NULL,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    change_type VARCHAR(32) NOT NULL DEFAULT 'DIAL',
    source_record_id VARCHAR(255),
    raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_res_line_ip_history_line_time ON res_line_ip_history(line_id,last_seen_at DESC);
CREATE INDEX IF NOT EXISTS idx_res_line_ip_history_ip ON res_line_ip_history(ip_address,last_seen_at DESC);

CREATE TABLE IF NOT EXISTS res_line_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id BIGINT NOT NULL REFERENCES res_line(id) ON DELETE CASCADE,
    operation_type VARCHAR(64) NOT NULL,
    operation_source VARCHAR(32) NOT NULL DEFAULT 'PLATFORM',
    before_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    after_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    result_status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
    result_message VARCHAR(1000),
    operator_id BIGINT REFERENCES sys_user(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_res_line_operation_line_time ON res_line_operation_log(line_id,created_at DESC);

ALTER TABLE res_pool ADD COLUMN IF NOT EXISTS pool_type VARCHAR(32) NOT NULL DEFAULT 'MIXED';
ALTER TABLE res_pool ADD COLUMN IF NOT EXISTS member_mode VARCHAR(20) NOT NULL DEFAULT 'LINE';

CREATE TABLE IF NOT EXISTS res_pool_line (
    pool_id BIGINT NOT NULL REFERENCES res_pool(id) ON DELETE CASCADE,
    line_id BIGINT NOT NULL REFERENCES res_line(id) ON DELETE CASCADE,
    source_reason VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    removed_at TIMESTAMPTZ,
    PRIMARY KEY(pool_id,line_id)
);
CREATE INDEX IF NOT EXISTS idx_res_pool_line_line ON res_pool_line(line_id);
CREATE INDEX IF NOT EXISTS idx_res_pool_line_enabled ON res_pool_line(pool_id,enabled);

-- 从旧IP成员关系尽可能迁移出线路成员，保留旧表用于历史兼容。
INSERT INTO res_pool_line(pool_id,line_id,source_reason,enabled,joined_at,removed_at)
SELECT DISTINCT pi.pool_id,ip.line_id,COALESCE(pi.source_reason,'V1.2由IP成员迁移'),pi.enabled,pi.joined_at,pi.removed_at
FROM res_pool_ip pi
JOIN res_ip ip ON ip.id=pi.ip_id
WHERE ip.line_id IS NOT NULL
ON CONFLICT(pool_id,line_id) DO NOTHING;

ALTER TABLE res_exclusive_allocation ADD COLUMN IF NOT EXISTS current_ip_snapshot INET;
ALTER TABLE res_exclusive_allocation ADD COLUMN IF NOT EXISTS service_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE res_domain ADD COLUMN IF NOT EXISTS customer_id BIGINT REFERENCES customer(id);
ALTER TABLE res_domain ADD COLUMN IF NOT EXISTS dns_provider VARCHAR(32) NOT NULL DEFAULT 'DNSPOD';
ALTER TABLE res_domain ADD COLUMN IF NOT EXISTS dns_record_id VARCHAR(255);
ALTER TABLE res_domain ADD COLUMN IF NOT EXISTS last_sync_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS res_domain_sync_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id BIGINT NOT NULL REFERENCES res_domain(id) ON DELETE CASCADE,
    before_ip INET,
    after_ip INET,
    provider VARCHAR(32) NOT NULL DEFAULT 'DNSPOD',
    action_type VARCHAR(32) NOT NULL DEFAULT 'SYNC',
    status VARCHAR(20) NOT NULL,
    message VARCHAR(1000),
    operator_id BIGINT REFERENCES sys_user(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_res_domain_sync_domain_time ON res_domain_sync_log(domain_id,created_at DESC);

COMMENT ON TABLE res_line IS 'V1.2统一家宽/线路对象：ROS逻辑线路=家宽账号=节点；current_public_ip为当前拨号IP';
COMMENT ON TABLE res_pool_line IS 'V1.2资源池按家宽/线路组织，不再以独立IP主数据为核心成员';
COMMENT ON COLUMN res_ros.b_prefix_count IS 'ROS当前全部拨号IPv4按前2个八位组(/16口径)去重数量';
COMMENT ON COLUMN res_ros.c_prefix_count IS 'ROS当前全部拨号IPv4按前3个八位组(/24口径)去重数量';
