-- IP代理管理平台 V14 - 外部供应商套餐采购与反向代理交付
-- V1.2真实链路：供应商 -> 运营采购套餐 -> 反向代理 -> 平台入口 -> 客户服务。

ALTER TABLE res_supplier ADD COLUMN IF NOT EXISTS supplier_website VARCHAR(1000);
ALTER TABLE res_supplier ADD COLUMN IF NOT EXISTS purchase_remark VARCHAR(1000);

CREATE TABLE IF NOT EXISTS res_supplier_purchase (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_no VARCHAR(64) NOT NULL,
    supplier_id BIGINT NOT NULL REFERENCES res_supplier(id),
    customer_id BIGINT REFERENCES customer(id),
    supplier_package_name VARCHAR(255) NOT NULL,
    supplier_package_no VARCHAR(128),
    purchase_account VARCHAR(255),
    purchase_secret_cipher TEXT,
    interface_endpoint VARCHAR(1000),
    package_quota VARCHAR(255),
    remaining_quota VARCHAR(255),
    purchase_cost NUMERIC(18,2),
    currency CHAR(3) NOT NULL DEFAULT 'CNY',
    effective_at TIMESTAMPTZ,
    expire_at TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('DRAFT','ACTIVE','EXPIRED','DISABLED')),
    remark VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_res_supplier_purchase_no ON res_supplier_purchase(purchase_no) WHERE deleted=FALSE;
CREATE INDEX IF NOT EXISTS idx_res_supplier_purchase_supplier ON res_supplier_purchase(supplier_id,status) WHERE deleted=FALSE;
CREATE INDEX IF NOT EXISTS idx_res_supplier_purchase_customer ON res_supplier_purchase(customer_id,status) WHERE deleted=FALSE;
CREATE INDEX IF NOT EXISTS idx_res_supplier_purchase_expire ON res_supplier_purchase(expire_at) WHERE deleted=FALSE AND status='ACTIVE';

CREATE TABLE IF NOT EXISTS res_reverse_proxy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proxy_no VARCHAR(64) NOT NULL,
    purchase_id BIGINT NOT NULL REFERENCES res_supplier_purchase(id),
    customer_id BIGINT NOT NULL REFERENCES customer(id),
    service_id BIGINT REFERENCES svc_instance(id),
    protocol_code VARCHAR(32) NOT NULL,
    upstream_host VARCHAR(255) NOT NULL,
    upstream_port INT NOT NULL CHECK (upstream_port BETWEEN 1 AND 65535),
    upstream_account VARCHAR(255),
    upstream_secret_cipher TEXT,
    platform_host VARCHAR(255) NOT NULL,
    platform_port INT NOT NULL CHECK (platform_port BETWEEN 1 AND 65535),
    platform_account VARCHAR(255),
    platform_secret_cipher TEXT,
    effective_at TIMESTAMPTZ,
    expire_at TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','ACTIVE','ABNORMAL','EXPIRED','DISABLED')),
    last_checked_at TIMESTAMPTZ,
    last_error VARCHAR(1000),
    remark VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_res_reverse_proxy_no ON res_reverse_proxy(proxy_no) WHERE deleted=FALSE;
CREATE INDEX IF NOT EXISTS idx_res_reverse_proxy_purchase ON res_reverse_proxy(purchase_id,status) WHERE deleted=FALSE;
CREATE INDEX IF NOT EXISTS idx_res_reverse_proxy_customer ON res_reverse_proxy(customer_id,status) WHERE deleted=FALSE;
CREATE INDEX IF NOT EXISTS idx_res_reverse_proxy_service ON res_reverse_proxy(service_id) WHERE deleted=FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS uk_res_reverse_proxy_platform_endpoint ON res_reverse_proxy(platform_host,platform_port) WHERE deleted=FALSE AND status<>'DISABLED';

ALTER TABLE svc_instance ADD COLUMN IF NOT EXISTS delivery_mode VARCHAR(24) NOT NULL DEFAULT 'SELF_OWNED';
ALTER TABLE svc_instance ADD COLUMN IF NOT EXISTS supplier_purchase_id BIGINT REFERENCES res_supplier_purchase(id);
ALTER TABLE svc_instance ADD COLUMN IF NOT EXISTS reverse_proxy_id BIGINT REFERENCES res_reverse_proxy(id);
ALTER TABLE svc_instance ADD COLUMN IF NOT EXISTS builtin_policy_code VARCHAR(64);

-- 扩展服务资源绑定类型，旧类型继续兼容。
ALTER TABLE svc_resource_binding DROP CONSTRAINT IF EXISTS svc_resource_binding_resource_type_check;
ALTER TABLE svc_resource_binding ADD CONSTRAINT svc_resource_binding_resource_type_check CHECK (
    resource_type IN ('POOL','CENTOS','ROS','LINE','IP','DOMAIN','SUPPLIER','SUPPLIER_PURCHASE','REVERSE_PROXY')
);

CREATE TABLE IF NOT EXISTS res_reverse_proxy_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reverse_proxy_id BIGINT NOT NULL REFERENCES res_reverse_proxy(id) ON DELETE CASCADE,
    operation_type VARCHAR(64) NOT NULL,
    before_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    after_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
    message VARCHAR(1000),
    operator_id BIGINT REFERENCES sys_user(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_res_reverse_proxy_log_time ON res_reverse_proxy_operation_log(reverse_proxy_id,created_at DESC);

COMMENT ON TABLE res_supplier_purchase IS '运营根据客户需求在第三方供应商购买的套餐/资源，不等同于客户销售产品';
COMMENT ON TABLE res_reverse_proxy IS '将供应商套餐通过平台反向代理入口交付给客户的配置';
COMMENT ON COLUMN svc_instance.delivery_mode IS 'SELF_OWNED=自有资源交付，EXTERNAL_PROXY=外部供应商反向代理交付';
