-- IP代理管理平台 V15 - 长效代理专项监控与客户机器人通知
-- 区分基础设施监控（CentOS/ROS）与客户服务保障监控（长效代理）。

CREATE TABLE IF NOT EXISTS lm_bot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_no VARCHAR(64) NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES customer(id),
    bot_name VARCHAR(200) NOT NULL,
    bot_type VARCHAR(20) NOT NULL CHECK (bot_type IN ('DINGTALK','FEISHU')),
    webhook_url VARCHAR(1500) NOT NULL,
    access_token_cipher TEXT,
    secret_cipher TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_test_at TIMESTAMPTZ,
    last_test_status VARCHAR(20),
    last_test_message VARCHAR(1000),
    remark VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_lm_bot_no ON lm_bot(bot_no) WHERE deleted=FALSE;
CREATE INDEX IF NOT EXISTS idx_lm_bot_customer ON lm_bot(customer_id,enabled) WHERE deleted=FALSE;

CREATE TABLE IF NOT EXISTS lm_monitor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitor_no VARCHAR(64) NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES customer(id),
    service_id BIGINT NOT NULL REFERENCES svc_instance(id),
    line_id BIGINT REFERENCES res_line(id),
    reverse_proxy_id BIGINT REFERENCES res_reverse_proxy(id),
    target_host VARCHAR(255) NOT NULL,
    target_port INT NOT NULL CHECK (target_port BETWEEN 1 AND 65535),
    proxy_protocol VARCHAR(32) NOT NULL DEFAULT 'HTTP',
    check_method VARCHAR(32) NOT NULL DEFAULT 'PROXY_CONNECT',
    check_url VARCHAR(1000),
    interval_seconds INT NOT NULL DEFAULT 60 CHECK (interval_seconds>=30),
    timeout_seconds INT NOT NULL DEFAULT 10 CHECK (timeout_seconds>0),
    failure_threshold INT NOT NULL DEFAULT 3 CHECK (failure_threshold>0),
    recovery_threshold INT NOT NULL DEFAULT 2 CHECK (recovery_threshold>0),
    bot_id BIGINT REFERENCES lm_bot(id),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    current_status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN' CHECK (current_status IN ('NORMAL','ABNORMAL','UNKNOWN')),
    consecutive_failures INT NOT NULL DEFAULT 0,
    consecutive_successes INT NOT NULL DEFAULT 0,
    last_checked_at TIMESTAMPTZ,
    last_success_at TIMESTAMPTZ,
    last_failure_at TIMESTAMPTZ,
    last_error VARCHAR(1000),
    remark VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK (line_id IS NOT NULL OR reverse_proxy_id IS NOT NULL OR target_host<>'')
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_lm_monitor_no ON lm_monitor(monitor_no) WHERE deleted=FALSE;
CREATE INDEX IF NOT EXISTS idx_lm_monitor_customer ON lm_monitor(customer_id,enabled,current_status) WHERE deleted=FALSE;
CREATE INDEX IF NOT EXISTS idx_lm_monitor_service ON lm_monitor(service_id,enabled) WHERE deleted=FALSE;
CREATE INDEX IF NOT EXISTS idx_lm_monitor_due ON lm_monitor(enabled,last_checked_at) WHERE deleted=FALSE;

CREATE TABLE IF NOT EXISTS lm_check_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitor_id BIGINT NOT NULL REFERENCES lm_monitor(id) ON DELETE CASCADE,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    success BOOLEAN NOT NULL,
    latency_ms INT,
    outbound_ip INET,
    response_code INT,
    error_type VARCHAR(64),
    error_message VARCHAR(1000),
    detail JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_lm_check_monitor_time ON lm_check_record(monitor_id,checked_at DESC);

CREATE TABLE IF NOT EXISTS lm_alarm (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alarm_no VARCHAR(64) NOT NULL,
    monitor_id BIGINT NOT NULL REFERENCES lm_monitor(id),
    customer_id BIGINT NOT NULL REFERENCES customer(id),
    service_id BIGINT NOT NULL REFERENCES svc_instance(id),
    alarm_type VARCHAR(64) NOT NULL DEFAULT 'LONG_PROXY_UNAVAILABLE',
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','RECOVERED','CLOSED')),
    opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    recovered_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    failure_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    recovery_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    close_reason VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_lm_alarm_no ON lm_alarm(alarm_no);
CREATE INDEX IF NOT EXISTS idx_lm_alarm_customer_status ON lm_alarm(customer_id,status,opened_at DESC);
CREATE INDEX IF NOT EXISTS idx_lm_alarm_monitor_time ON lm_alarm(monitor_id,opened_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uk_lm_alarm_open_monitor ON lm_alarm(monitor_id) WHERE status='OPEN';

CREATE TABLE IF NOT EXISTS lm_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alarm_id BIGINT REFERENCES lm_alarm(id),
    monitor_id BIGINT NOT NULL REFERENCES lm_monitor(id),
    bot_id BIGINT REFERENCES lm_bot(id),
    notification_type VARCHAR(32) NOT NULL CHECK (notification_type IN ('ALARM','RECOVERY','TEST')),
    channel VARCHAR(20) NOT NULL CHECK (channel IN ('DINGTALK','FEISHU')),
    request_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    response_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    send_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (send_status IN ('PENDING','SUCCESS','FAILED')),
    sent_at TIMESTAMPTZ,
    error_message VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_lm_notification_monitor_time ON lm_notification(monitor_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lm_notification_alarm ON lm_notification(alarm_id,created_at DESC);

COMMENT ON TABLE lm_monitor IS '针对客户长效代理服务创建的专项监控，不属于CentOS/ROS基础设施监控';
COMMENT ON TABLE lm_bot IS '客户钉钉/飞书机器人配置，Webhook、Token、Secret均需加密/脱敏';
