-- IP代理管理平台 V1 - 系统与客户
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    department VARCHAR(100),
    mobile VARCHAR(32),
    email VARCHAR(128),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','FROZEN','DISABLED')),
    last_login_at TIMESTAMPTZ,
    last_login_ip INET,
    password_changed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT,
    version INT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_sys_user_username ON sys_user(username) WHERE deleted = FALSE;
CREATE INDEX idx_sys_user_status ON sys_user(status) WHERE deleted = FALSE;

CREATE TABLE sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(64) NOT NULL,
    role_name VARCHAR(100) NOT NULL,
    data_scope VARCHAR(32) NOT NULL DEFAULT 'ALL',
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_sys_role_code ON sys_role(role_code) WHERE deleted = FALSE;

CREATE TABLE sys_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(128) NOT NULL,
    permission_name VARCHAR(128) NOT NULL,
    permission_type VARCHAR(20) NOT NULL CHECK (permission_type IN ('MENU','ACTION','DATA')),
    parent_id BIGINT REFERENCES sys_permission(id),
    route_path VARCHAR(255),
    sort_order INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_sys_permission_code ON sys_permission(permission_code) WHERE deleted = FALSE;
CREATE INDEX idx_sys_permission_parent ON sys_permission(parent_id);

CREATE TABLE sys_user_role (
    user_id BIGINT NOT NULL REFERENCES sys_user(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES sys_role(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);
CREATE INDEX idx_sys_user_role_role ON sys_user_role(role_id);

CREATE TABLE sys_role_permission (
    role_id BIGINT NOT NULL REFERENCES sys_role(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES sys_permission(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (role_id, permission_id)
);
CREATE INDEX idx_sys_role_permission_permission ON sys_role_permission(permission_id);

CREATE TABLE sys_dict_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_code VARCHAR(64) NOT NULL,
    dict_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    editable BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_sys_dict_type_code ON sys_dict_type(dict_code) WHERE deleted = FALSE;

CREATE TABLE sys_dict_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_type_id BIGINT NOT NULL REFERENCES sys_dict_type(id) ON DELETE CASCADE,
    item_code VARCHAR(64) NOT NULL,
    item_name VARCHAR(100) NOT NULL,
    item_value VARCHAR(255),
    sort_order INT NOT NULL DEFAULT 0,
    color_tag VARCHAR(32),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')),
    remark VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_sys_dict_item_code ON sys_dict_item(dict_type_id, item_code) WHERE deleted = FALSE;
CREATE INDEX idx_sys_dict_item_type_sort ON sys_dict_item(dict_type_id, sort_order) WHERE deleted = FALSE;

CREATE TABLE sys_parameter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    param_group VARCHAR(64) NOT NULL,
    param_code VARCHAR(128) NOT NULL,
    param_name VARCHAR(128) NOT NULL,
    param_value TEXT,
    value_type VARCHAR(20) NOT NULL DEFAULT 'STRING' CHECK (value_type IN ('STRING','NUMBER','BOOLEAN','JSON','SECRET')),
    sensitive BOOLEAN NOT NULL DEFAULT FALSE,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_sys_parameter_code ON sys_parameter(param_code) WHERE deleted = FALSE;
CREATE INDEX idx_sys_parameter_group ON sys_parameter(param_group) WHERE deleted = FALSE;

CREATE TABLE sys_login_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES sys_user(id),
    username VARCHAR(64) NOT NULL,
    login_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    login_ip INET,
    user_agent VARCHAR(1000),
    result VARCHAR(20) NOT NULL CHECK (result IN ('SUCCESS','FAILURE')),
    failure_reason VARCHAR(500),
    request_id VARCHAR(64)
);
CREATE INDEX idx_sys_login_log_user_time ON sys_login_log(user_id, login_at DESC);
CREATE INDEX idx_sys_login_log_time ON sys_login_log(login_at DESC);

CREATE TABLE sys_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id BIGINT REFERENCES sys_user(id),
    operator_name VARCHAR(100),
    module_code VARCHAR(64) NOT NULL,
    object_type VARCHAR(64) NOT NULL,
    object_id VARCHAR(128),
    operation VARCHAR(64) NOT NULL,
    before_data JSONB,
    after_data JSONB,
    reason VARCHAR(1000),
    source_ip INET,
    request_id VARCHAR(64),
    result VARCHAR(20) NOT NULL CHECK (result IN ('SUCCESS','FAILURE')),
    error_message VARCHAR(1000),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_sys_operation_log_operator_time ON sys_operation_log(operator_id, occurred_at DESC);
CREATE INDEX idx_sys_operation_log_object ON sys_operation_log(object_type, object_id, occurred_at DESC);
CREATE INDEX idx_sys_operation_log_time ON sys_operation_log(occurred_at DESC);

CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code VARCHAR(32) NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    customer_type_code VARCHAR(64) NOT NULL,
    contact_name VARCHAR(100),
    contact_phone VARCHAR(32),
    contact_email VARCHAR(128),
    auth_status VARCHAR(20) NOT NULL DEFAULT 'UNVERIFIED' CHECK (auth_status IN ('UNVERIFIED','PENDING','APPROVED','REJECTED')),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','FROZEN','DISABLED')),
    owner_user_id BIGINT REFERENCES sys_user(id),
    remark VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_customer_code ON customer(customer_code) WHERE deleted = FALSE;
CREATE INDEX idx_customer_name ON customer(customer_name) WHERE deleted = FALSE;
CREATE INDEX idx_customer_status ON customer(status, auth_status) WHERE deleted = FALSE;
CREATE INDEX idx_customer_owner ON customer(owner_user_id) WHERE deleted = FALSE;

CREATE TABLE customer_auth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_no VARCHAR(40) NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES customer(id),
    auth_type_code VARCHAR(64) NOT NULL,
    submitted_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    attachment_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','REVIEWING','APPROVED','REJECTED')),
    reviewer_id BIGINT REFERENCES sys_user(id),
    reviewed_at TIMESTAMPTZ,
    review_opinion VARCHAR(1000),
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_customer_auth_no ON customer_auth(auth_no) WHERE deleted = FALSE;
CREATE INDEX idx_customer_auth_customer ON customer_auth(customer_id, submitted_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_customer_auth_status ON customer_auth(status, submitted_at DESC) WHERE deleted = FALSE;

CREATE TABLE customer_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customer(id),
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    account_type_code VARCHAR(64) NOT NULL DEFAULT 'DEFAULT',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','FROZEN','DISABLED')),
    password_changed_at TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    last_login_ip INET,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_customer_account_username ON customer_account(username) WHERE deleted = FALSE;
CREATE INDEX idx_customer_account_customer ON customer_account(customer_id) WHERE deleted = FALSE;
CREATE INDEX idx_customer_account_status ON customer_account(status) WHERE deleted = FALSE;
