-- IP代理管理平台 V2 - 资源域

CREATE TABLE res_centos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_code VARCHAR(64) NOT NULL,
    resource_name VARCHAR(128),
    source_system VARCHAR(64) NOT NULL,
    source_id VARCHAR(128) NOT NULL,
    management_ip INET,
    region_code VARCHAR(64),
    online_status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN' CHECK (online_status IN ('ONLINE','OFFLINE','UNKNOWN')),
    cpu_usage NUMERIC(5,2),
    memory_usage NUMERIC(5,2),
    disk_usage NUMERIC(5,2),
    network_in_bps BIGINT,
    network_out_bps BIGINT,
    last_communicated_at TIMESTAMPTZ,
    last_sync_at TIMESTAMPTZ,
    raw_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_res_centos_code ON res_centos(resource_code) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_res_centos_source ON res_centos(source_system, source_id) WHERE deleted = FALSE;
CREATE INDEX idx_res_centos_status ON res_centos(online_status, region_code) WHERE deleted = FALSE;

CREATE TABLE res_ros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_code VARCHAR(64) NOT NULL,
    resource_name VARCHAR(128),
    centos_id BIGINT REFERENCES res_centos(id),
    source_system VARCHAR(64) NOT NULL,
    source_id VARCHAR(128) NOT NULL,
    management_ip INET,
    region_code VARCHAR(64),
    carrier_code VARCHAR(64),
    online_status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN' CHECK (online_status IN ('ONLINE','OFFLINE','ABNORMAL','UNKNOWN')),
    line_total INT NOT NULL DEFAULT 0,
    line_online INT NOT NULL DEFAULT 0,
    line_abnormal INT NOT NULL DEFAULT 0,
    current_ip_count INT NOT NULL DEFAULT 0,
    last_communicated_at TIMESTAMPTZ,
    last_sync_at TIMESTAMPTZ,
    raw_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_res_ros_code ON res_ros(resource_code) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_res_ros_source ON res_ros(source_system, source_id) WHERE deleted = FALSE;
CREATE INDEX idx_res_ros_centos ON res_ros(centos_id) WHERE deleted = FALSE;
CREATE INDEX idx_res_ros_status ON res_ros(online_status, region_code, carrier_code) WHERE deleted = FALSE;

CREATE TABLE res_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_code VARCHAR(64) NOT NULL,
    resource_name VARCHAR(128),
    ros_id BIGINT NOT NULL REFERENCES res_ros(id),
    source_system VARCHAR(64) NOT NULL,
    source_id VARCHAR(128) NOT NULL,
    region_code VARCHAR(64),
    carrier_code VARCHAR(64),
    broadband_account_mask VARCHAR(128),
    current_public_ip INET,
    online_status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN' CHECK (online_status IN ('ONLINE','OFFLINE','ABNORMAL','UNKNOWN')),
    dial_status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN' CHECK (dial_status IN ('CONNECTED','DIALING','FAILED','DISCONNECTED','UNKNOWN')),
    latency_ms INT,
    availability_rate NUMERIC(6,3),
    last_dial_at TIMESTAMPTZ,
    last_ip_changed_at TIMESTAMPTZ,
    last_sync_at TIMESTAMPTZ,
    raw_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_res_line_code ON res_line(resource_code) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_res_line_source ON res_line(source_system, source_id) WHERE deleted = FALSE;
CREATE INDEX idx_res_line_ros ON res_line(ros_id) WHERE deleted = FALSE;
CREATE INDEX idx_res_line_status ON res_line(online_status, dial_status, region_code, carrier_code) WHERE deleted = FALSE;
CREATE INDEX idx_res_line_ip ON res_line(current_public_ip) WHERE deleted = FALSE;

CREATE TABLE res_supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code VARCHAR(64) NOT NULL,
    supplier_name VARCHAR(200) NOT NULL,
    contact_name VARCHAR(100),
    contact_phone VARCHAR(32),
    api_endpoint VARCHAR(1000) NOT NULL,
    auth_type_code VARCHAR(64) NOT NULL,
    api_account VARCHAR(255),
    secret_cipher TEXT,
    region_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    carrier_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    fetch_mode VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED' CHECK (fetch_mode IN ('SCHEDULED','REALTIME','MANUAL')),
    interface_status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN' CHECK (interface_status IN ('NORMAL','ABNORMAL','UNKNOWN')),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','PAUSED','DISABLED')),
    last_success_at TIMESTAMPTZ,
    last_failure_at TIMESTAMPTZ,
    last_error VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_res_supplier_code ON res_supplier(supplier_code) WHERE deleted = FALSE;
CREATE INDEX idx_res_supplier_status ON res_supplier(status, interface_status) WHERE deleted = FALSE;

CREATE TABLE res_ip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address INET NOT NULL,
    source_type VARCHAR(20) NOT NULL CHECK (source_type IN ('SELF','EXTERNAL')),
    source_system VARCHAR(64),
    source_id VARCHAR(128),
    centos_id BIGINT REFERENCES res_centos(id),
    ros_id BIGINT REFERENCES res_ros(id),
    line_id BIGINT REFERENCES res_line(id),
    supplier_id BIGINT REFERENCES res_supplier(id),
    region_code VARCHAR(64),
    carrier_code VARCHAR(64),
    available_status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN' CHECK (available_status IN ('AVAILABLE','UNAVAILABLE','UNKNOWN','DISABLED')),
    latency_ms INT,
    duplicate_flag BOOLEAN NOT NULL DEFAULT FALSE,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_checked_at TIMESTAMPTZ,
    quality_score NUMERIC(6,2),
    raw_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK ((source_type='SELF' AND (line_id IS NOT NULL OR ros_id IS NOT NULL)) OR source_type='EXTERNAL')
);
CREATE UNIQUE INDEX uk_res_ip_address_source ON res_ip(ip_address, source_type, COALESCE(line_id,0), COALESCE(supplier_id,0)) WHERE deleted = FALSE;
CREATE INDEX idx_res_ip_address ON res_ip(ip_address) WHERE deleted = FALSE;
CREATE INDEX idx_res_ip_line ON res_ip(line_id) WHERE deleted = FALSE;
CREATE INDEX idx_res_ip_ros ON res_ip(ros_id) WHERE deleted = FALSE;
CREATE INDEX idx_res_ip_supplier ON res_ip(supplier_id) WHERE deleted = FALSE;
CREATE INDEX idx_res_ip_status ON res_ip(available_status, region_code, carrier_code) WHERE deleted = FALSE;
CREATE INDEX idx_res_ip_last_seen ON res_ip(last_seen_at DESC) WHERE deleted = FALSE;

CREATE TABLE res_pool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pool_code VARCHAR(64) NOT NULL,
    pool_name VARCHAR(200) NOT NULL,
    purpose VARCHAR(500),
    region_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    carrier_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    source_scope VARCHAR(20) NOT NULL DEFAULT 'MIXED' CHECK (source_scope IN ('SELF','EXTERNAL','MIXED')),
    admission_rule JSONB NOT NULL DEFAULT '{}'::jsonb,
    detection_rule JSONB NOT NULL DEFAULT '{}'::jsonb,
    dedup_rule JSONB NOT NULL DEFAULT '{}'::jsonb,
    priority INT NOT NULL DEFAULT 100,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED','ABNORMAL')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_res_pool_code ON res_pool(pool_code) WHERE deleted = FALSE;
CREATE INDEX idx_res_pool_status ON res_pool(status) WHERE deleted = FALSE;

CREATE TABLE res_pool_ip (
    pool_id BIGINT NOT NULL REFERENCES res_pool(id) ON DELETE CASCADE,
    ip_id BIGINT NOT NULL REFERENCES res_ip(id) ON DELETE CASCADE,
    source_reason VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    removed_at TIMESTAMPTZ,
    PRIMARY KEY (pool_id, ip_id)
);
CREATE INDEX idx_res_pool_ip_ip ON res_pool_ip(ip_id);
CREATE INDEX idx_res_pool_ip_enabled ON res_pool_ip(pool_id, enabled);

CREATE TABLE res_exclusive_allocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allocation_no VARCHAR(64) NOT NULL,
    resource_type VARCHAR(20) NOT NULL CHECK (resource_type IN ('IP','LINE')),
    ip_id BIGINT REFERENCES res_ip(id),
    line_id BIGINT REFERENCES res_line(id),
    customer_id BIGINT NOT NULL REFERENCES customer(id),
    service_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'LOCKED' CHECK (status IN ('AVAILABLE','LOCKED','ALLOCATED','PENDING_RECYCLE','DISABLED')),
    locked_at TIMESTAMPTZ,
    effective_at TIMESTAMPTZ,
    expire_at TIMESTAMPTZ,
    released_at TIMESTAMPTZ,
    release_reason VARCHAR(1000),
    health_status VARCHAR(20) DEFAULT 'UNKNOWN' CHECK (health_status IN ('NORMAL','ABNORMAL','UNKNOWN')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK ((resource_type='IP' AND ip_id IS NOT NULL AND line_id IS NULL) OR (resource_type='LINE' AND line_id IS NOT NULL AND ip_id IS NULL))
);
CREATE UNIQUE INDEX uk_res_exclusive_allocation_no ON res_exclusive_allocation(allocation_no) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_res_exclusive_active_ip ON res_exclusive_allocation(ip_id) WHERE deleted=FALSE AND resource_type='IP' AND status IN ('LOCKED','ALLOCATED');
CREATE UNIQUE INDEX uk_res_exclusive_active_line ON res_exclusive_allocation(line_id) WHERE deleted=FALSE AND resource_type='LINE' AND status IN ('LOCKED','ALLOCATED');
CREATE INDEX idx_res_exclusive_customer ON res_exclusive_allocation(customer_id, status) WHERE deleted = FALSE;

CREATE TABLE res_domain (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_name VARCHAR(255) NOT NULL,
    current_ip_id BIGINT REFERENCES res_ip(id),
    line_id BIGINT REFERENCES res_line(id),
    usage_type_code VARCHAR(64),
    update_mode VARCHAR(20) NOT NULL DEFAULT 'AUTO' CHECK (update_mode IN ('AUTO','MANUAL','API')),
    status VARCHAR(20) NOT NULL DEFAULT 'NORMAL' CHECK (status IN ('NORMAL','PENDING_UPDATE','FAILED','DISABLED')),
    last_updated_at TIMESTAMPTZ,
    last_error VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_res_domain_name ON res_domain(domain_name) WHERE deleted = FALSE;
CREATE INDEX idx_res_domain_status ON res_domain(status) WHERE deleted = FALSE;

CREATE TABLE res_sync_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no VARCHAR(64) NOT NULL,
    source_type VARCHAR(20) NOT NULL CHECK (source_type IN ('CENTOS','ROS','LINE','IP','SUPPLIER')),
    supplier_id BIGINT REFERENCES res_supplier(id),
    sync_mode VARCHAR(20) NOT NULL CHECK (sync_mode IN ('SCHEDULED','MANUAL','REALTIME')),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','RUNNING','SUCCESS','PARTIAL_SUCCESS','FAILED','CANCELLED')),
    requested_count INT NOT NULL DEFAULT 0,
    received_count INT NOT NULL DEFAULT 0,
    normalized_count INT NOT NULL DEFAULT 0,
    deduped_count INT NOT NULL DEFAULT 0,
    available_count INT NOT NULL DEFAULT 0,
    target_pool_id BIGINT REFERENCES res_pool(id),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    triggered_by BIGINT REFERENCES sys_user(id),
    request_id VARCHAR(64),
    error_message VARCHAR(2000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_res_sync_task_no ON res_sync_task(task_no);
CREATE INDEX idx_res_sync_task_status_time ON res_sync_task(status, created_at DESC);
CREATE INDEX idx_res_sync_task_supplier ON res_sync_task(supplier_id, created_at DESC);

CREATE TABLE res_sync_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES res_sync_task(id) ON DELETE CASCADE,
    source_record_id VARCHAR(255),
    raw_record JSONB,
    normalized_record JSONB,
    resource_type VARCHAR(20) NOT NULL CHECK (resource_type IN ('CENTOS','ROS','LINE','IP')),
    resource_id BIGINT,
    process_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (process_status IN ('PENDING','NORMALIZED','CHECKED','DEDUPED','IMPORTED','SKIPPED','FAILED')),
    duplicate_flag BOOLEAN,
    available_flag BOOLEAN,
    error_message VARCHAR(1000),
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_res_sync_detail_task_status ON res_sync_detail(task_id, process_status);
CREATE INDEX idx_res_sync_detail_resource ON res_sync_detail(resource_type, resource_id);
