-- IP代理管理平台 V3 - 产品、订单与服务

CREATE TABLE prd_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(64) NOT NULL,
    product_name VARCHAR(200) NOT NULL,
    product_type VARCHAR(20) NOT NULL CHECK (product_type IN ('SHORT_IP','LONG_IP','EXCLUSIVE_IP','VPN','TUNNEL')),
    access_mode_code VARCHAR(64) NOT NULL,
    protocol_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    auth_mode_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    resource_mode VARCHAR(20) NOT NULL DEFAULT 'SHARED' CHECK (resource_mode IN ('SHARED','EXCLUSIVE')),
    region_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    carrier_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    description VARCHAR(1000),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','ACTIVE','DISABLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_prd_product_code ON prd_product(product_code) WHERE deleted = FALSE;
CREATE INDEX idx_prd_product_type_status ON prd_product(product_type, status) WHERE deleted = FALSE;

CREATE TABLE prd_short_ip_config (
    product_id BIGINT PRIMARY KEY REFERENCES prd_product(id) ON DELETE CASCADE,
    ip_valid_seconds INT NOT NULL CHECK (ip_valid_seconds > 0),
    single_extract_limit INT NOT NULL CHECK (single_extract_limit > 0),
    extract_rate_limit INT,
    extract_rate_window_seconds INT,
    dedup_period_seconds INT,
    switch_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
    whitelist_required BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE prd_long_ip_config (
    product_id BIGINT PRIMARY KEY REFERENCES prd_product(id) ON DELETE CASCADE,
    hold_period_seconds BIGINT,
    bind_type VARCHAR(20) NOT NULL CHECK (bind_type IN ('IP','LINE')),
    auto_replace BOOLEAN NOT NULL DEFAULT TRUE,
    failure_threshold INT NOT NULL DEFAULT 3 CHECK (failure_threshold > 0),
    failover_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE prd_exclusive_ip_config (
    product_id BIGINT PRIMARY KEY REFERENCES prd_product(id) ON DELETE CASCADE,
    exclusive_resource_type VARCHAR(20) NOT NULL CHECK (exclusive_resource_type IN ('IP','LINE')),
    resource_count_default INT NOT NULL DEFAULT 1 CHECK (resource_count_default > 0),
    lock_timeout_seconds INT NOT NULL DEFAULT 300,
    replacement_rule JSONB NOT NULL DEFAULT '{}'::jsonb,
    release_rule JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE prd_vpn_config (
    product_id BIGINT PRIMARY KEY REFERENCES prd_product(id) ON DELETE CASCADE,
    vpn_protocol_code VARCHAR(64) NOT NULL,
    credential_type_code VARCHAR(64) NOT NULL,
    default_device_limit INT,
    default_connection_limit INT,
    outbound_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE prd_tunnel_config (
    product_id BIGINT PRIMARY KEY REFERENCES prd_product(id) ON DELETE CASCADE,
    entry_domain_id BIGINT REFERENCES res_domain(id),
    entry_host VARCHAR(255),
    entry_port INT NOT NULL CHECK (entry_port BETWEEN 1 AND 65535),
    session_hold_seconds INT,
    concurrency_limit INT,
    ip_switch_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (entry_domain_id IS NOT NULL OR entry_host IS NOT NULL)
);

CREATE TABLE prd_package (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_code VARCHAR(64) NOT NULL,
    product_id BIGINT NOT NULL REFERENCES prd_product(id),
    package_name VARCHAR(200) NOT NULL,
    service_days INT NOT NULL CHECK (service_days > 0),
    ip_count INT,
    extract_quota BIGINT,
    traffic_quota_bytes BIGINT,
    concurrency_limit INT,
    device_limit INT,
    whitelist_limit INT,
    change_ip_limit INT,
    price NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (price >= 0),
    currency CHAR(3) NOT NULL DEFAULT 'CNY',
    quota_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_prd_package_code ON prd_package(package_code) WHERE deleted = FALSE;
CREATE INDEX idx_prd_package_product ON prd_package(product_id, status) WHERE deleted = FALSE;

CREATE TABLE prd_resource_strategy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_code VARCHAR(64) NOT NULL,
    strategy_name VARCHAR(200) NOT NULL,
    product_id BIGINT NOT NULL REFERENCES prd_product(id),
    dispatch_mode VARCHAR(32) NOT NULL CHECK (dispatch_mode IN ('PRIORITY','ROUND_ROBIN','RANDOM','WEIGHTED_RANDOM','QUALITY_FIRST','LATENCY_FIRST')),
    source_priority JSONB NOT NULL DEFAULT '[]'::jsonb,
    region_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    carrier_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    failover_rule JSONB NOT NULL DEFAULT '{}'::jsonb,
    ip_hold_rule JSONB NOT NULL DEFAULT '{}'::jsonb,
    switch_rule JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_prd_strategy_code ON prd_resource_strategy(strategy_code) WHERE deleted = FALSE;
CREATE INDEX idx_prd_strategy_product ON prd_resource_strategy(product_id, status) WHERE deleted = FALSE;

CREATE TABLE prd_strategy_pool (
    strategy_id BIGINT NOT NULL REFERENCES prd_resource_strategy(id) ON DELETE CASCADE,
    pool_id BIGINT NOT NULL REFERENCES res_pool(id),
    priority INT NOT NULL DEFAULT 100,
    weight INT NOT NULL DEFAULT 100,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (strategy_id, pool_id)
);
CREATE INDEX idx_prd_strategy_pool_pool ON prd_strategy_pool(pool_id);

CREATE TABLE prd_strategy_scope (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_id BIGINT NOT NULL REFERENCES prd_resource_strategy(id) ON DELETE CASCADE,
    scope_type VARCHAR(20) NOT NULL CHECK (scope_type IN ('CENTOS','ROS','LINE','IP','NODE_TAG')),
    resource_id BIGINT,
    scope_code VARCHAR(128),
    include_flag BOOLEAN NOT NULL DEFAULT TRUE,
    priority INT NOT NULL DEFAULT 100,
    CHECK (resource_id IS NOT NULL OR scope_code IS NOT NULL)
);
CREATE INDEX idx_prd_strategy_scope_strategy ON prd_strategy_scope(strategy_id, scope_type);

CREATE TABLE biz_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES customer(id),
    order_type VARCHAR(20) NOT NULL CHECK (order_type IN ('NEW','RENEW','EXPAND','CHANGE')),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING_CONFIRM' CHECK (status IN ('DRAFT','PENDING_CONFIRM','PENDING_PROVISION','PROVISIONED','COMPLETED','CANCELLED')),
    total_amount NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    currency CHAR(3) NOT NULL DEFAULT 'CNY',
    expected_effective_at TIMESTAMPTZ,
    expected_expire_at TIMESTAMPTZ,
    owner_user_id BIGINT REFERENCES sys_user(id),
    remark VARCHAR(1000),
    confirmed_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    cancel_reason VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_biz_order_no ON biz_order(order_no) WHERE deleted = FALSE;
CREATE INDEX idx_biz_order_customer_time ON biz_order(customer_id, created_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_biz_order_status_time ON biz_order(status, created_at DESC) WHERE deleted = FALSE;

CREATE TABLE biz_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES biz_order(id) ON DELETE CASCADE,
    line_no INT NOT NULL,
    product_id BIGINT NOT NULL REFERENCES prd_product(id),
    package_id BIGINT REFERENCES prd_package(id),
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (unit_price >= 0),
    line_amount NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (line_amount >= 0),
    product_snapshot JSONB NOT NULL,
    package_snapshot JSONB,
    entitlement_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    service_count INT NOT NULL DEFAULT 1 CHECK (service_count > 0),
    remark VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(order_id, line_no)
);
CREATE INDEX idx_biz_order_item_product ON biz_order_item(product_id);
CREATE INDEX idx_biz_order_item_package ON biz_order_item(package_id);

CREATE TABLE svc_instance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_no VARCHAR(64) NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES customer(id),
    order_id BIGINT REFERENCES biz_order(id),
    order_item_id BIGINT REFERENCES biz_order_item(id),
    product_id BIGINT NOT NULL REFERENCES prd_product(id),
    package_id BIGINT REFERENCES prd_package(id),
    strategy_id BIGINT REFERENCES prd_resource_strategy(id),
    product_type VARCHAR(20) NOT NULL CHECK (product_type IN ('SHORT_IP','LONG_IP','EXCLUSIVE_IP','VPN','TUNNEL')),
    product_snapshot JSONB NOT NULL,
    package_snapshot JSONB,
    strategy_snapshot JSONB,
    quota_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    effective_at TIMESTAMPTZ,
    expire_at TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','ACTIVE','SUSPENDED','EXPIRED','TERMINATED','PROVISION_FAILED')),
    last_used_at TIMESTAMPTZ,
    failure_reason VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_svc_instance_no ON svc_instance(service_no) WHERE deleted = FALSE;
CREATE INDEX idx_svc_instance_customer_status ON svc_instance(customer_id, status) WHERE deleted = FALSE;
CREATE INDEX idx_svc_instance_product_status ON svc_instance(product_id, status) WHERE deleted = FALSE;
CREATE INDEX idx_svc_instance_expire ON svc_instance(expire_at) WHERE deleted = FALSE AND status IN ('ACTIVE','SUSPENDED');
CREATE INDEX idx_svc_instance_order ON svc_instance(order_id, order_item_id) WHERE deleted = FALSE;

ALTER TABLE res_exclusive_allocation
    ADD CONSTRAINT fk_res_exclusive_service FOREIGN KEY (service_id) REFERENCES svc_instance(id);

CREATE TABLE svc_resource_binding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL REFERENCES svc_instance(id) ON DELETE CASCADE,
    resource_type VARCHAR(20) NOT NULL CHECK (resource_type IN ('POOL','CENTOS','ROS','LINE','IP','DOMAIN','SUPPLIER')),
    resource_id BIGINT NOT NULL,
    binding_role VARCHAR(20) NOT NULL DEFAULT 'PRIMARY' CHECK (binding_role IN ('PRIMARY','BACKUP','CANDIDATE','ENTRY','OUTBOUND')),
    effective_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    released_at TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','RELEASED','FAILED')),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    UNIQUE(service_id, resource_type, resource_id, effective_at)
);
CREATE INDEX idx_svc_resource_binding_service ON svc_resource_binding(service_id, status);
CREATE INDEX idx_svc_resource_binding_resource ON svc_resource_binding(resource_type, resource_id, status);

CREATE TABLE svc_credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL REFERENCES svc_instance(id) ON DELETE CASCADE,
    credential_type VARCHAR(32) NOT NULL CHECK (credential_type IN ('TOKEN','USERNAME_PASSWORD','VPN_PRIVATE_KEY','VPN_CERTIFICATE','TUNNEL_ACCOUNT')),
    account_name VARCHAR(128),
    secret_hash VARCHAR(255),
    secret_cipher TEXT,
    secret_mask VARCHAR(128),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','FROZEN','REVOKED','EXPIRED')),
    issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expire_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    rotated_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_svc_credential_service ON svc_credential(service_id, credential_type, status) WHERE deleted = FALSE;
CREATE INDEX idx_svc_credential_account ON svc_credential(account_name) WHERE deleted = FALSE AND account_name IS NOT NULL;

CREATE TABLE svc_whitelist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL REFERENCES svc_instance(id) ON DELETE CASCADE,
    ip_address INET NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')),
    remark VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_svc_whitelist_service_ip ON svc_whitelist(service_id, ip_address) WHERE deleted = FALSE;

CREATE TABLE svc_change (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    change_no VARCHAR(64) NOT NULL,
    service_id BIGINT NOT NULL REFERENCES svc_instance(id),
    change_type VARCHAR(32) NOT NULL CHECK (change_type IN ('RENEW','EXPAND','PACKAGE_CHANGE','IP_CHANGE','LINE_CHANGE','POOL_CHANGE','SUSPEND','RESUME','TERMINATE','CREDENTIAL_RESET')),
    before_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    after_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    reason VARCHAR(1000),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','PROCESSING','SUCCESS','FAILED','CANCELLED')),
    operator_id BIGINT REFERENCES sys_user(id),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    error_message VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_svc_change_no ON svc_change(change_no) WHERE deleted = FALSE;
CREATE INDEX idx_svc_change_service_time ON svc_change(service_id, created_at DESC) WHERE deleted = FALSE;
CREATE INDEX idx_svc_change_status ON svc_change(status, created_at DESC) WHERE deleted = FALSE;

CREATE TABLE svc_release_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_no VARCHAR(64) NOT NULL,
    service_id BIGINT NOT NULL REFERENCES svc_instance(id),
    trigger_type VARCHAR(20) NOT NULL CHECK (trigger_type IN ('EXPIRE','TERMINATE','MANUAL','CHANGE')),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','PROCESSING','SUCCESS','PARTIAL_SUCCESS','FAILED')),
    credential_result JSONB NOT NULL DEFAULT '{}'::jsonb,
    resource_result JSONB NOT NULL DEFAULT '{}'::jsonb,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    operator_id BIGINT REFERENCES sys_user(id),
    error_message VARCHAR(2000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_svc_release_no ON svc_release_record(release_no);
CREATE INDEX idx_svc_release_service_time ON svc_release_record(service_id, created_at DESC);
CREATE INDEX idx_svc_release_status ON svc_release_record(status, created_at DESC);
