-- IP代理管理平台 V4 - 监控、日志、告警、统计

CREATE TABLE mon_object_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_type VARCHAR(32) NOT NULL CHECK (object_type IN ('CENTOS','ROS','LINE','IP','POOL','SUPPLIER','SERVICE')),
    object_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN' CHECK (status IN ('NORMAL','ABNORMAL','ONLINE','OFFLINE','UNKNOWN')),
    health_score NUMERIC(6,2),
    current_metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    last_success_at TIMESTAMPTZ,
    last_failure_at TIMESTAMPTZ,
    last_collected_at TIMESTAMPTZ,
    last_error VARCHAR(1000),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version INT NOT NULL DEFAULT 0,
    UNIQUE(object_type, object_id)
);
CREATE INDEX idx_mon_object_status_state ON mon_object_status(object_type, status);
CREATE INDEX idx_mon_object_status_collected ON mon_object_status(last_collected_at);

CREATE TABLE mon_metric_sample (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    object_type VARCHAR(32) NOT NULL,
    object_id BIGINT NOT NULL,
    metric_code VARCHAR(64) NOT NULL,
    metric_value NUMERIC(24,6),
    metric_text VARCHAR(500),
    labels JSONB NOT NULL DEFAULT '{}'::jsonb,
    collected_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id, collected_at)
) PARTITION BY RANGE (collected_at);
CREATE INDEX idx_mon_metric_object_time ON mon_metric_sample(object_type, object_id, collected_at DESC);
CREATE INDEX idx_mon_metric_code_time ON mon_metric_sample(metric_code, collected_at DESC);
CREATE TABLE mon_metric_sample_default PARTITION OF mon_metric_sample DEFAULT;

CREATE TABLE log_ip_extract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_id VARCHAR(64) NOT NULL,
    customer_id BIGINT REFERENCES customer(id),
    account_id BIGINT REFERENCES customer_account(id),
    service_id BIGINT REFERENCES svc_instance(id),
    product_id BIGINT REFERENCES prd_product(id),
    client_ip INET,
    requested_protocol_code VARCHAR(64),
    region_code VARCHAR(64),
    carrier_code VARCHAR(64),
    requested_count INT NOT NULL DEFAULT 0,
    returned_count INT NOT NULL DEFAULT 0,
    returned_ips JSONB NOT NULL DEFAULT '[]'::jsonb,
    resource_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    result VARCHAR(20) NOT NULL CHECK (result IN ('SUCCESS','FAILURE','PARTIAL')),
    error_code VARCHAR(64),
    error_message VARCHAR(1000),
    elapsed_ms INT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);
CREATE INDEX idx_log_ip_extract_service_time ON log_ip_extract(service_id, occurred_at DESC);
CREATE INDEX idx_log_ip_extract_customer_time ON log_ip_extract(customer_id, occurred_at DESC);
CREATE INDEX idx_log_ip_extract_request ON log_ip_extract(request_id, occurred_at DESC);
CREATE TABLE log_ip_extract_default PARTITION OF log_ip_extract DEFAULT;

CREATE TABLE log_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_id VARCHAR(64),
    customer_id BIGINT REFERENCES customer(id),
    service_id BIGINT REFERENCES svc_instance(id),
    product_id BIGINT REFERENCES prd_product(id),
    client_ip INET,
    outbound_ip INET,
    ros_id BIGINT REFERENCES res_ros(id),
    line_id BIGINT REFERENCES res_line(id),
    protocol_code VARCHAR(64),
    target_host VARCHAR(512),
    target_url TEXT,
    result VARCHAR(20) NOT NULL CHECK (result IN ('SUCCESS','FAILURE')),
    status_code VARCHAR(32),
    upload_bytes BIGINT NOT NULL DEFAULT 0,
    download_bytes BIGINT NOT NULL DEFAULT 0,
    elapsed_ms INT,
    error_message VARCHAR(1000),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);
CREATE INDEX idx_log_usage_service_time ON log_usage(service_id, occurred_at DESC);
CREATE INDEX idx_log_usage_customer_time ON log_usage(customer_id, occurred_at DESC);
CREATE INDEX idx_log_usage_outbound_time ON log_usage(outbound_ip, occurred_at DESC);
CREATE TABLE log_usage_default PARTITION OF log_usage DEFAULT;

CREATE TABLE log_api (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_id VARCHAR(64) NOT NULL,
    api_scope VARCHAR(20) NOT NULL CHECK (api_scope IN ('ADMIN','OPEN','INTERNAL')),
    customer_id BIGINT REFERENCES customer(id),
    account_id BIGINT REFERENCES customer_account(id),
    user_id BIGINT REFERENCES sys_user(id),
    service_id BIGINT REFERENCES svc_instance(id),
    method VARCHAR(10) NOT NULL,
    path VARCHAR(1000) NOT NULL,
    query_summary JSONB,
    client_ip INET,
    response_status INT,
    result VARCHAR(20) NOT NULL CHECK (result IN ('SUCCESS','FAILURE')),
    error_code VARCHAR(64),
    error_message VARCHAR(1000),
    elapsed_ms INT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);
CREATE INDEX idx_log_api_request ON log_api(request_id, occurred_at DESC);
CREATE INDEX idx_log_api_customer_time ON log_api(customer_id, occurred_at DESC);
CREATE INDEX idx_log_api_path_time ON log_api(path, occurred_at DESC);
CREATE TABLE log_api_default PARTITION OF log_api DEFAULT;

CREATE TABLE log_ros_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    centos_id BIGINT REFERENCES res_centos(id),
    ros_id BIGINT REFERENCES res_ros(id),
    event_type VARCHAR(64) NOT NULL,
    event_content JSONB NOT NULL DEFAULT '{}'::jsonb,
    result VARCHAR(20) CHECK (result IN ('SUCCESS','FAILURE','INFO')),
    error_message VARCHAR(1000),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);
CREATE INDEX idx_log_ros_event_ros_time ON log_ros_event(ros_id, occurred_at DESC);
CREATE TABLE log_ros_event_default PARTITION OF log_ros_event DEFAULT;

CREATE TABLE log_line_dial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ros_id BIGINT REFERENCES res_ros(id),
    line_id BIGINT NOT NULL REFERENCES res_line(id),
    before_ip INET,
    after_ip INET,
    dial_result VARCHAR(20) NOT NULL CHECK (dial_result IN ('SUCCESS','FAILURE')),
    elapsed_ms INT,
    failure_reason VARCHAR(1000),
    trigger_type VARCHAR(20) DEFAULT 'UPSTREAM' CHECK (trigger_type IN ('UPSTREAM','MANUAL','STRATEGY','UNKNOWN')),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);
CREATE INDEX idx_log_line_dial_line_time ON log_line_dial(line_id, occurred_at DESC);
CREATE TABLE log_line_dial_default PARTITION OF log_line_dial DEFAULT;

CREATE TABLE log_ip_change (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ros_id BIGINT REFERENCES res_ros(id),
    line_id BIGINT NOT NULL REFERENCES res_line(id),
    old_ip INET,
    new_ip INET,
    change_reason VARCHAR(64),
    domain_update_status VARCHAR(20) CHECK (domain_update_status IN ('NOT_REQUIRED','PENDING','SUCCESS','FAILED')),
    affected_service_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);
CREATE INDEX idx_log_ip_change_line_time ON log_ip_change(line_id, occurred_at DESC);
CREATE INDEX idx_log_ip_change_new_ip ON log_ip_change(new_ip, occurred_at DESC);
CREATE TABLE log_ip_change_default PARTITION OF log_ip_change DEFAULT;

CREATE TABLE log_external_fetch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    supplier_id BIGINT NOT NULL REFERENCES res_supplier(id),
    sync_task_id BIGINT REFERENCES res_sync_task(id),
    request_id VARCHAR(64),
    endpoint VARCHAR(1000),
    requested_count INT NOT NULL DEFAULT 0,
    received_count INT NOT NULL DEFAULT 0,
    imported_count INT NOT NULL DEFAULT 0,
    result VARCHAR(20) NOT NULL CHECK (result IN ('SUCCESS','PARTIAL','FAILURE')),
    response_code VARCHAR(64),
    elapsed_ms INT,
    error_message VARCHAR(1000),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);
CREATE INDEX idx_log_external_supplier_time ON log_external_fetch(supplier_id, occurred_at DESC);
CREATE INDEX idx_log_external_task ON log_external_fetch(sync_task_id, occurred_at DESC);
CREATE TABLE log_external_fetch_default PARTITION OF log_external_fetch DEFAULT;

CREATE TABLE alarm_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code VARCHAR(64) NOT NULL,
    rule_name VARCHAR(200) NOT NULL,
    object_type VARCHAR(32) NOT NULL CHECK (object_type IN ('CENTOS','ROS','LINE','IP','POOL','SUPPLIER','SERVICE')),
    metric_code VARCHAR(64) NOT NULL,
    operator VARCHAR(16) NOT NULL CHECK (operator IN ('EQ','NE','GT','GTE','LT','LTE','IN','NOT_IN')),
    threshold JSONB NOT NULL,
    duration_seconds INT NOT NULL DEFAULT 0,
    consecutive_count INT NOT NULL DEFAULT 1 CHECK (consecutive_count > 0),
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('INFO','MINOR','MAJOR','CRITICAL')),
    notification_channels JSONB NOT NULL DEFAULT '["PLATFORM"]'::jsonb,
    notify_recovery BOOLEAN NOT NULL DEFAULT TRUE,
    repeat_interval_seconds INT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_by BIGINT,
    version INT NOT NULL DEFAULT 0, deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX uk_alarm_rule_code ON alarm_rule(rule_code) WHERE deleted = FALSE;
CREATE INDEX idx_alarm_rule_object_status ON alarm_rule(object_type, status) WHERE deleted = FALSE;

CREATE TABLE alarm_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alarm_no VARCHAR(64) NOT NULL,
    rule_id BIGINT REFERENCES alarm_rule(id),
    object_type VARCHAR(32) NOT NULL,
    object_id BIGINT NOT NULL,
    object_name VARCHAR(255),
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('INFO','MINOR','MAJOR','CRITICAL')),
    metric_code VARCHAR(64),
    threshold JSONB,
    current_value JSONB,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','ACKNOWLEDGED','PROCESSING','RECOVERED','CLOSED')),
    first_triggered_at TIMESTAMPTZ NOT NULL,
    last_triggered_at TIMESTAMPTZ NOT NULL,
    occurrence_count INT NOT NULL DEFAULT 1,
    acknowledged_by BIGINT REFERENCES sys_user(id),
    acknowledged_at TIMESTAMPTZ,
    handler_id BIGINT REFERENCES sys_user(id),
    recovered_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    recovery_value JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version INT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX uk_alarm_event_no ON alarm_event(alarm_no);
CREATE INDEX idx_alarm_event_status_severity ON alarm_event(status, severity, first_triggered_at DESC);
CREATE INDEX idx_alarm_event_object ON alarm_event(object_type, object_id, status);
CREATE INDEX idx_alarm_event_rule ON alarm_event(rule_id, first_triggered_at DESC);

CREATE TABLE alarm_process_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alarm_id BIGINT NOT NULL REFERENCES alarm_event(id) ON DELETE CASCADE,
    action VARCHAR(32) NOT NULL CHECK (action IN ('ACKNOWLEDGE','START_PROCESS','ADD_NOTE','RECOVER','CLOSE','REOPEN')),
    before_status VARCHAR(20),
    after_status VARCHAR(20),
    operator_id BIGINT REFERENCES sys_user(id),
    remark VARCHAR(2000),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_alarm_process_alarm_time ON alarm_process_record(alarm_id, occurred_at DESC);

CREATE TABLE alarm_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alarm_id BIGINT NOT NULL REFERENCES alarm_event(id) ON DELETE CASCADE,
    channel VARCHAR(20) NOT NULL CHECK (channel IN ('PLATFORM','DINGTALK','WEBHOOK')),
    target VARCHAR(1000),
    template_code VARCHAR(64),
    message_snapshot TEXT,
    result VARCHAR(20) NOT NULL CHECK (result IN ('PENDING','SUCCESS','FAILURE')),
    retry_count INT NOT NULL DEFAULT 0,
    sent_at TIMESTAMPTZ,
    error_message VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_alarm_notification_alarm ON alarm_notification(alarm_id, created_at DESC);
CREATE INDEX idx_alarm_notification_result ON alarm_notification(result, created_at);

CREATE TABLE stat_resource_hourly (
    stat_hour TIMESTAMPTZ NOT NULL,
    region_code VARCHAR(64) NOT NULL DEFAULT '',
    carrier_code VARCHAR(64) NOT NULL DEFAULT '',
    centos_total INT NOT NULL DEFAULT 0,
    centos_online INT NOT NULL DEFAULT 0,
    ros_total INT NOT NULL DEFAULT 0,
    ros_online INT NOT NULL DEFAULT 0,
    line_total INT NOT NULL DEFAULT 0,
    line_online INT NOT NULL DEFAULT 0,
    line_abnormal INT NOT NULL DEFAULT 0,
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stat_hour, region_code, carrier_code)
);

CREATE TABLE stat_ip_hourly (
    stat_hour TIMESTAMPTZ NOT NULL,
    pool_id BIGINT NOT NULL DEFAULT 0,
    region_code VARCHAR(64) NOT NULL DEFAULT '',
    carrier_code VARCHAR(64) NOT NULL DEFAULT '',
    source_type VARCHAR(20) NOT NULL DEFAULT '',
    ip_total BIGINT NOT NULL DEFAULT 0,
    ip_unique BIGINT NOT NULL DEFAULT 0,
    ip_available BIGINT NOT NULL DEFAULT 0,
    ip_unavailable BIGINT NOT NULL DEFAULT 0,
    duplicate_count BIGINT NOT NULL DEFAULT 0,
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stat_hour, pool_id, region_code, carrier_code, source_type)
);

CREATE TABLE stat_customer_usage_hourly (
    stat_hour TIMESTAMPTZ NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES customer(id),
    service_id BIGINT NOT NULL REFERENCES svc_instance(id),
    product_id BIGINT NOT NULL REFERENCES prd_product(id),
    extract_count BIGINT NOT NULL DEFAULT 0,
    returned_ip_count BIGINT NOT NULL DEFAULT 0,
    unique_outbound_ip_count BIGINT NOT NULL DEFAULT 0,
    request_count BIGINT NOT NULL DEFAULT 0,
    success_count BIGINT NOT NULL DEFAULT 0,
    failure_count BIGINT NOT NULL DEFAULT 0,
    upload_bytes BIGINT NOT NULL DEFAULT 0,
    download_bytes BIGINT NOT NULL DEFAULT 0,
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stat_hour, customer_id, service_id)
);
CREATE INDEX idx_stat_customer_usage_product ON stat_customer_usage_hourly(product_id, stat_hour DESC);

CREATE TABLE stat_product_service_hourly (
    stat_hour TIMESTAMPTZ NOT NULL,
    product_id BIGINT NOT NULL REFERENCES prd_product(id),
    package_id BIGINT NOT NULL DEFAULT 0,
    active_customer_count BIGINT NOT NULL DEFAULT 0,
    active_service_count BIGINT NOT NULL DEFAULT 0,
    extract_count BIGINT NOT NULL DEFAULT 0,
    request_count BIGINT NOT NULL DEFAULT 0,
    success_count BIGINT NOT NULL DEFAULT 0,
    unique_outbound_ip_count BIGINT NOT NULL DEFAULT 0,
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stat_hour, product_id, package_id)
);

CREATE TABLE stat_supplier_hourly (
    stat_hour TIMESTAMPTZ NOT NULL,
    supplier_id BIGINT NOT NULL REFERENCES res_supplier(id),
    fetch_count BIGINT NOT NULL DEFAULT 0,
    success_count BIGINT NOT NULL DEFAULT 0,
    failure_count BIGINT NOT NULL DEFAULT 0,
    received_resource_count BIGINT NOT NULL DEFAULT 0,
    unique_ip_count BIGINT NOT NULL DEFAULT 0,
    available_ip_count BIGINT NOT NULL DEFAULT 0,
    imported_ip_count BIGINT NOT NULL DEFAULT 0,
    avg_elapsed_ms NUMERIC(12,2),
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stat_hour, supplier_id)
);
