package com.ipproxy.platform.runtime;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.time.OffsetDateTime;
import java.util.*;

@Repository
public class RuntimeOperationsRepository {
    private final JdbcTemplate jdbc;
    public RuntimeOperationsRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
    private Map<String,Object> one(String sql,Object... args){List<Map<String,Object>> r=jdbc.queryForList(sql,args);return r.isEmpty()?null:r.getFirst();}

    public Long startCollect(String triggerType,Long userId){return jdbc.queryForObject("INSERT INTO mon_collect_run(trigger_type,status,created_by) VALUES(?,'RUNNING',?) RETURNING id",Long.class,triggerType,userId);}
    public void finishCollect(Long id,String status,int objects,int samples,int triggered,int recovered,String error){jdbc.update("UPDATE mon_collect_run SET status=?,object_count=?,sample_count=?,alarm_trigger_count=?,alarm_recovery_count=?,error_message=?,finished_at=now() WHERE id=?",status,objects,samples,triggered,recovered,error,id);}
    public Map<String,Object> lastCollect(){return one("SELECT * FROM mon_collect_run ORDER BY started_at DESC LIMIT 1");}

    public List<Map<String,Object>> centosTargets(){return jdbc.queryForList("SELECT id object_id,resource_code object_code,COALESCE(resource_name,resource_code) object_name,online_status source_status,last_sync_at source_at,cpu_usage,memory_usage,disk_usage,network_in_bps,network_out_bps FROM res_centos WHERE deleted=FALSE ORDER BY id");}
    public List<Map<String,Object>> rosTargets(){return jdbc.queryForList("SELECT id object_id,resource_code object_code,COALESCE(resource_name,resource_code) object_name,online_status source_status,last_sync_at source_at,line_total,line_online,line_abnormal,current_ip_count FROM res_ros WHERE deleted=FALSE ORDER BY id");}
    public List<Map<String,Object>> lineTargets(){return jdbc.queryForList("SELECT id object_id,resource_code object_code,COALESCE(resource_name,resource_code) object_name,online_status source_status,last_sync_at source_at,dial_status,latency_ms,availability_rate FROM res_line WHERE deleted=FALSE ORDER BY id");}
    public List<Map<String,Object>> ipTargets(){return jdbc.queryForList("SELECT id object_id,host(ip_address) object_code,host(ip_address) object_name,available_status source_status,COALESCE(last_checked_at,last_seen_at) source_at,latency_ms,quality_score,duplicate_flag FROM res_ip WHERE deleted=FALSE ORDER BY id");}
    public List<Map<String,Object>> poolTargets(){return jdbc.queryForList("SELECT p.id object_id,p.pool_code object_code,p.pool_name object_name,p.status source_status,p.updated_at source_at,COUNT(pi.ip_id) FILTER(WHERE pi.enabled=TRUE) ip_total,COUNT(pi.ip_id) FILTER(WHERE pi.enabled=TRUE AND i.available_status='AVAILABLE') ip_available,COUNT(pi.ip_id) FILTER(WHERE pi.enabled=TRUE AND i.available_status='UNAVAILABLE') ip_unavailable FROM res_pool p LEFT JOIN res_pool_ip pi ON pi.pool_id=p.id LEFT JOIN res_ip i ON i.id=pi.ip_id AND i.deleted=FALSE WHERE p.deleted=FALSE GROUP BY p.id ORDER BY p.id");}
    public List<Map<String,Object>> supplierTargets(){return jdbc.queryForList("SELECT id object_id,supplier_code object_code,supplier_name object_name,CASE WHEN status='DISABLED' THEN 'DISABLED' WHEN interface_status='NORMAL' THEN 'NORMAL' WHEN interface_status='ABNORMAL' THEN 'ABNORMAL' ELSE 'UNKNOWN' END source_status,COALESCE(last_success_at,last_failure_at,updated_at) source_at,interface_status,status supplier_status FROM res_supplier WHERE deleted=FALSE ORDER BY id");}
    public List<Map<String,Object>> serviceTargets(){return jdbc.queryForList("SELECT s.id object_id,s.service_no object_code,s.service_no object_name,s.status source_status,s.updated_at source_at,COALESCE((SELECT COUNT(*) FROM log_api a WHERE a.service_id=s.id AND a.occurred_at>=now()-interval '5 minutes'),0) api_requests_5m,COALESCE((SELECT COUNT(*) FROM log_api a WHERE a.service_id=s.id AND a.result='FAILURE' AND a.occurred_at>=now()-interval '5 minutes'),0) api_failures_5m,COALESCE((SELECT SUM(e.returned_count) FROM log_ip_extract e WHERE e.service_id=s.id AND e.occurred_at>=now()-interval '5 minutes'),0) returned_ips_5m FROM svc_instance s WHERE s.deleted=FALSE ORDER BY s.id");}

    public void upsertObjectStatus(String type,Long id,String status,Double health,String metricsJson,boolean success,String error){jdbc.update("INSERT INTO mon_object_status(object_type,object_id,status,health_score,current_metrics,last_success_at,last_failure_at,last_collected_at,last_error,updated_at) VALUES(?,?,?,?,CAST(? AS jsonb),CASE WHEN ? THEN now() END,CASE WHEN ? THEN NULL ELSE now() END,now(),?,now()) ON CONFLICT(object_type,object_id) DO UPDATE SET status=EXCLUDED.status,health_score=EXCLUDED.health_score,current_metrics=EXCLUDED.current_metrics,last_success_at=CASE WHEN ? THEN now() ELSE mon_object_status.last_success_at END,last_failure_at=CASE WHEN ? THEN mon_object_status.last_failure_at ELSE now() END,last_collected_at=now(),last_error=?,updated_at=now(),version=mon_object_status.version+1",type,id,status,health,metricsJson,success,success,error,success,success,error);}
    public void insertMetric(String type,Long id,String code,Number value,String text,String labelsJson,OffsetDateTime collectedAt){jdbc.update("INSERT INTO mon_metric_sample(object_type,object_id,metric_code,metric_value,metric_text,labels,collected_at) VALUES(?,?,?,?,?,CAST(? AS jsonb),?)",type,id,code,value,text,labelsJson,collectedAt);}

    private static final String OBJECT_NAMES="""
      WITH names AS (
        SELECT 'CENTOS' object_type,id object_id,resource_code object_code,COALESCE(resource_name,resource_code) object_name FROM res_centos WHERE deleted=FALSE
        UNION ALL SELECT 'ROS',id,resource_code,COALESCE(resource_name,resource_code) FROM res_ros WHERE deleted=FALSE
        UNION ALL SELECT 'LINE',id,resource_code,COALESCE(resource_name,resource_code) FROM res_line WHERE deleted=FALSE
        UNION ALL SELECT 'IP',id,host(ip_address),host(ip_address) FROM res_ip WHERE deleted=FALSE
        UNION ALL SELECT 'POOL',id,pool_code,pool_name FROM res_pool WHERE deleted=FALSE
        UNION ALL SELECT 'SUPPLIER',id,supplier_code,supplier_name FROM res_supplier WHERE deleted=FALSE
        UNION ALL SELECT 'SERVICE',id,service_no,service_no FROM svc_instance WHERE deleted=FALSE
      )
    """;
    public long monitorCount(String type,String keyword){String k="%"+(keyword==null?"":keyword.trim())+"%";return jdbc.queryForObject(OBJECT_NAMES+" SELECT COUNT(*) FROM mon_object_status m LEFT JOIN names n ON n.object_type=m.object_type AND n.object_id=m.object_id WHERE (?='' OR m.object_type=?) AND (?='%%' OR COALESCE(n.object_name,'') ILIKE ? OR COALESCE(n.object_code,'') ILIKE ?)",Long.class,type==null?"":type,type==null?"":type,k,k,k);}
    public List<Map<String,Object>> monitorRows(String type,String keyword,int limit,int offset){String k="%"+(keyword==null?"":keyword.trim())+"%";return jdbc.queryForList(OBJECT_NAMES+" SELECT m.*,n.object_code,n.object_name FROM mon_object_status m LEFT JOIN names n ON n.object_type=m.object_type AND n.object_id=m.object_id WHERE (?='' OR m.object_type=?) AND (?='%%' OR COALESCE(n.object_name,'') ILIKE ? OR COALESCE(n.object_code,'') ILIKE ?) ORDER BY CASE m.status WHEN 'OFFLINE' THEN 1 WHEN 'ABNORMAL' THEN 2 WHEN 'UNKNOWN' THEN 3 ELSE 4 END,m.last_collected_at DESC,m.object_id LIMIT ? OFFSET ?",type==null?"":type,type==null?"":type,k,k,k,limit,offset);}
    public List<Map<String,Object>> metricHistory(String type,Long id,String code,OffsetDateTime from){return jdbc.queryForList("SELECT metric_code,metric_value,metric_text,labels,collected_at FROM mon_metric_sample WHERE object_type=? AND object_id=? AND (?='' OR metric_code=?) AND collected_at>=? ORDER BY collected_at",type,id,code==null?"":code,code==null?"":code,from);}
    public List<Map<String,Object>> recentMetricSamples(String type,Long id,String code,int limit){return jdbc.queryForList("SELECT metric_value,metric_text,collected_at FROM mon_metric_sample WHERE object_type=? AND object_id=? AND metric_code=? ORDER BY collected_at DESC LIMIT ?",type,id,code,limit);}
    public List<Map<String,Object>> activeRules(){return jdbc.queryForList("SELECT id,rule_code,rule_name,object_type,metric_code,operator,threshold::text threshold_json,duration_seconds,consecutive_count,severity,notification_channels::text notification_channels_json,notify_recovery,repeat_interval_seconds,status FROM alarm_rule WHERE deleted=FALSE AND status='ACTIVE' ORDER BY id");}

    public Map<String,Object> activeAlarm(Long ruleId,String type,Long objectId,String metricCode){return one("SELECT * FROM alarm_event WHERE rule_id=? AND object_type=? AND object_id=? AND COALESCE(metric_code,'')=? AND status IN ('OPEN','ACKNOWLEDGED','PROCESSING') ORDER BY id DESC LIMIT 1",ruleId,type,objectId,metricCode==null?"":metricCode);}
    public Long insertAlarm(Long ruleId,String no,String type,Long objectId,String objectName,String severity,String metricCode,String thresholdJson,String currentJson){return jdbc.queryForObject("INSERT INTO alarm_event(alarm_no,rule_id,object_type,object_id,object_name,severity,metric_code,threshold,current_value,status,first_triggered_at,last_triggered_at) VALUES(?,?,?,?,?,?,?,CAST(? AS jsonb),CAST(? AS jsonb),'OPEN',now(),now()) RETURNING id",Long.class,no,ruleId,type,objectId,objectName,severity,metricCode,thresholdJson,currentJson);}
    public void touchAlarm(Long id,String currentJson){jdbc.update("UPDATE alarm_event SET current_value=CAST(? AS jsonb),last_triggered_at=now(),occurrence_count=occurrence_count+1,updated_at=now(),version=version+1 WHERE id=?",currentJson,id);}
    public void recoverAlarm(Long id,String recoveryJson){jdbc.update("UPDATE alarm_event SET status='RECOVERED',recovery_value=CAST(? AS jsonb),recovered_at=now(),updated_at=now(),version=version+1 WHERE id=? AND status IN ('OPEN','ACKNOWLEDGED','PROCESSING')",recoveryJson,id);}
    public void addAlarmProcess(Long alarmId,String action,String before,String after,Long userId,String remark){jdbc.update("INSERT INTO alarm_process_record(alarm_id,action,before_status,after_status,operator_id,remark) VALUES(?,?,?,?,?,?)",alarmId,action,before,after,userId,remark);}
    public OffsetDateTime lastNotificationAt(Long alarmId,String channel){return jdbc.query("SELECT MAX(created_at) FROM alarm_notification WHERE alarm_id=? AND channel=?",rs->{if(!rs.next())return null;return rs.getObject(1,OffsetDateTime.class);},alarmId,channel);}
    public Long insertNotification(Long alarmId,String channel,String target,String message,String result,String error){return jdbc.queryForObject("INSERT INTO alarm_notification(alarm_id,channel,target,message_snapshot,result,sent_at,error_message) VALUES(?,?,?,?,?,CASE WHEN ?='SUCCESS' THEN now() END,?) RETURNING id",Long.class,alarmId,channel,target,message,result,result,error);}

    public long alarmCount(String status,String severity,String keyword){String k="%"+(keyword==null?"":keyword.trim())+"%";return jdbc.queryForObject("SELECT COUNT(*) FROM alarm_event WHERE (?='' OR status=?) AND (?='' OR severity=?) AND (?='%%' OR alarm_no ILIKE ? OR COALESCE(object_name,'') ILIKE ? OR COALESCE(metric_code,'') ILIKE ?)",Long.class,n(status),n(status),n(severity),n(severity),k,k,k,k);}
    public List<Map<String,Object>> alarms(String status,String severity,String keyword,int limit,int offset){String k="%"+(keyword==null?"":keyword.trim())+"%";return jdbc.queryForList("SELECT e.*,r.rule_code,r.rule_name FROM alarm_event e LEFT JOIN alarm_rule r ON r.id=e.rule_id WHERE (?='' OR e.status=?) AND (?='' OR e.severity=?) AND (?='%%' OR e.alarm_no ILIKE ? OR COALESCE(e.object_name,'') ILIKE ? OR COALESCE(e.metric_code,'') ILIKE ?) ORDER BY CASE e.status WHEN 'OPEN' THEN 1 WHEN 'ACKNOWLEDGED' THEN 2 WHEN 'PROCESSING' THEN 3 WHEN 'RECOVERED' THEN 4 ELSE 5 END,e.last_triggered_at DESC LIMIT ? OFFSET ?",n(status),n(status),n(severity),n(severity),k,k,k,k,limit,offset);}
    public Map<String,Object> alarm(Long id){return one("SELECT e.*,r.rule_code,r.rule_name,r.notification_channels::text notification_channels_json,r.notify_recovery FROM alarm_event e LEFT JOIN alarm_rule r ON r.id=e.rule_id WHERE e.id=?",id);}
    public List<Map<String,Object>> alarmProcesses(Long id){return jdbc.queryForList("SELECT p.*,u.display_name operator_name FROM alarm_process_record p LEFT JOIN sys_user u ON u.id=p.operator_id WHERE p.alarm_id=? ORDER BY p.occurred_at",id);}
    public List<Map<String,Object>> alarmNotifications(Long id){return jdbc.queryForList("SELECT * FROM alarm_notification WHERE alarm_id=? ORDER BY created_at",id);}
    public int changeAlarmStatus(Long id,String fromCsv,String to,Long userId){String[] allowed=fromCsv.split(",");String marks=String.join(",",Collections.nCopies(allowed.length,"?"));List<Object> args=new ArrayList<>();args.add(to);args.add(userId);args.add(userId);args.add(id);args.addAll(Arrays.asList(allowed));return jdbc.update("UPDATE alarm_event SET status=?,acknowledged_by=CASE WHEN ? IS NOT NULL AND acknowledged_by IS NULL THEN ? ELSE acknowledged_by END,acknowledged_at=CASE WHEN acknowledged_at IS NULL AND ? IS NOT NULL THEN now() ELSE acknowledged_at END,handler_id=CASE WHEN ?='PROCESSING' THEN ? ELSE handler_id END,closed_at=CASE WHEN ?='CLOSED' THEN now() ELSE closed_at END,updated_at=now(),version=version+1 WHERE id=? AND status IN ("+marks+")",buildStatusArgs(to,userId,id,allowed));}
    private Object[] buildStatusArgs(String to,Long userId,Long id,String[] allowed){List<Object> a=new ArrayList<>();a.add(to);a.add(userId);a.add(userId);a.add(userId);a.add(to);a.add(userId);a.add(to);a.add(id);a.addAll(Arrays.asList(allowed));return a.toArray();}

    public long ruleCount(String keyword){String k="%"+(keyword==null?"":keyword.trim())+"%";return jdbc.queryForObject("SELECT COUNT(*) FROM alarm_rule WHERE deleted=FALSE AND (?='%%' OR rule_code ILIKE ? OR rule_name ILIKE ? OR metric_code ILIKE ?)",Long.class,k,k,k,k);}
    public List<Map<String,Object>> rules(String keyword,int limit,int offset){String k="%"+(keyword==null?"":keyword.trim())+"%";return jdbc.queryForList("SELECT id,rule_code,rule_name,object_type,metric_code,operator,threshold::text threshold_json,duration_seconds,consecutive_count,severity,notification_channels::text notification_channels_json,notify_recovery,repeat_interval_seconds,status,created_at,updated_at FROM alarm_rule WHERE deleted=FALSE AND (?='%%' OR rule_code ILIKE ? OR rule_name ILIKE ? OR metric_code ILIKE ?) ORDER BY status DESC,id DESC LIMIT ? OFFSET ?",k,k,k,k,limit,offset);}
    public Map<String,Object> rule(Long id){return one("SELECT id,rule_code,rule_name,object_type,metric_code,operator,threshold::text threshold_json,duration_seconds,consecutive_count,severity,notification_channels::text notification_channels_json,notify_recovery,repeat_interval_seconds,status FROM alarm_rule WHERE id=? AND deleted=FALSE",id);}
    public Long createRule(String code,String name,String type,String metric,String op,String thresholdJson,int duration,int consecutive,String severity,String channelsJson,boolean notifyRecovery,Integer repeat,Long userId){return jdbc.queryForObject("INSERT INTO alarm_rule(rule_code,rule_name,object_type,metric_code,operator,threshold,duration_seconds,consecutive_count,severity,notification_channels,notify_recovery,repeat_interval_seconds,status,created_by,updated_by) VALUES(?,?,?,?,?,CAST(? AS jsonb),?,?,?,?,CAST(? AS jsonb),?,?,'ACTIVE',?,?) RETURNING id",Long.class,code,name,type,metric,op,thresholdJson,duration,consecutive,severity,channelsJson,notifyRecovery,repeat,userId,userId);}
    public int updateRule(Long id,String name,String type,String metric,String op,String thresholdJson,int duration,int consecutive,String severity,String channelsJson,boolean notifyRecovery,Integer repeat,Long userId){return jdbc.update("UPDATE alarm_rule SET rule_name=?,object_type=?,metric_code=?,operator=?,threshold=CAST(? AS jsonb),duration_seconds=?,consecutive_count=?,severity=?,notification_channels=CAST(? AS jsonb),notify_recovery=?,repeat_interval_seconds=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",name,type,metric,op,thresholdJson,duration,consecutive,severity,channelsJson,notifyRecovery,repeat,userId,id);}
    public int setRuleStatus(Long id,String status,Long userId){return jdbc.update("UPDATE alarm_rule SET status=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",status,userId,id);}
    public int softDeleteRule(Long id,Long userId){return jdbc.update("UPDATE alarm_rule SET deleted=TRUE,status='DISABLED',updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",userId,id);}
    public long notificationCount(String channel,String result){return jdbc.queryForObject("SELECT COUNT(*) FROM alarm_notification WHERE (?='' OR channel=?) AND (?='' OR result=?)",Long.class,n(channel),n(channel),n(result),n(result));}
    public List<Map<String,Object>> notifications(String channel,String result,int limit,int offset){return jdbc.queryForList("SELECT n.*,e.alarm_no,e.object_name,e.severity FROM alarm_notification n JOIN alarm_event e ON e.id=n.alarm_id WHERE (?='' OR n.channel=?) AND (?='' OR n.result=?) ORDER BY n.created_at DESC LIMIT ? OFFSET ?",n(channel),n(channel),n(result),n(result),limit,offset);}

    public Long startStatRun(OffsetDateTime hour,String trigger,Long userId){return jdbc.queryForObject("INSERT INTO stat_calculation_run(stat_hour,trigger_type,status,created_by) VALUES(? ,?,'RUNNING',?) RETURNING id",Long.class,hour,trigger,userId);}
    public void finishStatRun(Long id,String status,int r,int ip,int cu,int ps,int su,String error){jdbc.update("UPDATE stat_calculation_run SET status=?,resource_rows=?,ip_rows=?,customer_usage_rows=?,product_service_rows=?,supplier_rows=?,error_message=?,finished_at=now() WHERE id=?",status,r,ip,cu,ps,su,error,id);}
    public Map<String,Object> lastStatRun(){return one("SELECT * FROM stat_calculation_run ORDER BY started_at DESC LIMIT 1");}

    public int calculateResource(OffsetDateTime h,OffsetDateTime end){jdbc.update("DELETE FROM stat_resource_hourly WHERE stat_hour=?",h);return jdbc.update("INSERT INTO stat_resource_hourly(stat_hour,region_code,carrier_code,centos_total,centos_online,ros_total,ros_online,line_total,line_online,line_abnormal) SELECT ?,'','',(SELECT COUNT(*) FROM res_centos WHERE deleted=FALSE),(SELECT COUNT(*) FROM res_centos WHERE deleted=FALSE AND online_status='ONLINE'),(SELECT COUNT(*) FROM res_ros WHERE deleted=FALSE),(SELECT COUNT(*) FROM res_ros WHERE deleted=FALSE AND online_status='ONLINE'),(SELECT COUNT(*) FROM res_line WHERE deleted=FALSE),(SELECT COUNT(*) FROM res_line WHERE deleted=FALSE AND online_status='ONLINE'),(SELECT COUNT(*) FROM res_line WHERE deleted=FALSE AND online_status='ABNORMAL')",h);}
    public int calculateIp(OffsetDateTime h,OffsetDateTime end){jdbc.update("DELETE FROM stat_ip_hourly WHERE stat_hour=?",h);return jdbc.update("INSERT INTO stat_ip_hourly(stat_hour,pool_id,region_code,carrier_code,source_type,ip_total,ip_unique,ip_available,ip_unavailable,duplicate_count) SELECT ?,0,'','','',COUNT(*),COUNT(DISTINCT ip_address),COUNT(*) FILTER(WHERE available_status='AVAILABLE'),COUNT(*) FILTER(WHERE available_status='UNAVAILABLE'),COUNT(*) FILTER(WHERE duplicate_flag=TRUE) FROM res_ip WHERE deleted=FALSE",h);}
    public int calculateCustomerUsage(OffsetDateTime h,OffsetDateTime end){jdbc.update("DELETE FROM stat_customer_usage_hourly WHERE stat_hour=?",h);return jdbc.update("INSERT INTO stat_customer_usage_hourly(stat_hour,customer_id,service_id,product_id,extract_count,returned_ip_count,unique_outbound_ip_count,request_count,success_count,failure_count,upload_bytes,download_bytes) SELECT ?,s.customer_id,s.id,s.product_id,COALESCE((SELECT SUM(e.requested_count) FROM log_ip_extract e WHERE e.service_id=s.id AND e.occurred_at>=? AND e.occurred_at<?),0),COALESCE((SELECT SUM(e.returned_count) FROM log_ip_extract e WHERE e.service_id=s.id AND e.occurred_at>=? AND e.occurred_at<?),0),COALESCE((SELECT COUNT(DISTINCT u.outbound_ip) FROM log_usage u WHERE u.service_id=s.id AND u.occurred_at>=? AND u.occurred_at<?),0),COALESCE((SELECT COUNT(*) FROM log_usage u WHERE u.service_id=s.id AND u.occurred_at>=? AND u.occurred_at<?),0),COALESCE((SELECT COUNT(*) FROM log_usage u WHERE u.service_id=s.id AND u.result='SUCCESS' AND u.occurred_at>=? AND u.occurred_at<?),0),COALESCE((SELECT COUNT(*) FROM log_usage u WHERE u.service_id=s.id AND u.result='FAILURE' AND u.occurred_at>=? AND u.occurred_at<?),0),COALESCE((SELECT SUM(u.upload_bytes) FROM log_usage u WHERE u.service_id=s.id AND u.occurred_at>=? AND u.occurred_at<?),0),COALESCE((SELECT SUM(u.download_bytes) FROM log_usage u WHERE u.service_id=s.id AND u.occurred_at>=? AND u.occurred_at<?),0) FROM svc_instance s WHERE s.deleted=FALSE AND (EXISTS(SELECT 1 FROM log_ip_extract e WHERE e.service_id=s.id AND e.occurred_at>=? AND e.occurred_at<?) OR EXISTS(SELECT 1 FROM log_usage u WHERE u.service_id=s.id AND u.occurred_at>=? AND u.occurred_at<?))",h,h,end,h,end,h,end,h,end,h,end,h,end,h,end,h,end,h,end,h,end);}
    public int calculateProductService(OffsetDateTime h,OffsetDateTime end){jdbc.update("DELETE FROM stat_product_service_hourly WHERE stat_hour=?",h);return jdbc.update("INSERT INTO stat_product_service_hourly(stat_hour,product_id,package_id,active_customer_count,active_service_count,extract_count,request_count,success_count,unique_outbound_ip_count) SELECT ?,p.id,COALESCE(s.package_id,0),COUNT(DISTINCT s.customer_id) FILTER(WHERE s.status='ACTIVE'),COUNT(*) FILTER(WHERE s.status='ACTIVE'),COALESCE(SUM((SELECT COALESCE(SUM(e.requested_count),0) FROM log_ip_extract e WHERE e.service_id=s.id AND e.occurred_at>=? AND e.occurred_at<?)),0),COALESCE(SUM((SELECT COUNT(*) FROM log_usage u WHERE u.service_id=s.id AND u.occurred_at>=? AND u.occurred_at<?)),0),COALESCE(SUM((SELECT COUNT(*) FROM log_usage u WHERE u.service_id=s.id AND u.result='SUCCESS' AND u.occurred_at>=? AND u.occurred_at<?)),0),COALESCE(SUM((SELECT COUNT(DISTINCT u.outbound_ip) FROM log_usage u WHERE u.service_id=s.id AND u.occurred_at>=? AND u.occurred_at<?)),0) FROM prd_product p JOIN svc_instance s ON s.product_id=p.id AND s.deleted=FALSE WHERE p.deleted=FALSE GROUP BY p.id,COALESCE(s.package_id,0)",h,h,end,h,end,h,end,h,end);}
    public int calculateSupplier(OffsetDateTime h,OffsetDateTime end){jdbc.update("DELETE FROM stat_supplier_hourly WHERE stat_hour=?",h);return jdbc.update("INSERT INTO stat_supplier_hourly(stat_hour,supplier_id,fetch_count,success_count,failure_count,received_resource_count,unique_ip_count,available_ip_count,imported_ip_count,avg_elapsed_ms) SELECT ?,s.id,COUNT(f.id),COUNT(f.id) FILTER(WHERE f.result='SUCCESS'),COUNT(f.id) FILTER(WHERE f.result='FAILURE'),COALESCE(SUM(f.received_count),0),(SELECT COUNT(DISTINCT i.ip_address) FROM res_ip i WHERE i.supplier_id=s.id AND i.deleted=FALSE),(SELECT COUNT(*) FROM res_ip i WHERE i.supplier_id=s.id AND i.deleted=FALSE AND i.available_status='AVAILABLE'),COALESCE(SUM(f.imported_count),0),AVG(f.elapsed_ms) FROM res_supplier s LEFT JOIN log_external_fetch f ON f.supplier_id=s.id AND f.occurred_at>=? AND f.occurred_at<? WHERE s.deleted=FALSE GROUP BY s.id",h,h,end);}

    public List<Map<String,Object>> resourceStats(OffsetDateTime from,OffsetDateTime to){return jdbc.queryForList("SELECT * FROM stat_resource_hourly WHERE stat_hour>=? AND stat_hour<? AND region_code='' AND carrier_code='' ORDER BY stat_hour",from,to);}
    public List<Map<String,Object>> ipStats(OffsetDateTime from,OffsetDateTime to){return jdbc.queryForList("SELECT * FROM stat_ip_hourly WHERE stat_hour>=? AND stat_hour<? AND pool_id=0 AND region_code='' AND carrier_code='' AND source_type='' ORDER BY stat_hour",from,to);}
    public List<Map<String,Object>> customerStats(OffsetDateTime from,OffsetDateTime to){return jdbc.queryForList("SELECT s.*,c.customer_name,svc.service_no,p.product_name FROM stat_customer_usage_hourly s JOIN customer c ON c.id=s.customer_id JOIN svc_instance svc ON svc.id=s.service_id JOIN prd_product p ON p.id=s.product_id WHERE s.stat_hour>=? AND s.stat_hour<? ORDER BY s.stat_hour DESC,s.extract_count DESC",from,to);}
    public List<Map<String,Object>> productStats(OffsetDateTime from,OffsetDateTime to){return jdbc.queryForList("SELECT s.*,p.product_name,COALESCE(pkg.package_name,'无套餐') package_name FROM stat_product_service_hourly s JOIN prd_product p ON p.id=s.product_id LEFT JOIN prd_package pkg ON pkg.id=NULLIF(s.package_id,0) WHERE s.stat_hour>=? AND s.stat_hour<? ORDER BY s.stat_hour DESC,s.active_service_count DESC",from,to);}
    public List<Map<String,Object>> supplierStats(OffsetDateTime from,OffsetDateTime to){return jdbc.queryForList("SELECT s.*,r.supplier_name FROM stat_supplier_hourly s JOIN res_supplier r ON r.id=s.supplier_id WHERE s.stat_hour>=? AND s.stat_hour<? ORDER BY s.stat_hour DESC,s.fetch_count DESC",from,to);}
    public Map<String,Object> dashboard(){return one("SELECT (SELECT COUNT(*) FROM customer WHERE deleted=FALSE AND status='ACTIVE') active_customers,(SELECT COUNT(*) FROM svc_instance WHERE deleted=FALSE AND status='ACTIVE') active_services,(SELECT COUNT(*) FROM svc_instance WHERE deleted=FALSE AND status IN ('ACTIVE','SUSPENDED') AND expire_at BETWEEN now() AND now()+interval '3 days') expiring_services_3d,(SELECT COALESCE(SUM(returned_count),0) FROM log_ip_extract WHERE occurred_at>=date_trunc('day',now())) today_returned_ips,(SELECT COUNT(DISTINCT host(ip_address)) FROM res_ip WHERE deleted=FALSE AND available_status='AVAILABLE') available_unique_ips,(SELECT COUNT(*) FROM alarm_event WHERE status IN ('OPEN','ACKNOWLEDGED','PROCESSING')) active_alarms,(SELECT COUNT(*) FROM mon_object_status WHERE object_type='CENTOS' AND status IN ('ONLINE','NORMAL')) online_centos,(SELECT COUNT(*) FROM mon_object_status WHERE object_type='ROS' AND status IN ('ONLINE','NORMAL')) online_ros,(SELECT COUNT(*) FROM mon_object_status WHERE object_type='LINE' AND status IN ('ONLINE','NORMAL')) online_lines");}

    private String n(String v){return v==null?"":v.trim();}
}
