package com.ipproxy.platform.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.ipproxy.platform.common.api.PageResult;
import com.ipproxy.platform.common.exception.BusinessException;
import com.ipproxy.platform.security.UserPrincipal;
import com.ipproxy.platform.service.adapter.ServiceProvisionAdapter;
import com.ipproxy.platform.service.mapper.OrderServiceMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.*;

@Service
public class OrderServiceService {
    private final OrderServiceMapper db; private final ObjectMapper json; private final ServiceProvisionAdapter adapter;
    public OrderServiceService(OrderServiceMapper db,ObjectMapper json,ServiceProvisionAdapter adapter){this.db=db;this.json=json;this.adapter=adapter;}
    public record OrderItemInput(Long productId,Long packageId,Integer quantity,Integer serviceCount,BigDecimal unitPrice,String remark){}
    public record OrderInput(Long customerId,String orderType,String currency,OffsetDateTime expectedEffectiveAt,OffsetDateTime expectedExpireAt,Long ownerUserId,String remark,List<OrderItemInput> items){}
    public record ManualProvisionInput(Long customerId,Long productId,Long packageId,Long strategyId,OffsetDateTime effectiveAt,OffsetDateTime expireAt,String remark){}

    public PageResult<Map<String,Object>> orders(int page,int size,String keyword,String status,Long customerId){page=Math.max(1,page);size=Math.min(200,Math.max(1,size));keyword=n(keyword);status=n(status);return new PageResult<>(page,size,db.countOrders(keyword,status,customerId),db.orders(keyword,status,customerId,size,(page-1)*size));}
    public Map<String,Object> order(Long id){Map<String,Object> x=mustOrder(id);x.put("items",db.orderItems(id));return x;}
    @Transactional public Long createOrder(OrderInput in,UserPrincipal actor,String ip){Map<String,Object> c=mustCustomer(in.customerId());if(!"ACTIVE".equals(s(c.get("status"))))throw err("CUSTOMER_NOT_ACTIVE","仅正常客户可创建订单");if(in.items()==null||in.items().isEmpty())throw err("ORDER_ITEMS_REQUIRED","订单至少包含一个订单项");String type=Set.of("NEW","RENEW","EXPAND","CHANGE").contains(n(in.orderType()))?in.orderType():"NEW";String currency=n(in.currency()).isBlank()?"CNY":in.currency().trim().toUpperCase();BigDecimal total=BigDecimal.ZERO;List<Map<String,Object>> prepared=new ArrayList<>();int line=1;for(OrderItemInput item:in.items()){Map<String,Object> p=mustActiveProduct(item.productId());Map<String,Object> k=item.packageId()==null?null:mustActivePackage(item.packageId(),item.productId());int qty=item.quantity()==null?1:Math.max(1,item.quantity());int sc=item.serviceCount()==null?1:Math.max(1,item.serviceCount());BigDecimal unit=item.unitPrice()!=null?item.unitPrice():(k==null?BigDecimal.ZERO:new BigDecimal(s(k.get("price"))));BigDecimal amount=unit.multiply(BigDecimal.valueOf(qty));total=total.add(amount);prepared.add(new LinkedHashMap<>(Map.of("line",line++,"product",p,"package",k==null?Map.of():k,"qty",qty,"sc",sc,"unit",unit,"amount",amount,"remark",n(item.remark()))));}
        String no=db.nextOrderNo();Long id=db.insertOrder(no,in.customerId(),type,total,currency,in.expectedEffectiveAt(),in.expectedExpireAt(),in.ownerUserId(),n(in.remark()),actor.userId());for(Map<String,Object> a:prepared){Map<String,Object> p=(Map<String,Object>)a.get("product");Map<String,Object> k=(Map<String,Object>)a.get("package");db.insertItem(id,(Integer)a.get("line"),longv(p.get("id")),k.isEmpty()?null:longv(k.get("id")),(Integer)a.get("qty"),(BigDecimal)a.get("unit"),(BigDecimal)a.get("amount"),s(p.get("product_json")),k.isEmpty()?null:s(k.get("package_json")),(Integer)a.get("sc"),s(a.get("remark")));}audit(actor,"ORDER",id,"CREATE","新增订单",ip);return id;}
    @Transactional public void confirmOrder(Long id,String reason,UserPrincipal actor,String ip){Map<String,Object> o=mustOrder(id);if(!Set.of("PENDING_CONFIRM","DRAFT").contains(s(o.get("status"))))throw err("ORDER_STATUS_INVALID","当前订单状态不能确认");db.orderStatus(id,"PENDING_PROVISION",actor.userId());audit(actor,"ORDER",id,"CONFIRM",required(reason),ip);}
    @Transactional public void cancelOrder(Long id,String reason,UserPrincipal actor,String ip){Map<String,Object> o=mustOrder(id);if(Set.of("PROVISIONED","COMPLETED","CANCELLED").contains(s(o.get("status"))))throw err("ORDER_STATUS_INVALID","当前订单状态不能取消");db.cancelOrder(id,required(reason),actor.userId());audit(actor,"ORDER",id,"CANCEL",reason,ip);}

    @Transactional public Map<String,Object> provisionOrder(Long id,String reason,UserPrincipal actor,String ip){Map<String,Object> o=mustOrder(id);if(!"PENDING_PROVISION".equals(s(o.get("status"))))throw err("ORDER_STATUS_INVALID","订单必须处于待开通状态");List<Map<String,Object>> issued=new ArrayList<>();for(Map<String,Object> item:db.orderItems(id)){int n=((Number)item.get("service_count")).intValue();for(int i=0;i<n;i++)issued.add(provisionOne(longv(o.get("customer_id")),id,longv(item.get("id")),longv(item.get("product_id")),item.get("package_id")==null?null:longv(item.get("package_id")),null,(OffsetDateTime)o.get("expected_effective_at"),(OffsetDateTime)o.get("expected_expire_at"),actor,ip));}db.orderStatus(id,"PROVISIONED",actor.userId());audit(actor,"ORDER",id,"PROVISION",required(reason),ip);return Map.of("orderId",id,"services",issued);}
    @Transactional public Map<String,Object> manualProvision(ManualProvisionInput in,UserPrincipal actor,String ip){mustCustomer(in.customerId());return provisionOne(in.customerId(),null,null,in.productId(),in.packageId(),in.strategyId(),in.effectiveAt(),in.expireAt(),actor,ip);}

    private Map<String,Object> provisionOne(Long customerId,Long orderId,Long itemId,Long productId,Long packageId,Long requestedStrategy,OffsetDateTime effective,OffsetDateTime expire,UserPrincipal actor,String ip){Map<String,Object> p=mustActiveProduct(productId);Map<String,Object> k=packageId==null?null:mustActivePackage(packageId,productId);Map<String,Object> st=requestedStrategy==null?db.activeStrategy(productId):null;if(requestedStrategy!=null){Map<String,Object> candidate=db.activeStrategy(productId);if(candidate!=null&&Objects.equals(longv(candidate.get("id")),requestedStrategy))st=candidate;}if(st==null)throw err("SERVICE_STRATEGY_REQUIRED","产品没有可用的已启用资源策略");Map<String,Object> pool=db.primaryPool(longv(st.get("id")));if(pool==null||((Number)pool.get("member_count")).longValue()<=0)throw err("SERVICE_RESOURCE_UNAVAILABLE","资源策略没有可用资源池");OffsetDateTime eff=effective==null?OffsetDateTime.now(ZoneOffset.UTC):effective;OffsetDateTime exp=expire;if(exp==null&&k!=null)exp=eff.plusDays(((Number)k.get("service_days")).longValue());String serviceNo=db.nextServiceNo();String quota=k==null?"{}":j(Map.of("packageId",k.get("id"),"packageCode",k.get("package_code"),"serviceDays",k.get("service_days")));Long sid=db.insertService(serviceNo,customerId,orderId,itemId,productId,packageId,longv(st.get("id")),s(p.get("product_type")),s(p.get("product_json")),k==null?null:s(k.get("package_json")),s(st.get("strategy_json")),quota,eff,exp,actor.userId());db.bind(sid,"POOL",longv(pool.get("id")),"PRIMARY",j(Map.of("poolCode",pool.get("pool_code"))),actor.userId());if("EXCLUSIVE_IP".equals(s(p.get("product_type")))){Map<String,Object> ipr=db.freeExclusiveIp(longv(pool.get("id")));if(ipr==null)throw err("EXCLUSIVE_RESOURCE_UNAVAILABLE","当前资源池没有可分配的独享IP");db.allocateExclusive(sid,"IP",longv(ipr.get("id")),customerId,exp,j(ipr),actor.userId());db.bind(sid,"IP",longv(ipr.get("id")),"OUTBOUND",j(ipr),actor.userId());}if("TUNNEL".equals(s(p.get("product_type")))){Long domain=db.tunnelDomain(productId);if(domain!=null)db.bind(sid,"DOMAIN",domain,"ENTRY","{}",actor.userId());}
        Map<String,Object> cred=issueCredential(sid,serviceNo,s(p.get("product_type")),exp,actor.userId());Map<String,Object> ctx=new LinkedHashMap<>();ctx.put("poolId",pool.get("id"));ctx.put("serviceNo",serviceNo);ctx.put("customerId",customerId);ServiceProvisionAdapter.Result result=adapter.provision(s(p.get("product_type")),sid,ctx);if(!result.success()){db.serviceStatus(sid,"PROVISION_FAILED",result.message(),actor.userId());audit(actor,"SERVICE",sid,"PROVISION_FAILED",result.message(),ip);return Map.of("serviceId",sid,"serviceNo",serviceNo,"status","PROVISION_FAILED","message",result.message());}db.serviceStatus(sid,"ACTIVE",null,actor.userId());audit(actor,"SERVICE",sid,"PROVISION","服务开通成功",ip);Map<String,Object> out=new LinkedHashMap<>();out.put("serviceId",sid);out.put("serviceNo",serviceNo);out.put("status","ACTIVE");out.put("oneTimeCredential",cred);return out;}

    public PageResult<Map<String,Object>> services(int page,int size,String keyword,String status,Long customerId,String productType){page=Math.max(1,page);size=Math.min(200,Math.max(1,size));keyword=n(keyword);status=n(status);productType=n(productType);return new PageResult<>(page,size,db.countServices(keyword,status,customerId,productType),db.services(keyword,status,customerId,productType,size,(page-1)*size));}
    public Map<String,Object> service(Long id){Map<String,Object>x=mustService(id);x.put("resourceBindings",db.bindings(id));x.put("whitelist",db.whitelist(id));x.put("changes",db.changes(id));return x;}
    public List<Map<String,Object>> credentials(Long id){mustService(id);return db.credentials(id);}
    @Transactional public void suspend(Long id,String reason,UserPrincipal actor,String ip){Map<String,Object>s=mustService(id);if(!"ACTIVE".equals(s(s.get("status"))))throw err("SERVICE_STATUS_INVALID","仅正常服务可暂停");db.freezeCredentials(id);db.serviceStatus(id,"SUSPENDED",null,actor.userId());db.insertChange(db.nextChangeNo(),id,"SUSPEND",j(s),j(Map.of("status","SUSPENDED")),required(reason),"SUCCESS",actor.userId());audit(actor,"SERVICE",id,"SUSPEND",reason,ip);}
    @Transactional public void resume(Long id,String reason,UserPrincipal actor,String ip){Map<String,Object>s=mustService(id);if(!"SUSPENDED".equals(s(s.get("status"))))throw err("SERVICE_STATUS_INVALID","仅暂停服务可恢复");db.activateCredentials(id);db.serviceStatus(id,"ACTIVE",null,actor.userId());db.insertChange(db.nextChangeNo(),id,"RESUME",j(s),j(Map.of("status","ACTIVE")),required(reason),"SUCCESS",actor.userId());audit(actor,"SERVICE",id,"RESUME",reason,ip);}
    @Transactional public OffsetDateTime renew(Long id,int days,String reason,UserPrincipal actor,String ip){if(days<=0)throw err("RENEW_DAYS_INVALID","续费天数必须大于0");Map<String,Object>s=mustService(id);if(Set.of("TERMINATED","PROVISION_FAILED").contains(s(s.get("status"))))throw err("SERVICE_STATUS_INVALID","当前服务不能续费");OffsetDateTime old=(OffsetDateTime)s.get("expire_at");OffsetDateTime base=old==null||old.isBefore(OffsetDateTime.now(ZoneOffset.UTC))?OffsetDateTime.now(ZoneOffset.UTC):old;OffsetDateTime exp=base.plusDays(days);db.renew(id,exp,actor.userId());db.insertChange(db.nextChangeNo(),id,"RENEW",j(Map.of("expireAt",old==null?"":old.toString())),j(Map.of("expireAt",exp.toString(),"days",days)),required(reason),"SUCCESS",actor.userId());audit(actor,"SERVICE",id,"RENEW",reason,ip);return exp;}
    @Transactional public Map<String,Object> terminate(Long id,String reason,UserPrincipal actor,String ip){Map<String,Object>s=mustService(id);if("TERMINATED".equals(s(s.get("status"))))throw err("SERVICE_STATUS_INVALID","服务已终止");ServiceProvisionAdapter.Result ar=adapter.release(s(s.get("product_type")),id,Map.of("serviceNo",s.get("service_no")));if(!ar.success()){Long rid=db.insertRelease(db.nextReleaseNo(),id,"TERMINATE","FAILED","{}","{}",actor.userId(),ar.message());audit(actor,"SERVICE",id,"RELEASE_FAILED",ar.message(),ip);return Map.of("releaseId",rid,"status","FAILED","message",ar.message());}int creds=db.revokeCredentials(id),bindings=db.releaseBindings(id),exclusive=db.recycleExclusive(id);db.serviceStatus(id,"TERMINATED",null,actor.userId());Long rid=db.insertRelease(db.nextReleaseNo(),id,"TERMINATE","SUCCESS",j(Map.of("revoked",creds)),j(Map.of("bindings",bindings,"exclusivePendingRecycle",exclusive)),actor.userId(),null);db.insertChange(db.nextChangeNo(),id,"TERMINATE",j(s),j(Map.of("status","TERMINATED")),required(reason),"SUCCESS",actor.userId());audit(actor,"SERVICE",id,"TERMINATE",reason,ip);return Map.of("releaseId",rid,"status","SUCCESS");}
    @Transactional public Map<String,Object> resetCredential(Long id,String reason,UserPrincipal actor,String ip){Map<String,Object>s=mustService(id);db.revokeCurrentCredential(id);Map<String,Object> c=issueCredential(id,s(s.get("service_no")),s(s.get("product_type")),(OffsetDateTime)s.get("expire_at"),actor.userId());db.insertChange(db.nextChangeNo(),id,"CREDENTIAL_RESET","{}",j(Map.of("credentialReset",true)),required(reason),"SUCCESS",actor.userId());audit(actor,"SERVICE",id,"CREDENTIAL_RESET",reason,ip);return c;}
    @Transactional public Long addWhitelist(Long id,String address,String remark,UserPrincipal actor,String ip){Map<String,Object>s=mustService(id);if(!Set.of("ACTIVE","SUSPENDED").contains(s(s.get("status"))))throw err("SERVICE_STATUS_INVALID","当前服务不能维护白名单");try{Long wid=db.addWhitelist(id,address,n(remark),actor.userId());audit(actor,"SERVICE",id,"WHITELIST_ADD",address,ip);return wid;}catch(Exception e){throw err("WHITELIST_INVALID","IP格式无效或已存在");}}
    @Transactional public void disableWhitelist(Long id,Long wid,String reason,UserPrincipal actor,String ip){mustService(id);if(db.disableWhitelist(id,wid,actor.userId())==0)throw err("WHITELIST_NOT_FOUND","白名单记录不存在");audit(actor,"SERVICE",id,"WHITELIST_DISABLE",required(reason),ip);}
    public PageResult<Map<String,Object>> releases(int page,int size,String status){page=Math.max(1,page);size=Math.min(200,Math.max(1,size));status=n(status);return new PageResult<>(page,size,db.countReleases(status),db.releases(status,size,(page-1)*size));}

    public Map<String,Object> options(){return Map.of("customers",List.of(),"orderTypes",List.of("NEW","RENEW","EXPAND","CHANGE"),"serviceStatuses",List.of("PENDING","ACTIVE","SUSPENDED","EXPIRED","TERMINATED","PROVISION_FAILED"),"productTypes",List.of("SHORT_IP","LONG_IP","EXCLUSIVE_IP","VPN","TUNNEL"));}
    private Map<String,Object> issueCredential(Long sid,String serviceNo,String productType,OffsetDateTime expire,Long actor){String type=switch(productType){case "VPN"->"USERNAME_PASSWORD";case "TUNNEL"->"TUNNEL_ACCOUNT";default->"TOKEN";};String secret=UUID.randomUUID().toString().replace("-","")+Long.toString(System.nanoTime(),36);String account=("TOKEN".equals(type)?null:"svc_"+serviceNo.toLowerCase());String hash=sha(secret);String mask=secret.substring(0,Math.min(6,secret.length()))+"••••••"+secret.substring(Math.max(0,secret.length()-4));Long cid=db.insertCredential(sid,type,account,hash,mask,expire,j(Map.of("issuedBy","M6")),actor);Map<String,Object> out=new LinkedHashMap<>();out.put("credentialId",cid);out.put("type",type);out.put("account",account);out.put("secret",secret);out.put("mask",mask);return out;}
    private Map<String,Object> mustCustomer(Long id){Map<String,Object>x=db.customer(id);if(x==null)throw err("CUSTOMER_NOT_FOUND","客户不存在");return x;}
    private Map<String,Object> mustActiveProduct(Long id){Map<String,Object>x=db.product(id);if(x==null)throw err("PRODUCT_NOT_FOUND","产品不存在");if(!"ACTIVE".equals(s(x.get("status"))))throw err("PRODUCT_NOT_ACTIVE","仅已启用产品可下单/开通");return x;}
    private Map<String,Object> mustActivePackage(Long id,Long productId){Map<String,Object>x=db.pkg(id);if(x==null)throw err("PACKAGE_NOT_FOUND","套餐不存在");if(!Objects.equals(longv(x.get("product_id")),productId))throw err("PACKAGE_PRODUCT_MISMATCH","套餐不属于当前产品");if(!"ACTIVE".equals(s(x.get("status"))))throw err("PACKAGE_NOT_ACTIVE","仅已启用套餐可下单/开通");return x;}
    private Map<String,Object> mustOrder(Long id){Map<String,Object>x=db.order(id);if(x==null)throw err("ORDER_NOT_FOUND","订单不存在");return x;}
    private Map<String,Object> mustService(Long id){Map<String,Object>x=db.service(id);if(x==null)throw err("SERVICE_NOT_FOUND","服务不存在");return x;}
    private void audit(UserPrincipal a,String ot,Object id,String op,String reason,String ip){db.audit(a.userId(),n(a.displayName()).isBlank()?a.username():a.displayName(),ot,id,op,n(reason),n(ip));}
    private String required(String x){if(n(x).isBlank())throw err("REASON_REQUIRED","必须填写操作原因");return x.trim();}
    private String sha(String x){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(x.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private String j(Object o){try{return json.writeValueAsString(o==null?Map.of():o);}catch(Exception e){throw err("JSON_INVALID","数据无法序列化");}}
    private long longv(Object o){return o instanceof Number n?n.longValue():Long.parseLong(String.valueOf(o));}
    private String s(Object o){return o==null?"":String.valueOf(o);}
    private String n(String x){return x==null?"":x.trim();}
    private BusinessException err(String c,String m){return new BusinessException(c,m);}
}
