<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
const route=useRoute();const router=useRouter();const auth=useAuthStore()
const active=computed(()=>route.path.startsWith('/customers/')?'/customers':route.path)
function logout(){auth.logout();router.replace('/login')}
</script>
<template><el-container class="console-shell"><el-aside width="236px" class="console-aside"><div class="console-brand"><span>IP</span><div><b>IP代理管理平台</b><small>Management Console</small></div></div><el-menu :default-active="active" router class="console-menu"><el-menu-item index="/dashboard">首页工作台</el-menu-item><el-sub-menu v-if="auth.hasPermission('customer:access')" index="customer"><template #title>客户管理</template><el-menu-item v-if="auth.hasPermission('customer:read')" index="/customers">客户列表</el-menu-item><el-menu-item v-if="auth.hasPermission('customer:auth:read')" index="/customer-auth">客户认证</el-menu-item><el-menu-item v-if="auth.hasPermission('customer:account:read')" index="/customer-accounts">客户账号</el-menu-item></el-sub-menu><el-sub-menu v-if="auth.hasPermission('resource:access')" index="resource"><template #title>资源管理</template><el-menu-item v-if="auth.hasPermission('resource:read')" index="/resources">资源概览</el-menu-item><el-menu-item v-if="auth.hasPermission('resource:read')" index="/resources/centos">CentOS列表</el-menu-item><el-menu-item v-if="auth.hasPermission('resource:read')" index="/resources/ros">ROS列表</el-menu-item><el-menu-item v-if="auth.hasPermission('resource:read')" index="/resources/lines">家宽/线路列表</el-menu-item><el-menu-item v-if="auth.hasPermission('resource:read')" index="/resources/ips">IP资源列表</el-menu-item><el-menu-item v-if="auth.hasPermission('resource:pool:read')" index="/resource-pools">IP资源池</el-menu-item><el-menu-item v-if="auth.hasPermission('resource:exclusive:read')" index="/exclusive-allocations">独享资源</el-menu-item><el-menu-item v-if="auth.hasPermission('resource:domain:read')" index="/domains">域名配置</el-menu-item><el-menu-item v-if="auth.hasPermission('resource:supplier:read')" index="/suppliers">外部供应商</el-menu-item><el-menu-item v-if="auth.hasPermission('resource:sync-task:read')" index="/sync-tasks">同步任务</el-menu-item></el-sub-menu><el-menu-item index="/products">产品管理</el-menu-item><el-menu-item index="/orders">订单与服务</el-menu-item><el-menu-item index="/monitor">监控中心</el-menu-item><el-menu-item index="/logs">日志中心</el-menu-item><el-menu-item index="/alarms">告警中心</el-menu-item><el-menu-item index="/statistics">数据统计</el-menu-item><el-menu-item v-if="auth.hasPermission('system:access')" index="/system">系统管理</el-menu-item></el-menu></el-aside><el-container><el-header class="console-header"><div><span class="env-chip">M4</span><b>{{ route.meta.title }}</b></div><div class="header-user"><span>{{ auth.user?.displayName||auth.user?.username }}</span><el-button text @click="logout">退出登录</el-button></div></el-header><el-main class="console-main"><router-view/></el-main></el-container></el-container></template>
