package com.ipproxy.platform.resource.mapper;

import org.apache.ibatis.annotations.*;
import java.math.BigDecimal;
import java.util.*;

public interface ResourceMapper {
    @Select("""
      SELECT
       (SELECT count(*) FROM res_centos WHERE deleted=FALSE) centos_total,
       (SELECT count(*) FROM res_centos WHERE deleted=FALSE AND online_status='ONLINE') centos_online,
       (SELECT count(*) FROM res_ros WHERE deleted=FALSE) ros_total,
       (SELECT count(*) FROM res_ros WHERE deleted=FALSE AND online_status='ONLINE') ros_online,
       (SELECT count(*) FROM res_line WHERE deleted=FALSE) line_total,
       (SELECT count(*) FROM res_line WHERE deleted=FALSE AND online_status='ONLINE') line_online,
       (SELECT count(*) FROM res_line WHERE deleted=FALSE AND online_status='ABNORMAL') line_abnormal,
       (SELECT count(*) FROM res_ip WHERE deleted=FALSE) ip_total,
       (SELECT count(*) FROM res_ip WHERE deleted=FALSE AND available_status='AVAILABLE' AND duplicate_flag=FALSE) ip_available,
       (SELECT count(*) FROM res_ip WHERE deleted=FALSE AND source_type='EXTERNAL') external_ip_total,
       (SELECT count(*) FROM res_pool WHERE deleted=FALSE AND status='ACTIVE') active_pool_total,
       (SELECT count(*) FROM res_exclusive_allocation WHERE deleted=FALSE AND status IN ('LOCKED','ALLOCATED')) exclusive_active_total,
       (SELECT count(*) FROM res_supplier WHERE deleted=FALSE AND status='ACTIVE') active_supplier_total,
       (SELECT count(*) FROM res_sync_task WHERE status='FAILED' AND created_at>=now()-interval '24 hours') sync_failed_24h
      """) Map<String,Object> overview();

    @Select("SELECT count(*) FROM res_centos WHERE deleted=FALSE AND (#{keyword}='' OR resource_code ILIKE '%'||#{keyword}||'%' OR COALESCE(resource_name,'') ILIKE '%'||#{keyword}||'%' OR host(management_ip) ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR online_status=#{status})") long countCentos(@Param("keyword") String keyword,@Param("status") String status);
    @Select("""SELECT id,resource_code,resource_name,source_system,source_id,host(management_ip) management_ip,region_code,online_status,cpu_usage,memory_usage,disk_usage,network_in_bps,network_out_bps,last_communicated_at,last_sync_at,created_at,updated_at FROM res_centos WHERE deleted=FALSE AND (#{keyword}='' OR resource_code ILIKE '%'||#{keyword}||'%' OR COALESCE(resource_name,'') ILIKE '%'||#{keyword}||'%' OR host(management_ip) ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR online_status=#{status}) ORDER BY updated_at DESC,id DESC LIMIT #{size} OFFSET #{offset}""") List<Map<String,Object>> listCentos(@Param("keyword") String keyword,@Param("status") String status,@Param("size") int size,@Param("offset") int offset);
    @Select("SELECT id,resource_code,resource_name,source_system,source_id,host(management_ip) management_ip,region_code,online_status,cpu_usage,memory_usage,disk_usage,network_in_bps,network_out_bps,last_communicated_at,last_sync_at,created_at,updated_at FROM res_centos WHERE id=#{id} AND deleted=FALSE") Map<String,Object> getCentos(@Param("id") Long id);

    @Select("SELECT count(*) FROM res_ros r LEFT JOIN res_centos c ON c.id=r.centos_id WHERE r.deleted=FALSE AND (#{keyword}='' OR r.resource_code ILIKE '%'||#{keyword}||'%' OR COALESCE(r.resource_name,'') ILIKE '%'||#{keyword}||'%' OR COALESCE(c.resource_name,'') ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR r.online_status=#{status})") long countRos(@Param("keyword") String keyword,@Param("status") String status);
    @Select("""SELECT r.id,r.resource_code,r.resource_name,r.centos_id,c.resource_code centos_code,c.resource_name centos_name,r.source_system,r.source_id,host(r.management_ip) management_ip,r.region_code,r.carrier_code,r.online_status,r.line_total,r.line_online,r.line_abnormal,r.current_ip_count,r.last_communicated_at,r.last_sync_at,r.created_at,r.updated_at FROM res_ros r LEFT JOIN res_centos c ON c.id=r.centos_id WHERE r.deleted=FALSE AND (#{keyword}='' OR r.resource_code ILIKE '%'||#{keyword}||'%' OR COALESCE(r.resource_name,'') ILIKE '%'||#{keyword}||'%' OR COALESCE(c.resource_name,'') ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR r.online_status=#{status}) ORDER BY r.updated_at DESC,r.id DESC LIMIT #{size} OFFSET #{offset}""") List<Map<String,Object>> listRos(@Param("keyword") String keyword,@Param("status") String status,@Param("size") int size,@Param("offset") int offset);
    @Select("""SELECT r.id,r.resource_code,r.resource_name,r.centos_id,c.resource_code centos_code,c.resource_name centos_name,r.source_system,r.source_id,host(r.management_ip) management_ip,r.region_code,r.carrier_code,r.online_status,r.line_total,r.line_online,r.line_abnormal,r.current_ip_count,r.last_communicated_at,r.last_sync_at,r.created_at,r.updated_at FROM res_ros r LEFT JOIN res_centos c ON c.id=r.centos_id WHERE r.id=#{id} AND r.deleted=FALSE""") Map<String,Object> getRos(@Param("id") Long id);

    @Select("SELECT count(*) FROM res_line l JOIN res_ros r ON r.id=l.ros_id WHERE l.deleted=FALSE AND (#{keyword}='' OR l.resource_code ILIKE '%'||#{keyword}||'%' OR COALESCE(l.resource_name,'') ILIKE '%'||#{keyword}||'%' OR COALESCE(l.broadband_account_mask,'') ILIKE '%'||#{keyword}||'%' OR host(l.current_public_ip) ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR l.online_status=#{status})") long countLines(@Param("keyword") String keyword,@Param("status") String status);
    @Select("""SELECT l.id,l.resource_code,l.resource_name,l.ros_id,r.resource_code ros_code,r.resource_name ros_name,c.id centos_id,c.resource_name centos_name,l.source_system,l.source_id,l.region_code,l.carrier_code,l.broadband_account_mask,host(l.current_public_ip) current_public_ip,l.online_status,l.dial_status,l.latency_ms,l.availability_rate,l.last_dial_at,l.last_ip_changed_at,l.last_sync_at,l.created_at,l.updated_at FROM res_line l JOIN res_ros r ON r.id=l.ros_id LEFT JOIN res_centos c ON c.id=r.centos_id WHERE l.deleted=FALSE AND (#{keyword}='' OR l.resource_code ILIKE '%'||#{keyword}||'%' OR COALESCE(l.resource_name,'') ILIKE '%'||#{keyword}||'%' OR COALESCE(l.broadband_account_mask,'') ILIKE '%'||#{keyword}||'%' OR host(l.current_public_ip) ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR l.online_status=#{status}) ORDER BY l.updated_at DESC,l.id DESC LIMIT #{size} OFFSET #{offset}""") List<Map<String,Object>> listLines(@Param("keyword") String keyword,@Param("status") String status,@Param("size") int size,@Param("offset") int offset);
    @Select("""SELECT l.id,l.resource_code,l.resource_name,l.ros_id,r.resource_code ros_code,r.resource_name ros_name,c.id centos_id,c.resource_name centos_name,l.source_system,l.source_id,l.region_code,l.carrier_code,l.broadband_account_mask,host(l.current_public_ip) current_public_ip,l.online_status,l.dial_status,l.latency_ms,l.availability_rate,l.last_dial_at,l.last_ip_changed_at,l.last_sync_at,l.created_at,l.updated_at FROM res_line l JOIN res_ros r ON r.id=l.ros_id LEFT JOIN res_centos c ON c.id=r.centos_id WHERE l.id=#{id} AND l.deleted=FALSE""") Map<String,Object> getLine(@Param("id") Long id);

    @Select("SELECT count(*) FROM res_ip ip WHERE ip.deleted=FALSE AND (#{keyword}='' OR host(ip.ip_address) ILIKE '%'||#{keyword}||'%' OR COALESCE(ip.source_id,'') ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR ip.available_status=#{status}) AND (#{sourceType}='' OR ip.source_type=#{sourceType})") long countIps(@Param("keyword") String keyword,@Param("status") String status,@Param("sourceType") String sourceType);
    @Select("""SELECT ip.id,host(ip.ip_address) ip_address,ip.source_type,ip.source_system,ip.source_id,ip.centos_id,c.resource_name centos_name,ip.ros_id,r.resource_name ros_name,ip.line_id,l.resource_name line_name,ip.supplier_id,s.supplier_name,ip.region_code,ip.carrier_code,ip.available_status,ip.latency_ms,ip.duplicate_flag,ip.first_seen_at,ip.last_seen_at,ip.last_checked_at,ip.quality_score,(SELECT count(*) FROM res_pool_ip pi WHERE pi.ip_id=ip.id AND pi.enabled=TRUE) pool_count FROM res_ip ip LEFT JOIN res_centos c ON c.id=ip.centos_id LEFT JOIN res_ros r ON r.id=ip.ros_id LEFT JOIN res_line l ON l.id=ip.line_id LEFT JOIN res_supplier s ON s.id=ip.supplier_id WHERE ip.deleted=FALSE AND (#{keyword}='' OR host(ip.ip_address) ILIKE '%'||#{keyword}||'%' OR COALESCE(ip.source_id,'') ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR ip.available_status=#{status}) AND (#{sourceType}='' OR ip.source_type=#{sourceType}) ORDER BY ip.last_seen_at DESC,ip.id DESC LIMIT #{size} OFFSET #{offset}""") List<Map<String,Object>> listIps(@Param("keyword") String keyword,@Param("status") String status,@Param("sourceType") String sourceType,@Param("size") int size,@Param("offset") int offset);
    @Select("""SELECT ip.id,host(ip.ip_address) ip_address,ip.source_type,ip.source_system,ip.source_id,ip.centos_id,c.resource_name centos_name,ip.ros_id,r.resource_name ros_name,ip.line_id,l.resource_name line_name,ip.supplier_id,s.supplier_name,ip.region_code,ip.carrier_code,ip.available_status,ip.latency_ms,ip.duplicate_flag,ip.first_seen_at,ip.last_seen_at,ip.last_checked_at,ip.quality_score,(SELECT string_agg(p.pool_name,', ' ORDER BY p.pool_name) FROM res_pool_ip pi JOIN res_pool p ON p.id=pi.pool_id WHERE pi.ip_id=ip.id AND pi.enabled=TRUE) pool_names FROM res_ip ip LEFT JOIN res_centos c ON c.id=ip.centos_id LEFT JOIN res_ros r ON r.id=ip.ros_id LEFT JOIN res_line l ON l.id=ip.line_id LEFT JOIN res_supplier s ON s.id=ip.supplier_id WHERE ip.id=#{id} AND ip.deleted=FALSE""") Map<String,Object> getIp(@Param("id") Long id);

    @Select("SELECT id FROM res_centos WHERE source_system=#{sourceSystem} AND source_id=#{sourceId} AND deleted=FALSE") Long centosIdBySource(@Param("sourceSystem") String sourceSystem,@Param("sourceId") String sourceId);
    @Select("SELECT id FROM res_ros WHERE source_system=#{sourceSystem} AND source_id=#{sourceId} AND deleted=FALSE") Long rosIdBySource(@Param("sourceSystem") String sourceSystem,@Param("sourceId") String sourceId);
    @Select("SELECT id FROM res_line WHERE source_system=#{sourceSystem} AND source_id=#{sourceId} AND deleted=FALSE") Long lineIdBySource(@Param("sourceSystem") String sourceSystem,@Param("sourceId") String sourceId);
    @Select("SELECT id FROM res_ip WHERE source_type=#{sourceType} AND COALESCE(source_system,'')=COALESCE(#{sourceSystem},'') AND COALESCE(source_id,'')=COALESCE(#{sourceId},'') AND COALESCE(line_id,0)=COALESCE(#{lineId},0) AND COALESCE(supplier_id,0)=COALESCE(#{supplierId},0) AND deleted=FALSE ORDER BY id DESC LIMIT 1") Long ipIdBySource(@Param("sourceType") String sourceType,@Param("sourceSystem") String sourceSystem,@Param("sourceId") String sourceId,@Param("lineId") Long lineId,@Param("supplierId") Long supplierId);

    @Select("""INSERT INTO res_centos(resource_code,resource_name,source_system,source_id,management_ip,region_code,online_status,cpu_usage,memory_usage,disk_usage,last_communicated_at,last_sync_at,raw_data) VALUES(#{code},#{name},#{sourceSystem},#{sourceId},CAST(NULLIF(#{managementIp},'') AS inet),#{regionCode},#{onlineStatus},#{cpuUsage},#{memoryUsage},#{diskUsage},now(),now(),CAST(#{rawJson} AS jsonb)) ON CONFLICT (source_system,source_id) WHERE deleted=FALSE DO UPDATE SET resource_name=EXCLUDED.resource_name,management_ip=EXCLUDED.management_ip,region_code=EXCLUDED.region_code,online_status=EXCLUDED.online_status,cpu_usage=EXCLUDED.cpu_usage,memory_usage=EXCLUDED.memory_usage,disk_usage=EXCLUDED.disk_usage,last_communicated_at=now(),last_sync_at=now(),raw_data=EXCLUDED.raw_data,updated_at=now(),version=res_centos.version+1 RETURNING id""") Long upsertCentos(@Param("code") String code,@Param("name") String name,@Param("sourceSystem") String sourceSystem,@Param("sourceId") String sourceId,@Param("managementIp") String managementIp,@Param("regionCode") String regionCode,@Param("onlineStatus") String onlineStatus,@Param("cpuUsage") BigDecimal cpuUsage,@Param("memoryUsage") BigDecimal memoryUsage,@Param("diskUsage") BigDecimal diskUsage,@Param("rawJson") String rawJson);
    @Select("""INSERT INTO res_ros(resource_code,resource_name,centos_id,source_system,source_id,management_ip,region_code,carrier_code,online_status,last_communicated_at,last_sync_at,raw_data) VALUES(#{code},#{name},#{centosId},#{sourceSystem},#{sourceId},CAST(NULLIF(#{managementIp},'') AS inet),#{regionCode},#{carrierCode},#{onlineStatus},now(),now(),CAST(#{rawJson} AS jsonb)) ON CONFLICT (source_system,source_id) WHERE deleted=FALSE DO UPDATE SET resource_name=EXCLUDED.resource_name,centos_id=EXCLUDED.centos_id,management_ip=EXCLUDED.management_ip,region_code=EXCLUDED.region_code,carrier_code=EXCLUDED.carrier_code,online_status=EXCLUDED.online_status,last_communicated_at=now(),last_sync_at=now(),raw_data=EXCLUDED.raw_data,updated_at=now(),version=res_ros.version+1 RETURNING id""") Long upsertRos(@Param("code") String code,@Param("name") String name,@Param("centosId") Long centosId,@Param("sourceSystem") String sourceSystem,@Param("sourceId") String sourceId,@Param("managementIp") String managementIp,@Param("regionCode") String regionCode,@Param("carrierCode") String carrierCode,@Param("onlineStatus") String onlineStatus,@Param("rawJson") String rawJson);
    @Select("""INSERT INTO res_line(resource_code,resource_name,ros_id,source_system,source_id,region_code,carrier_code,broadband_account_mask,current_public_ip,online_status,dial_status,latency_ms,last_dial_at,last_sync_at,raw_data) VALUES(#{code},#{name},#{rosId},#{sourceSystem},#{sourceId},#{regionCode},#{carrierCode},#{accountMask},CAST(NULLIF(#{currentIp},'') AS inet),#{onlineStatus},#{dialStatus},#{latencyMs},now(),now(),CAST(#{rawJson} AS jsonb)) ON CONFLICT (source_system,source_id) WHERE deleted=FALSE DO UPDATE SET resource_name=EXCLUDED.resource_name,ros_id=EXCLUDED.ros_id,region_code=EXCLUDED.region_code,carrier_code=EXCLUDED.carrier_code,broadband_account_mask=EXCLUDED.broadband_account_mask,current_public_ip=EXCLUDED.current_public_ip,online_status=EXCLUDED.online_status,dial_status=EXCLUDED.dial_status,latency_ms=EXCLUDED.latency_ms,last_sync_at=now(),raw_data=EXCLUDED.raw_data,updated_at=now(),version=res_line.version+1 RETURNING id""") Long upsertLine(@Param("code") String code,@Param("name") String name,@Param("rosId") Long rosId,@Param("sourceSystem") String sourceSystem,@Param("sourceId") String sourceId,@Param("regionCode") String regionCode,@Param("carrierCode") String carrierCode,@Param("accountMask") String accountMask,@Param("currentIp") String currentIp,@Param("onlineStatus") String onlineStatus,@Param("dialStatus") String dialStatus,@Param("latencyMs") Integer latencyMs,@Param("rawJson") String rawJson);
    @Select("""INSERT INTO res_ip(ip_address,source_type,source_system,source_id,centos_id,ros_id,line_id,supplier_id,region_code,carrier_code,available_status,latency_ms,duplicate_flag,last_checked_at,quality_score,raw_data) VALUES(CAST(#{ipAddress} AS inet),#{sourceType},#{sourceSystem},#{sourceId},#{centosId},#{rosId},#{lineId},#{supplierId},#{regionCode},#{carrierCode},#{availableStatus},#{latencyMs},FALSE,now(),#{qualityScore},CAST(#{rawJson} AS jsonb)) RETURNING id""") Long insertIp(@Param("ipAddress") String ipAddress,@Param("sourceType") String sourceType,@Param("sourceSystem") String sourceSystem,@Param("sourceId") String sourceId,@Param("centosId") Long centosId,@Param("rosId") Long rosId,@Param("lineId") Long lineId,@Param("supplierId") Long supplierId,@Param("regionCode") String regionCode,@Param("carrierCode") String carrierCode,@Param("availableStatus") String availableStatus,@Param("latencyMs") Integer latencyMs,@Param("qualityScore") BigDecimal qualityScore,@Param("rawJson") String rawJson);
    @Update("""UPDATE res_ip SET ip_address=CAST(#{ipAddress} AS inet),centos_id=#{centosId},ros_id=#{rosId},line_id=#{lineId},supplier_id=#{supplierId},region_code=#{regionCode},carrier_code=#{carrierCode},available_status=#{availableStatus},latency_ms=#{latencyMs},last_seen_at=now(),last_checked_at=now(),quality_score=#{qualityScore},raw_data=CAST(#{rawJson} AS jsonb),updated_at=now(),version=version+1 WHERE id=#{id} AND deleted=FALSE""") int updateIp(@Param("id") Long id,@Param("ipAddress") String ipAddress,@Param("centosId") Long centosId,@Param("rosId") Long rosId,@Param("lineId") Long lineId,@Param("supplierId") Long supplierId,@Param("regionCode") String regionCode,@Param("carrierCode") String carrierCode,@Param("availableStatus") String availableStatus,@Param("latencyMs") Integer latencyMs,@Param("qualityScore") BigDecimal qualityScore,@Param("rawJson") String rawJson);

    @Select("""INSERT INTO res_sync_task(task_no,source_type,supplier_id,sync_mode,status,target_pool_id,triggered_by,request_id) VALUES(#{taskNo},#{sourceType},#{supplierId},#{mode},'PENDING',#{targetPoolId},#{actorId},#{requestId}) RETURNING id""") Long insertSyncTask(@Param("taskNo") String taskNo,@Param("sourceType") String sourceType,@Param("supplierId") Long supplierId,@Param("mode") String mode,@Param("targetPoolId") Long targetPoolId,@Param("actorId") Long actorId,@Param("requestId") String requestId);
    @Update("UPDATE res_sync_task SET status=#{status},requested_count=#{requested},received_count=#{received},normalized_count=#{normalized},deduped_count=#{deduped},available_count=#{available},started_at=COALESCE(started_at,CASE WHEN #{status}='RUNNING' THEN now() ELSE started_at END),finished_at=CASE WHEN #{status} IN ('SUCCESS','PARTIAL_SUCCESS','FAILED','CANCELLED') THEN now() ELSE finished_at END,error_message=#{error} WHERE id=#{id}") int updateSyncTask(@Param("id") Long id,@Param("status") String status,@Param("requested") int requested,@Param("received") int received,@Param("normalized") int normalized,@Param("deduped") int deduped,@Param("available") int available,@Param("error") String error);
    @Insert("""INSERT INTO res_sync_detail(task_id,source_record_id,raw_record,normalized_record,resource_type,resource_id,process_status,duplicate_flag,available_flag,error_message,processed_at) VALUES(#{taskId},#{sourceRecordId},CAST(#{rawJson} AS jsonb),CAST(#{normalizedJson} AS jsonb),#{resourceType},#{resourceId},#{processStatus},#{duplicateFlag},#{availableFlag},#{error},now())""") int insertSyncDetail(@Param("taskId") Long taskId,@Param("sourceRecordId") String sourceRecordId,@Param("rawJson") String rawJson,@Param("normalizedJson") String normalizedJson,@Param("resourceType") String resourceType,@Param("resourceId") Long resourceId,@Param("processStatus") String processStatus,@Param("duplicateFlag") Boolean duplicateFlag,@Param("availableFlag") Boolean availableFlag,@Param("error") String error);

    @Select("SELECT count(*) FROM res_pool p WHERE p.deleted=FALSE AND (#{keyword}='' OR p.pool_code ILIKE '%'||#{keyword}||'%' OR p.pool_name ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR p.status=#{status})") long countPools(@Param("keyword") String keyword,@Param("status") String status);
    @Select("""SELECT p.id,p.pool_code,p.pool_name,p.purpose,p.region_codes,p.carrier_codes,p.source_scope,p.admission_rule,p.detection_rule,p.dedup_rule,p.priority,p.status,p.created_at,p.updated_at,(SELECT count(*) FROM res_pool_ip pi WHERE pi.pool_id=p.id AND pi.enabled=TRUE) ip_count,(SELECT count(*) FROM res_pool_ip pi JOIN res_ip ip ON ip.id=pi.ip_id WHERE pi.pool_id=p.id AND pi.enabled=TRUE AND ip.available_status='AVAILABLE' AND ip.duplicate_flag=FALSE) available_ip_count FROM res_pool p WHERE p.deleted=FALSE AND (#{keyword}='' OR p.pool_code ILIKE '%'||#{keyword}||'%' OR p.pool_name ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR p.status=#{status}) ORDER BY p.priority,p.id DESC LIMIT #{size} OFFSET #{offset}""") List<Map<String,Object>> listPools(@Param("keyword") String keyword,@Param("status") String status,@Param("size") int size,@Param("offset") int offset);
    @Select("""SELECT p.id,p.pool_code,p.pool_name,p.purpose,p.region_codes,p.carrier_codes,p.source_scope,p.admission_rule,p.detection_rule,p.dedup_rule,p.priority,p.status,p.created_at,p.updated_at,(SELECT count(*) FROM res_pool_ip pi WHERE pi.pool_id=p.id AND pi.enabled=TRUE) ip_count FROM res_pool p WHERE p.id=#{id} AND p.deleted=FALSE""") Map<String,Object> getPool(@Param("id") Long id);
    @Select("""INSERT INTO res_pool(pool_code,pool_name,purpose,region_codes,carrier_codes,source_scope,admission_rule,detection_rule,dedup_rule,priority,created_by,updated_by) VALUES(#{code},#{name},#{purpose},CAST(#{regionsJson} AS jsonb),CAST(#{carriersJson} AS jsonb),#{sourceScope},CAST(#{admissionJson} AS jsonb),CAST(#{detectionJson} AS jsonb),CAST(#{dedupJson} AS jsonb),#{priority},#{actorId},#{actorId}) RETURNING id""") Long insertPool(@Param("code") String code,@Param("name") String name,@Param("purpose") String purpose,@Param("regionsJson") String regionsJson,@Param("carriersJson") String carriersJson,@Param("sourceScope") String sourceScope,@Param("admissionJson") String admissionJson,@Param("detectionJson") String detectionJson,@Param("dedupJson") String dedupJson,@Param("priority") int priority,@Param("actorId") Long actorId);
    @Update("""UPDATE res_pool SET pool_name=#{name},purpose=#{purpose},region_codes=CAST(#{regionsJson} AS jsonb),carrier_codes=CAST(#{carriersJson} AS jsonb),source_scope=#{sourceScope},admission_rule=CAST(#{admissionJson} AS jsonb),detection_rule=CAST(#{detectionJson} AS jsonb),dedup_rule=CAST(#{dedupJson} AS jsonb),priority=#{priority},updated_at=now(),updated_by=#{actorId},version=version+1 WHERE id=#{id} AND deleted=FALSE""") int updatePool(@Param("id") Long id,@Param("name") String name,@Param("purpose") String purpose,@Param("regionsJson") String regionsJson,@Param("carriersJson") String carriersJson,@Param("sourceScope") String sourceScope,@Param("admissionJson") String admissionJson,@Param("detectionJson") String detectionJson,@Param("dedupJson") String dedupJson,@Param("priority") int priority,@Param("actorId") Long actorId);
    @Update("UPDATE res_pool SET status=#{status},updated_at=now(),updated_by=#{actorId},version=version+1 WHERE id=#{id} AND deleted=FALSE") int updatePoolStatus(@Param("id") Long id,@Param("status") String status,@Param("actorId") Long actorId);
    @Update("UPDATE res_pool_ip SET enabled=FALSE,removed_at=now() WHERE pool_id=#{poolId} AND enabled=TRUE") int disablePoolMembers(@Param("poolId") Long poolId);
    @Insert("""INSERT INTO res_pool_ip(pool_id,ip_id,source_reason,enabled,joined_at,removed_at) SELECT p.id,ip.id,'M4基础规则自动计算',TRUE,now(),NULL FROM res_pool p JOIN res_ip ip ON ip.deleted=FALSE WHERE p.id=#{poolId} AND p.deleted=FALSE AND ip.available_status='AVAILABLE' AND ip.duplicate_flag=FALSE AND (p.source_scope='MIXED' OR p.source_scope=ip.source_type) AND (jsonb_array_length(p.region_codes)=0 OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(p.region_codes) x(v) WHERE x.v=ip.region_code)) AND (jsonb_array_length(p.carrier_codes)=0 OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(p.carrier_codes) x(v) WHERE x.v=ip.carrier_code)) ON CONFLICT (pool_id,ip_id) DO UPDATE SET enabled=TRUE,removed_at=NULL,joined_at=now(),source_reason='M4基础规则自动计算'""") int recalculatePoolMembers(@Param("poolId") Long poolId);
    @Select("SELECT count(*) FROM res_pool_ip pi JOIN res_ip ip ON ip.id=pi.ip_id WHERE pi.pool_id=#{poolId} AND pi.enabled=TRUE AND (#{keyword}='' OR host(ip.ip_address) ILIKE '%'||#{keyword}||'%')") long countPoolIps(@Param("poolId") Long poolId,@Param("keyword") String keyword);
    @Select("""SELECT ip.id,host(ip.ip_address) ip_address,ip.source_type,ip.region_code,ip.carrier_code,ip.available_status,ip.latency_ms,ip.quality_score,pi.source_reason,pi.joined_at FROM res_pool_ip pi JOIN res_ip ip ON ip.id=pi.ip_id WHERE pi.pool_id=#{poolId} AND pi.enabled=TRUE AND (#{keyword}='' OR host(ip.ip_address) ILIKE '%'||#{keyword}||'%') ORDER BY ip.quality_score DESC NULLS LAST,ip.id DESC LIMIT #{size} OFFSET #{offset}""") List<Map<String,Object>> listPoolIps(@Param("poolId") Long poolId,@Param("keyword") String keyword,@Param("size") int size,@Param("offset") int offset);

    @Select("SELECT count(*) FROM res_exclusive_allocation a JOIN customer c ON c.id=a.customer_id WHERE a.deleted=FALSE AND (#{keyword}='' OR a.allocation_no ILIKE '%'||#{keyword}||'%' OR c.customer_name ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR a.status=#{status})") long countExclusive(@Param("keyword") String keyword,@Param("status") String status);
    @Select("""SELECT a.id,a.allocation_no,a.resource_type,a.ip_id,host(ip.ip_address) ip_address,a.line_id,l.resource_name line_name,a.customer_id,c.customer_code,c.customer_name,a.service_id,a.status,a.locked_at,a.effective_at,a.expire_at,a.released_at,a.release_reason,a.health_status,a.created_at FROM res_exclusive_allocation a JOIN customer c ON c.id=a.customer_id LEFT JOIN res_ip ip ON ip.id=a.ip_id LEFT JOIN res_line l ON l.id=a.line_id WHERE a.deleted=FALSE AND (#{keyword}='' OR a.allocation_no ILIKE '%'||#{keyword}||'%' OR c.customer_name ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR a.status=#{status}) ORDER BY a.created_at DESC,a.id DESC LIMIT #{size} OFFSET #{offset}""") List<Map<String,Object>> listExclusive(@Param("keyword") String keyword,@Param("status") String status,@Param("size") int size,@Param("offset") int offset);
    @Select("""SELECT a.id,a.allocation_no,a.resource_type,a.ip_id,host(ip.ip_address) ip_address,a.line_id,l.resource_name line_name,a.customer_id,c.customer_code,c.customer_name,a.service_id,a.status,a.locked_at,a.effective_at,a.expire_at,a.released_at,a.release_reason,a.health_status,a.created_at FROM res_exclusive_allocation a JOIN customer c ON c.id=a.customer_id LEFT JOIN res_ip ip ON ip.id=a.ip_id LEFT JOIN res_line l ON l.id=a.line_id WHERE a.id=#{id} AND a.deleted=FALSE""") Map<String,Object> getExclusive(@Param("id") Long id);
    @Update("UPDATE res_exclusive_allocation SET status='PENDING_RECYCLE',released_at=now(),release_reason=#{reason},updated_at=now(),updated_by=#{actorId},version=version+1 WHERE id=#{id} AND deleted=FALSE AND status IN ('LOCKED','ALLOCATED')") int releaseExclusive(@Param("id") Long id,@Param("reason") String reason,@Param("actorId") Long actorId);

    @Select("SELECT count(*) FROM res_domain d WHERE d.deleted=FALSE AND (#{keyword}='' OR d.domain_name ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR d.status=#{status})") long countDomains(@Param("keyword") String keyword,@Param("status") String status);
    @Select("""SELECT d.id,d.domain_name,d.current_ip_id,host(ip.ip_address) current_ip,d.line_id,l.resource_name line_name,d.usage_type_code,d.update_mode,d.status,d.last_updated_at,d.last_error,d.created_at,d.updated_at FROM res_domain d LEFT JOIN res_ip ip ON ip.id=d.current_ip_id LEFT JOIN res_line l ON l.id=d.line_id WHERE d.deleted=FALSE AND (#{keyword}='' OR d.domain_name ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR d.status=#{status}) ORDER BY d.updated_at DESC,d.id DESC LIMIT #{size} OFFSET #{offset}""") List<Map<String,Object>> listDomains(@Param("keyword") String keyword,@Param("status") String status,@Param("size") int size,@Param("offset") int offset);
    @Select("""SELECT d.id,d.domain_name,d.current_ip_id,host(ip.ip_address) current_ip,d.line_id,l.resource_name line_name,d.usage_type_code,d.update_mode,d.status,d.last_updated_at,d.last_error,d.created_at,d.updated_at FROM res_domain d LEFT JOIN res_ip ip ON ip.id=d.current_ip_id LEFT JOIN res_line l ON l.id=d.line_id WHERE d.id=#{id} AND d.deleted=FALSE""") Map<String,Object> getDomain(@Param("id") Long id);
    @Select("""INSERT INTO res_domain(domain_name,current_ip_id,line_id,usage_type_code,update_mode,status,created_by,updated_by) VALUES(#{domainName},#{currentIpId},#{lineId},#{usageTypeCode},#{updateMode},'NORMAL',#{actorId},#{actorId}) RETURNING id""") Long insertDomain(@Param("domainName") String domainName,@Param("currentIpId") Long currentIpId,@Param("lineId") Long lineId,@Param("usageTypeCode") String usageTypeCode,@Param("updateMode") String updateMode,@Param("actorId") Long actorId);
    @Update("UPDATE res_domain SET current_ip_id=#{currentIpId},line_id=#{lineId},usage_type_code=#{usageTypeCode},update_mode=#{updateMode},updated_at=now(),updated_by=#{actorId},version=version+1 WHERE id=#{id} AND deleted=FALSE") int updateDomain(@Param("id") Long id,@Param("currentIpId") Long currentIpId,@Param("lineId") Long lineId,@Param("usageTypeCode") String usageTypeCode,@Param("updateMode") String updateMode,@Param("actorId") Long actorId);
    @Select("SELECT id FROM res_ip WHERE line_id=#{lineId} AND deleted=FALSE AND available_status='AVAILABLE' AND duplicate_flag=FALSE ORDER BY last_seen_at DESC,id DESC LIMIT 1") Long latestAvailableIpForLine(@Param("lineId") Long lineId);
    @Update("UPDATE res_domain SET current_ip_id=#{ipId},status=#{status},last_updated_at=now(),last_error=#{error},updated_at=now(),updated_by=#{actorId},version=version+1 WHERE id=#{id} AND deleted=FALSE") int updateDomainRefresh(@Param("id") Long id,@Param("ipId") Long ipId,@Param("status") String status,@Param("error") String error,@Param("actorId") Long actorId);

    @Select("SELECT count(*) FROM res_supplier WHERE deleted=FALSE AND (#{keyword}='' OR supplier_code ILIKE '%'||#{keyword}||'%' OR supplier_name ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR status=#{status})") long countSuppliers(@Param("keyword") String keyword,@Param("status") String status);
    @Select("""SELECT id,supplier_code,supplier_name,contact_name,contact_phone,api_endpoint,auth_type_code,api_account,region_codes,carrier_codes,fetch_mode,interface_status,status,last_success_at,last_failure_at,last_error,created_at,updated_at,(secret_cipher IS NOT NULL AND secret_cipher<>'') secret_configured FROM res_supplier WHERE deleted=FALSE AND (#{keyword}='' OR supplier_code ILIKE '%'||#{keyword}||'%' OR supplier_name ILIKE '%'||#{keyword}||'%') AND (#{status}='' OR status=#{status}) ORDER BY updated_at DESC,id DESC LIMIT #{size} OFFSET #{offset}""") List<Map<String,Object>> listSuppliers(@Param("keyword") String keyword,@Param("status") String status,@Param("size") int size,@Param("offset") int offset);
    @Select("""SELECT id,supplier_code,supplier_name,contact_name,contact_phone,api_endpoint,auth_type_code,api_account,region_codes,carrier_codes,fetch_mode,interface_status,status,last_success_at,last_failure_at,last_error,created_at,updated_at,(secret_cipher IS NOT NULL AND secret_cipher<>'') secret_configured FROM res_supplier WHERE id=#{id} AND deleted=FALSE""") Map<String,Object> getSupplier(@Param("id") Long id);
    @Select("SELECT id,supplier_code,supplier_name,api_endpoint,auth_type_code,api_account,secret_cipher,region_codes,carrier_codes,fetch_mode,interface_status,status FROM res_supplier WHERE id=#{id} AND deleted=FALSE") Map<String,Object> getSupplierInternal(@Param("id") Long id);
    @Select("""INSERT INTO res_supplier(supplier_code,supplier_name,contact_name,contact_phone,api_endpoint,auth_type_code,api_account,secret_cipher,region_codes,carrier_codes,fetch_mode,created_by,updated_by) VALUES(#{code},#{name},#{contactName},#{contactPhone},#{apiEndpoint},#{authTypeCode},#{apiAccount},#{secretCipher},CAST(#{regionsJson} AS jsonb),CAST(#{carriersJson} AS jsonb),#{fetchMode},#{actorId},#{actorId}) RETURNING id""") Long insertSupplier(@Param("code") String code,@Param("name") String name,@Param("contactName") String contactName,@Param("contactPhone") String contactPhone,@Param("apiEndpoint") String apiEndpoint,@Param("authTypeCode") String authTypeCode,@Param("apiAccount") String apiAccount,@Param("secretCipher") String secretCipher,@Param("regionsJson") String regionsJson,@Param("carriersJson") String carriersJson,@Param("fetchMode") String fetchMode,@Param("actorId") Long actorId);
    @Update("""UPDATE res_supplier SET supplier_name=#{name},contact_name=#{contactName},contact_phone=#{contactPhone},api_endpoint=#{apiEndpoint},auth_type_code=#{authTypeCode},api_account=#{apiAccount},secret_cipher=COALESCE(#{secretCipher},secret_cipher),region_codes=CAST(#{regionsJson} AS jsonb),carrier_codes=CAST(#{carriersJson} AS jsonb),fetch_mode=#{fetchMode},updated_at=now(),updated_by=#{actorId},version=version+1 WHERE id=#{id} AND deleted=FALSE""") int updateSupplier(@Param("id") Long id,@Param("name") String name,@Param("contactName") String contactName,@Param("contactPhone") String contactPhone,@Param("apiEndpoint") String apiEndpoint,@Param("authTypeCode") String authTypeCode,@Param("apiAccount") String apiAccount,@Param("secretCipher") String secretCipher,@Param("regionsJson") String regionsJson,@Param("carriersJson") String carriersJson,@Param("fetchMode") String fetchMode,@Param("actorId") Long actorId);
    @Update("UPDATE res_supplier SET status=#{status},updated_at=now(),updated_by=#{actorId},version=version+1 WHERE id=#{id} AND deleted=FALSE") int updateSupplierStatus(@Param("id") Long id,@Param("status") String status,@Param("actorId") Long actorId);
    @Update("UPDATE res_supplier SET interface_status=#{interfaceStatus},last_success_at=CASE WHEN #{interfaceStatus}='NORMAL' THEN now() ELSE last_success_at END,last_failure_at=CASE WHEN #{interfaceStatus}='ABNORMAL' THEN now() ELSE last_failure_at END,last_error=#{message},updated_at=now(),version=version+1 WHERE id=#{id} AND deleted=FALSE") int updateSupplierTest(@Param("id") Long id,@Param("interfaceStatus") String interfaceStatus,@Param("message") String message);

    @Select("SELECT count(*) FROM res_sync_task t LEFT JOIN res_supplier s ON s.id=t.supplier_id WHERE (#{sourceType}='' OR t.source_type=#{sourceType}) AND (#{status}='' OR t.status=#{status})") long countSyncTasks(@Param("sourceType") String sourceType,@Param("status") String status);
    @Select("""SELECT t.id,t.task_no,t.source_type,t.supplier_id,s.supplier_name,t.sync_mode,t.status,t.requested_count,t.received_count,t.normalized_count,t.deduped_count,t.available_count,t.target_pool_id,p.pool_name target_pool_name,t.started_at,t.finished_at,t.triggered_by,u.display_name triggered_by_name,t.request_id,t.error_message,t.created_at FROM res_sync_task t LEFT JOIN res_supplier s ON s.id=t.supplier_id LEFT JOIN res_pool p ON p.id=t.target_pool_id LEFT JOIN sys_user u ON u.id=t.triggered_by WHERE (#{sourceType}='' OR t.source_type=#{sourceType}) AND (#{status}='' OR t.status=#{status}) ORDER BY t.created_at DESC,t.id DESC LIMIT #{size} OFFSET #{offset}""") List<Map<String,Object>> listSyncTasks(@Param("sourceType") String sourceType,@Param("status") String status,@Param("size") int size,@Param("offset") int offset);
    @Select("""SELECT t.id,t.task_no,t.source_type,t.supplier_id,s.supplier_name,t.sync_mode,t.status,t.requested_count,t.received_count,t.normalized_count,t.deduped_count,t.available_count,t.target_pool_id,p.pool_name target_pool_name,t.started_at,t.finished_at,t.triggered_by,u.display_name triggered_by_name,t.request_id,t.error_message,t.created_at FROM res_sync_task t LEFT JOIN res_supplier s ON s.id=t.supplier_id LEFT JOIN res_pool p ON p.id=t.target_pool_id LEFT JOIN sys_user u ON u.id=t.triggered_by WHERE t.id=#{id}""") Map<String,Object> getSyncTask(@Param("id") Long id);
    @Select("SELECT id,task_id,source_record_id,normalized_record,resource_type,resource_id,process_status,duplicate_flag,available_flag,error_message,processed_at,created_at FROM res_sync_detail WHERE task_id=#{taskId} ORDER BY id") List<Map<String,Object>> listSyncDetails(@Param("taskId") Long taskId);

    @Select("""SELECT i.item_code,i.item_name,i.item_value,i.sort_order FROM sys_dict_item i JOIN sys_dict_type t ON t.id=i.dict_type_id WHERE t.dict_code=#{dictCode} AND t.deleted=FALSE AND i.deleted=FALSE AND t.status='ACTIVE' AND i.status='ACTIVE' ORDER BY i.sort_order,i.id""") List<Map<String,Object>> dictOptions(@Param("dictCode") String dictCode);
    @Insert("""INSERT INTO sys_operation_log(operator_id,operator_name,module_code,object_type,object_id,operation,reason,source_ip,request_id,result) VALUES(#{operatorId},#{operatorName},'RESOURCE',#{objectType},#{objectId},#{operation},#{reason},CAST(NULLIF(#{ip},'') AS inet),#{requestId},'SUCCESS')""") int insertAudit(@Param("operatorId") Long operatorId,@Param("operatorName") String operatorName,@Param("objectType") String objectType,@Param("objectId") String objectId,@Param("operation") String operation,@Param("reason") String reason,@Param("ip") String ip,@Param("requestId") String requestId);
}
