package com.ipproxy.platform.resource.mapper;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import java.math.BigDecimal;
import java.util.*;

/**
 * M4 资源域数据访问层。资源域查询较多且SQL高度聚合，使用JdbcTemplate避免将长SQL塞进注解。
 */
@Repository
public class ResourceMapper {
    private final JdbcTemplate jdbc;
    public ResourceMapper(JdbcTemplate jdbc){this.jdbc=jdbc;}
    private Map<String,Object> one(String sql,Object... args){List<Map<String,Object>> rows=jdbc.queryForList(sql,args);return rows.isEmpty()?null:rows.getFirst();}

    public Map<String,Object> overview(){return one("SELECT (SELECT count(*) FROM res_centos WHERE deleted=FALSE) centos_total,(SELECT count(*) FROM res_centos WHERE deleted=FALSE AND online_status='ONLINE') centos_online,(SELECT count(*) FROM res_ros WHERE deleted=FALSE) ros_total,(SELECT count(*) FROM res_ros WHERE deleted=FALSE AND online_status='ONLINE') ros_online,(SELECT count(*) FROM res_line WHERE deleted=FALSE) line_total,(SELECT count(*) FROM res_line WHERE deleted=FALSE AND online_status='ONLINE') line_online,(SELECT count(*) FROM res_line WHERE deleted=FALSE AND online_status='ABNORMAL') line_abnormal,(SELECT count(*) FROM res_ip WHERE deleted=FALSE) ip_total,(SELECT count(*) FROM res_ip WHERE deleted=FALSE AND available_status='AVAILABLE' AND duplicate_flag=FALSE) ip_available,(SELECT count(*) FROM res_ip WHERE deleted=FALSE AND source_type='EXTERNAL') external_ip_total,(SELECT count(*) FROM res_pool WHERE deleted=FALSE AND status='ACTIVE') active_pool_total,(SELECT count(*) FROM res_exclusive_allocation WHERE deleted=FALSE AND status IN ('LOCKED','ALLOCATED')) exclusive_active_total,(SELECT count(*) FROM res_supplier WHERE deleted=FALSE AND status='ACTIVE') active_supplier_total,(SELECT count(*) FROM res_sync_task WHERE status='FAILED' AND created_at>=now()-interval '24 hours') sync_failed_24h");}

    public long countCentos(String keyword,String status){return jdbc.queryForObject("SELECT count(*) FROM res_centos WHERE deleted=FALSE AND (?='' OR resource_code ILIKE '%'||?||'%' OR COALESCE(resource_name,'') ILIKE '%'||?||'%' OR host(management_ip) ILIKE '%'||?||'%') AND (?='' OR online_status=?)",Long.class,keyword,keyword,keyword,keyword,status,status);}
    public List<Map<String,Object>> listCentos(String keyword,String status,int size,int offset){return jdbc.queryForList("SELECT id,resource_code,resource_name,source_system,source_id,host(management_ip) management_ip,region_code,online_status,cpu_usage,memory_usage,disk_usage,network_in_bps,network_out_bps,last_communicated_at,last_sync_at,created_at,updated_at FROM res_centos WHERE deleted=FALSE AND (?='' OR resource_code ILIKE '%'||?||'%' OR COALESCE(resource_name,'') ILIKE '%'||?||'%' OR host(management_ip) ILIKE '%'||?||'%') AND (?='' OR online_status=?) ORDER BY updated_at DESC,id DESC LIMIT ? OFFSET ?",keyword,keyword,keyword,keyword,status,status,size,offset);}
    public Map<String,Object> getCentos(Long id){return one("SELECT id,resource_code,resource_name,source_system,source_id,host(management_ip) management_ip,region_code,online_status,cpu_usage,memory_usage,disk_usage,network_in_bps,network_out_bps,last_communicated_at,last_sync_at,created_at,updated_at FROM res_centos WHERE id=? AND deleted=FALSE",id);}

    public long countRos(String keyword,String status){return jdbc.queryForObject("SELECT count(*) FROM res_ros r LEFT JOIN res_centos c ON c.id=r.centos_id WHERE r.deleted=FALSE AND (?='' OR r.resource_code ILIKE '%'||?||'%' OR COALESCE(r.resource_name,'') ILIKE '%'||?||'%' OR COALESCE(c.resource_name,'') ILIKE '%'||?||'%') AND (?='' OR r.online_status=?)",Long.class,keyword,keyword,keyword,keyword,status,status);}
    public List<Map<String,Object>> listRos(String keyword,String status,int size,int offset){return jdbc.queryForList("SELECT r.id,r.resource_code,r.resource_name,r.centos_id,c.resource_code centos_code,c.resource_name centos_name,r.source_system,r.source_id,host(r.management_ip) management_ip,r.region_code,r.carrier_code,r.online_status,r.line_total,r.line_online,r.line_abnormal,r.current_ip_count,r.last_communicated_at,r.last_sync_at,r.created_at,r.updated_at FROM res_ros r LEFT JOIN res_centos c ON c.id=r.centos_id WHERE r.deleted=FALSE AND (?='' OR r.resource_code ILIKE '%'||?||'%' OR COALESCE(r.resource_name,'') ILIKE '%'||?||'%' OR COALESCE(c.resource_name,'') ILIKE '%'||?||'%') AND (?='' OR r.online_status=?) ORDER BY r.updated_at DESC,r.id DESC LIMIT ? OFFSET ?",keyword,keyword,keyword,keyword,status,status,size,offset);}
    public Map<String,Object> getRos(Long id){return one("SELECT r.id,r.resource_code,r.resource_name,r.centos_id,c.resource_code centos_code,c.resource_name centos_name,r.source_system,r.source_id,host(r.management_ip) management_ip,r.region_code,r.carrier_code,r.online_status,r.line_total,r.line_online,r.line_abnormal,r.current_ip_count,r.last_communicated_at,r.last_sync_at,r.created_at,r.updated_at FROM res_ros r LEFT JOIN res_centos c ON c.id=r.centos_id WHERE r.id=? AND r.deleted=FALSE",id);}

    public long countLines(String keyword,String status){return jdbc.queryForObject("SELECT count(*) FROM res_line l JOIN res_ros r ON r.id=l.ros_id WHERE l.deleted=FALSE AND (?='' OR l.resource_code ILIKE '%'||?||'%' OR COALESCE(l.resource_name,'') ILIKE '%'||?||'%' OR COALESCE(l.broadband_account_mask,'') ILIKE '%'||?||'%' OR host(l.current_public_ip) ILIKE '%'||?||'%') AND (?='' OR l.online_status=?)",Long.class,keyword,keyword,keyword,keyword,keyword,status,status);}
    public List<Map<String,Object>> listLines(String keyword,String status,int size,int offset){return jdbc.queryForList("SELECT l.id,l.resource_code,l.resource_name,l.ros_id,r.resource_code ros_code,r.resource_name ros_name,c.id centos_id,c.resource_name centos_name,l.source_system,l.source_id,l.region_code,l.carrier_code,l.broadband_account_mask,host(l.current_public_ip) current_public_ip,l.online_status,l.dial_status,l.latency_ms,l.availability_rate,l.last_dial_at,l.last_ip_changed_at,l.last_sync_at,l.created_at,l.updated_at FROM res_line l JOIN res_ros r ON r.id=l.ros_id LEFT JOIN res_centos c ON c.id=r.centos_id WHERE l.deleted=FALSE AND (?='' OR l.resource_code ILIKE '%'||?||'%' OR COALESCE(l.resource_name,'') ILIKE '%'||?||'%' OR COALESCE(l.broadband_account_mask,'') ILIKE '%'||?||'%' OR host(l.current_public_ip) ILIKE '%'||?||'%') AND (?='' OR l.online_status=?) ORDER BY l.updated_at DESC,l.id DESC LIMIT ? OFFSET ?",keyword,keyword,keyword,keyword,keyword,status,status,size,offset);}
    public Map<String,Object> getLine(Long id){return one("SELECT l.id,l.resource_code,l.resource_name,l.ros_id,r.resource_code ros_code,r.resource_name ros_name,c.id centos_id,c.resource_name centos_name,l.source_system,l.source_id,l.region_code,l.carrier_code,l.broadband_account_mask,host(l.current_public_ip) current_public_ip,l.online_status,l.dial_status,l.latency_ms,l.availability_rate,l.last_dial_at,l.last_ip_changed_at,l.last_sync_at,l.created_at,l.updated_at FROM res_line l JOIN res_ros r ON r.id=l.ros_id LEFT JOIN res_centos c ON c.id=r.centos_id WHERE l.id=? AND l.deleted=FALSE",id);}

    public long countIps(String keyword,String status,String sourceType){return jdbc.queryForObject("SELECT count(*) FROM res_ip ip WHERE ip.deleted=FALSE AND (?='' OR host(ip.ip_address) ILIKE '%'||?||'%' OR COALESCE(ip.source_id,'') ILIKE '%'||?||'%') AND (?='' OR ip.available_status=?) AND (?='' OR ip.source_type=?)",Long.class,keyword,keyword,keyword,status,status,sourceType,sourceType);}
    public List<Map<String,Object>> listIps(String keyword,String status,String sourceType,int size,int offset){return jdbc.queryForList("SELECT ip.id,host(ip.ip_address) ip_address,ip.source_type,ip.source_system,ip.source_id,ip.centos_id,c.resource_name centos_name,ip.ros_id,r.resource_name ros_name,ip.line_id,l.resource_name line_name,ip.supplier_id,s.supplier_name,ip.region_code,ip.carrier_code,ip.available_status,ip.latency_ms,ip.duplicate_flag,ip.first_seen_at,ip.last_seen_at,ip.last_checked_at,ip.quality_score,(SELECT count(*) FROM res_pool_ip pi WHERE pi.ip_id=ip.id AND pi.enabled=TRUE) pool_count FROM res_ip ip LEFT JOIN res_centos c ON c.id=ip.centos_id LEFT JOIN res_ros r ON r.id=ip.ros_id LEFT JOIN res_line l ON l.id=ip.line_id LEFT JOIN res_supplier s ON s.id=ip.supplier_id WHERE ip.deleted=FALSE AND (?='' OR host(ip.ip_address) ILIKE '%'||?||'%' OR COALESCE(ip.source_id,'') ILIKE '%'||?||'%') AND (?='' OR ip.available_status=?) AND (?='' OR ip.source_type=?) ORDER BY ip.last_seen_at DESC,ip.id DESC LIMIT ? OFFSET ?",keyword,keyword,keyword,status,status,sourceType,sourceType,size,offset);}
    public Map<String,Object> getIp(Long id){return one("SELECT ip.id,host(ip.ip_address) ip_address,ip.source_type,ip.source_system,ip.source_id,ip.centos_id,c.resource_name centos_name,ip.ros_id,r.resource_name ros_name,ip.line_id,l.resource_name line_name,ip.supplier_id,s.supplier_name,ip.region_code,ip.carrier_code,ip.available_status,ip.latency_ms,ip.duplicate_flag,ip.first_seen_at,ip.last_seen_at,ip.last_checked_at,ip.quality_score,(SELECT string_agg(p.pool_name,', ' ORDER BY p.pool_name) FROM res_pool_ip pi JOIN res_pool p ON p.id=pi.pool_id WHERE pi.ip_id=ip.id AND pi.enabled=TRUE) pool_names FROM res_ip ip LEFT JOIN res_centos c ON c.id=ip.centos_id LEFT JOIN res_ros r ON r.id=ip.ros_id LEFT JOIN res_line l ON l.id=ip.line_id LEFT JOIN res_supplier s ON s.id=ip.supplier_id WHERE ip.id=? AND ip.deleted=FALSE",id);}

    public Long centosIdBySource(String sourceSystem,String sourceId){return scalarLong("SELECT id FROM res_centos WHERE source_system=? AND source_id=? AND deleted=FALSE",sourceSystem,sourceId);}
    public Long rosIdBySource(String sourceSystem,String sourceId){return scalarLong("SELECT id FROM res_ros WHERE source_system=? AND source_id=? AND deleted=FALSE",sourceSystem,sourceId);}
    public Long lineIdBySource(String sourceSystem,String sourceId){return scalarLong("SELECT id FROM res_line WHERE source_system=? AND source_id=? AND deleted=FALSE",sourceSystem,sourceId);}
    public Long ipIdBySource(String sourceType,String sourceSystem,String sourceId,Long lineId,Long supplierId){return scalarLong("SELECT id FROM res_ip WHERE source_type=? AND COALESCE(source_system,'')=COALESCE(?,'') AND COALESCE(source_id,'')=COALESCE(?,'') AND COALESCE(line_id,0)=COALESCE(?,0) AND COALESCE(supplier_id,0)=COALESCE(?,0) AND deleted=FALSE ORDER BY id DESC LIMIT 1",sourceType,sourceSystem,sourceId,lineId,supplierId);}
    private Long scalarLong(String sql,Object... args){List<Long> rows=jdbc.query(sql,(rs,n)->rs.getLong(1),args);return rows.isEmpty()?null:rows.getFirst();}

    public Long upsertCentos(String code,String name,String sourceSystem,String sourceId,String managementIp,String regionCode,String onlineStatus,BigDecimal cpuUsage,BigDecimal memoryUsage,BigDecimal diskUsage,String rawJson){return jdbc.queryForObject("INSERT INTO res_centos(resource_code,resource_name,source_system,source_id,management_ip,region_code,online_status,cpu_usage,memory_usage,disk_usage,last_communicated_at,last_sync_at,raw_data) VALUES(?,?,?,?,CAST(NULLIF(?,'') AS inet),?,?,?,?,?,now(),now(),CAST(? AS jsonb)) ON CONFLICT (source_system,source_id) WHERE deleted=FALSE DO UPDATE SET resource_name=EXCLUDED.resource_name,management_ip=EXCLUDED.management_ip,region_code=EXCLUDED.region_code,online_status=EXCLUDED.online_status,cpu_usage=EXCLUDED.cpu_usage,memory_usage=EXCLUDED.memory_usage,disk_usage=EXCLUDED.disk_usage,last_communicated_at=now(),last_sync_at=now(),raw_data=EXCLUDED.raw_data,updated_at=now(),version=res_centos.version+1 RETURNING id",Long.class,code,name,sourceSystem,sourceId,managementIp,regionCode,onlineStatus,cpuUsage,memoryUsage,diskUsage,rawJson);}
    public Long upsertRos(String code,String name,Long centosId,String sourceSystem,String sourceId,String managementIp,String regionCode,String carrierCode,String onlineStatus,String rawJson){return jdbc.queryForObject("INSERT INTO res_ros(resource_code,resource_name,centos_id,source_system,source_id,management_ip,region_code,carrier_code,online_status,last_communicated_at,last_sync_at,raw_data) VALUES(?,?,?,?,?,CAST(NULLIF(?,'') AS inet),?,?,?,now(),now(),CAST(? AS jsonb)) ON CONFLICT (source_system,source_id) WHERE deleted=FALSE DO UPDATE SET resource_name=EXCLUDED.resource_name,centos_id=EXCLUDED.centos_id,management_ip=EXCLUDED.management_ip,region_code=EXCLUDED.region_code,carrier_code=EXCLUDED.carrier_code,online_status=EXCLUDED.online_status,last_communicated_at=now(),last_sync_at=now(),raw_data=EXCLUDED.raw_data,updated_at=now(),version=res_ros.version+1 RETURNING id",Long.class,code,name,centosId,sourceSystem,sourceId,managementIp,regionCode,carrierCode,onlineStatus,rawJson);}
    public Long upsertLine(String code,String name,Long rosId,String sourceSystem,String sourceId,String regionCode,String carrierCode,String accountMask,String currentIp,String onlineStatus,String dialStatus,Integer latencyMs,String rawJson){return jdbc.queryForObject("INSERT INTO res_line(resource_code,resource_name,ros_id,source_system,source_id,region_code,carrier_code,broadband_account_mask,current_public_ip,online_status,dial_status,latency_ms,last_dial_at,last_sync_at,raw_data) VALUES(?,?,?,?,?,?,?,?,CAST(NULLIF(?,'') AS inet),?,?,?,now(),now(),CAST(? AS jsonb)) ON CONFLICT (source_system,source_id) WHERE deleted=FALSE DO UPDATE SET resource_name=EXCLUDED.resource_name,ros_id=EXCLUDED.ros_id,region_code=EXCLUDED.region_code,carrier_code=EXCLUDED.carrier_code,broadband_account_mask=EXCLUDED.broadband_account_mask,current_public_ip=EXCLUDED.current_public_ip,online_status=EXCLUDED.online_status,dial_status=EXCLUDED.dial_status,latency_ms=EXCLUDED.latency_ms,last_sync_at=now(),raw_data=EXCLUDED.raw_data,updated_at=now(),version=res_line.version+1 RETURNING id",Long.class,code,name,rosId,sourceSystem,sourceId,regionCode,carrierCode,accountMask,currentIp,onlineStatus,dialStatus,latencyMs,rawJson);}
    public Long insertIp(String ipAddress,String sourceType,String sourceSystem,String sourceId,Long centosId,Long rosId,Long lineId,Long supplierId,String regionCode,String carrierCode,String availableStatus,Integer latencyMs,BigDecimal qualityScore,String rawJson){return jdbc.queryForObject("INSERT INTO res_ip(ip_address,source_type,source_system,source_id,centos_id,ros_id,line_id,supplier_id,region_code,carrier_code,available_status,latency_ms,duplicate_flag,last_checked_at,quality_score,raw_data) VALUES(CAST(? AS inet),?,?,?,?,?,?,?,?,?,?,?,FALSE,now(),?,CAST(? AS jsonb)) RETURNING id",Long.class,ipAddress,sourceType,sourceSystem,sourceId,centosId,rosId,lineId,supplierId,regionCode,carrierCode,availableStatus,latencyMs,qualityScore,rawJson);}
    public int updateIp(Long id,String ipAddress,Long centosId,Long rosId,Long lineId,Long supplierId,String regionCode,String carrierCode,String availableStatus,Integer latencyMs,BigDecimal qualityScore,String rawJson){return jdbc.update("UPDATE res_ip SET ip_address=CAST(? AS inet),centos_id=?,ros_id=?,line_id=?,supplier_id=?,region_code=?,carrier_code=?,available_status=?,latency_ms=?,last_seen_at=now(),last_checked_at=now(),quality_score=?,raw_data=CAST(? AS jsonb),updated_at=now(),version=version+1 WHERE id=? AND deleted=FALSE",ipAddress,centosId,rosId,lineId,supplierId,regionCode,carrierCode,availableStatus,latencyMs,qualityScore,rawJson,id);}

    public Long insertSyncTask(String taskNo,String sourceType,Long supplierId,String mode,Long targetPoolId,Long actorId,String requestId){return jdbc.queryForObject("INSERT INTO res_sync_task(task_no,source_type,supplier_id,sync_mode,status,target_pool_id,triggered_by,request_id) VALUES(?,?,?,?,'PENDING',?,?,?) RETURNING id",Long.class,taskNo,sourceType,supplierId,mode,targetPoolId,actorId,requestId);}
    public int updateSyncTask(Long id,String status,int requested,int received,int normalized,int deduped,int available,String error){return jdbc.update("UPDATE res_sync_task SET status=?,requested_count=?,received_count=?,normalized_count=?,deduped_count=?,available_count=?,started_at=COALESCE(started_at,CASE WHEN ?='RUNNING' THEN now() ELSE started_at END),finished_at=CASE WHEN ? IN ('SUCCESS','PARTIAL_SUCCESS','FAILED','CANCELLED') THEN now() ELSE finished_at END,error_message=? WHERE id=?",status,requested,received,normalized,deduped,available,status,status,error,id);}
    public int insertSyncDetail(Long taskId,String sourceRecordId,String rawJson,String normalizedJson,String resourceType,Long resourceId,String processStatus,Boolean duplicateFlag,Boolean availableFlag,String error){return jdbc.update("INSERT INTO res_sync_detail(task_id,source_record_id,raw_record,normalized_record,resource_type,resource_id,process_status,duplicate_flag,available_flag,error_message,processed_at) VALUES(?,?,CAST(? AS jsonb),CAST(? AS jsonb),?,?,?,?,?,?,now())",taskId,sourceRecordId,rawJson,normalizedJson,resourceType,resourceId,processStatus,duplicateFlag,availableFlag,error);}

    public long countPools(String keyword,String status){return jdbc.queryForObject("SELECT count(*) FROM res_pool p WHERE p.deleted=FALSE AND (?='' OR p.pool_code ILIKE '%'||?||'%' OR p.pool_name ILIKE '%'||?||'%') AND (?='' OR p.status=?)",Long.class,keyword,keyword,keyword,status,status);}
    public List<Map<String,Object>> listPools(String keyword,String status,int size,int offset){return jdbc.queryForList("SELECT p.id,p.pool_code,p.pool_name,p.purpose,p.region_codes,p.carrier_codes,p.source_scope,p.admission_rule,p.detection_rule,p.dedup_rule,p.priority,p.status,p.created_at,p.updated_at,(SELECT count(*) FROM res_pool_ip pi WHERE pi.pool_id=p.id AND pi.enabled=TRUE) ip_count,(SELECT count(*) FROM res_pool_ip pi JOIN res_ip ip ON ip.id=pi.ip_id WHERE pi.pool_id=p.id AND pi.enabled=TRUE AND ip.available_status='AVAILABLE' AND ip.duplicate_flag=FALSE) available_ip_count FROM res_pool p WHERE p.deleted=FALSE AND (?='' OR p.pool_code ILIKE '%'||?||'%' OR p.pool_name ILIKE '%'||?||'%') AND (?='' OR p.status=?) ORDER BY p.priority,p.id DESC LIMIT ? OFFSET ?",keyword,keyword,keyword,status,status,size,offset);}
    public Map<String,Object> getPool(Long id){return one("SELECT p.id,p.pool_code,p.pool_name,p.purpose,p.region_codes,p.carrier_codes,p.source_scope,p.admission_rule,p.detection_rule,p.dedup_rule,p.priority,p.status,p.created_at,p.updated_at,(SELECT count(*) FROM res_pool_ip pi WHERE pi.pool_id=p.id AND pi.enabled=TRUE) ip_count FROM res_pool p WHERE p.id=? AND p.deleted=FALSE",id);}
    public Long insertPool(String code,String name,String purpose,String regionsJson,String carriersJson,String sourceScope,String admissionJson,String detectionJson,String dedupJson,int priority,Long actorId){return jdbc.queryForObject("INSERT INTO res_pool(pool_code,pool_name,purpose,region_codes,carrier_codes,source_scope,admission_rule,detection_rule,dedup_rule,priority,created_by,updated_by) VALUES(?,?,?,CAST(? AS jsonb),CAST(? AS jsonb),?,CAST(? AS jsonb),CAST(? AS jsonb),CAST(? AS jsonb),?,?,?) RETURNING id",Long.class,code,name,purpose,regionsJson,carriersJson,sourceScope,admissionJson,detectionJson,dedupJson,priority,actorId,actorId);}
    public int updatePool(Long id,String name,String purpose,String regionsJson,String carriersJson,String sourceScope,String admissionJson,String detectionJson,String dedupJson,int priority,Long actorId){return jdbc.update("UPDATE res_pool SET pool_name=?,purpose=?,region_codes=CAST(? AS jsonb),carrier_codes=CAST(? AS jsonb),source_scope=?,admission_rule=CAST(? AS jsonb),detection_rule=CAST(? AS jsonb),dedup_rule=CAST(? AS jsonb),priority=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",name,purpose,regionsJson,carriersJson,sourceScope,admissionJson,detectionJson,dedupJson,priority,actorId,id);}
    public int updatePoolStatus(Long id,String status,Long actorId){return jdbc.update("UPDATE res_pool SET status=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",status,actorId,id);}
    public int disablePoolMembers(Long poolId){return jdbc.update("UPDATE res_pool_ip SET enabled=FALSE,removed_at=now() WHERE pool_id=? AND enabled=TRUE",poolId);}
    public int recalculatePoolMembers(Long poolId){return jdbc.update("INSERT INTO res_pool_ip(pool_id,ip_id,source_reason,enabled,joined_at,removed_at) SELECT p.id,ip.id,'M4基础规则自动计算',TRUE,now(),NULL FROM res_pool p JOIN res_ip ip ON ip.deleted=FALSE WHERE p.id=? AND p.deleted=FALSE AND ip.available_status='AVAILABLE' AND ip.duplicate_flag=FALSE AND (p.source_scope='MIXED' OR p.source_scope=ip.source_type) AND (jsonb_array_length(p.region_codes)=0 OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(p.region_codes) x(v) WHERE x.v=ip.region_code)) AND (jsonb_array_length(p.carrier_codes)=0 OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(p.carrier_codes) x(v) WHERE x.v=ip.carrier_code)) ON CONFLICT (pool_id,ip_id) DO UPDATE SET enabled=TRUE,removed_at=NULL,joined_at=now(),source_reason='M4基础规则自动计算'",poolId);}
    public long countPoolIps(Long poolId,String keyword){return jdbc.queryForObject("SELECT count(*) FROM res_pool_ip pi JOIN res_ip ip ON ip.id=pi.ip_id WHERE pi.pool_id=? AND pi.enabled=TRUE AND (?='' OR host(ip.ip_address) ILIKE '%'||?||'%')",Long.class,poolId,keyword,keyword);}
    public List<Map<String,Object>> listPoolIps(Long poolId,String keyword,int size,int offset){return jdbc.queryForList("SELECT ip.id,host(ip.ip_address) ip_address,ip.source_type,ip.region_code,ip.carrier_code,ip.available_status,ip.latency_ms,ip.quality_score,pi.source_reason,pi.joined_at FROM res_pool_ip pi JOIN res_ip ip ON ip.id=pi.ip_id WHERE pi.pool_id=? AND pi.enabled=TRUE AND (?='' OR host(ip.ip_address) ILIKE '%'||?||'%') ORDER BY ip.quality_score DESC NULLS LAST,ip.id DESC LIMIT ? OFFSET ?",poolId,keyword,keyword,size,offset);}

    public long countExclusive(String keyword,String status){return jdbc.queryForObject("SELECT count(*) FROM res_exclusive_allocation a JOIN customer c ON c.id=a.customer_id WHERE a.deleted=FALSE AND (?='' OR a.allocation_no ILIKE '%'||?||'%' OR c.customer_name ILIKE '%'||?||'%') AND (?='' OR a.status=?)",Long.class,keyword,keyword,keyword,status,status);}
    public List<Map<String,Object>> listExclusive(String keyword,String status,int size,int offset){return jdbc.queryForList("SELECT a.id,a.allocation_no,a.resource_type,a.ip_id,host(ip.ip_address) ip_address,a.line_id,l.resource_name line_name,a.customer_id,c.customer_code,c.customer_name,a.service_id,a.status,a.locked_at,a.effective_at,a.expire_at,a.released_at,a.release_reason,a.health_status,a.created_at FROM res_exclusive_allocation a JOIN customer c ON c.id=a.customer_id LEFT JOIN res_ip ip ON ip.id=a.ip_id LEFT JOIN res_line l ON l.id=a.line_id WHERE a.deleted=FALSE AND (?='' OR a.allocation_no ILIKE '%'||?||'%' OR c.customer_name ILIKE '%'||?||'%') AND (?='' OR a.status=?) ORDER BY a.created_at DESC,a.id DESC LIMIT ? OFFSET ?",keyword,keyword,keyword,status,status,size,offset);}
    public Map<String,Object> getExclusive(Long id){return one("SELECT a.id,a.allocation_no,a.resource_type,a.ip_id,host(ip.ip_address) ip_address,a.line_id,l.resource_name line_name,a.customer_id,c.customer_code,c.customer_name,a.service_id,a.status,a.locked_at,a.effective_at,a.expire_at,a.released_at,a.release_reason,a.health_status,a.created_at FROM res_exclusive_allocation a JOIN customer c ON c.id=a.customer_id LEFT JOIN res_ip ip ON ip.id=a.ip_id LEFT JOIN res_line l ON l.id=a.line_id WHERE a.id=? AND a.deleted=FALSE",id);}
    public int releaseExclusive(Long id,String reason,Long actorId){return jdbc.update("UPDATE res_exclusive_allocation SET status='PENDING_RECYCLE',released_at=now(),release_reason=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE AND status IN ('LOCKED','ALLOCATED')",reason,actorId,id);}

    public long countDomains(String keyword,String status){return jdbc.queryForObject("SELECT count(*) FROM res_domain d WHERE d.deleted=FALSE AND (?='' OR d.domain_name ILIKE '%'||?||'%') AND (?='' OR d.status=?)",Long.class,keyword,keyword,status,status);}
    public List<Map<String,Object>> listDomains(String keyword,String status,int size,int offset){return jdbc.queryForList("SELECT d.id,d.domain_name,d.current_ip_id,host(ip.ip_address) current_ip,d.line_id,l.resource_name line_name,d.usage_type_code,d.update_mode,d.status,d.last_updated_at,d.last_error,d.created_at,d.updated_at FROM res_domain d LEFT JOIN res_ip ip ON ip.id=d.current_ip_id LEFT JOIN res_line l ON l.id=d.line_id WHERE d.deleted=FALSE AND (?='' OR d.domain_name ILIKE '%'||?||'%') AND (?='' OR d.status=?) ORDER BY d.updated_at DESC,d.id DESC LIMIT ? OFFSET ?",keyword,keyword,status,status,size,offset);}
    public Map<String,Object> getDomain(Long id){return one("SELECT d.id,d.domain_name,d.current_ip_id,host(ip.ip_address) current_ip,d.line_id,l.resource_name line_name,d.usage_type_code,d.update_mode,d.status,d.last_updated_at,d.last_error,d.created_at,d.updated_at FROM res_domain d LEFT JOIN res_ip ip ON ip.id=d.current_ip_id LEFT JOIN res_line l ON l.id=d.line_id WHERE d.id=? AND d.deleted=FALSE",id);}
    public Long insertDomain(String domainName,Long currentIpId,Long lineId,String usageTypeCode,String updateMode,Long actorId){return jdbc.queryForObject("INSERT INTO res_domain(domain_name,current_ip_id,line_id,usage_type_code,update_mode,status,created_by,updated_by) VALUES(?,?,?,?,?,'NORMAL',?,?) RETURNING id",Long.class,domainName,currentIpId,lineId,usageTypeCode,updateMode,actorId,actorId);}
    public int updateDomain(Long id,Long currentIpId,Long lineId,String usageTypeCode,String updateMode,Long actorId){return jdbc.update("UPDATE res_domain SET current_ip_id=?,line_id=?,usage_type_code=?,update_mode=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",currentIpId,lineId,usageTypeCode,updateMode,actorId,id);}
    public Long latestAvailableIpForLine(Long lineId){return scalarLong("SELECT id FROM res_ip WHERE line_id=? AND deleted=FALSE AND available_status='AVAILABLE' AND duplicate_flag=FALSE ORDER BY last_seen_at DESC,id DESC LIMIT 1",lineId);}
    public int updateDomainRefresh(Long id,Long ipId,String status,String error,Long actorId){return jdbc.update("UPDATE res_domain SET current_ip_id=?,status=?,last_updated_at=now(),last_error=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",ipId,status,error,actorId,id);}

    public long countSuppliers(String keyword,String status){return jdbc.queryForObject("SELECT count(*) FROM res_supplier WHERE deleted=FALSE AND (?='' OR supplier_code ILIKE '%'||?||'%' OR supplier_name ILIKE '%'||?||'%') AND (?='' OR status=?)",Long.class,keyword,keyword,keyword,status,status);}
    public List<Map<String,Object>> listSuppliers(String keyword,String status,int size,int offset){return jdbc.queryForList("SELECT id,supplier_code,supplier_name,contact_name,contact_phone,api_endpoint,auth_type_code,api_account,region_codes,carrier_codes,fetch_mode,interface_status,status,last_success_at,last_failure_at,last_error,created_at,updated_at,(secret_cipher IS NOT NULL AND secret_cipher<>'') secret_configured FROM res_supplier WHERE deleted=FALSE AND (?='' OR supplier_code ILIKE '%'||?||'%' OR supplier_name ILIKE '%'||?||'%') AND (?='' OR status=?) ORDER BY updated_at DESC,id DESC LIMIT ? OFFSET ?",keyword,keyword,keyword,status,status,size,offset);}
    public Map<String,Object> getSupplier(Long id){return one("SELECT id,supplier_code,supplier_name,contact_name,contact_phone,api_endpoint,auth_type_code,api_account,region_codes,carrier_codes,fetch_mode,interface_status,status,last_success_at,last_failure_at,last_error,created_at,updated_at,(secret_cipher IS NOT NULL AND secret_cipher<>'') secret_configured FROM res_supplier WHERE id=? AND deleted=FALSE",id);}
    public Map<String,Object> getSupplierInternal(Long id){return one("SELECT id,supplier_code,supplier_name,api_endpoint,auth_type_code,api_account,secret_cipher,region_codes,carrier_codes,fetch_mode,interface_status,status FROM res_supplier WHERE id=? AND deleted=FALSE",id);}
    public Long insertSupplier(String code,String name,String contactName,String contactPhone,String apiEndpoint,String authTypeCode,String apiAccount,String secretCipher,String regionsJson,String carriersJson,String fetchMode,Long actorId){return jdbc.queryForObject("INSERT INTO res_supplier(supplier_code,supplier_name,contact_name,contact_phone,api_endpoint,auth_type_code,api_account,secret_cipher,region_codes,carrier_codes,fetch_mode,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,CAST(? AS jsonb),CAST(? AS jsonb),?,?,?) RETURNING id",Long.class,code,name,contactName,contactPhone,apiEndpoint,authTypeCode,apiAccount,secretCipher,regionsJson,carriersJson,fetchMode,actorId,actorId);}
    public int updateSupplier(Long id,String name,String contactName,String contactPhone,String apiEndpoint,String authTypeCode,String apiAccount,String secretCipher,String regionsJson,String carriersJson,String fetchMode,Long actorId){return jdbc.update("UPDATE res_supplier SET supplier_name=?,contact_name=?,contact_phone=?,api_endpoint=?,auth_type_code=?,api_account=?,secret_cipher=COALESCE(?,secret_cipher),region_codes=CAST(? AS jsonb),carrier_codes=CAST(? AS jsonb),fetch_mode=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",name,contactName,contactPhone,apiEndpoint,authTypeCode,apiAccount,secretCipher,regionsJson,carriersJson,fetchMode,actorId,id);}
    public int updateSupplierStatus(Long id,String status,Long actorId){return jdbc.update("UPDATE res_supplier SET status=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",status,actorId,id);}
    public int updateSupplierTest(Long id,String interfaceStatus,String message){return jdbc.update("UPDATE res_supplier SET interface_status=?,last_success_at=CASE WHEN ?='NORMAL' THEN now() ELSE last_success_at END,last_failure_at=CASE WHEN ?='ABNORMAL' THEN now() ELSE last_failure_at END,last_error=?,updated_at=now(),version=version+1 WHERE id=? AND deleted=FALSE",interfaceStatus,interfaceStatus,interfaceStatus,message,id);}

    public long countSyncTasks(String sourceType,String status){return jdbc.queryForObject("SELECT count(*) FROM res_sync_task t LEFT JOIN res_supplier s ON s.id=t.supplier_id WHERE (?='' OR t.source_type=?) AND (?='' OR t.status=?)",Long.class,sourceType,sourceType,status,status);}
    public List<Map<String,Object>> listSyncTasks(String sourceType,String status,int size,int offset){return jdbc.queryForList("SELECT t.id,t.task_no,t.source_type,t.supplier_id,s.supplier_name,t.sync_mode,t.status,t.requested_count,t.received_count,t.normalized_count,t.deduped_count,t.available_count,t.target_pool_id,p.pool_name target_pool_name,t.started_at,t.finished_at,t.triggered_by,u.display_name triggered_by_name,t.request_id,t.error_message,t.created_at FROM res_sync_task t LEFT JOIN res_supplier s ON s.id=t.supplier_id LEFT JOIN res_pool p ON p.id=t.target_pool_id LEFT JOIN sys_user u ON u.id=t.triggered_by WHERE (?='' OR t.source_type=?) AND (?='' OR t.status=?) ORDER BY t.created_at DESC,t.id DESC LIMIT ? OFFSET ?",sourceType,sourceType,status,status,size,offset);}
    public Map<String,Object> getSyncTask(Long id){return one("SELECT t.id,t.task_no,t.source_type,t.supplier_id,s.supplier_name,t.sync_mode,t.status,t.requested_count,t.received_count,t.normalized_count,t.deduped_count,t.available_count,t.target_pool_id,p.pool_name target_pool_name,t.started_at,t.finished_at,t.triggered_by,u.display_name triggered_by_name,t.request_id,t.error_message,t.created_at FROM res_sync_task t LEFT JOIN res_supplier s ON s.id=t.supplier_id LEFT JOIN res_pool p ON p.id=t.target_pool_id LEFT JOIN sys_user u ON u.id=t.triggered_by WHERE t.id=?",id);}
    public List<Map<String,Object>> listSyncDetails(Long taskId){return jdbc.queryForList("SELECT id,task_id,source_record_id,normalized_record,resource_type,resource_id,process_status,duplicate_flag,available_flag,error_message,processed_at,created_at FROM res_sync_detail WHERE task_id=? ORDER BY id",taskId);}

    public List<Map<String,Object>> dictOptions(String dictCode){return jdbc.queryForList("SELECT i.item_code,i.item_name,i.item_value,i.sort_order FROM sys_dict_item i JOIN sys_dict_type t ON t.id=i.dict_type_id WHERE t.dict_code=? AND t.deleted=FALSE AND i.deleted=FALSE AND t.status='ACTIVE' AND i.status='ACTIVE' ORDER BY i.sort_order,i.id",dictCode);}
    public int insertAudit(Long operatorId,String operatorName,String objectType,String objectId,String operation,String reason,String ip,String requestId){return jdbc.update("INSERT INTO sys_operation_log(operator_id,operator_name,module_code,object_type,object_id,operation,reason,source_ip,request_id,result) VALUES(?,?,'RESOURCE',?,?,?,?,CAST(NULLIF(?,'') AS inet),?,'SUCCESS')",operatorId,operatorName,objectType,objectId,operation,reason,ip,requestId);}
}
