package com.ipproxy.platform.system.auth.service;

import com.ipproxy.platform.common.exception.BusinessException; import com.ipproxy.platform.security.*; import com.ipproxy.platform.system.auth.dto.*; import com.ipproxy.platform.system.user.mapper.SystemUserMapper; import com.ipproxy.platform.system.user.model.SystemUser; import org.slf4j.MDC; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import java.util.List;

@Service
public class AuthService {
    private final SystemUserMapper userMapper; private final PasswordEncoder passwordEncoder; private final JwtTokenService tokenService;
    public AuthService(SystemUserMapper userMapper,PasswordEncoder passwordEncoder,JwtTokenService tokenService){this.userMapper=userMapper;this.passwordEncoder=passwordEncoder;this.tokenService=tokenService;}
    public LoginResponse login(LoginRequest request,String ip,String ua){SystemUser user=userMapper.findByUsername(request.username());if(user==null||!passwordEncoder.matches(request.password(),user.getPasswordHash())){userMapper.insertLoginLog(user==null?null:user.getId(),request.username(),ip,ua,"FAILURE","用户名或密码错误",MDC.get("requestId"));throw new BusinessException("AUTH_INVALID_CREDENTIALS","用户名或密码错误");}if(!"ACTIVE".equals(user.getStatus())){userMapper.insertLoginLog(user.getId(),user.getUsername(),ip,ua,"FAILURE","账号状态不可用",MDC.get("requestId"));throw new BusinessException("AUTH_USER_DISABLED","账号当前不可登录");}List<String> roles=userMapper.findRoleCodesByUserId(user.getId());List<String> permissions=userMapper.findPermissionCodesByUserId(user.getId());UserPrincipal p=new UserPrincipal(user.getId(),user.getUsername(),user.getDisplayName(),roles,permissions);String token=tokenService.create(p);userMapper.updateLastLogin(user.getId(),ip);userMapper.insertLoginLog(user.getId(),user.getUsername(),ip,ua,"SUCCESS",null,MDC.get("requestId"));return new LoginResponse(token,"Bearer",tokenService.expirationSeconds(),new LoginResponse.UserInfo(user.getId(),user.getUsername(),user.getDisplayName(),roles,permissions));}
}
