package com.ipproxy.platform.system.admin;

import com.ipproxy.platform.common.exception.BusinessException;
import com.ipproxy.platform.security.UserPrincipal;
import org.slf4j.MDC;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;

@Service
public class SystemAdminService {
    private final JdbcTemplate jdbc; private final PasswordEncoder encoder;
    public SystemAdminService(JdbcTemplate jdbc,PasswordEncoder encoder){this.jdbc=jdbc;this.encoder=encoder;}

    public List<Map<String,Object>> users(){return jdbc.queryForList("SELECT u.id,u.username,u.display_name,u.department,u.mobile,u.email,u.status,u.last_login_at,u.created_at,COALESCE(string_agg(r.role_name,',' ORDER BY r.role_name),'') role_names,COALESCE(string_agg(r.id::text,',' ORDER BY r.id),'') role_ids FROM sys_user u LEFT JOIN sys_user_role ur ON ur.user_id=u.id LEFT JOIN sys_role r ON r.id=ur.role_id AND r.deleted=FALSE WHERE u.deleted=FALSE GROUP BY u.id ORDER BY u.id DESC");}
    @Transactional public Long createUser(String username,String password,String displayName,String department,String mobile,String email,String status,List<Long> roleIds,UserPrincipal actor,String ip){if(username==null||username.isBlank())throw new BusinessException("SYSTEM_USER_USERNAME_REQUIRED","用户名不能为空");ensurePassword(password);if(count("SELECT count(*) FROM sys_user WHERE username=? AND deleted=FALSE",username)>0)throw new BusinessException("SYSTEM_USER_EXISTS","用户名已存在");Long id=jdbc.queryForObject("INSERT INTO sys_user(username,password_hash,display_name,department,mobile,email,status,password_changed_at,created_by,updated_by) VALUES(?,?,?,?,?,?,?,now(),?,?) RETURNING id",Long.class,username,encoder.encode(password),defaultText(displayName,username),department,mobile,email,defaultText(status,"ACTIVE"),actor.userId(),actor.userId());replaceUserRoles(id,roleIds);audit(actor,"SYSTEM","SYS_USER",id,"CREATE",ip,"创建用户 "+username);return id;}
    @Transactional public void updateUser(Long id,String displayName,String department,String mobile,String email,String status,List<Long> roleIds,UserPrincipal actor,String ip){String targetStatus=defaultText(status,"ACTIVE");if(Objects.equals(id,actor.userId())&&!"ACTIVE".equals(targetStatus))throw new BusinessException("SYSTEM_SELF_DISABLE_FORBIDDEN","不能冻结或停用当前登录账号");if(Objects.equals(id,actor.userId())&&actor.roles().contains("SUPER_ADMIN")&&!containsRoleCode(roleIds,"SUPER_ADMIN"))throw new BusinessException("SYSTEM_SELF_ROLE_FORBIDDEN","不能移除当前超级管理员账号的超级管理员角色");jdbc.update("UPDATE sys_user SET display_name=?,department=?,mobile=?,email=?,status=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",displayName,department,mobile,email,targetStatus,actor.userId(),id);replaceUserRoles(id,roleIds);audit(actor,"SYSTEM","SYS_USER",id,"UPDATE",ip,"修改用户");}
    public void resetPassword(Long id,String password,UserPrincipal actor,String ip){ensurePassword(password);jdbc.update("UPDATE sys_user SET password_hash=?,password_changed_at=now(),updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",encoder.encode(password),actor.userId(),id);audit(actor,"SYSTEM","SYS_USER",id,"RESET_PASSWORD",ip,"重置密码");}
    private void replaceUserRoles(Long userId,List<Long> ids){jdbc.update("DELETE FROM sys_user_role WHERE user_id=?",userId);if(ids!=null)for(Long roleId:ids)jdbc.update("INSERT INTO sys_user_role(user_id,role_id) VALUES(?,?) ON CONFLICT DO NOTHING",userId,roleId);}

    public List<Map<String,Object>> roles(){return jdbc.queryForList("SELECT r.id,r.role_code,r.role_name,r.data_scope,r.description,r.status,r.created_at,(r.role_code='SUPER_ADMIN') built_in,COALESCE(count(rp.permission_id),0) permission_count FROM sys_role r LEFT JOIN sys_role_permission rp ON rp.role_id=r.id WHERE r.deleted=FALSE GROUP BY r.id ORDER BY r.id");}
    public Long createRole(String code,String name,String scope,String description,String status,UserPrincipal actor,String ip){if(code==null||code.isBlank())throw new BusinessException("SYSTEM_ROLE_CODE_REQUIRED","角色编码不能为空");if(count("SELECT count(*) FROM sys_role WHERE role_code=? AND deleted=FALSE",code)>0)throw new BusinessException("SYSTEM_ROLE_EXISTS","角色编码已存在");Long id=jdbc.queryForObject("INSERT INTO sys_role(role_code,role_name,data_scope,description,status,created_by,updated_by) VALUES(?,?,?,?,?,?,?) RETURNING id",Long.class,code,name,defaultText(scope,"ALL"),description,defaultText(status,"ACTIVE"),actor.userId(),actor.userId());audit(actor,"SYSTEM","SYS_ROLE",id,"CREATE",ip,"创建角色 "+code);return id;}
    public void updateRole(Long id,String name,String scope,String description,String status,UserPrincipal actor,String ip){protectBuiltInRole(id);jdbc.update("UPDATE sys_role SET role_name=?,data_scope=?,description=?,status=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",name,defaultText(scope,"ALL"),description,defaultText(status,"ACTIVE"),actor.userId(),id);audit(actor,"SYSTEM","SYS_ROLE",id,"UPDATE",ip,"修改角色");}
    @Transactional public void replaceRolePermissions(Long roleId,List<Long> ids,UserPrincipal actor,String ip){protectBuiltInRole(roleId);jdbc.update("DELETE FROM sys_role_permission WHERE role_id=?",roleId);if(ids!=null)for(Long permissionId:ids)jdbc.update("INSERT INTO sys_role_permission(role_id,permission_id) VALUES(?,?) ON CONFLICT DO NOTHING",roleId,permissionId);audit(actor,"SYSTEM","SYS_ROLE",roleId,"AUTHORIZE",ip,"更新角色权限");}
    public List<Map<String,Object>> rolePermissionIds(Long roleId){return jdbc.queryForList("SELECT permission_id FROM sys_role_permission WHERE role_id=? ORDER BY permission_id",roleId);}
    public List<Map<String,Object>> permissions(){return jdbc.queryForList("SELECT id,permission_code,permission_name,permission_type,parent_id,route_path,sort_order,status FROM sys_permission WHERE deleted=FALSE ORDER BY sort_order,id");}

    public List<Map<String,Object>> dictTypes(){return jdbc.queryForList("SELECT id,dict_code,dict_name,description,editable,status,created_at FROM sys_dict_type WHERE deleted=FALSE ORDER BY dict_code");}
    public Long createDictType(String code,String name,String description,Boolean editable,String status,UserPrincipal actor,String ip){if(count("SELECT count(*) FROM sys_dict_type WHERE dict_code=? AND deleted=FALSE",code)>0)throw new BusinessException("SYSTEM_DICT_EXISTS","字典编码已存在");Long id=jdbc.queryForObject("INSERT INTO sys_dict_type(dict_code,dict_name,description,editable,status,created_by,updated_by) VALUES(?,?,?,?,?,?,?) RETURNING id",Long.class,code,name,description,editable==null||editable,defaultText(status,"ACTIVE"),actor.userId(),actor.userId());audit(actor,"SYSTEM","SYS_DICT_TYPE",id,"CREATE",ip,"创建字典类型 "+code);return id;}
    public void updateDictType(Long id,String name,String description,Boolean editable,String status,UserPrincipal actor,String ip){jdbc.update("UPDATE sys_dict_type SET dict_name=?,description=?,editable=?,status=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",name,description,editable==null||editable,defaultText(status,"ACTIVE"),actor.userId(),id);audit(actor,"SYSTEM","SYS_DICT_TYPE",id,"UPDATE",ip,"修改字典类型");}
    public List<Map<String,Object>> dictItems(Long typeId){return jdbc.queryForList("SELECT id,dict_type_id,item_code,item_name,item_value,sort_order,color_tag,is_default,status,remark FROM sys_dict_item WHERE dict_type_id=? AND deleted=FALSE ORDER BY sort_order,id",typeId);}
    public Long createDictItem(Long typeId,String code,String name,String value,Integer sort,String color,Boolean isDefault,String status,String remark,UserPrincipal actor,String ip){if(count2("SELECT count(*) FROM sys_dict_item WHERE dict_type_id=? AND item_code=? AND deleted=FALSE",typeId,code)>0)throw new BusinessException("SYSTEM_DICT_ITEM_EXISTS","字典项编码已存在");Long id=jdbc.queryForObject("INSERT INTO sys_dict_item(dict_type_id,item_code,item_name,item_value,sort_order,color_tag,is_default,status,remark,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?) RETURNING id",Long.class,typeId,code,name,value,sort==null?0:sort,color,isDefault!=null&&isDefault,defaultText(status,"ACTIVE"),remark,actor.userId(),actor.userId());audit(actor,"SYSTEM","SYS_DICT_ITEM",id,"CREATE",ip,"创建字典项 "+code);return id;}
    public void updateDictItem(Long id,String name,String value,Integer sort,String color,Boolean isDefault,String status,String remark,UserPrincipal actor,String ip){jdbc.update("UPDATE sys_dict_item SET item_name=?,item_value=?,sort_order=?,color_tag=?,is_default=?,status=?,remark=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE",name,value,sort==null?0:sort,color,isDefault!=null&&isDefault,defaultText(status,"ACTIVE"),remark,actor.userId(),id);audit(actor,"SYSTEM","SYS_DICT_ITEM",id,"UPDATE",ip,"修改字典项");}

    public List<Map<String,Object>> parameters(){return jdbc.queryForList("SELECT id,param_group,param_code,param_name,CASE WHEN sensitive THEN '******' ELSE param_value END param_value,value_type,sensitive,description,status,updated_at FROM sys_parameter WHERE deleted=FALSE ORDER BY param_group,param_code");}
    public Long createParameter(String group,String code,String name,String value,String type,Boolean sensitive,String description,String status,UserPrincipal actor,String ip){if(count("SELECT count(*) FROM sys_parameter WHERE param_code=? AND deleted=FALSE",code)>0)throw new BusinessException("SYSTEM_PARAMETER_EXISTS","参数编码已存在");Long id=jdbc.queryForObject("INSERT INTO sys_parameter(param_group,param_code,param_name,param_value,value_type,sensitive,description,status,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?) RETURNING id",Long.class,group,code,name,value,defaultText(type,"STRING"),sensitive!=null&&sensitive,description,defaultText(status,"ACTIVE"),actor.userId(),actor.userId());audit(actor,"SYSTEM","SYS_PARAMETER",id,"CREATE",ip,"创建参数 "+code);return id;}
    public void updateParameter(Long id,String group,String name,String value,String type,Boolean sensitive,String description,String status,UserPrincipal actor,String ip){boolean keepMasked="******".equals(value);String sql=keepMasked?"UPDATE sys_parameter SET param_group=?,param_name=?,value_type=?,sensitive=?,description=?,status=?,updated_at=now(),updated_by=?,version=version+1 WHERE id=? AND deleted=FALSE":"UPDATE sys_parameter SET param_group=?,param_name=?,value_type=?,sensitive=?,description=?,status=?,updated_at=now(),updated_by=?,version=version+1,param_value=? WHERE id=? AND deleted=FALSE";if(keepMasked)jdbc.update(sql,group,name,defaultText(type,"STRING"),sensitive!=null&&sensitive,description,defaultText(status,"ACTIVE"),actor.userId(),id);else jdbc.update(sql,group,name,defaultText(type,"STRING"),sensitive!=null&&sensitive,description,defaultText(status,"ACTIVE"),actor.userId(),value,id);audit(actor,"SYSTEM","SYS_PARAMETER",id,"UPDATE",ip,"修改系统参数");}

    public List<Map<String,Object>> loginLogs(){return jdbc.queryForList("SELECT id,user_id,username,login_at,host(login_ip) login_ip,user_agent,result,failure_reason,request_id FROM sys_login_log ORDER BY login_at DESC LIMIT 200");}
    public List<Map<String,Object>> operationLogs(){return jdbc.queryForList("SELECT id,operator_id,operator_name,module_code,object_type,object_id,operation,reason,host(source_ip) source_ip,request_id,result,error_message,occurred_at FROM sys_operation_log ORDER BY occurred_at DESC LIMIT 200");}

    private int count(String sql,Object arg){Integer n=jdbc.queryForObject(sql,Integer.class,arg);return n==null?0:n;}
    private int count2(String sql,Object a,Object b){Integer n=jdbc.queryForObject(sql,Integer.class,a,b);return n==null?0:n;}
    private boolean containsRoleCode(List<Long> roleIds,String code){if(roleIds==null||roleIds.isEmpty())return false;for(Long id:roleIds){String c=jdbc.query("SELECT role_code FROM sys_role WHERE id=? AND deleted=FALSE",ps->ps.setLong(1,id),rs->rs.next()?rs.getString(1):null);if(code.equals(c))return true;}return false;}
    private void protectBuiltInRole(Long roleId){String code=jdbc.query("SELECT role_code FROM sys_role WHERE id=? AND deleted=FALSE",ps->ps.setLong(1,roleId),rs->rs.next()?rs.getString(1):null);if("SUPER_ADMIN".equals(code))throw new BusinessException("SYSTEM_BUILTIN_ROLE_PROTECTED","超级管理员为系统内置角色，不允许修改或重新授权");}
    private void ensurePassword(String password){if(password==null||password.length()<6)throw new BusinessException("SYSTEM_PASSWORD_TOO_SHORT","密码至少6位");}
    private String defaultText(String value,String fallback){return value==null||value.isBlank()?fallback:value;}
    private void audit(UserPrincipal actor,String module,String objectType,Object objectId,String operation,String ip,String reason){jdbc.update("INSERT INTO sys_operation_log(operator_id,operator_name,module_code,object_type,object_id,operation,reason,source_ip,request_id,result) VALUES(?,?,?,?,?,?,?,CAST(NULLIF(?,'') AS inet),?,'SUCCESS')",actor.userId(),actor.displayName(),module,objectType,String.valueOf(objectId),operation,reason,ip,MDC.get("requestId"));}
}
