package com.ipproxy.platform.product;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.ipproxy.platform.common.api.PageResult;
import com.ipproxy.platform.common.exception.BusinessException;
import com.ipproxy.platform.product.mapper.ProductMapper;
import com.ipproxy.platform.security.UserPrincipal;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.util.*;

@Service
public class ProductService {
    private static final Set<String> TYPES=Set.of("SHORT_IP","LONG_IP","EXCLUSIVE_IP","VPN","TUNNEL");
    private static final Set<String> DISPATCH=Set.of("PRIORITY","ROUND_ROBIN","RANDOM","WEIGHTED_RANDOM","QUALITY_FIRST","LATENCY_FIRST");
    private static final Set<String> SCOPES=Set.of("CENTOS","ROS","LINE","IP","NODE_TAG");
    private final ProductMapper db; private final ObjectMapper json;
    public ProductService(ProductMapper db,ObjectMapper json){this.db=db;this.json=json;}

    public record ProductInput(String productCode,String productName,String productType,String accessModeCode,List<String> protocolCodes,List<String> authModeCodes,String resourceMode,List<String> regionCodes,List<String> carrierCodes,String description,Map<String,Object> typeConfig){}
    public record PackageInput(String packageCode,Long productId,String packageName,Integer serviceDays,Integer ipCount,Long extractQuota,Long trafficQuotaBytes,Integer concurrencyLimit,Integer deviceLimit,Integer whitelistLimit,Integer changeIpLimit,BigDecimal price,String currency,Map<String,Object> quotaConfig){}
    public record PoolBinding(Long poolId,Integer priority,Integer weight,Boolean enabled){}
    public record ScopeInput(String scopeType,Long resourceId,String scopeCode,Boolean includeFlag,Integer priority){}
    public record StrategyInput(String strategyCode,String strategyName,Long productId,String dispatchMode,List<String> sourcePriority,List<String> regionCodes,List<String> carrierCodes,List<PoolBinding> poolBindings,List<ScopeInput> scopes,Map<String,Object> failoverRule,Map<String,Object> ipHoldRule,Map<String,Object> switchRule){}

    public Map<String,Object> overview(){return db.overview();}
    public PageResult<Map<String,Object>> products(int page,int size,String keyword,String status,String type){page=Math.max(1,page);size=Math.min(500,Math.max(1,size));keyword=n(keyword);status=n(status);type=n(type);return new PageResult<>(page,size,db.countProducts(keyword,status,type),normalize(db.listProducts(keyword,status,type,size,(page-1)*size)));}
    public Map<String,Object> product(Long id){Map<String,Object> p=mustProduct(id);p.put("type_config",config(id));return p;}
    public Map<String,Object> config(Long id){Map<String,Object> p=mustProduct(id);String t=s(p.get("product_type"));Map<String,Object> c=switch(t){case "SHORT_IP"->db.getShortConfig(id);case "LONG_IP"->db.getLongConfig(id);case "EXCLUSIVE_IP"->db.getExclusiveConfig(id);case "VPN"->db.getVpnConfig(id);case "TUNNEL"->db.getTunnelConfig(id);default->null;};return c==null?null:normalize(c);}

    @Transactional public Long createProduct(ProductInput in,UserPrincipal actor,String ip){validateProduct(in,false,null);if(db.productCodeExists(in.productCode()))throw err("PRODUCT_CODE_EXISTS","产品编号已存在");String mode=resolvedMode(in.productType(),in.resourceMode());Long id=db.insertProduct(in.productCode().trim(),in.productName().trim(),in.productType(),in.accessModeCode().trim(),j(list(in.protocolCodes())),j(list(in.authModeCodes())),mode,j(list(in.regionCodes())),j(list(in.carrierCodes())),n(in.description()),actor.userId());if(in.typeConfig()!=null&&!in.typeConfig().isEmpty())saveConfig(id,in.productType(),in.typeConfig());audit(actor,"PRODUCT",id,"CREATE","新增产品",ip);return id;}
    @Transactional public void updateProduct(Long id,ProductInput in,UserPrincipal actor,String ip){Map<String,Object> old=mustProduct(id);validateProduct(in,true,old);String mode=resolvedMode(in.productType(),in.resourceMode());db.updateProduct(id,in.productName().trim(),in.accessModeCode().trim(),j(list(in.protocolCodes())),j(list(in.authModeCodes())),mode,j(list(in.regionCodes())),j(list(in.carrierCodes())),n(in.description()),actor.userId());if(in.typeConfig()!=null&&!in.typeConfig().isEmpty())saveConfig(id,in.productType(),in.typeConfig());audit(actor,"PRODUCT",id,"UPDATE","修改产品配置",ip);}
    @Transactional public void updateConfig(Long id,Map<String,Object> cfg,UserPrincipal actor,String ip){Map<String,Object> p=mustProduct(id);if(cfg==null)cfg=Map.of();saveConfig(id,s(p.get("product_type")),cfg);audit(actor,"PRODUCT",id,"UPDATE_CONFIG","修改产品专项配置",ip);}
    @Transactional public Long copyProduct(Long id,String reason,UserPrincipal actor,String ip){Map<String,Object> p=mustProduct(id);String code=copyCode(s(p.get("product_code")));Long nid=db.insertProduct(code,s(p.get("product_name"))+"-副本",s(p.get("product_type")),s(p.get("access_mode_code")),j(asList(p.get("protocol_codes"))),j(asList(p.get("auth_mode_codes"))),s(p.get("resource_mode")),j(asList(p.get("region_codes"))),j(asList(p.get("carrier_codes"))),s(p.get("description")),actor.userId());Map<String,Object> cfg=config(id);if(cfg!=null)saveConfig(nid,s(p.get("product_type")),cfg);audit(actor,"PRODUCT",nid,"COPY",n(reason).isBlank()?"复制产品，仅复制产品及专项配置":reason,ip);return nid;}
    @Transactional public void enableProduct(Long id,String reason,UserPrincipal actor,String ip){Map<String,Object> p=mustProduct(id);if(config(id)==null)throw err("PRODUCT_CONFIG_REQUIRED","产品专项配置未完成");List<Long> ids=db.activeStrategyIds(id);if(ids.isEmpty())throw err("PRODUCT_STRATEGY_REQUIRED","产品至少需要一条已启用的资源策略");boolean valid=ids.stream().anyMatch(x->Boolean.TRUE.equals(validateStrategy(x,false,null,null).get("valid")));if(!valid)throw err("PRODUCT_STRATEGY_INVALID","已启用资源策略当前均不可用，请先检查资源池和策略验证结果");db.updateProductStatus(id,"ACTIVE",actor.userId());audit(actor,"PRODUCT",id,"ENABLE",requiredReason(reason),ip);}
    @Transactional public void disableProduct(Long id,String reason,UserPrincipal actor,String ip){mustProduct(id);db.updateProductStatus(id,"DISABLED",actor.userId());audit(actor,"PRODUCT",id,"DISABLE",requiredReason(reason),ip);}

    public PageResult<Map<String,Object>> packages(int page,int size,String keyword,String status,Long productId){page=Math.max(1,page);size=Math.min(500,Math.max(1,size));keyword=n(keyword);status=n(status);long pid=productId==null?0:productId;return new PageResult<>(page,size,db.countPackages(keyword,status,pid),normalize(db.listPackages(keyword,status,pid,size,(page-1)*size)));}
    public Map<String,Object> pkg(Long id){Map<String,Object> x=db.getPackage(id);if(x==null)throw err("PACKAGE_NOT_FOUND","套餐不存在");return normalize(x);}
    @Transactional public Long createPackage(PackageInput in,UserPrincipal actor,String ip){validatePackage(in,false,null);if(db.packageCodeExists(in.packageCode()))throw err("PACKAGE_CODE_EXISTS","套餐编号已存在");Long id=db.insertPackage(in.packageCode().trim(),in.productId(),in.packageName().trim(),in.serviceDays(),in.ipCount(),in.extractQuota(),in.trafficQuotaBytes(),in.concurrencyLimit(),in.deviceLimit(),in.whitelistLimit(),in.changeIpLimit(),price(in.price()),currency(in.currency()),j(map(in.quotaConfig())),"ACTIVE",actor.userId());audit(actor,"PACKAGE",id,"CREATE","新增套餐",ip);return id;}
    @Transactional public void updatePackage(Long id,PackageInput in,UserPrincipal actor,String ip){Map<String,Object> old=pkg(id);validatePackage(in,true,old);db.updatePackage(id,in.packageName().trim(),in.serviceDays(),in.ipCount(),in.extractQuota(),in.trafficQuotaBytes(),in.concurrencyLimit(),in.deviceLimit(),in.whitelistLimit(),in.changeIpLimit(),price(in.price()),currency(in.currency()),j(map(in.quotaConfig())),actor.userId());audit(actor,"PACKAGE",id,"UPDATE","修改套餐",ip);}
    @Transactional public Long copyPackage(Long id,String reason,UserPrincipal actor,String ip){Map<String,Object> x=pkg(id);Long nid=db.insertPackage(copyCode(s(x.get("package_code"))),s(x.get("product_id")).isBlank()?null:Long.valueOf(s(x.get("product_id"))),s(x.get("package_name"))+"-副本",i(x,"service_days",1),intOrNull(x.get("ip_count")),longOrNull(x.get("extract_quota")),longOrNull(x.get("traffic_quota_bytes")),intOrNull(x.get("concurrency_limit")),intOrNull(x.get("device_limit")),intOrNull(x.get("whitelist_limit")),intOrNull(x.get("change_ip_limit")),new BigDecimal(s(x.get("price"))),currency(s(x.get("currency"))),j(asMap(x.get("quota_config"))),"DISABLED",actor.userId());audit(actor,"PACKAGE",nid,"COPY",n(reason).isBlank()?"复制套餐，副本默认停用":reason,ip);return nid;}
    @Transactional public void packageStatus(Long id,String status,String reason,UserPrincipal actor,String ip){pkg(id);db.updatePackageStatus(id,status,actor.userId());audit(actor,"PACKAGE",id,status,requiredReason(reason),ip);}

    public PageResult<Map<String,Object>> strategies(int page,int size,String keyword,String status,Long productId){page=Math.max(1,page);size=Math.min(500,Math.max(1,size));keyword=n(keyword);status=n(status);long pid=productId==null?0:productId;return new PageResult<>(page,size,db.countStrategies(keyword,status,pid),normalize(db.listStrategies(keyword,status,pid,size,(page-1)*size)));}
    public Map<String,Object> strategy(Long id){Map<String,Object> x=db.getStrategy(id);if(x==null)throw err("STRATEGY_NOT_FOUND","资源策略不存在");x=normalize(x);x.put("pool_bindings",normalize(db.strategyPools(id)));x.put("scopes",db.strategyScopes(id));return x;}
    @Transactional public Long createStrategy(StrategyInput in,UserPrincipal actor,String ip){validateStrategyInput(in,false,null);if(db.strategyCodeExists(in.strategyCode()))throw err("STRATEGY_CODE_EXISTS","策略编号已存在");Long id=db.insertStrategy(in.strategyCode().trim(),in.strategyName().trim(),in.productId(),in.dispatchMode(),j(list(in.sourcePriority())),j(list(in.regionCodes())),j(list(in.carrierCodes())),j(map(in.failoverRule())),j(map(in.ipHoldRule())),j(map(in.switchRule())),actor.userId());replaceBindings(id,in);audit(actor,"STRATEGY",id,"CREATE","新增资源策略，默认停用",ip);return id;}
    @Transactional public void updateStrategy(Long id,StrategyInput in,UserPrincipal actor,String ip){Map<String,Object> old=strategy(id);validateStrategyInput(in,true,old);db.updateStrategy(id,in.strategyName().trim(),in.dispatchMode(),j(list(in.sourcePriority())),j(list(in.regionCodes())),j(list(in.carrierCodes())),j(map(in.failoverRule())),j(map(in.ipHoldRule())),j(map(in.switchRule())),actor.userId());replaceBindings(id,in);if("ACTIVE".equals(s(old.get("status"))))db.updateStrategyStatus(id,"DISABLED",actor.userId());audit(actor,"STRATEGY",id,"UPDATE","修改资源策略；已启用策略修改后自动停用，需重新验证",ip);}
    public Map<String,Object> validateStrategy(Long id,boolean audit,String reason,UserPrincipal actor){return validateStrategy(id,audit,reason,actor,null);}
    public Map<String,Object> validateStrategy(Long id,boolean doAudit,String reason,UserPrincipal actor,String ip){Map<String,Object> st=strategy(id);List<String> errors=new ArrayList<>(),warnings=new ArrayList<>();List<Map<String,Object>> pools=(List<Map<String,Object>>)st.get("pool_bindings");int usable=0;long members=0;for(Map<String,Object> p:pools){if(!bool(p.get("enabled"),true))continue;if(!"ACTIVE".equals(s(p.get("status")))){errors.add("资源池 "+s(p.get("pool_name"))+" 未启用");continue;}long c=longVal(p.get("member_count"),0);if(c<=0){errors.add("资源池 "+s(p.get("pool_name"))+" 当前无可用成员");continue;}usable++;members+=c;}if(pools.isEmpty())errors.add("未绑定资源池");if(usable==0)errors.add("没有可用于调度的资源池");List<Map<String,Object>> scopes=(List<Map<String,Object>>)st.get("scopes");for(Map<String,Object> sc:scopes){String t=s(sc.get("scope_type"));Long rid=longOrNull(sc.get("resource_id"));String code=s(sc.get("scope_code"));if("NODE_TAG".equals(t)){if(code.isBlank())errors.add("NODE_TAG范围必须填写scopeCode");}else if(rid!=null&&!db.scopeResourceExists(t,rid))errors.add("范围资源不存在: "+t+"#"+rid);}if(asList(st.get("source_priority")).isEmpty())warnings.add("未设置自有/外部资源来源优先级，将完全依赖资源池排序");Map<String,Object> result=new LinkedHashMap<>();result.put("valid",errors.isEmpty());result.put("errors",errors);result.put("warnings",warnings);result.put("usablePoolCount",usable);result.put("memberCount",members);if(doAudit&&actor!=null)audit(actor,"STRATEGY",id,"VALIDATE",requiredReason(reason),ip);return result;}
    @Transactional public void enableStrategy(Long id,String reason,UserPrincipal actor,String ip){Map<String,Object> v=validateStrategy(id,false,null,null,null);if(!Boolean.TRUE.equals(v.get("valid")))throw err("STRATEGY_INVALID","策略验证未通过: "+String.join("；",(List<String>)v.get("errors")));db.updateStrategyStatus(id,"ACTIVE",actor.userId());audit(actor,"STRATEGY",id,"ENABLE",requiredReason(reason),ip);}
    @Transactional public void disableStrategy(Long id,String reason,UserPrincipal actor,String ip){strategy(id);db.updateStrategyStatus(id,"DISABLED",actor.userId());audit(actor,"STRATEGY",id,"DISABLE",requiredReason(reason),ip);}

    public Map<String,Object> options(){Map<String,Object> r=new LinkedHashMap<>();r.put("productTypes",List.of(Map.of("code","SHORT_IP","name","短效IP"),Map.of("code","LONG_IP","name","长效IP"),Map.of("code","EXCLUSIVE_IP","name","独享IP"),Map.of("code","VPN","name","VPN"),Map.of("code","TUNNEL","name","隧道")));r.put("accessModes",db.dictOptions("access_mode"));r.put("protocols",db.dictOptions("proxy_protocol"));r.put("authModes",db.dictOptions("auth_mode"));r.put("carriers",db.dictOptions("carrier"));r.put("regions",db.dictOptions("region"));r.put("vpnProtocols",db.dictOptions("vpn_protocol"));r.put("products",db.productOptions());r.put("pools",db.poolOptions());r.put("domains",db.domainOptions());r.put("dispatchModes",DISPATCH.stream().sorted().toList());return r;}

    private void validateProduct(ProductInput in,boolean update,Map<String,Object> old){if(in==null||n(in.productCode()).isBlank()||n(in.productName()).isBlank()||n(in.productType()).isBlank()||n(in.accessModeCode()).isBlank())throw err("PRODUCT_REQUIRED","产品编号、名称、类型、接入方式不能为空");if(!TYPES.contains(in.productType()))throw err("PRODUCT_TYPE_INVALID","未知产品类型");if(update){if(!s(old.get("product_code")).equals(in.productCode()))throw err("PRODUCT_CODE_IMMUTABLE","产品编号创建后不可修改");if(!s(old.get("product_type")).equals(in.productType()))throw err("PRODUCT_TYPE_IMMUTABLE","产品类型创建后不可修改");}}
    private void validatePackage(PackageInput in,boolean update,Map<String,Object> old){if(in==null||n(in.packageCode()).isBlank()||in.productId()==null||n(in.packageName()).isBlank()||in.serviceDays()==null||in.serviceDays()<=0)throw err("PACKAGE_REQUIRED","套餐编号、所属产品、名称、有效天数不能为空");mustProduct(in.productId());if(price(in.price()).signum()<0)throw err("PACKAGE_PRICE_INVALID","套餐价格不能小于0");if(update){if(!s(old.get("package_code")).equals(in.packageCode()))throw err("PACKAGE_CODE_IMMUTABLE","套餐编号创建后不可修改");if(!Objects.equals(longOrNull(old.get("product_id")),in.productId()))throw err("PACKAGE_PRODUCT_IMMUTABLE","套餐创建后不可更换所属产品");}}
    private void validateStrategyInput(StrategyInput in,boolean update,Map<String,Object> old){if(in==null||n(in.strategyCode()).isBlank()||n(in.strategyName()).isBlank()||in.productId()==null||!DISPATCH.contains(n(in.dispatchMode())))throw err("STRATEGY_REQUIRED","策略编号、名称、所属产品和合法调度模式不能为空");mustProduct(in.productId());if(in.poolBindings()==null||in.poolBindings().isEmpty())throw err("STRATEGY_POOL_REQUIRED","资源策略至少绑定一个资源池");for(PoolBinding b:in.poolBindings()){if(b.poolId()==null||!db.poolExists(b.poolId()))throw err("STRATEGY_POOL_INVALID","绑定的资源池不存在");}if(in.scopes()!=null)for(ScopeInput s:in.scopes())if(!SCOPES.contains(n(s.scopeType())))throw err("STRATEGY_SCOPE_INVALID","不支持的范围类型: "+s.scopeType());if(update){if(!s(old.get("strategy_code")).equals(in.strategyCode()))throw err("STRATEGY_CODE_IMMUTABLE","策略编号创建后不可修改");if(!Objects.equals(longOrNull(old.get("product_id")),in.productId()))throw err("STRATEGY_PRODUCT_IMMUTABLE","策略创建后不可更换所属产品");}}
    private void replaceBindings(Long id,StrategyInput in){db.deleteStrategyPools(id);for(PoolBinding b:in.poolBindings())db.insertStrategyPool(id,b.poolId(),b.priority()==null?100:b.priority(),b.weight()==null?100:b.weight(),b.enabled()==null||b.enabled());db.deleteStrategyScopes(id);if(in.scopes()!=null)for(ScopeInput s:in.scopes())db.insertStrategyScope(id,s.scopeType(),s.resourceId(),n(s.scopeCode()).isBlank()?null:s.scopeCode(),s.includeFlag()==null||s.includeFlag(),s.priority()==null?100:s.priority());}
    private void saveConfig(Long id,String type,Map<String,Object> c){switch(type){case "SHORT_IP"->{int valid=intReq(c,"ipValidSeconds","ip_valid_seconds");int single=intReq(c,"singleExtractLimit","single_extract_limit");db.upsertShort(id,valid,single,intOpt(c,"extractRateLimit","extract_rate_limit"),intOpt(c,"extractRateWindowSeconds","extract_rate_window_seconds"),intOpt(c,"dedupPeriodSeconds","dedup_period_seconds"),j(mapVal(c,"switchPolicy","switch_policy")),boolVal(c,true,"whitelistRequired","whitelist_required"));}case "LONG_IP"->{String bind=strReq(c,"bindType","bind_type");if(!Set.of("IP","LINE").contains(bind))throw err("PRODUCT_CONFIG_INVALID","长效IP绑定类型只能为IP或LINE");db.upsertLong(id,longOpt(c,"holdPeriodSeconds","hold_period_seconds"),bind,boolVal(c,true,"autoReplace","auto_replace"),intDefault(c,3,"failureThreshold","failure_threshold"),j(mapVal(c,"failoverPolicy","failover_policy")));}case "EXCLUSIVE_IP"->{String rt=strReq(c,"exclusiveResourceType","exclusive_resource_type");if(!Set.of("IP","LINE").contains(rt))throw err("PRODUCT_CONFIG_INVALID","独享资源类型只能为IP或LINE");db.upsertExclusive(id,rt,intDefault(c,1,"resourceCountDefault","resource_count_default"),intDefault(c,300,"lockTimeoutSeconds","lock_timeout_seconds"),j(mapVal(c,"replacementRule","replacement_rule")),j(mapVal(c,"releaseRule","release_rule")));}case "VPN"->{db.upsertVpn(id,strReq(c,"vpnProtocolCode","vpn_protocol_code"),strReq(c,"credentialTypeCode","credential_type_code"),intOpt(c,"defaultDeviceLimit","default_device_limit"),intOpt(c,"defaultConnectionLimit","default_connection_limit"),j(mapVal(c,"outboundPolicy","outbound_policy")));}case "TUNNEL"->{Long did=longOpt(c,"entryDomainId","entry_domain_id");String host=str(c,"entryHost","entry_host");if(did==null&&host.isBlank())throw err("PRODUCT_CONFIG_INVALID","隧道入口域名或入口主机至少填写一个");if(did!=null&&!db.domainExists(did))throw err("PRODUCT_CONFIG_INVALID","隧道入口域名不存在");int port=intReq(c,"entryPort","entry_port");if(port<1||port>65535)throw err("PRODUCT_CONFIG_INVALID","隧道端口范围应为1-65535");db.upsertTunnel(id,did,host.isBlank()?null:host,port,intOpt(c,"sessionHoldSeconds","session_hold_seconds"),intOpt(c,"concurrencyLimit","concurrency_limit"),j(mapVal(c,"ipSwitchPolicy","ip_switch_policy")));}default->throw err("PRODUCT_TYPE_INVALID","未知产品类型");}}
    private Map<String,Object> mustProduct(Long id){Map<String,Object> p=db.getProduct(id);if(p==null)throw err("PRODUCT_NOT_FOUND","产品不存在");return normalize(p);}
    private String resolvedMode(String type,String mode){return "EXCLUSIVE_IP".equals(type)?"EXCLUSIVE":(n(mode).isBlank()?"SHARED":mode);}
    private String copyCode(String source){String suffix="-COPY-"+Long.toString(System.currentTimeMillis(),36).toUpperCase();String base=source.length()+suffix.length()>64?source.substring(0,64-suffix.length()):source;return base+suffix;}
    private void audit(UserPrincipal a,String objectType,Object id,String op,String reason,String ip){db.insertAudit(a.userId(),n(a.displayName()).isBlank()?a.username():a.displayName(),objectType,String.valueOf(id),op,n(reason),n(ip),UUID.randomUUID().toString());}
    private String requiredReason(String r){if(n(r).isBlank())throw err("REASON_REQUIRED","必须填写操作原因");return r.trim();}
    private BusinessException err(String code,String msg){return new BusinessException(code,msg);}
    private String j(Object v){try{return json.writeValueAsString(v==null?Map.of():v);}catch(Exception e){throw err("JSON_INVALID","配置JSON无法序列化");}}
    private Map<String,Object> normalize(Map<String,Object> m){if(m==null)return null;Map<String,Object> r=new LinkedHashMap<>(m);for(String k:new ArrayList<>(r.keySet()))if(k.endsWith("_json")){Object v=parse(s(r.remove(k)));r.put(k.substring(0,k.length()-5),v);}return r;}
    private List<Map<String,Object>> normalize(List<Map<String,Object>> list){return list.stream().map(this::normalize).toList();}
    private Object parse(String s){if(s.isBlank())return null;try{return json.readValue(s,Object.class);}catch(Exception e){return s;}}
    private List<String> list(List<String> x){return x==null?List.of():x;}
    private Map<String,Object> map(Map<String,Object> x){return x==null?Map.of():x;}
    private List<String> asList(Object x){if(x instanceof List<?> l)return l.stream().map(String::valueOf).toList();return List.of();}
    private Map<String,Object> asMap(Object x){return x instanceof Map<?,?> m?(Map<String,Object>)m:Map.of();}
    private Object val(Map<String,Object> c,String...keys){for(String k:keys)if(c.containsKey(k)&&c.get(k)!=null)return c.get(k);return null;}
    private String str(Map<String,Object> c,String...keys){return s(val(c,keys));}
    private String strReq(Map<String,Object> c,String...keys){String x=str(c,keys);if(x.isBlank())throw err("PRODUCT_CONFIG_REQUIRED","产品专项配置缺少字段: "+keys[0]);return x;}
    private Integer intOpt(Map<String,Object> c,String...keys){Object v=val(c,keys);return v==null?null:Integer.valueOf(String.valueOf(v));}
    private int intReq(Map<String,Object> c,String...keys){Integer v=intOpt(c,keys);if(v==null||v<=0)throw err("PRODUCT_CONFIG_REQUIRED","产品专项配置字段必须大于0: "+keys[0]);return v;}
    private int intDefault(Map<String,Object> c,int d,String...keys){Integer v=intOpt(c,keys);return v==null?d:v;}
    private Long longOpt(Map<String,Object> c,String...keys){Object v=val(c,keys);return v==null?null:Long.valueOf(String.valueOf(v));}
    private boolean boolVal(Map<String,Object> c,boolean d,String...keys){Object v=val(c,keys);return v==null?d:Boolean.parseBoolean(String.valueOf(v));}
    private Map<String,Object> mapVal(Map<String,Object> c,String...keys){Object v=val(c,keys);return v instanceof Map<?,?> m?(Map<String,Object>)m:Map.of();}
    private String n(String x){return x==null?"":x.trim();} private String s(Object x){return x==null?"":String.valueOf(x);} private int i(Map<String,Object> m,String k,int d){Object x=m.get(k);return x==null?d:Integer.parseInt(s(x));}
    private Integer intOrNull(Object x){return x==null?null:Integer.valueOf(s(x));} private Long longOrNull(Object x){return x==null?null:Long.valueOf(s(x));} private long longVal(Object x,long d){return x==null?d:Long.parseLong(s(x));}
    private boolean bool(Object x,boolean d){return x==null?d:Boolean.parseBoolean(s(x));} private BigDecimal price(BigDecimal x){return x==null?BigDecimal.ZERO:x;} private String currency(String x){return n(x).isBlank()?"CNY":x.trim().toUpperCase(Locale.ROOT);}
}
