<script setup lang="ts">
import{computed,onMounted,reactive,ref,watch}from'vue'
import{ElMessage,ElMessageBox}from'element-plus'
import{alarmApi}from'@/api/runtimeOps'
import{useAuthStore}from'@/stores/auth'
const auth=useAuthStore(),active=ref('events'),loading=ref(false),rows=ref<any[]>([]),total=ref(0),page=ref(1),size=ref(20),keyword=ref(''),status=ref(''),severity=ref(''),channel=ref(''),result=ref(''),drawer=ref(false),detail=ref<any>(),ruleDialog=ref(false),editingId=ref<number>(),saving=ref(false)
const form=reactive<any>({ruleCode:'',ruleName:'',objectType:'LINE',metricCode:'LATENCY_MS',operator:'GT',threshold:100,durationSeconds:0,consecutiveCount:1,severity:'MAJOR',notificationChannels:['PLATFORM'],notifyRecovery:true,repeatIntervalSeconds:300})
const metricOptions:any={CENTOS:['CPU_USAGE','MEMORY_USAGE','DISK_USAGE','STATUS_VALUE'],ROS:['LINE_ABNORMAL','STATUS_VALUE'],LINE:['LATENCY_MS','AVAILABILITY_RATE','ACTIVE_PROBE_LATENCY_MS','STATUS_VALUE'],IP:['LATENCY_MS','QUALITY_SCORE','STATUS_VALUE'],POOL:['IP_AVAILABLE','IP_AVAILABLE_RATE','STATUS_VALUE'],SUPPLIER:['INTERFACE_UP','STATUS_VALUE'],SERVICE:['API_FAILURE_RATE','API_FAILURES_5M','SERVICE_ACTIVE','STATUS_VALUE']}
const metrics=computed(()=>metricOptions[form.objectType]||[])
function fmt(v:any){return v?new Date(v).toLocaleString():'-'}
function sevType(v:string){return v==='CRITICAL'?'danger':v==='MAJOR'?'warning':v==='MINOR'?'primary':'info'}
function statusType(v:string){return v==='OPEN'?'danger':v==='ACKNOWLEDGED'?'warning':v==='PROCESSING'?'primary':v==='RECOVERED'?'success':'info'}
async function load(){loading.value=true;try{let r:any;if(active.value==='events')r=await alarmApi.list({page:page.value,size:size.value,keyword:keyword.value,status:status.value,severity:severity.value});else if(active.value==='rules')r=await alarmApi.rules({page:page.value,size:size.value,keyword:keyword.value});else r=await alarmApi.notifications({page:page.value,size:size.value,channel:channel.value,result:result.value});rows.value=r.data.data.items;total.value=r.data.data.total}finally{loading.value=false}}
function search(){page.value=1;load()}
watch(active,()=>{page.value=1;rows.value=[];load()});onMounted(load)
async function openDetail(r:any){detail.value=(await alarmApi.detail(r.id)).data.data;drawer.value=true}
async function action(kind:string){if(!detail.value)return;const {value}=await ElMessageBox.prompt('请输入处理备注','告警处理',{inputPlaceholder:'说明本次处理情况',inputType:'textarea'});if(kind==='ack')await alarmApi.acknowledge(detail.value.id,value);if(kind==='process')await alarmApi.process(detail.value.id,value);if(kind==='close')await alarmApi.close(detail.value.id,value);if(kind==='note')await alarmApi.note(detail.value.id,value);ElMessage.success('操作成功');detail.value=(await alarmApi.detail(detail.value.id)).data.data;load()}
function openCreate(){editingId.value=undefined;Object.assign(form,{ruleCode:'',ruleName:'',objectType:'LINE',metricCode:'LATENCY_MS',operator:'GT',threshold:100,durationSeconds:0,consecutiveCount:1,severity:'MAJOR',notificationChannels:['PLATFORM'],notifyRecovery:true,repeatIntervalSeconds:300});ruleDialog.value=true}
function openEdit(r:any){editingId.value=r.id;Object.assign(form,{ruleCode:r.rule_code,ruleName:r.rule_name,objectType:r.object_type,metricCode:r.metric_code,operator:r.operator,threshold:r.threshold,durationSeconds:r.duration_seconds,consecutiveCount:r.consecutive_count,severity:r.severity,notificationChannels:r.notification_channels||['PLATFORM'],notifyRecovery:r.notify_recovery,repeatIntervalSeconds:r.repeat_interval_seconds});ruleDialog.value=true}
async function saveRule(){saving.value=true;try{const raw=String(form.threshold);const threshold=raw!==''&&!Number.isNaN(Number(raw))?Number(raw):raw;const data={...form,threshold};if(editingId.value)await alarmApi.updateRule(editingId.value,data);else await alarmApi.createRule(data);ElMessage.success('规则已保存');ruleDialog.value=false;load()}finally{saving.value=false}}
async function toggleRule(r:any){await alarmApi.ruleStatus(r.id,r.status==='ACTIVE'?'DISABLED':'ACTIVE');ElMessage.success('规则状态已更新');load()}
async function deleteRule(r:any){await ElMessageBox.confirm(`确认删除规则“${r.rule_name}”？历史告警不会删除。`,'确认');await alarmApi.deleteRule(r.id);ElMessage.success('规则已删除');load()}
</script>
<template><div class="page-stack"><el-card shadow="never"><div class="page-title"><div><h2>告警中心</h2><p>监控指标按规则判定后自动生成告警；同一规则和对象在恢复前自动合并，恢复后保留完整处理与通知记录。</p></div><el-button v-if="active==='rules'&&auth.hasPermission('alarm:rule:write')" type="primary" @click="openCreate">新增告警规则</el-button></div><el-tabs v-model="active"><el-tab-pane v-if="auth.hasPermission('alarm:read')" label="告警记录" name="events"/><el-tab-pane v-if="auth.hasPermission('alarm:rule:read')" label="告警规则" name="rules"/><el-tab-pane v-if="auth.hasPermission('alarm:notification:read')" label="通知记录" name="notifications"/></el-tabs><div class="filter-row"><el-input v-if="active!=='notifications'" v-model="keyword" clearable placeholder="告警号 / 对象 / 规则 / 指标" style="width:320px" @keyup.enter="search"/><template v-if="active==='events'"><el-select v-model="status" clearable placeholder="状态" style="width:150px"><el-option v-for="x in ['OPEN','ACKNOWLEDGED','PROCESSING','RECOVERED','CLOSED']" :key="x" :label="x" :value="x"/></el-select><el-select v-model="severity" clearable placeholder="级别" style="width:130px"><el-option v-for="x in ['INFO','MINOR','MAJOR','CRITICAL']" :key="x" :label="x" :value="x"/></el-select></template><template v-if="active==='notifications'"><el-select v-model="channel" clearable placeholder="通知通道" style="width:150px"><el-option v-for="x in ['PLATFORM','DINGTALK','WEBHOOK']" :key="x" :label="x" :value="x"/></el-select><el-select v-model="result" clearable placeholder="发送结果" style="width:130px"><el-option v-for="x in ['PENDING','SUCCESS','FAILURE']" :key="x" :label="x" :value="x"/></el-select></template><el-button type="primary" @click="search">查询</el-button><el-button @click="keyword='';status='';severity='';channel='';result='';search()">重置</el-button></div></el-card>
<el-card shadow="never"><el-table :data="rows" v-loading="loading" border stripe>
<template v-if="active==='events'"><el-table-column prop="alarm_no" label="告警号" min-width="180"/><el-table-column prop="rule_name" label="规则" min-width="170"/><el-table-column prop="object_name" label="对象" min-width="160"/><el-table-column prop="metric_code" label="指标" min-width="150"/><el-table-column label="级别" width="100"><template #default="s"><el-tag :type="sevType(s.row.severity)">{{s.row.severity}}</el-tag></template></el-table-column><el-table-column label="状态" width="130"><template #default="s"><el-tag :type="statusType(s.row.status)">{{s.row.status}}</el-tag></template></el-table-column><el-table-column prop="occurrence_count" label="触发次数" width="90"/><el-table-column label="首次触发" min-width="170"><template #default="s">{{fmt(s.row.first_triggered_at)}}</template></el-table-column><el-table-column label="最近触发" min-width="170"><template #default="s">{{fmt(s.row.last_triggered_at)}}</template></el-table-column><el-table-column label="操作" width="90" fixed="right"><template #default="s"><el-button link type="primary" @click="openDetail(s.row)">详情</el-button></template></el-table-column></template>
<template v-else-if="active==='rules'"><el-table-column prop="rule_code" label="规则编码" min-width="150"/><el-table-column prop="rule_name" label="规则名称" min-width="180"/><el-table-column prop="object_type" label="对象类型" width="110"/><el-table-column prop="metric_code" label="指标" min-width="160"/><el-table-column label="条件" min-width="150"><template #default="s">{{s.row.operator}} {{s.row.threshold}}</template></el-table-column><el-table-column prop="consecutive_count" label="连续次数" width="90"/><el-table-column prop="duration_seconds" label="持续秒" width="90"/><el-table-column prop="severity" label="级别" width="100"/><el-table-column prop="status" label="状态" width="100"/><el-table-column label="通知" min-width="160"><template #default="s">{{(s.row.notification_channels||[]).join(' / ')}}</template></el-table-column><el-table-column label="操作" width="210" fixed="right"><template #default="s"><el-button link type="primary" @click="openEdit(s.row)">编辑</el-button><el-button link @click="toggleRule(s.row)">{{s.row.status==='ACTIVE'?'停用':'启用'}}</el-button><el-button link type="danger" @click="deleteRule(s.row)">删除</el-button></template></el-table-column></template>
<template v-else><el-table-column prop="alarm_no" label="告警号" min-width="180"/><el-table-column prop="object_name" label="对象" min-width="160"/><el-table-column prop="severity" label="级别" width="100"/><el-table-column prop="channel" label="通道" width="110"/><el-table-column prop="target" label="目标" min-width="180"/><el-table-column prop="result" label="结果" width="100"/><el-table-column prop="retry_count" label="重试" width="70"/><el-table-column prop="error_message" label="错误信息" min-width="220"/><el-table-column label="发送时间" min-width="170"><template #default="s">{{fmt(s.row.sent_at||s.row.created_at)}}</template></el-table-column></template>
</el-table><div style="display:flex;justify-content:flex-end;margin-top:16px"><el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" :page-sizes="[20,50,100]" layout="total,sizes,prev,pager,next" @change="load"/></div></el-card>
<el-drawer v-model="drawer" size="65%" :title="detail?.alarm_no"><template v-if="detail"><el-descriptions :column="2" border><el-descriptions-item label="对象">{{detail.object_name}}</el-descriptions-item><el-descriptions-item label="规则">{{detail.rule_name}}</el-descriptions-item><el-descriptions-item label="指标">{{detail.metric_code}}</el-descriptions-item><el-descriptions-item label="级别">{{detail.severity}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.status}}</el-descriptions-item><el-descriptions-item label="触发次数">{{detail.occurrence_count}}</el-descriptions-item><el-descriptions-item label="当前值">{{detail.current_value}}</el-descriptions-item><el-descriptions-item label="阈值">{{detail.threshold}}</el-descriptions-item></el-descriptions><div v-if="auth.hasPermission('alarm:handle')" style="margin:16px 0"><el-button v-if="detail.status==='OPEN'" type="primary" @click="action('ack')">确认告警</el-button><el-button v-if="['OPEN','ACKNOWLEDGED'].includes(detail.status)" @click="action('process')">开始处理</el-button><el-button v-if="detail.status!=='CLOSED'" @click="action('note')">添加备注</el-button><el-button v-if="detail.status!=='CLOSED'" type="success" @click="action('close')">关闭告警</el-button></div><h3>处理记录</h3><el-table :data="detail.processes" border size="small"><el-table-column prop="action" label="动作" width="130"/><el-table-column prop="before_status" label="之前" width="120"/><el-table-column prop="after_status" label="之后" width="120"/><el-table-column prop="operator_name" label="操作人" width="120"/><el-table-column prop="remark" label="备注" min-width="220"/><el-table-column label="时间" width="180"><template #default="s">{{fmt(s.row.occurred_at)}}</template></el-table-column></el-table><h3 style="margin-top:20px">通知记录</h3><el-table :data="detail.notifications" border size="small"><el-table-column prop="channel" label="通道" width="110"/><el-table-column prop="result" label="结果" width="100"/><el-table-column prop="target" label="目标" min-width="180"/><el-table-column prop="error_message" label="错误" min-width="200"/><el-table-column label="时间" width="180"><template #default="s">{{fmt(s.row.sent_at||s.row.created_at)}}</template></el-table-column></el-table></template></el-drawer>
<el-dialog v-model="ruleDialog" :title="editingId?'编辑告警规则':'新增告警规则'" width="720px"><el-form label-width="110px"><el-row :gutter="16"><el-col :span="12"><el-form-item label="规则编码"><el-input v-model="form.ruleCode" :disabled="!!editingId"/></el-form-item></el-col><el-col :span="12"><el-form-item label="规则名称"><el-input v-model="form.ruleName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="对象类型"><el-select v-model="form.objectType" style="width:100%" @change="form.metricCode=(metricOptions[form.objectType]||[])[0]"><el-option v-for="x in ['CENTOS','ROS','LINE','IP','POOL','SUPPLIER','SERVICE']" :key="x" :label="x" :value="x"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="监控指标"><el-select v-model="form.metricCode" filterable allow-create style="width:100%"><el-option v-for="x in metrics" :key="x" :label="x" :value="x"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="运算符"><el-select v-model="form.operator" style="width:100%"><el-option v-for="x in ['GT','GTE','LT','LTE','EQ','NE','IN','NOT_IN']" :key="x" :label="x" :value="x"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="阈值"><el-input v-model="form.threshold"/></el-form-item></el-col><el-col :span="8"><el-form-item label="告警级别"><el-select v-model="form.severity" style="width:100%"><el-option v-for="x in ['INFO','MINOR','MAJOR','CRITICAL']" :key="x" :label="x" :value="x"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="连续次数"><el-input-number v-model="form.consecutiveCount" :min="1" :max="100"/></el-form-item></el-col><el-col :span="8"><el-form-item label="持续秒数"><el-input-number v-model="form.durationSeconds" :min="0"/></el-form-item></el-col><el-col :span="8"><el-form-item label="重复通知秒"><el-input-number v-model="form.repeatIntervalSeconds" :min="0"/></el-form-item></el-col><el-col :span="24"><el-form-item label="通知通道"><el-checkbox-group v-model="form.notificationChannels"><el-checkbox value="PLATFORM">站内记录</el-checkbox><el-checkbox value="DINGTALK">钉钉机器人</el-checkbox><el-checkbox value="WEBHOOK">Webhook</el-checkbox></el-checkbox-group></el-form-item></el-col><el-col :span="24"><el-form-item label="恢复通知"><el-switch v-model="form.notifyRecovery"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="ruleDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveRule">保存</el-button></template></el-dialog></div></template>
