<script setup lang="ts">
import{computed,nextTick,onBeforeUnmount,onMounted,ref,watch}from'vue'
import * as echarts from'echarts'
import{ElMessage}from'element-plus'
import{monitorApi}from'@/api/runtimeOps'
import{useAuthStore}from'@/stores/auth'
const auth=useAuthStore(),active=ref('CENTOS'),loading=ref(false),collecting=ref(false),rows=ref<any[]>([]),total=ref(0),page=ref(1),size=ref(20),keyword=ref(''),overview=ref<any>({types:{}}),drawer=ref(false),selected=ref<any>(null),history=ref<any[]>([]),hours=ref(24),chartEl=ref<HTMLElement>(),chart=ref<echarts.ECharts>()
const tabs=[['CENTOS','CentOS监控'],['ROS','ROS监控'],['LINE','线路监控'],['IP','IP资源监控'],['SUPPLIER','外部资源监控'],['SERVICE','服务运行监控']]
const summary=computed(()=>overview.value?.types?.[active.value]||{total:0,healthy:0,abnormal:0,unknown:0})
function fmt(v:any){return v?new Date(v).toLocaleString():'-'}
function statusType(v:string){return['NORMAL','ONLINE'].includes(v)?'success':v==='ABNORMAL'?'warning':v==='OFFLINE'?'danger':'info'}
function metricsText(r:any){const x=r.current_metrics;if(!x)return'-';if(typeof x==='string')return x;const value=x.value?x.value:x;try{return Object.entries(value).slice(0,5).map(([k,v])=>`${k}:${typeof v==='number'?Number(v).toFixed(1):v}`).join(' / ')}catch{return String(x)}}
async function load(){loading.value=true;try{const [o,r]=await Promise.all([monitorApi.overview(),monitorApi.objects({page:page.value,size:size.value,objectType:active.value,keyword:keyword.value})]);overview.value=o.data.data;rows.value=r.data.data.items;total.value=r.data.data.total}finally{loading.value=false}}
function search(){page.value=1;load()}
async function collect(){collecting.value=true;try{const r=await monitorApi.collect();ElMessage.success(`采集完成：${r.data.data.objectCount}个对象，${r.data.data.sampleCount}个指标`);await load()}finally{collecting.value=false}}
async function openMetrics(r:any){selected.value=r;drawer.value=true;await loadHistory()}
async function loadHistory(){if(!selected.value)return;const r=await monitorApi.metrics(selected.value.object_type,selected.value.object_id,{hours:hours.value});history.value=r.data.data||[];await nextTick();draw()}
function draw(){if(!chartEl.value)return;chart.value?.dispose();chart.value=echarts.init(chartEl.value);const numeric=history.value.filter(x=>x.metric_value!==null&&x.metric_value!==undefined);const codes=[...new Set(numeric.map(x=>x.metric_code))].slice(0,4);chart.value.setOption({tooltip:{trigger:'axis'},legend:{data:codes},grid:{left:55,right:20,top:50,bottom:45},xAxis:{type:'time'},yAxis:{type:'value'},series:codes.map(code=>({name:code,type:'line',showSymbol:false,data:numeric.filter(x=>x.metric_code===code).map(x=>[x.collected_at,Number(x.metric_value)])}))})}
watch(active,()=>{page.value=1;load()});watch(hours,loadHistory);onMounted(load);onBeforeUnmount(()=>chart.value?.dispose())
</script>
<template><div class="page-stack"><el-card shadow="never"><div class="page-title"><div><h2>监控中心</h2><p>统一展示资源与服务的最新状态；超过监控过期阈值后按 UNKNOWN 展示。主动探测指标通过 MonitorProbeAdapter 接入，正式环境不使用模拟数据。</p></div><el-button v-if="auth.hasPermission('monitor:collect')" type="primary" :loading="collecting" @click="collect">立即采集</el-button></div><el-tabs v-model="active"><el-tab-pane v-for="t in tabs" :key="t[0]" :label="t[1]" :name="t[0]"/></el-tabs><div class="metric-grid" style="margin-top:12px"><el-card shadow="never"><span>监控对象</span><strong>{{summary.total}}</strong><small>当前页签全部对象</small></el-card><el-card shadow="never"><span>健康</span><strong>{{summary.healthy}}</strong><small>NORMAL / ONLINE</small></el-card><el-card shadow="never"><span>异常/离线</span><strong>{{summary.abnormal}}</strong><small>ABNORMAL / OFFLINE</small></el-card><el-card shadow="never"><span>未知/过期</span><strong>{{summary.unknown}}</strong><small>UNKNOWN 或采集过期</small></el-card></div><div class="filter-row" style="margin-top:16px"><el-input v-model="keyword" clearable placeholder="资源编码 / 名称" style="width:320px" @keyup.enter="search"/><el-button type="primary" @click="search">查询</el-button><el-button @click="keyword='';search()">重置</el-button><span style="margin-left:auto;color:#8a94a6">最近采集：{{fmt(overview?.lastCollect?.started_at)}} · 过期阈值 {{overview?.staleSeconds||'-'}} 秒</span></div></el-card>
<el-card shadow="never"><el-table :data="rows" v-loading="loading" border stripe @row-dblclick="openMetrics"><el-table-column prop="object_code" label="对象编码" min-width="150"/><el-table-column prop="object_name" label="对象名称" min-width="160"/><el-table-column label="运行状态" width="120"><template #default="s"><el-tag :type="statusType(s.row.display_status)">{{s.row.display_status}}</el-tag></template></el-table-column><el-table-column label="健康分" width="90"><template #default="s">{{s.row.health_score??'-'}}</template></el-table-column><el-table-column label="关键指标" min-width="360"><template #default="s"><span class="mono-small">{{metricsText(s.row)}}</span></template></el-table-column><el-table-column label="数据时间" min-width="170"><template #default="s">{{fmt(s.row.last_collected_at)}}</template></el-table-column><el-table-column label="过期" width="80"><template #default="s"><el-tag :type="s.row.stale?'warning':'success'">{{s.row.stale?'是':'否'}}</el-tag></template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="s"><el-button link type="primary" @click="openMetrics(s.row)">趋势</el-button></template></el-table-column></el-table><div style="display:flex;justify-content:flex-end;margin-top:16px"><el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" :page-sizes="[20,50,100]" layout="total,sizes,prev,pager,next" @change="load"/></div></el-card>
<el-drawer v-model="drawer" size="72%" :title="`${selected?.object_name||''} · 指标趋势`"><div class="filter-row"><span>时间范围</span><el-select v-model="hours" style="width:140px"><el-option label="最近1小时" :value="1"/><el-option label="最近6小时" :value="6"/><el-option label="最近24小时" :value="24"/><el-option label="最近7天" :value="168"/></el-select></div><div ref="chartEl" style="height:340px;margin-top:16px"></div><el-table :data="history.slice().reverse().slice(0,100)" border size="small"><el-table-column prop="metric_code" label="指标" min-width="180"/><el-table-column label="值" min-width="140"><template #default="s">{{s.row.metric_value??s.row.metric_text??'-'}}</template></el-table-column><el-table-column label="采集时间" min-width="180"><template #default="s">{{fmt(s.row.collected_at)}}</template></el-table-column></el-table></el-drawer></div></template>
<style scoped>.mono-small{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;color:#526173}</style>
