<script setup lang="ts">
import { computed,onMounted,ref,watch } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { monitorApi } from '@/api/runtimeOps'
import { useAuthStore } from '@/stores/auth'
const auth=useAuthStore(),router=useRouter(),active=ref('CENTOS'),loading=ref(false),collecting=ref(false),rows=ref<any[]>([]),total=ref(0),page=ref(1),size=ref(20),keyword=ref(''),overview=ref<any>({types:{}})
const tabs=[['CENTOS','CentOS监控'],['ROS','ROS监控']];const summary=computed(()=>overview.value?.types?.[active.value]||{total:0,healthy:0,abnormal:0,unknown:0});const data=(r:any)=>r.data.data
function fmt(v:any){return v?new Date(v).toLocaleString():'-'}function statusType(v:string){return['NORMAL','ONLINE'].includes(v)?'success':v==='ABNORMAL'?'warning':v==='OFFLINE'?'danger':'info'}function metricsText(r:any){const x=r.current_metrics;if(!x)return'-';if(typeof x==='string')return x;const value=x.value?x.value:x;try{return Object.entries(value).slice(0,6).map(([k,v])=>`${k}:${typeof v==='number'?Number(v).toFixed(1):v}`).join(' / ')}catch{return String(x)}}
async function load(){loading.value=true;try{const [o,r]=await Promise.all([monitorApi.overview(),monitorApi.objects({page:page.value,size:size.value,objectType:active.value,keyword:keyword.value})]);overview.value=data(o)||{};const d=data(r)||{};rows.value=d.items||[];total.value=d.total||0}finally{loading.value=false}}
async function collect(){collecting.value=true;try{const r=data(await monitorApi.collect());ElMessage.success(`采集完成：${r?.objectCount||0}个对象，${r?.sampleCount||0}个指标`);load()}finally{collecting.value=false}}
function detail(r:any){router.push(`/monitor/${String(r.object_type||active.value).toLowerCase()}/${r.object_id}`)}
watch(active,()=>{page.value=1;load()});onMounted(load)
</script>
<template><div class="page"><div class="head"><div><h2>监控中心</h2><p>V1.2仅对 CentOS 与 ROS 做主机级监控；家宽/线路状态、拨号、IP变化等在资源列表和日志中查看。</p></div><el-button v-if="auth.hasPermission('monitor:collect')" type="primary" :loading="collecting" @click="collect">立即采集</el-button></div><el-card shadow="never"><el-tabs v-model="active"><el-tab-pane v-for="t in tabs" :key="t[0]" :label="t[1]" :name="t[0]"/></el-tabs><div class="metrics"><el-card shadow="never"><span>对象总数</span><strong>{{summary.total||0}}</strong></el-card><el-card shadow="never"><span>健康</span><strong>{{summary.healthy||0}}</strong></el-card><el-card shadow="never"><span>异常/离线</span><strong>{{summary.abnormal||0}}</strong></el-card><el-card shadow="never"><span>未知/过期</span><strong>{{summary.unknown||0}}</strong></el-card></div><div class="filters"><el-input v-model="keyword" clearable placeholder="资源编码 / 名称" @keyup.enter="page=1;load()"/><el-button type="primary" @click="page=1;load()">查询</el-button><span class="hint">最近采集：{{fmt(overview?.lastCollect?.started_at)}} · 过期阈值 {{overview?.staleSeconds||'-'}} 秒</span></div></el-card><el-card shadow="never"><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="object_code" label="对象编码" min-width="150"/><el-table-column prop="object_name" label="对象名称" min-width="160"/><el-table-column label="状态" width="110"><template #default="s"><el-tag :type="statusType(s.row.display_status)">{{s.row.display_status}}</el-tag></template></el-table-column><el-table-column label="健康分" width="90"><template #default="s">{{s.row.health_score??'-'}}</template></el-table-column><el-table-column label="关键指标" min-width="380"><template #default="s"><span class="mono">{{metricsText(s.row)}}</span></template></el-table-column><el-table-column label="采集时间" width="180"><template #default="s">{{fmt(s.row.last_collected_at)}}</template></el-table-column><el-table-column label="操作" width="90"><template #default="s"><el-button link type="primary" @click="detail(s.row)">趋势</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" layout="total,sizes,prev,pager,next" @change="load"/></div></el-card></div></template>
<style scoped>.page{display:grid;gap:16px}.head{display:flex;justify-content:space-between}.head h2{margin:0 0 6px}.head p{margin:0;color:#7b8494}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.metrics strong{display:block;font-size:28px;margin-top:10px}.filters{display:flex;gap:10px;align-items:center;margin-top:14px}.filters .el-input{width:320px}.hint{margin-left:auto;color:#8a94a6}.mono{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px}.pager{display:flex;justify-content:flex-end;margin-top:14px}</style>
