<script setup lang="ts">
import{onMounted,ref,watch}from'vue'
import{runtimeLogApi}from'@/api/runtimeLog'
import{useAuthStore}from'@/stores/auth'
const auth=useAuthStore(),active=ref('extract'),loading=ref(false),rows=ref<any[]>([]),total=ref(0),page=ref(1),size=ref(20),keyword=ref(''),serviceId=ref('')
const tabs=[{name:'extract',label:'IP提取日志',permission:'runtime-log:extract:read'},{name:'api',label:'API日志',permission:'runtime-log:api:read'},{name:'usage',label:'使用日志',permission:'runtime-log:usage:read'}]
function fmt(v:any){return v?new Date(v).toLocaleString():'-'}
async function load(){loading.value=true;try{const params:any={page:page.value,size:size.value,keyword:keyword.value};if(serviceId.value)params.serviceId=Number(serviceId.value);const call=active.value==='extract'?runtimeLogApi.extracts:active.value==='api'?runtimeLogApi.apis:runtimeLogApi.usage;const r=await call(params);rows.value=r.data.data.items;total.value=r.data.data.total}finally{loading.value=false}}
function search(){page.value=1;load()}
watch(active,()=>{page.value=1;load()});onMounted(load)
</script>
<template><div class="page-stack"><el-card shadow="never"><div class="page-title"><div><h2>运行日志</h2><p>Open API 调用链以 requestId 串联。IP提取日志和API日志由平台实时产生；使用日志等待真实代理运行面回传。</p></div></div><el-tabs v-model="active"><el-tab-pane v-for="t in tabs" v-show="auth.hasPermission(t.permission)" :key="t.name" :label="t.label" :name="t.name"/></el-tabs><div class="filter-row"><el-input v-model="keyword" clearable placeholder="requestId / 客户 / 服务 / 路径 / 出站IP" style="width:360px" @keyup.enter="search"/><el-input v-model="serviceId" clearable placeholder="服务ID" style="width:140px" @keyup.enter="search"/><el-button type="primary" @click="search">查询</el-button><el-button @click="keyword='';serviceId='';search()">重置</el-button></div></el-card>
<el-card shadow="never"><el-table :data="rows" v-loading="loading" border stripe>
<template v-if="active==='extract'"><el-table-column prop="request_id" label="Request ID" min-width="190"/><el-table-column prop="customer_name" label="客户" min-width="150"/><el-table-column prop="service_no" label="服务编号" min-width="150"/><el-table-column prop="product_name" label="产品" min-width="130"/><el-table-column prop="client_ip" label="客户端IP" min-width="130"/><el-table-column prop="requested_protocol_code" label="协议" width="80"/><el-table-column prop="requested_count" label="请求" width="70"/><el-table-column prop="returned_count" label="返回" width="70"/><el-table-column prop="result" label="结果" width="90"/><el-table-column prop="error_code" label="错误码" min-width="150"/><el-table-column label="耗时" width="90"><template #default="s">{{s.row.elapsed_ms??'-'}} ms</template></el-table-column><el-table-column label="时间" min-width="170"><template #default="s">{{fmt(s.row.occurred_at)}}</template></el-table-column></template>
<template v-else-if="active==='api'"><el-table-column prop="request_id" label="Request ID" min-width="190"/><el-table-column prop="customer_name" label="客户" min-width="150"/><el-table-column prop="service_no" label="服务编号" min-width="150"/><el-table-column prop="method" label="方法" width="80"/><el-table-column prop="path" label="接口" min-width="220"/><el-table-column prop="client_ip" label="客户端IP" min-width="130"/><el-table-column prop="response_status" label="HTTP" width="80"/><el-table-column prop="result" label="结果" width="90"/><el-table-column prop="error_code" label="错误码" min-width="150"/><el-table-column label="耗时" width="90"><template #default="s">{{s.row.elapsed_ms??'-'}} ms</template></el-table-column><el-table-column label="时间" min-width="170"><template #default="s">{{fmt(s.row.occurred_at)}}</template></el-table-column></template>
<template v-else><el-table-column prop="request_id" label="Request ID" min-width="190"/><el-table-column prop="customer_name" label="客户" min-width="150"/><el-table-column prop="service_no" label="服务编号" min-width="150"/><el-table-column prop="product_name" label="产品" min-width="130"/><el-table-column prop="client_ip" label="客户端IP" min-width="130"/><el-table-column prop="outbound_ip" label="出站IP" min-width="130"/><el-table-column prop="protocol_code" label="协议" width="80"/><el-table-column prop="target_host" label="目标Host" min-width="160"/><el-table-column prop="upload_bytes" label="上行字节" min-width="100"/><el-table-column prop="download_bytes" label="下行字节" min-width="100"/><el-table-column prop="result" label="结果" width="90"/><el-table-column label="时间" min-width="170"><template #default="s">{{fmt(s.row.occurred_at)}}</template></el-table-column></template>
</el-table><div style="display:flex;justify-content:flex-end;margin-top:16px"><el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" :page-sizes="[20,50,100]" layout="total, sizes, prev, pager, next" @change="load"/></div></el-card></div></template>
