<script setup lang="ts">
import{nextTick,onBeforeUnmount,onMounted,ref,watch}from'vue'
import * as echarts from'echarts'
import{ElMessage}from'element-plus'
import{statisticsApi}from'@/api/runtimeOps'
import{useAuthStore}from'@/stores/auth'
const auth=useAuthStore(),active=ref('resources'),loading=ref(false),calculating=ref(false),rows=ref<any[]>([]),overview=ref<any>({}),chartEl=ref<HTMLElement>(),chart=ref<echarts.ECharts>(),range=ref<[Date,Date]>([new Date(Date.now()-24*3600_000),new Date()])
const tabs=[['resources','基础资源统计'],['ips','IP资源统计'],['customers','客户使用统计'],['products','产品与服务统计'],['suppliers','外部资源统计']]
function fmt(v:any){return v?new Date(v).toLocaleString():'-'}
function params(){return{from:range.value?.[0]?.toISOString(),to:range.value?.[1]?.toISOString()}}
async function load(){loading.value=true;try{const api:any=(statisticsApi as any)[active.value];const [o,r]=await Promise.all([statisticsApi.overview(),api(params())]);overview.value=o.data.data;rows.value=r.data.data||[];await nextTick();draw()}finally{loading.value=false}}
async function recalculate(){calculating.value=true;try{await statisticsApi.recalculate();ElMessage.success('当前小时统计已重算');await load()}finally{calculating.value=false}}
function aggregate(fields:string[]){const map=new Map<string,Record<string,number>>();for(const r of rows.value){const key=new Date(r.stat_hour).toISOString();if(!map.has(key))map.set(key,{});const v=map.get(key)!;for(const f of fields)v[f]=(v[f]||0)+Number(r[f]||0)}return[...map.entries()].sort((a,b)=>a[0].localeCompare(b[0]))}
function draw(){if(!chartEl.value)return;chart.value?.dispose();chart.value=echarts.init(chartEl.value);let fields:string[]=[];if(active.value==='resources')fields=['centos_online','ros_online','line_online'];if(active.value==='ips')fields=['ip_available','ip_total','ip_unique'];if(active.value==='customers')fields=['extract_count','returned_ip_count','request_count'];if(active.value==='products')fields=['active_service_count','extract_count','request_count'];if(active.value==='suppliers')fields=['fetch_count','success_count','received_resource_count'];const data=aggregate(fields);chart.value.setOption({tooltip:{trigger:'axis'},legend:{data:fields},grid:{left:60,right:20,top:48,bottom:48},xAxis:{type:'time'},yAxis:{type:'value'},series:fields.map(f=>({name:f,type:'line',smooth:true,showSymbol:false,data:data.map(([t,v])=>[t,v[f]||0])}))})}
watch(active,load);onMounted(load);onBeforeUnmount(()=>chart.value?.dispose())
</script>
<template><div class="page-stack"><el-card shadow="never"><div class="page-title"><div><h2>数据统计</h2><p>统计最小粒度为 1 小时。IP提取与API调用来自 M7 真实运行日志；代理流量请求、上下行字节等指标仅在真实数据面回传使用日志后计入。</p></div><el-button v-if="auth.hasPermission('statistics:recalculate')" type="primary" :loading="calculating" @click="recalculate">重算当前小时</el-button></div><el-tabs v-model="active"><el-tab-pane v-for="t in tabs" :key="t[0]" :label="t[1]" :name="t[0]"/></el-tabs><div class="filter-row"><el-date-picker v-model="range" type="datetimerange" range-separator="至" start-placeholder="开始时间" end-placeholder="结束时间"/><el-button type="primary" @click="load">查询</el-button><span style="margin-left:auto;color:#8a94a6">最近计算：{{fmt(overview?.lastCalculation?.started_at)}}</span></div><div class="metric-grid" style="margin-top:16px"><el-card shadow="never"><span>有效客户</span><strong>{{overview.active_customers??0}}</strong><small>当前 ACTIVE 客户</small></el-card><el-card shadow="never"><span>有效服务</span><strong>{{overview.active_services??0}}</strong><small>当前 ACTIVE 服务</small></el-card><el-card shadow="never"><span>今日返回IP</span><strong>{{overview.today_returned_ips??0}}</strong><small>来自 IP 提取日志</small></el-card><el-card shadow="never"><span>当前活动告警</span><strong>{{overview.active_alarms??0}}</strong><small>未恢复/处理中</small></el-card></div></el-card>
<el-card shadow="never" v-loading="loading"><div ref="chartEl" style="height:330px"></div></el-card>
<el-card shadow="never"><el-table :data="rows" v-loading="loading" border stripe>
<template v-if="active==='resources'"><el-table-column label="统计小时" min-width="170"><template #default="s">{{fmt(s.row.stat_hour)}}</template></el-table-column><el-table-column prop="centos_total" label="CentOS总数"/><el-table-column prop="centos_online" label="CentOS在线"/><el-table-column prop="ros_total" label="ROS总数"/><el-table-column prop="ros_online" label="ROS在线"/><el-table-column prop="line_total" label="线路总数"/><el-table-column prop="line_online" label="线路在线"/><el-table-column prop="line_abnormal" label="线路异常"/></template>
<template v-else-if="active==='ips'"><el-table-column label="统计小时" min-width="170"><template #default="s">{{fmt(s.row.stat_hour)}}</template></el-table-column><el-table-column prop="ip_total" label="IP总量"/><el-table-column prop="ip_unique" label="去重IP"/><el-table-column prop="ip_available" label="可用IP"/><el-table-column prop="ip_unavailable" label="不可用IP"/><el-table-column prop="duplicate_count" label="重复标记"/></template>
<template v-else-if="active==='customers'"><el-table-column label="统计小时" min-width="170"><template #default="s">{{fmt(s.row.stat_hour)}}</template></el-table-column><el-table-column prop="customer_name" label="客户" min-width="160"/><el-table-column prop="service_no" label="服务" min-width="160"/><el-table-column prop="product_name" label="产品" min-width="150"/><el-table-column prop="extract_count" label="提取请求IP数"/><el-table-column prop="returned_ip_count" label="返回IP数"/><el-table-column prop="unique_outbound_ip_count" label="实际出站IP去重"/><el-table-column prop="request_count" label="代理请求数"/><el-table-column prop="success_count" label="成功请求"/><el-table-column prop="failure_count" label="失败请求"/></template>
<template v-else-if="active==='products'"><el-table-column label="统计小时" min-width="170"><template #default="s">{{fmt(s.row.stat_hour)}}</template></el-table-column><el-table-column prop="product_name" label="产品" min-width="160"/><el-table-column prop="package_name" label="套餐" min-width="150"/><el-table-column prop="active_customer_count" label="有效客户"/><el-table-column prop="active_service_count" label="有效服务"/><el-table-column prop="extract_count" label="提取IP数"/><el-table-column prop="request_count" label="代理请求"/><el-table-column prop="success_count" label="成功请求"/><el-table-column prop="unique_outbound_ip_count" label="出站IP去重"/></template>
<template v-else><el-table-column label="统计小时" min-width="170"><template #default="s">{{fmt(s.row.stat_hour)}}</template></el-table-column><el-table-column prop="supplier_name" label="供应商" min-width="170"/><el-table-column prop="fetch_count" label="获取次数"/><el-table-column prop="success_count" label="成功"/><el-table-column prop="failure_count" label="失败"/><el-table-column prop="received_resource_count" label="获取资源数"/><el-table-column prop="unique_ip_count" label="供应商去重IP"/><el-table-column prop="available_ip_count" label="可用IP"/><el-table-column prop="imported_ip_count" label="入库IP"/><el-table-column prop="avg_elapsed_ms" label="平均耗时ms"/></template>
</el-table></el-card></div></template>
